WIP EmergencyAccess first commit
dani-garcia/vaultwarden pull request #1377
Opened 2021-02-10 13:59 UTC by thelittlefireman

Signed-off-by: thelittlefireman <thomas.goureau@gmail.com>

2021-02-11 16:06 UTC, thelittlefireman commented
Ok all basic features are implemented and tested.

I haven't tested all the `if` branch, so this pr need loooots of further testing :) Be free to test and add comment if you find issue !

Todo list : 
 * [ ] : Add policies route which was added yesterday
 * [ ] : Handle automatic timeout when requesting access on an emergency contact
 * [ ] : Implement all emails features and test if correct (links in email, accept/confirm user)
* [ ] : Finish others TODO ...

2021-02-14 23:39 UTC, jjlin commented
I haven't looked at this in detail, but from a cursory look, here are a few changes I would suggest:

* Instead of `emergency` or `emergencies`, I think it should just be `emergency_access` to be consistent with the name of the feature itself, as well as the APIs being under `/emergency-access`. This applies to source file names and table names.
* Rather than `JOBS_DEBUG`, it would be more useful to have one or more config settings that control job frequency via cron-like syntax. This could be useful for both end users who want to customize the frequency, as well as for debugging. You may want to switch to a scheduler that accepts cron syntax (it doesn't seem like `clokwerk` does, but maybe I'm missing something).

2021-02-15 14:41 UTC, thelittlefireman commented
> I haven't looked at this in detail, but from a cursory look, here are a few changes I would suggest:
> 
> * Instead of `emergency` or `emergencies`, I think it should just be `emergency_access` to be consistent with the name of the feature itself, as well as the APIs being under `/emergency-access`. This applies to source file names and table names.
> * Rather than `JOBS_DEBUG`, it would be more useful to have one or more config settings that control job frequency via cron-like syntax. This could be useful for both end users who want to customize the frequency, as well as for debugging. You may want to switch to a scheduler that accepts cron syntax (it doesn't seem like `clokwerk` does, but maybe I'm missing something).

Thanks :) 
* Rename have been done
* The advantage of clokwerk is that it could be run in background (in parallel with rocket loop). I can't find a cron sentence library (job_scheduler or sheduler_rs) can do that. Is the cron configuration a really must-have feature ? 
For now I will just change the JOBS_DEBUG to JOB_FREQUENCY_HOUR to be able to set how often per hours jobs must run if it's ok for you ?

2021-02-15 19:57 UTC, dani-garcia reviewed
I don't have much time now to actually test and run the code, but a cursory check of it all looks pretty good so far, especially if this is a first! I've made some comments, nothing particularly big.

I don't necessarily see the point of allowing to configure the scheduled jobs interval, the minimum emergency timeout access is one day, so one hour intervals seem fast enough even for that case and shouldn't be very resource intensive anyway.

If you want to run some basic scheduling in parallel with rocket, you can always spawn a new background thread and be done with it:
```rust
std::thread::spawn(move || {
    loop {
        do_hourly();
        std::thread::sleep(std::time::Duration::from_secs(60 * 60));
    }
});
```

2021-02-15 19:57 UTC, dani-garcia commented on src/jobs.rs
> +            (emer.last_notification_at.is_none() || (emer.last_notification_at.is_some() && Utc::now().naive_utc() >= emer.last_notification_at.unwrap() + Duration::days(1) )){
Not sure I quite understand what's going on here, we send a reminder whenever we are past the `date - 1` days mark, but only if we haven't sent one before, or once every day forever? So I assume this keeps sending emails until the grantor disables access? Is that how upstream does it as well?

2021-02-15 19:57 UTC, dani-garcia commented on src/api/core/emergency_accesses.rs
> +            if !CONFIG.mail_enabled() {
If email is enabled, we aren't sending an email here. Might need to do somehting like: https://github.com/dani-garcia/bitwarden_rs/blob/c836f88ff2a7f94ee7427ae04b91e702a31ab52a/src/api/admin.rs#L275.

2021-02-15 19:57 UTC, dani-garcia commented on src/api/core/emergency_accesses.rs
> +            user.save(&conn)?;
There's no need to create this user here, it's only used to get an uuid for `find_by_grantor_uuid_and_grantee_uuid` but it's enough to just search by email.

2021-02-15 19:57 UTC, dani-garcia commented on src/api/core/emergency_accesses.rs
> +    if emergency_access.grantee_uuid.is_some() {
Does something like this work here?:
```rust
if let Some(grantee_uuid) =  emergency_access.grantee_uuid.as_ref() {
     let grantee_user = match User::find_by_uuid(grantee_uuid, &conn) {
}
```

2021-02-15 19:57 UTC, dani-garcia commented on src/api/core/emergency_accesses.rs
> +    if emergency_access.grantee_uuid.is_some() {
Same as above with the if let Some(..) = ..grantee_uuid.as_ref()

2021-02-15 19:57 UTC, dani-garcia commented on src/api/core/emergency_accesses.rs
> +    if emergency_access.grantee_uuid.is_some() {
And same here

2021-02-15 19:57 UTC, dani-garcia commented on src/static/templates/email/send_emergency_access_invite.hbs
> +<!---------------->
Before this line is the subject of the email, which should be filled

2021-02-15 19:57 UTC, dani-garcia commented on src/static/templates/email/send_emergency_access_invite.html.hbs
> +Join {{{org_name}}}
This subject needs to be updated

2021-02-16 18:56 UTC, thelittlefireman commented on src/api/core/emergency_accesses.rs
> +            if !CONFIG.mail_enabled() {
Email is send at line 237 :) I don't know if it is Invitation object is really needed for that kind of invitation. What do you think ?

2021-02-16 18:57 UTC, thelittlefireman commented
> I don't have much time now to actually test and run the code, but a cursory check of it all looks pretty good so far, especially if this is a first! I've made some comments, nothing particularly big.
> 
> I don't necessarily see the point of allowing to configure the scheduled jobs interval, the minimum emergency timeout access is one day, so one hour intervals seem fast enough even for that case and shouldn't be very resource intensive anyway.
> 
> If you want to run some basic scheduling in parallel with rocket, you can always spawn a new background thread and be done with it:
> 
> ```rust
> std::thread::spawn(move || {
>     loop {
>         do_hourly();
>         std::thread::sleep(std::time::Duration::from_secs(60 * 60));
>     }
> });
> ```

Thanks a lot :) I will take a look at all of that's !

2021-02-16 21:20 UTC, thelittlefireman commented on src/jobs.rs
> +            (emer.last_notification_at.is_none() || (emer.last_notification_at.is_some() && Utc::now().naive_utc() >= emer.last_notification_at.unwrap() + Duration::days(1) )){
I just recopy the upstream; It just sends one email, 1 day before the end of the timed out.

https://github.com/bitwarden/server/blob/979eb4a8428c730aa21e49ee6cb012e7f280a180/src/Core/Services/Implementations/EmergencyAccessService.cs#L305-L315 
https://github.com/bitwarden/server/blob/0f1af2333e9e2af5aecd1b290130f3925a7e280d/src/Sql/dbo/Stored%20Procedures/EmergencyAccess_ReadToNotify.sql

2021-02-21 01:00 UTC, williamdes commented on migrations/postgresql/2021-02-10-174254_create_emergency_access/up.sql
> +  grantee_uuid              TEXT,
no FK here ?

2021-02-21 01:03 UTC, williamdes commented on src/jobs.rs
> +                    error!("Email not valid.")
```suggestion
                    error!("Email domain not valid.")
```

2021-02-21 01:06 UTC, williamdes commented on src/static/templates/email/emergency_access_recovery_initiated.hbs
> +If you do nothing, the request will automatically be approved after {{wait_time_days}} day(s.
```suggestion
If you do nothing, the request will automatically be approved after {{wait_time_days}} day(s).
```

2021-02-21 01:06 UTC, williamdes commented on src/static/templates/email/emergency_access_recovery_initiated.html.hbs
> +                                           If you do nothing, the request will automatically be approved after <b style="margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-si
```suggestion
                                           If you do nothing, the request will automatically be approved after <b style="margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; color: #333; line-height: 25px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none;">{{wait_time_days}}</b> day(s).
```

2021-02-21 01:08 UTC, williamdes commented on src/static/templates/email/emergency_access_recovery_rejected.html.hbs
> +                                           <b style="margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; color: #333; line-height: 25px; -
```suggestion
                                           <b style="margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; color: #333; line-height: 25px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none;">{{grantor_name}}</b> has rejected your emergency request.
```
Nothing major, only a trailing space

2021-02-21 01:08 UTC, williamdes commented on src/static/templates/email/emergency_access_recovery_reminder.hbs
> +If you do nothing, the request will automatically be approved after {{wait_time_days}} day(s.
same here for days, and on the html template

2021-02-21 01:10 UTC, williamdes commented on src/util.rs
> +}
is this a usefull diff or a mistake fix ?
@dani-garcia could you add a .editorconfig file ?

2021-02-25 14:39 UTC, thelittlefireman commented on src/util.rs
> +}
it's a mistake fix due to an add and delete lines of codes

2021-02-25 14:39 UTC, thelittlefireman commented on src/static/templates/email/send_emergency_access_invite.html.hbs
> +Join {{{org_name}}}
done

2021-02-25 14:39 UTC, thelittlefireman commented on src/static/templates/email/send_emergency_access_invite.hbs
> +<!---------------->
done

2021-02-25 14:39 UTC, thelittlefireman commented on src/main.rs
> +#[macro_use]
done

2021-02-25 14:39 UTC, thelittlefireman commented on migrations/postgresql/2021-02-10-174254_create_emergency_access/up.sql
> +  grantee_uuid              TEXT,
done

2021-02-25 14:39 UTC, thelittlefireman commented on migrations/mysql/2021-02-10-174254_create_emergency_access/up.sql
> +  uuid              TEXT     NOT NULL PRIMARY KEY,
done

2021-02-25 14:39 UTC, thelittlefireman commented on .env.template
> +# JOB_FREQUENCY_HOUR=1
done

2021-02-25 14:47 UTC, thelittlefireman commented on src/api/core/emergency_accesses.rs
> +            user.save(&conn)?;
This user it used to generate the token for the `mail::send_emergency_access_invite()`

2021-02-25 14:52 UTC, thelittlefireman commented on src/api/core/emergency_accesses.rs
> +    if emergency_access.grantee_uuid.is_some() {
done

2021-02-25 14:52 UTC, thelittlefireman commented on src/api/core/emergency_accesses.rs
> +    if emergency_access.grantee_uuid.is_some() {
done

2021-02-25 14:53 UTC, thelittlefireman commented on src/api/core/emergency_accesses.rs
> +    if emergency_access.grantee_uuid.is_some() {
done

2021-02-25 15:04 UTC, williamdes commented on src/api/core/emergency_accesses.rs
> +            if !CONFIG.is_email_domain_allowed(&grantee_user.email) {
Could you please update all error messages for `is_email_domain_allowed` ?

2021-02-25 15:23 UTC, thelittlefireman commented on src/api/core/emergency_accesses.rs
> +            if !CONFIG.is_email_domain_allowed(&grantee_user.email) {
done

2021-03-07 22:06 UTC, williamdes commented on src/api/core/emergency_accesses.rs
> +        err!("Cannot set yourself as an emergency contact.")
```suggestion
        err!("You can not set yourself as an emergency contact.")
```

2021-03-12 23:27 UTC, travisterrell commented
I'm just here to say a huge thank you for implementing this feature! I have no power to approve the merge, but hopefully it will get pulled in soon. Just wanted to issue my thanks for your quick work!

2021-03-14 15:37 UTC, BlackDex commented
@thelittlefireman: I just tried this PR (and merged it with current master), but it doesn't work for me.
Everything goes fine with adding a grantee, verifying, and accepting.

Then after i send an emergency request, which sends out a nice e-mail also goes good.
But if i then login with as the requester and try to see the vault i see the following in the logs:
```
[2021-03-14 15:34:47.986][request][INFO] GET /api/emergency-access/trusted
[2021-03-14 15:34:47.987][response][INFO] GET /api/emergency-access/trusted (get_contacts) => 200 OK
[2021-03-14 15:34:48.020][request][INFO] GET /api/emergency-access/granted
[2021-03-14 15:34:48.022][response][INFO] GET /api/emergency-access/granted (get_grantees) => 200 OK
[2021-03-14 15:34:53.671][request][INFO] POST /api/emergency-access/a8d1f7a7-9c25-4cf1-84c0-603d1a60369f/view
[2021-03-14 15:34:53.672][bitwarden_rs::api::core::emergency_accesses][ERROR] Emergency access not valid.
[2021-03-14 15:34:53.673][response][INFO] POST /api/emergency-access/<emer_id>/view (view_emergency_access) => 400 Bad Request
```

Though, when i lookup that UUID, it is there in the database.
I'm busy with some other stuff, so not much time to checkout why is going on here.

2021-03-14 15:44 UTC, thelittlefireman commented
> @thelittlefireman: I just tried this PR (and merged it with current master), but it doesn't work for me.
> Everything goes fine with adding a grantee, verifying, and accepting.
> 
> Then after i send an emergency request, which sends out a nice e-mail also goes good.
> But if i then login with as the requester and try to see the vault i see the following in the logs:
> ```
> [2021-03-14 15:34:47.986][request][INFO] GET /api/emergency-access/trusted
> [2021-03-14 15:34:47.987][response][INFO] GET /api/emergency-access/trusted (get_contacts) => 200 OK
> [2021-03-14 15:34:48.020][request][INFO] GET /api/emergency-access/granted
> [2021-03-14 15:34:48.022][response][INFO] GET /api/emergency-access/granted (get_grantees) => 200 OK
> [2021-03-14 15:34:53.671][request][INFO] POST /api/emergency-access/a8d1f7a7-9c25-4cf1-84c0-603d1a60369f/view
> [2021-03-14 15:34:53.672][bitwarden_rs::api::core::emergency_accesses][ERROR] Emergency access not valid.
> [2021-03-14 15:34:53.673][response][INFO] POST /api/emergency-access/<emer_id>/view (view_emergency_access) => 400 Bad Request
> ```
> 
> Though, when i lookup that UUID, it is there in the database.
> I'm busy with some other stuff, so not much time to checkout why is going on here.
> 

Thanks for the test ! I Will have a look

2021-03-15 21:26 UTC, thelittlefireman commented
> @thelittlefireman: I just tried this PR (and merged it with current master), but it doesn't work for me.
> Everything goes fine with adding a grantee, verifying, and accepting.
> 
> Then after i send an emergency request, which sends out a nice e-mail also goes good.
> But if i then login with as the requester and try to see the vault i see the following in the logs:
> 
> ```
> [2021-03-14 15:34:47.986][request][INFO] GET /api/emergency-access/trusted
> [2021-03-14 15:34:47.987][response][INFO] GET /api/emergency-access/trusted (get_contacts) => 200 OK
> [2021-03-14 15:34:48.020][request][INFO] GET /api/emergency-access/granted
> [2021-03-14 15:34:48.022][response][INFO] GET /api/emergency-access/granted (get_grantees) => 200 OK
> [2021-03-14 15:34:53.671][request][INFO] POST /api/emergency-access/a8d1f7a7-9c25-4cf1-84c0-603d1a60369f/view
> [2021-03-14 15:34:53.672][bitwarden_rs::api::core::emergency_accesses][ERROR] Emergency access not valid.
> [2021-03-14 15:34:53.673][response][INFO] POST /api/emergency-access/<emer_id>/view (view_emergency_access) => 400 Bad Request
> ```
> 
> Though, when i lookup that UUID, it is there in the database.
> I'm busy with some other stuff, so not much time to checkout why is going on here.

Fix by [https://github.com/dani-garcia/bitwarden_rs/pull/1377/commits/c09dafc4249360976972eef7b93def873d9705f6](https://github.com/dani-garcia/bitwarden_rs/pull/1377/commits/c09dafc4249360976972eef7b93def873d9705f6)
Sorry about this, that was a copy/paste mistake

2021-03-16 00:52 UTC, williamdes commented on src/db/models/emergency_access.rs
> +            "Takeovver"
typo ?

2021-03-16 00:52 UTC, williamdes commented on src/jobs.rs
> +                    error!("Email not valid.")
```suggestion
                    error!("Email domain not valid.")
```

2021-03-16 00:53 UTC, williamdes commented on src/jobs.rs
> +                    error!("Email not valid.")
```suggestion
                    error!("Email domain not valid.")
```

2021-03-21 22:25 UTC, williamdes commented
Hi @thelittlefireman 
There is quite too much commits (IMO), I think you could use `git rebase` (or `git rebase --interactive`) and `git push --force` and that would make a cleaner result

2021-03-21 22:28 UTC, BlackDex commented
Actually, i think something went wrong with a re-base maybe.
But a re-based pr, with just one commit to clean-up for now :)

2021-03-23 23:59 UTC, 0jdxt commented
Yeah you should've rebased instead of merged. I'd recommend this: merge up to date with master. Create a diff against the upstream/master. Create a new clean beanch from upstream/master and apply the patch. set upstream as the original branch and force push it as 1 commit.

2021-03-24 02:31 UTC, williamdes commented
> Yeah you should've rebased instead of merged. I'd recommend this: merge up to date with master. Create a diff against the upstream/master. Create a new clean branch from upstream/master and apply the patch. set upstream as the emergency_feature branch and force push it as 1 commit.

https://patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.patch
https://patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.diff

2021-03-24 02:36 UTC, 0jdxt commented
> [patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.patch](https://patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.patch)
> [patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.diff](https://patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.diff)

what is this sorcery?!

2021-03-24 02:42 UTC, williamdes commented
> > [patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.patch](https://patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.patch)
> > [patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.diff](https://patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.diff)
> 
> what is this sorcery?!

A very usefull way to inspect PRs, GitHub sends you this 2 links in your notifications emails.

https://github.com/dani-garcia/bitwarden_rs/pull/1377.patch
https://github.com/dani-garcia/bitwarden_rs/pull/1377.diff

Enjoy ;p

And you normally can do `git apply {downloadedFile}` as said here: https://stackoverflow.com/a/2249876/5155484

2021-03-24 19:04 UTC, thelittlefireman commented
> Yeah you should've rebased instead of merged. I'd recommend this: merge up to date with master. Create a diff against the upstream/master. Create a new clean branch from upstream/master and apply the patch. set upstream as the emergency_feature branch and force push it as 1 commit.

too many conflict on rebase. I'll do your second options

2021-03-24 19:19 UTC, thelittlefireman commented
> > > [patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.patch](https://patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.patch)
> > > [patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.diff](https://patch-diff.githubusercontent.com/raw/dani-garcia/bitwarden_rs/pull/1377.diff)
> > 
> > 
> > what is this sorcery?!
> 
> A very usefull way to inspect PRs, GitHub sends you this 2 links in your notifications emails.
> 
> https://github.com/dani-garcia/bitwarden_rs/pull/1377.patch
> https://github.com/dani-garcia/bitwarden_rs/pull/1377.diff
> 
> Enjoy ;p
> 
> And you normally can do `git apply {downloadedFile}` as said here: https://stackoverflow.com/a/2249876/5155484

done; better now ?

2021-03-24 19:23 UTC, BlackDex commented
Looks much better now.

2021-04-06 16:40 UTC, thelittlefireman commented
@BlackDex @dani-garcia Is there anything i can do to helping you merging this PR ?

2021-04-07 04:42 UTC, thelittlefireman commented
> Sorry, been meaning to test this thoroughly but I keep either being busy or forgetting, this week I'm dealing with the matters about the rename of the project, but after that I'll try to get this merged.
> 
> At this moment this needs a rebase, and it should probably swap the scheduler to the one just merged in #1579, but I can do that when I get to test it if you don't have the time.

Thanks for your reply. The rebase have been done. Happy testing !

2021-04-19 17:00 UTC, fdisamuel commented
Hi @thelittlefireman I was really excited about this project so I cloned your repo `thelittlefireman:emergency_feature` and built the docker image myself in order to test it a little. I manually commented out the `#bwrs-hide...` line in my browser so I could set up an emergency contact and test it with another account on the same server. 

When I just requested to view the vault, everything worked as intended, However I wasn't able to proceed a vault takeover. It goes well to the point where I am prompted to give a new master password , but after clicking save nothing happens. I was able to capture some errors in the browser developer tab as well as on the server side:

<details>
  <summary>On the browser side:</summary>

![image](https://user-images.githubusercontent.com/62856267/115273586-06dc1e80-a140-11eb-84af-c7b1b68827a5.png)
![image](https://user-images.githubusercontent.com/62856267/115273702-28d5a100-a140-11eb-9488-f1922db2c1c8.png)
![image](https://user-images.githubusercontent.com/62856267/115273743-38ed8080-a140-11eb-8c7c-9fa6fdfde4cb.png)

</details>


<details>
  <summary>On the server side:</summary>

 ```LOG
[2021-04-19 16:34:47.286][request][INFO] POST /api/accounts/prelogin,
[2021-04-19 16:34:47.346][response][INFO] POST /api/accounts/prelogin (prelogin) => 200 OK,
[2021-04-19 16:34:47.722][request][INFO] POST /identity/connect/token,
[2021-04-19 16:34:48.962][bitwarden_rs::api::identity][INFO] User **** logged in successfully. IP: 172.19.0.1,
[2021-04-19 16:34:48.962][response][INFO] POST /identity/connect/token (login) => 200 OK,
[2021-04-19 16:34:49.421][request][INFO] GET /api/sync?excludeDomains=true,
[2021-04-19 16:34:49.506][response][INFO] GET /api/sync?<data..> (sync) => 200 OK,
[2021-04-19 16:35:00.369][request][INFO] POST /api/accounts/prelogin,
[2021-04-19 16:35:00.398][response][INFO] POST /api/accounts/prelogin (prelogin) => 200 OK,
[2021-04-19 16:35:00.867][request][INFO] POST /identity/connect/token,
[2021-04-19 16:35:01.187][bitwarden_rs::api::identity][INFO] User ******* logged in successfully. IP: 172.19.0.1,
[2021-04-19 16:35:01.187][response][INFO] POST /identity/connect/token (login) => 200 OK,
[2021-04-19 16:35:01.714][request][INFO] GET /api/sync?excludeDomains=true,
[2021-04-19 16:35:01.717][response][INFO] GET /api/sync?<data..> (sync) => 200 OK,
[2021-04-19 16:35:10.051][request][INFO] GET /api/accounts/profile,
[2021-04-19 16:35:10.056][response][INFO] GET /api/accounts/profile (profile) => 200 OK,
[2021-04-19 16:35:11.636][request][INFO] GET /api/accounts/profile,
[2021-04-19 16:35:11.638][response][INFO] GET /api/accounts/profile (profile) => 200 OK,
[2021-04-19 16:36:20.899][request][INFO] GET /api/emergency-access/trusted,
[2021-04-19 16:36:20.901][response][INFO] GET /api/emergency-access/trusted (get_contacts) => 200 OK,
[2021-04-19 16:36:21.344][request][INFO] GET /api/emergency-access/granted,
[2021-04-19 16:36:21.346][response][INFO] GET /api/emergency-access/granted (get_grantees) => 200 OK,
[2021-04-19 16:36:22.005][request][INFO] GET /api/emergency-access/trusted,
[2021-04-19 16:36:22.007][response][INFO] GET /api/emergency-access/trusted (get_contacts) => 200 OK,
[2021-04-19 16:36:22.237][request][INFO] GET /api/emergency-access/granted,
[2021-04-19 16:36:22.238][response][INFO] GET /api/emergency-access/granted (get_grantees) => 200 OK,
[2021-04-19 16:36:46.649][request][INFO] GET /api/emergency-access/c1764782-d9d8-4cff-99e4-453b625bf66c/policies,
[2021-04-19 16:36:46.695][response][INFO] GET /api/emergency-access/<emer_id>/policies (policies_emergency_access) => 200 OK,
[2021-04-19 16:37:40.569][request][INFO] POST /api/emergency-access/c1764782-d9d8-4cff-99e4-453b625bf66c/takeover,
[2021-04-19 16:37:40.606][panic][ERROR] thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value': src/api/core/emergency_accesses.rs:662,
   0: bitwarden_rs::init_logging::{{closure}},
   1: std::panicking::rust_panic_with_hook,
             at rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/std/src/panicking.rs:595:17,
   2: std::panicking::begin_panic_handler::{{closure}},
             at rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/std/src/panicking.rs:495:13,
   3: std::sys_common::backtrace::__rust_end_short_backtrace,
             at rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/std/src/sys_common/backtrace.rs:141:18,
   4: rust_begin_unwind,
             at rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/std/src/panicking.rs:493:5,
   5: core::panicking::panic_fmt,
             at rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/core/src/panicking.rs:92:14,
   6: core::panicking::panic,
             at rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/core/src/panicking.rs:50:5,
   7: bitwarden_rs::api::core::emergency_accesses::rocket_route_fn_takeover_emergency_access,
   8: <F as rocket::handler::Handler>::handle,
   9: rocket::rocket::Rocket::route_and_process,
  10: <rocket::rocket::Rocket as hyper::server::Handler>::handle,
  11: hyper::server::Worker<H>::handle_connection,
  12: hyper::server::listener::spawn_with::{{closure}},
  13: std::sys_common::backtrace::__rust_begin_short_backtrace,
  14: core::ops::function::FnOnce::call_once{{vtable.shim}},
  15: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once,
             at rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/alloc/src/boxed.rs:1546:9,
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once,
             at rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/alloc/src/boxed.rs:1546:9,
      std::sys::unix::thread::Thread::new::thread_start,
             at rustc/132b4e5d167b7e622fcc11fa2b67b931105b4de1/library/std/src/sys/unix/thread.rs:71:17,
  16: start_thread,
  17: clone,
,
```
</details>

I am not sure whether I missed configure something. I just made a minimal setup to make it work enough for testing.
Any help appreciated!

2021-04-19 18:05 UTC, thelittlefireman commented
> Hi @thelittlefireman I was really excited about this project so I cloned your repo `thelittlefireman:emergency_feature` and built the docker image myself in order to test it a little. I manually commented out the `#bwrs-hide...` line in my browser so I could set up an emergency contact and test it with another account on the same server.
> 
> When I just requested to view the vault, everything worked as intended, However I wasn't able to proceed a vault takeover. It goes well to the point where I am prompted to give a new master password , but after clicking save nothing happens. I was able to capture some errors in the browser developer tab as well as on the server side:
> On the browser side:
> On the server side:
> 
> I am not sure whether I missed configure something. I just made a minimal setup to make it work enough for testing.
> Any help appreciated!

Thanks a lot :) !
I think it's fix now : Can you test again with https://github.com/dani-garcia/bitwarden_rs/pull/1377/commits/ca7c091ee38921b98f02eca506d14746232b3038

2021-04-19 19:58 UTC, fdisamuel commented
> > Hi @thelittlefireman I was really excited about this project so I cloned your repo `thelittlefireman:emergency_feature` and built the docker image myself in order to test it a little. I manually commented out the `#bwrs-hide...` line in my browser so I could set up an emergency contact and test it with another account on the same server.
> > When I just requested to view the vault, everything worked as intended, However I wasn't able to proceed a vault takeover. It goes well to the point where I am prompted to give a new master password , but after clicking save nothing happens. I was able to capture some errors in the browser developer tab as well as on the server side:
> > On the browser side:
> > On the server side:
> > I am not sure whether I missed configure something. I just made a minimal setup to make it work enough for testing.
> > Any help appreciated!
> 
> Thanks a lot :) !
> I think it's fix now : Can you test again with [ca7c091](https://github.com/dani-garcia/bitwarden_rs/commit/ca7c091ee38921b98f02eca506d14746232b3038)

Thanks for the quick action! I built and deployed the image. As far as I see the takeover action is working now ! Howewer I get an error on the browser side every time I proceed takeover (when click save): 

![image](https://user-images.githubusercontent.com/62856267/115295306-e325d200-a159-11eb-93d7-ba2e9cd697f5.png)

Besides this error (which has no visible impact on the functionality) everything is lookin good so far.

2021-04-24 18:12 UTC, TheDuffman85 commented
Will this PR be included in the next release? I'm really looking forward to this important functionality.

2021-04-25 09:57 UTC, fdisamuel commented
Okay so I have tested it a little more and I think I found a problem with emergency access grantee registration. When I invite a user who does not have account on the server yet, he cannot register using the link what is provided him by email, because of "Account with this email already exists". Screenshots below:

![image](https://user-images.githubusercontent.com/62856267/115989032-817fc080-a5bc-11eb-9aa5-97a2f5ad1430.png)
![image](https://user-images.githubusercontent.com/62856267/115989035-86dd0b00-a5bc-11eb-8a61-0c0a32c71df8.png)
![image](https://user-images.githubusercontent.com/62856267/115989040-8d6b8280-a5bc-11eb-9c23-2ca781ffac2a.png)

 Bitwarden-log:
```LOG
[2021-04-25 09:37:12.143][response][INFO] GET / (web_index) => 200 OK,
[2021-04-25 09:37:35.659][request][INFO] POST /api/accounts/register,
[2021-04-25 09:37:35.661][bitwarden_rs::api::core::accounts][ERROR] Account with this email already exists,
[2021-04-25 09:37:35.661][response][INFO] POST /api/accounts/register (register) => 400 Bad Request,
[2021-04-25 09:37:58.609][request][INFO] GET /alive,
[2021-04-25 09:37:58.610][response][INFO] GET /alive (alive) => 200 OK,
[2021-04-25 09:38:52.999][request][INFO] GET /notifications/hub?access_token=eyJ0eXAiOiJKV1QiL,
[2021-04-25 09:38:52.999][response][INFO] GET /notifications/hub (websockets_err) => 400 Bad Request,
[2021-04-25 09:38:59.018][request][INFO] GET /alive,
[2021-04-25 09:38:59.018][response][INFO] GET /alive (alive) => 200 OK,
[2021-04-25 09:39:04.791][request][INFO] POST /api/accounts/register,
[2021-04-25 09:39:04.792][bitwarden_rs::api::core::accounts][ERROR] Account with this email already exists,
[2021-04-25 09:39:04.793][response][INFO] POST /api/accounts/register (register) => 400 Bad Request,
[2021-04-25 09:39:59.407][request][INFO] GET /alive,
[2021-04-25 09:39:59.407][response][INFO] GET /alive (alive) => 200 OK,
```

Through the admin panel I can invite the user and he can register as well.
Have anybody (among the testers) experienced the same behavior? Maybe haven't configured something properly..

2021-04-25 16:26 UTC, fdisamuel commented
Hi! It seems I found one more "bug". When the person designated as emergency contact initiates a vault takeover, the email which supposed to inform the grantor about the action, will be sent to the emergency contact/grantee instead. (And there is a typo in the mail text.) 


![image](https://user-images.githubusercontent.com/62856267/116001225-b4917680-a5f3-11eb-9beb-a15913ed7066.png)
(server is the emergency contact)

2021-04-25 17:29 UTC, thelittlefireman commented
> Hi! It seems I found one more "bug". When the person designated as emergency contact initiates a vault takeover, the email which supposed to inform the grantor about the action, will be sent to the emergency contact/grantee instead. (And there is a typo in the mail text.)
> 
> ![image](https://user-images.githubusercontent.com/62856267/116001225-b4917680-a5f3-11eb-9beb-a15913ed7066.png)
> (_szerver_ is the emergency contact)

Thanks a lot for all your tests ! :) i've fixed the typo and the mail in [https://github.com/dani-garcia/bitwarden_rs/pull/1377/commits/c51277f855443950d5278ea4a64ede7146858a7b](https://github.com/dani-garcia/bitwarden_rs/pull/1377/commits/c51277f855443950d5278ea4a64ede7146858a7b)

2021-04-25 17:33 UTC, thelittlefireman commented
> Okay so I have tested it a little more and I think I found a problem with emergency access grantee registration. When I invite a user who does not have account on the server yet, he cannot register using the link what is provided him by email, because of "Account with this email already exists". Screenshots below:
> 
> ![image](https://user-images.githubusercontent.com/62856267/115989032-817fc080-a5bc-11eb-9aa5-97a2f5ad1430.png)
> ![image](https://user-images.githubusercontent.com/62856267/115989035-86dd0b00-a5bc-11eb-8a61-0c0a32c71df8.png)
> ![image](https://user-images.githubusercontent.com/62856267/115989040-8d6b8280-a5bc-11eb-9c23-2ca781ffac2a.png)
> 
> Bitwarden-log:
> 
> ```
> [2021-04-25 09:37:12.143][response][INFO] GET / (web_index) => 200 OK,
> [2021-04-25 09:37:35.659][request][INFO] POST /api/accounts/register,
> [2021-04-25 09:37:35.661][bitwarden_rs::api::core::accounts][ERROR] Account with this email already exists,
> [2021-04-25 09:37:35.661][response][INFO] POST /api/accounts/register (register) => 400 Bad Request,
> [2021-04-25 09:37:58.609][request][INFO] GET /alive,
> [2021-04-25 09:37:58.610][response][INFO] GET /alive (alive) => 200 OK,
> [2021-04-25 09:38:52.999][request][INFO] GET /notifications/hub?access_token=eyJ0eXAiOiJKV1QiL,
> [2021-04-25 09:38:52.999][response][INFO] GET /notifications/hub (websockets_err) => 400 Bad Request,
> [2021-04-25 09:38:59.018][request][INFO] GET /alive,
> [2021-04-25 09:38:59.018][response][INFO] GET /alive (alive) => 200 OK,
> [2021-04-25 09:39:04.791][request][INFO] POST /api/accounts/register,
> [2021-04-25 09:39:04.792][bitwarden_rs::api::core::accounts][ERROR] Account with this email already exists,
> [2021-04-25 09:39:04.793][response][INFO] POST /api/accounts/register (register) => 400 Bad Request,
> [2021-04-25 09:39:59.407][request][INFO] GET /alive,
> [2021-04-25 09:39:59.407][response][INFO] GET /alive (alive) => 200 OK,
> ```
> 
> Through the admin panel I can invite the user and he can register as well.
> Have anybody (among the testers) experienced the same behavior? Maybe haven't configured something properly..

i try without the link in the invitation. Unfortunately i do not have a mail server to test it for now. I will try later. I think it related to the token generated for the mail.

2021-04-25 18:22 UTC, williamdes commented
> i try without the link in the invitation. Unfortunately i do not have a mail server to test it for now. I will try later. I think it related to the token generated for the mail.

https://ethereal.email

That will save you :)

2021-04-25 18:48 UTC, thelittlefireman commented
Thanks @williamdes 

Ok @fdisamuel I thinks it's fix now :) [https://github.com/dani-garcia/bitwarden_rs/pull/1377/commits/0d30341188bbf7e33bfa4386b1233d69d4e36598](https://github.com/dani-garcia/bitwarden_rs/pull/1377/commits/0d30341188bbf7e33bfa4386b1233d69d4e36598)

2021-04-25 20:29 UTC, fdisamuel commented
> Thanks @williamdes
> 
> Ok @fdisamuel I thinks it's fix now :) [0d30341](https://github.com/dani-garcia/bitwarden_rs/commit/0d30341188bbf7e33bfa4386b1233d69d4e36598)

Hi @thelittlefireman Thanks for the quick reply and fixing again! I've done a quick test on this.

- the mailing function with c51277f is working properly  😁
- however the other problem with registration still exists (at least for me). I can see the link in the mail changed a bit, but it seems not to have an effect on this behavior. (still unable to register with emergency-access link)

2021-04-25 20:34 UTC, williamdes commented
Hi @thelittlefireman 
Is there a docker image I can pull into to my staging server and test ?

2021-04-25 22:29 UTC, thelittlefireman commented
> > Thanks @williamdes
> > Ok @fdisamuel I thinks it's fix now :) [0d30341](https://github.com/dani-garcia/bitwarden_rs/commit/0d30341188bbf7e33bfa4386b1233d69d4e36598)
> 
> Hi @thelittlefireman Thanks for the quick reply and fixing again! I've done a quick test on this.
> 
> * the mailing function with [c51277f](https://github.com/dani-garcia/bitwarden_rs/commit/c51277f855443950d5278ea4a64ede7146858a7b) is working properly  😁
> * however the other problem with registration still exists (at least for me). I can see the link in the mail changed a bit, but it seems not to have an effect on this behavior. (still unable to register with emergency-access link - got the same error message)

I try myself and it works properly, are you sure that you are on latest commit ?

2021-04-25 22:30 UTC, thelittlefireman commented
> Hi @thelittlefireman
> Is there a docker image I can pull into to my staging server and test ?

i do not have made a docker, i'm sorry you should try locally or  made it yourself :-s

2021-04-26 17:33 UTC, thelittlefireman commented
> > Thanks @williamdes
> > Ok @fdisamuel I thinks it's fix now :) [0d30341](https://github.com/dani-garcia/bitwarden_rs/commit/0d30341188bbf7e33bfa4386b1233d69d4e36598)
> 
> Hi @thelittlefireman Thanks for the quick reply and fixing again! I've done a quick test on this.
> 
> * the mailing function with [c51277f](https://github.com/dani-garcia/bitwarden_rs/commit/c51277f855443950d5278ea4a64ede7146858a7b) is working properly  grin
> * however the other problem with registration still exists (at least for me). I can see the link in the mail changed a bit, but it seems not to have an effect on this behavior. (still unable to register with emergency-access link - got the same error message)

Ok I make more tests and I think my previous test is working cause of a mess with organization invitation.

It seems to be a web-vault issue.

With organization invitation it sends a `token` request right after clicking on "create a new account".

`http://localhost:8000/api/organizations/655e59eb-5dc2-427d-a923-42bf43d5fb3c/policies/token?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJuYmYiOjE2MTk0NTU4NTUsImV4cCI6MTYxOTg4Nzg1NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdHxpbnZpdGUiLCJzdWIiOiJmYjA0OTA1NC00NjA2LTRjMzYtYjRlOS0zODJkNWFiMzE2YjkiLCJlbWFpbCI6ImVzaXIuZHJlYW0udGVhbUBnbWFpbC5jb20iLCJvcmdfaWQiOiI2NTVlNTllYi01ZGMyLTQyN2QtYTkyMy00MmJmNDNkNWZiM2MiLCJ1c2VyX29yZ19pZCI6IjIxNDczZTQ0LTg5YzgtNDhjZS05OTVkLTliMGIxMjc4MGIwZSIsImludml0ZWRfYnlfZW1haWwiOiJ0b3RvQGdtYWlsLmNvbSJ9.d57u5aGIdxltgWHCxiIpMDO8KHgvwHm6pmAE35tUGFBvlr40tcdHecsrToftEkFlXI-b4cIas5lL3qsQhH_Ckq1yBvUAemd4fUB9jkst6Y2q0l7YAgjvxdLgLPnzcDjBHawpmxQKw0nZUQnZYj18ZQMPwZP6RjzbBQacdlkhw2Cclze8Kta1xJsg4TWvY1_CTU9a7KxxArEC6Pu7JeuRgtZXPO8HvCD3jw1u7NsScNNhhMyKss8iS1m5E7VZu2OkgAAt0fZO7Ky1S6WDE1VE3776vK1x_Ia1xPUJqBaCzpAPP7GQrKAPNdzSbTnPsCoQp8-uQtovfG1M7H4_v5beBw&email=esir.dream.team%40test.com&organizationUserId=21473e44-89c8-48ce-995d-9b0b12780b0e`

With emergency invitation no `token` request is sent.

I think it's an issue right here : https://github.com/bitwarden/web/blob/d71d0d9af635ff12d3f832bdf09a8d7c662c6cb9/src/app/accounts/register.component.ts#L93-L107 Emergency access doesn't seem to be handled. I'm not sure, I could be wrong.

If someone with a premium Bitwarden account could test if emergency invitation link are working, that could be a good starting point.

2021-04-26 18:25 UTC, thelittlefireman commented
Mmm i try a trial premium account and emergency invitation is working so back to start =/ I don't know what it's wrong. I need help on it :cry:

2021-04-26 18:59 UTC, fdisamuel commented
Hi @thelittlefireman ! 

I am not sure if this issue is related to the upstream implementation of emergency access, if this would be the case, there would have to be at least some issue ticket opened at community.bitwarden.com (I think.) 


After some testing on different devices, I was still not be able to create account with the link provided by email. But. I found a "workaround" for registering:

1. As the grantor invite the user form emergency-access panel
2. After that, go to the admin panel and you will see the invited user with his email address.
3. Delete the newly invited user from admin panel (but just from the admin panel --> user section!)
4. The grantee can finally register with the email link + he will be linked  as "designated emergency contact" for the grantor account as well, so he can 

Sure it is not the desired behavior but it shows that this issue is maybe somehow related to the management of invited users  
 in the bitwarden_rs API implementation.

2021-05-07 16:07 UTC, BlackDex commented
> Mmm i try a trial premium account and emergency invitation is working so back to the beginning I don't know what it's wrong. I need help on it cry

I think the issue is that it looks like the emergency access generates a different token then the invite via the admin generates.
This causes some checks to fail during registration and triggers the user already exists message.

You probably want to look at the invite function used to generate an invite via the admin interface, and the register function used when someone tries to register.

Besides that i did a quick test, and it looks like the basics work, like
* invite (an already existing user)
* view and takeover
* approve and reject
* also reject after an approval

I didn't checked the rest yet, like logic etc...

2021-05-16 14:05 UTC, BlackDex commented
Also, when re-basing this PR, check the e-mail templates, they have also changed.

2021-05-16 14:55 UTC, thelittlefireman commented
> Also, when re-basing this PR, check the e-mail templates, they have also changed.

rebase done. Still the same. @BlackDex  could it be possible to get some help ?

2021-05-16 19:47 UTC, jjlin commented
Given that this is a very large change and there are still issues to be resolved, I think it would make sense to put this in an integration branch so that

1. Other developers can contribute changes/fixes.
2. A Docker image can be built for it, so non-developers who want to test and report issues can do that more easily.

2021-05-25 12:00 UTC, TheDuffman85 commented
I suggest to integrate features switches into this PR and than merge it into master branch as soon as possible. The longer the integration drags on, the more frustrating it becomes for the creator of the PR. I have seen too many projects where the PR creator eventually lost interest and the PR was abandoned. For such an important feature, I think it would be a shame.

2021-05-25 12:13 UTC, BlackDex commented
> I suggest to integrate features switches into this PR and than merge it into master branch as soon as possible. The longer the integration drags on, the more frustrating it becomes for the creator of the PR. I have seen too many projects where the PR creator eventually lost interest and the PR was abandoned. For such an important feature, I think it would be a shame.

Well, i'm not fond of adding non-working features into master. I still need to find the time to help and debug this issue.
Since this project is done by volunteers during there spare time, probably also for the creator of this PR, we just need to have some patients.

I think that we all are very happy that someone spend time on this, and i also think that we all want to have this merged, but only if it is working fine instead of having a half working or bugged functionality which will do nobody any good.

2021-06-05 15:00 UTC, BlackDex commented
Ok, a few pointers i have found so far while trying to debug the emergency-access invite.

* When you have invited a user, and later is deleted in any way, either be the user it self, or by the admin accessing the **Emergency Access** page causes a panic, because it searches for a user that doesn't exists any more.
```
[2021-06-05 15:48:25.398][request][INFO] GET /api/emergency-access/trusted
[2021-06-05 15:48:25.400][panic][ERROR] thread 'unnamed' panicked at 'Grantee user not found.': src/db/models/emergency_access.rs:95
```
You also need to clean-up the emergency-access table when a user is removed from the vaultwarden system either by an admin or the user it self. But besides that,  you need to prevent  this panic from being triggered at all by catching this.

Regarding the not working invite, that is because the Token is not sent to the server when you register via the `/#/accept-emergency` link. This is because that token is only sent when you are going to login, that is where the verification is going to happen. So, i think you need to first let someone register, and after that they can use that invite link to accept the emergency access invite.

To try and fix this i think  you need to either limit the emergency access creation to either only existing users, or use the same way as the admin does when the user doesn't exits and send that e-mail an create account mail first, and right after that also the invite to the emergency access.

The problem i kinda have with this is that it then could become possible for people to bypass invites allowed if that is disabled.
So the logic should probably we the following.

When creating an emergency access contact:
* Check if the user exists already.
   * If user exists already, then only send the invite to become an Emergcy Contact.
   * If not and invites are allowed: Send invite to join Vaultwarden and send invite to become Emergency Contact (maybe you need to have different e-mail templates or some extra variable/string which states a user must first have an account).
   * If not and invites are **NOT** allowed: Return error stating to contact the admin to invite the user.

I checked the official bitwarden logic, and if i invite a non-existing user, i need to create an account, and after that i need to click the invite link again, and press login to actually accept the invite to become an emergency-contact.

2021-06-05 15:11 UTC, BlackDex commented
Also, i think that emergency access can't be active if e-mail is not active because how would someone be notified of an access request?

2021-06-06 17:06 UTC, thelittlefireman commented
@BlackDex 
Thanks a lot for this analysis.
But if I remember well, on the official Bitwarden, the emergency-contact invitation allow you to create an account. Token is working, and you could see it on the account creation page request (analysis on chrome). I don't understand why it's not working with our invitations ?

2021-06-06 17:10 UTC, BlackDex commented
Because vaultwarden can have signups disable unless created via the admin interface, which mimics an org invite, which in turn does pass on the token.

2021-07-14 11:44 UTC, pianoquintet commented
Hi, was watching this space with interest, as emergency access is a critical feature missing from vaultwarden.  I see no progress in over a month: has this project been abandoned?

2021-07-14 13:22 UTC, williamdes commented
> Hi, was watching this space with interest, as emergency access is a critical feature missing from vaultwarden. I see no progress in over a month: has this project been abandoned?

Hi @dani-garcia 
Could we speed up integrating this feature ?

> has this project been abandoned?

No, it is quite active

2021-07-14 13:27 UTC, BlackDex commented
> > Hi, was watching this space with interest, as emergency access is a critical feature missing from vaultwarden. I see no progress in over a month: has this project been abandoned?
> 
> Hi @dani-garcia
> Could we speed up integrating this feature ?
> 
Well there are some issues to be addressed, and that is normally something the person who created the PR should do, so in this case @thelittlefireman. It's not common to hijack a PR.

> > has this project been abandoned?
> 
> No, it is quite active

It is indeed. While sometime it could take a while for PR's to be merged   and new versions to be tagged.

2021-07-14 13:44 UTC, pepa65 commented
> It is indeed. While sometime it could take a while for PR's to be merged and new versions to be tagged.

He did ask for help in his last comment...

2021-07-14 13:53 UTC, BlackDex commented
> > It is indeed. While sometime it could take a while for PR's to be merged and new versions to be tagged.
> 
> He did ask for help in his last comment...

Which i did.

2021-07-15 16:48 UTC, thelittlefireman commented
Huge sorry, i was really busy this times. I fixed to subscribe issue. @fdisamuel  could you try this new version ?
@BlackDex i think we are close to be ready for merge. Feel free to retest :)

2021-07-15 16:49 UTC, thelittlefireman commented
link https://github.com/dani-garcia/bw_web_builds/pull/42

2021-07-15 17:52 UTC, jjlin requested changes

2021-07-15 18:20 UTC, thelittlefireman commented
@jjlin You are commented an outdated version, please look at the most recent commit.

2021-07-15 18:25 UTC, jjlin commented
AFAICT, most or all of it still applies.

2021-07-15 18:28 UTC, thelittlefireman commented on src/db/models/organization.rs
> +    pub fn find_by_user_and_type(user_uuid: &str, atype: i32, conn: &DbConn) -> Vec<Self> {
done

2021-07-15 19:53 UTC, thelittlefireman commented on src/api/core/emergency_accesses.rs
> +        err!("Emergency access is not allowed.")
I don't know. I think it's better to entirely enable or disable a feature, not some part of it. For example in case of vulnerability on this feature it could be possible to disable it.

2021-07-15 20:03 UTC, thelittlefireman commented on src/api/core/emergency_accesses.rs
> +        || (claims.emer_id.is_some() && emer_id != claims.emer_id.unwrap())
done. code cleannup

2021-07-15 20:04 UTC, thelittlefireman commented on src/api/core/emergency_accesses.rs
> +    if !CONFIG.emergency_access_allowed() {
done

2021-07-15 20:59 UTC, thelittlefireman commented on migrations/mysql/2021-02-10-174254_create_emergency_access/up.sql
> +CREATE TABLE emergency_accesses (
done

2021-07-15 20:59 UTC, thelittlefireman commented on src/main.rs
> +    // Create a new scheduler
done

2021-07-15 20:59 UTC, thelittlefireman commented on src/jobs.rs
> +pub fn emergency_request_timed_out_job() {
done

2021-07-15 21:02 UTC, thelittlefireman commented on src/main.rs
> +
done

2021-07-15 21:02 UTC, thelittlefireman commented on src/jobs.rs
> +pub fn init_db_job() -> DbConn {
done

2021-07-15 21:03 UTC, thelittlefireman commented
> AFAICT, most or all of it still applies.

most of are done ;) happy reviewing

2021-07-16 01:50 UTC, pepa65 commented on src/api/core/emergency_accesses.rs
> +        err!("Emergency access is not allowed.")
Ideally you'd have both config options: to be able to prevent new signups, and to disable the feature altogether.

2021-07-16 10:01 UTC, thelittlefireman commented on src/api/core/emergency_accesses.rs
> +        err!("Emergency access is not allowed.")
Signup is already handle by `signups_allowed`

2021-07-26 13:01 UTC, BlackDex commented
@thelittlefireman i just did a quick glance over it, and i think it looks nice, just a few remarks.
1. The code needs some `cargo fmt` love i think, i see some `check_emergency_access_allowed()?` without indentation for example and some other small items.
2. The html mail templates arn't the same as the others. There is a shared header/footer now to prevent the need to modify all the templates every time we need to change something to the layout.

Also, when all seems to be working, in the end it would be nice to have just one commit, but that is something to be done at the very end.

Overall nice job i think.

2021-07-27 22:16 UTC, thelittlefireman commented
> @thelittlefireman i just did a quick glance over it, and i think it looks nice, just a few remarks.
> 
> 1. The code needs some `cargo fmt` love i think, i see some `check_emergency_access_allowed()?` without indentation for example and some other small items.
> 2. The html mail templates arn't the same as the others. There is a shared header/footer now to prevent the need to modify all the templates every time we need to change something to the layout.
> 
> Also, when all seems to be working, in the end it would be nice to have just one commit, but that is something to be done at the very end.
> 
> Overall nice job i think.

Done :)

2021-08-01 15:30 UTC, thelittlefireman commented
Fix for clippy

2021-08-08 21:47 UTC, MartB commented
@dani-garcia status on the review?
Im looking forward to this feature being an official part of vaultwarden and with the amount of work @thelittlefireman put into this since february it would be great if this would get approved in a timely manner.

2021-08-09 13:57 UTC, MartB requested changes
Great job, i added some potential code styling improvements.
The `bitwarden_rs` reference also needs to be removed, but besides that i did not find anything obvious thats broken. 

Im not familiar with rust nor vaultwardens source code so someone more experienced will have to take a look at this.

I set this up on my private instance and the grantor / grantee parts worked flawlessly.
Thanks for your time and this contribution!

2021-08-09 13:57 UTC, MartB commented on src/static/templates/email/emergency_access_invite_accepted.html.hbs
> +            To confirm this user, <a href="{{url}}/">log into</a> the bitwarden_rs web vault, go to settings and confirm the user.
Please consider removing the `bitwarden_rs` string.
It could be stripped in this context or replaced with vaultwarden.

2021-08-09 13:57 UTC, MartB commented on .env.template
> +# EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE="0 0 * * * *"
Double space after checks.
Can you slightly reword this description?
I would also add the 10 Minutes after the hour bit into the cron string below instead of the one used right now

2021-08-09 13:57 UTC, MartB commented on .env.template
> +# EMERGENCY_REQUEST_TIMEOUT_SCHEDULE="0 0 * * * *"
Same as above, rewording this to be slightly more readable should do.
The cron string example should also be changed here.

2021-08-09 13:57 UTC, MartB commented on .gitignore
> +# Fuzz data
Do we generate this somewhere in the repository?
If not can you drop it from the commit?

2021-08-09 13:57 UTC, MartB commented on src/api/core/emergency_access.rs
> +        err!("Emergency Access not valid.");
random caps on Access.
I would prefer all the error strings to be defined once and then referenced instead of duplicated too, what do you think?

2021-08-09 13:57 UTC, MartB commented on src/api/core/emergency_access.rs
> +    let emergency_access = match EmergencyAccess::find_by_uuid(&emer_id, &conn) {
These few lines end up being repeated quite a lot, can you move them to a helper?
Same for the "Grantor user not found." and possibly other common checks.

2021-08-09 13:57 UTC, MartB commented on src/api/core/emergency_access.rs
> +    if let Ok(conn) = pool.get() {
I would flip this check around to save an indent level.

2021-08-09 13:57 UTC, MartB commented on src/api/core/emergency_access.rs
> +            if !CONFIG.is_email_domain_allowed(&grantor_user.email) {
`mail_enabled` and `email_domain_allowed` could be combined into a helper and reused for some other occurences.

2021-08-09 13:57 UTC, MartB commented on src/api/core/emergency_access.rs
> +                    if !CONFIG.is_email_domain_allowed(&grantor_user.email) {
Move this check up below the the grantor_user retrieval.

2021-08-09 13:57 UTC, MartB commented on src/config.rs
> +        /// Defaults to hourly. Set blank to disable this job.
Same rewording required as in the  .env descriptions, just take these cron expressions and put them into the .env file.

2021-08-09 13:57 UTC, MartB commented on src/api/core/emergency_access.rs
> +    if let Ok(conn) = pool.get() {
Could also be one indent less if flipped here.

2021-08-09 14:16 UTC, BlackDex commented on src/api/core/emergency_access.rs
> +            if !CONFIG.is_email_domain_allowed(&grantor_user.email) {
I all other locations we separate these checks, so we first check if the domain is allowed, if not, generate an `err!()` which indicates that that domain isn't allowed. And after that we check if email is enabled. It kinda depends on the flow, but if i'm correct emergency access only works when mail is enabled. In this case it could also be separated which safes a nested if. and it could be checked before the mail enabled check.

2021-08-10 22:58 UTC, thelittlefireman commented on .gitignore
> +# Fuzz data
done

2021-08-10 22:58 UTC, thelittlefireman commented on src/static/templates/email/emergency_access_invite_accepted.html.hbs
> +            To confirm this user, <a href="{{url}}/">log into</a> the bitwarden_rs web vault, go to settings and confirm the user.
done

2021-08-10 23:07 UTC, thelittlefireman commented on src/api/core/emergency_access.rs
> +                    if !CONFIG.is_email_domain_allowed(&grantor_user.email) {
done

2021-08-10 23:13 UTC, thelittlefireman commented on src/api/core/emergency_access.rs
> +    if let Ok(conn) = pool.get() {
done

2021-08-10 23:13 UTC, thelittlefireman commented on src/api/core/emergency_access.rs
> +    if let Ok(conn) = pool.get() {
done

2021-08-10 23:36 UTC, thelittlefireman commented on .env.template
> +# EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE="0 0 * * * *"
Could you make a description suggestion please ?

2021-08-10 23:36 UTC, thelittlefireman commented on .env.template
> +# EMERGENCY_REQUEST_TIMEOUT_SCHEDULE="0 0 * * * *"
Could you make a description suggestion please ?

2021-08-23 19:57 UTC, TheDuffman85 commented
So why is this PR not merged? Are there any status updates?

2021-08-23 20:23 UTC, BlackDex commented
> So why is this PR not merged? Are there any status updates?

Well, for one: https://github.com/dani-garcia/vaultwarden/pull/1377/checks?check_run_id=3360855521
And there are some open items.

2021-08-23 21:08 UTC, thelittlefireman commented on src/api/core/emergency_access.rs
> +            if !CONFIG.is_email_domain_allowed(&grantor_user.email) {
Emergency access works even if email are not enable (auto accept like in organization invitation)

2021-08-23 21:10 UTC, thelittlefireman commented
I really don't have time to work on lasts suggestions sorry :disappointed: . Please merge this PR and make changes after

2021-08-23 21:10 UTC, jjlin commented on src/api/core/emergency_access.rs
> +        err!("Emergency Access not valid.");
Emergency Access is a proper noun. It's the name of the feature. See https://bitwarden.com/help/article/emergency-access/.

2021-08-23 21:39 UTC, BlackDex commented
Well, we can't merge as is, since we do not want to merge broken/out-of-sync PR's.

I think you have the `allow edits from maintainers` enabled, so that would mean i should be able to update this PR. When i have some time i will try to update some items.

2021-08-23 21:45 UTC, thelittlefireman commented on src/api/core/emergency_access.rs
> +        err!("Emergency Access not valid.");
done

2021-08-23 21:47 UTC, thelittlefireman commented
> Well, we can't merge as is, since we do not want to merge broken/out-of-sync PR's.
> 
> I think you have the `allow edits from maintainers` enabled, so that would mean i should be able to update this PR. When i have some time i will try to update some items.

i've added some compile error on my previous push, now it's fixed

2021-08-28 16:44 UTC, hrvylein commented
who else is hammering f5 to see this getting merged? ;D

2021-08-28 17:31 UTC, BlackDex commented
Ill see if i can check this tomorrow and where needed make adjustments.

2021-08-29 17:01 UTC, MartB commented on .env.template
> +# EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE="0 0 * * * *"
How about:
`Cron schedule of the job that sends expiration reminders to emergency request grantors.`

2021-08-29 17:02 UTC, MartB commented on .env.template
> +# EMERGENCY_REQUEST_TIMEOUT_SCHEDULE="0 0 * * * *"
I would probably go for something like this:
`Cron schedule of the job that checks for expired (i.e granted by timeout) emergency requests.`

2021-08-29 17:03 UTC, MartB commented on src/config.rs
> +        /// Defaults to hourly. Set blank to disable this job.
If reworded like above the only thing missing thats "easily" changeable are the cron timings in the .env file.

2021-08-29 17:05 UTC, MartB commented on src/api/core/emergency_access.rs
> +    let emergency_access = match EmergencyAccess::find_by_uuid(&emer_id, &conn) {
As discussed below, this could be postponed for general cleanup by a more experienced maintainer.

2021-08-30 17:02 UTC, thelittlefireman commented on .env.template
> +# EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE="0 0 * * * *"
Perfect, done. thanks ;)

2021-08-30 17:02 UTC, thelittlefireman commented on .env.template
> +# EMERGENCY_REQUEST_TIMEOUT_SCHEDULE="0 0 * * * *"
Perfect, done. thanks ;)

2021-08-30 17:02 UTC, thelittlefireman commented on src/api/core/emergency_access.rs
> +    let emergency_access = match EmergencyAccess::find_by_uuid(&emer_id, &conn) {
agreed

2021-08-30 17:02 UTC, thelittlefireman commented on src/config.rs
> +        /// Defaults to hourly. Set blank to disable this job.
done

2021-08-30 18:39 UTC, BlackDex commented
I have made some changes, but i'm now trying to get it to be merged/commited to this PR. No luck yet :p.

2021-08-30 19:02 UTC, thelittlefireman commented
> I have made some changes, but i'm now trying to get it to be merged/commited to this PR. No luck yet :p.

haha, just send me a git patch file i will add it ;)

2021-08-30 19:14 UTC, BlackDex commented
> > I have made some changes, but i'm now trying to get it to be merged/commited to this PR. No luck yet :p.
> 
> haha, just send me a git patch file i will add it ;)

@thelittlefireman 

I have a commit here at my repo:
https://github.com/BlackDex/vaultwarden/commit/3bc4f231a94281cda1905e80c7ba7ab2c7ec9e82
https://github.com/BlackDex/vaultwarden/commit/3bc4f231a94281cda1905e80c7ba7ab2c7ec9e82.patch
https://github.com/BlackDex/vaultwarden/commit/3bc4f231a94281cda1905e80c7ba7ab2c7ec9e82.diff

It also has the comments what and why :)

2021-08-30 19:34 UTC, BlackDex commented on src/jobs.rs
> +            (emer.last_notification_at.is_none() || (emer.last_notification_at.is_some() && Utc::now().naive_utc() >= emer.last_notification_at.unwrap() + Duration::days(1) )){
The logic is ok. It will only send those reminders every day once a day until the timeout is is eventually reached, which will change the status, and therefore will not be fetched by this function anymore.

And it it looks like upstream does the same.

2021-09-01 10:56 UTC, thelittlefireman commented
> > > I have made some changes, but i'm now trying to get it to be merged/commited to this PR. No luck yet :p.
> > 
> > 
> > haha, just send me a git patch file i will add it ;)
> 
> @thelittlefireman
> 
> I have a commit here at my repo:
> [BlackDex@3bc4f23](https://github.com/BlackDex/vaultwarden/commit/3bc4f231a94281cda1905e80c7ba7ab2c7ec9e82)
> https://github.com/BlackDex/vaultwarden/commit/3bc4f231a94281cda1905e80c7ba7ab2c7ec9e82.patch
> https://github.com/BlackDex/vaultwarden/commit/3bc4f231a94281cda1905e80c7ba7ab2c7ec9e82.diff
> 
> It also has the comments what and why :)

Done !
i've made a second commit to keep your commit message, but do prefer to make one feature commit ?

2021-09-03 12:47 UTC, BlackDex approved these changes

2021-09-09 11:01 UTC, TheDuffman85 commented
The PR branch is out-of-date again, because it wasn't merged in a timely matter. Seems to be an endless story 🙈

2021-09-09 11:24 UTC, BlackDex commented
> The PR branch is out-of-date again, because it wasn't merged in a timely matter. Seems to be an endless story see_no_evil

It has nothing to do with "merging in a timely matter" That is just how git works. If files overlap in other PR's then this will happen.
Sometimes this is no issue, and it can be merged without any issues, sometimes it is because there could be merge conflicts.
Doesn't matter which goes first, if they touch the same files this will happen.

2021-09-09 11:27 UTC, kbabioch commented
> It has nothing to do with "merging in a timely matter" That is just how git works. If files overlap in other PR's then this will happen.

Of course it has also something to do with "merging in a timely matter". When you merge a branches, this can no longer happen, as the ones working on new features will have to consider the changes that have recently been merged.

Obviously this doesn't mean that you should merge just for the sake of merging it "quickly", but having stale branches lying around for a long time, will only mean, that they will a.) become non-working and b.) need to be rebased later on. This feature in particular is quite old already and has a long history. It has been updated multiple times already.

2021-09-09 11:30 UTC, BlackDex commented
> > It has nothing to do with "merging in a timely matter" That is just how git works. If files overlap in other PR's then this will happen.
> 
> Of course it has also something to do with "merging in a timely matter". When you merge a branches, this can no longer happen, as the ones working on new features will have to consider the changes that have recently been merged.
> 
> Obviously this doesn't mean that you should merge just for the sake of merging it "quickly", but having stale branches lying around for a long time, will only mean, that they will a.) become non-working and b.) need to be rebased later on. This feature in particular is quite old already and has a long history. It has been updated multiple times already.

And where it was only from my point of view merge ready until a few commits ago, so yea sometimes new large features take time.

2021-09-10 21:46 UTC, hrvylein commented
but why isn't it merged when it is approved?

2021-09-16 23:28 UTC, thelittlefireman commented
Fix conflict

2021-09-19 22:03 UTC, merged

2021-09-19 22:07 UTC, dani-garcia commented
Alright, this seems in a good state for a merge, thank you all for your patience, I'll push the web vault patch and create a new release to include it in the testing image tomorrow.