Fix syncing with Bitwarden Desktop v1.28
dani-garcia/vaultwarden pull request #1925
Opened 2021-08-20 15:20 UTC by BlackDex

Syncing with the latest desktop client fails because it excepts some
json key/values to be there.

This PR adds those key/value pairs.

Resolves #1924

2021-08-20 15:31 UTC, jjlin requested changes

2021-08-20 15:31 UTC, jjlin commented on src/db/models/user.rs
> +            "Object": "profile",
The `Object` key should either be at the top or remain at the bottom. A trailing comma on the last entry would be good too.

2021-08-20 15:33 UTC, BlackDex commented on src/db/models/user.rs
> +            "Object": "profile",
Why is that? Doesn't matter where it is as long is it is there

2021-08-20 15:34 UTC, williamdes approved these changes

2021-08-20 15:34 UTC, jjlin commented on src/db/models/user.rs
> +            "Object": "profile",
Because that's the object type key, which is common across all responses, and therefore "special" in some sense. Also, it's the convention throughout the codebase.

2021-08-21 08:39 UTC, BlackDex commented on src/db/models/user.rs
> +            "Object": "profile",
Well, i agree upon the rest of the code base. But in general, it doesn't matter where it is at, though a quick look at the top or bottom and seeing this specific item is nice.

2021-08-21 08:41 UTC, BlackDex commented
Even though they seem to have fixed this issue in v1.28.1, i think it is useful to have this added, since who knows what future updates will bring without these values.

2021-08-22 20:30 UTC, merged