Update Debian base images to bullseye
dani-garcia/vaultwarden pull request #1959
Opened 2021-09-04 07:49 UTC by jjlin

2021-09-04 09:31 UTC, BlackDex approved these changes

2021-09-04 10:17 UTC, BlackDex requested changes
I did approved it already, but if we are going to use bullseye as a runtime, we probably also want to use that for building. So maybe change the default rust:1.54 to rust:1.54-bullseye ?

2021-09-04 18:47 UTC, jjlin commented
> I did approved it already, but if we are going to use bullseye as a runtime, we probably also want to use that for building. So maybe change the default rust:1.54 to rust:1.54-bullseye ?

Sure, updated.

2021-09-05 11:50 UTC, BlackDex approved these changes

2021-09-08 21:27 UTC, merged