Basic ratelimit for user login (including 2FA) and admin login
dani-garcia/vaultwarden pull request #2165
Opened 2021-12-22 20:51 UTC by dani-garcia

Might need to adjust the default rate limiting values and explain their use better.

Also needs to document their use in the .env template.

2021-12-22 20:59 UTC, BlackDex commented
That looks very simple indeed. Will be a nice addition. Ill see if i can do some checks tomorrow :).

2021-12-22 21:16 UTC, williamdes commented on src/ratelimit.rs
> +            err_code!("Too many admin requests", 429);
https://http.cat/

A bit of fun for everyone

2021-12-22 21:17 UTC, williamdes approved these changes

2021-12-23 14:16 UTC, BlackDex approved these changes

2021-12-23 14:18 UTC, BlackDex requested changes
All looks fine, but i'm missing the new config values in the `.env.template` file :).

2021-12-24 10:22 UTC, jjlin requested changes

2021-12-24 10:22 UTC, jjlin commented on src/config.rs
> +        /// Seconds between login requests |> Number of seconds, on average, between login requests before rate limiting kicks in. Note that this applies to both the login and the 2FA, so it's recomm
It would probably be helpful to clarify that this limit is per IP.

2021-12-25 08:13 UTC, BlackDex approved these changes

2021-12-27 23:27 UTC, merged