Upgrade Feature-Policy to Permissions-Policy
dani-garcia/vaultwarden pull request #2228
Opened 2022-01-11 16:43 UTC by iamdoubz

Convert old, [soon to be defunct](https://w3c.github.io/webappsec-permissions-policy/), Feature-Policy with its replacement Permissions-Policy

2022-01-11 22:06 UTC, BlackDex approved these changes

2022-01-11 22:34 UTC, jjlin requested changes

2022-01-11 22:34 UTC, jjlin commented on src/util.rs
> +        res.set_raw_header("Permissions-Policy", "accelerometer=(); ambient-light-sensor=(); autoplay=(); camera=(); encrypted-media=(); fullscreen=(); geolocation=(); gyroscope=(); magnetometer=();
`Permissions-Policy` uses commas as separators, not semicolons.

2022-01-12 01:48 UTC, williamdes approved these changes

2022-01-12 02:10 UTC, iamdoubz commented on src/util.rs
> +        res.set_raw_header("Permissions-Policy", "accelerometer=(); ambient-light-sensor=(); autoplay=(); camera=(); encrypted-media=(); fullscreen=(); geolocation=(); gyroscope=(); magnetometer=();
That is what I get for copy + paste. I have changed the semicolons to commas.

2022-01-12 13:38 UTC, BlackDex commented on src/util.rs
> +        res.set_raw_header("Permissions-Policy", "accelerometer=(); ambient-light-sensor=(); autoplay=(); camera=(); encrypted-media=(); fullscreen=(); geolocation=(); gyroscope=(); magnetometer=();
Could you squash the commits? Or do a force push?

The following should work (but this isn't tested)
```bash
git reset --soft HEAD~1
git commit --amend --no-edit
git push origin +iamdoubz-feature-to-permissions-policy-patch
```

2022-01-12 16:40 UTC, iamdoubz commented on src/util.rs
> +        res.set_raw_header("Permissions-Policy", "accelerometer=(); ambient-light-sensor=(); autoplay=(); camera=(); encrypted-media=(); fullscreen=(); geolocation=(); gyroscope=(); magnetometer=();
That was really fun... there is only one commit now. (PS The three commands did work)

2022-01-23 23:18 UTC, merged