Database connection init
dani-garcia/vaultwarden pull request #2440
Opened 2022-04-27 01:01 UTC by jjlin

Adds support for database connection init statements. This is probably mainly useful for running connection-scoped pragma statements.

Also adds default connection-scoped pragmas for SQLite:

* [`PRAGMA busy_timeout = 5000`](https://www.sqlite.org/pragma.html#pragma_busy_timeout) tells SQLite to keep trying for up to 5000 ms when there is lock contention, rather than aborting immediately. This should hopefully prevent the vast majority of "database is locked" panics observed since the async transition, e.g.: #2436

* [`PRAGMA synchronous = NORMAL`](https://www.sqlite.org/pragma.html#pragma_synchronous) trades better performance for a small potential loss in durability (the default is `FULL`). The SQLite docs recommend `NORMAL` as "a good choice for most applications running in WAL mode".

2022-04-27 04:36 UTC, BlackDex requested changes

2022-04-27 04:36 UTC, BlackDex commented on src/config.rs
> +        sqlite_conn_init:       String, false,  def,    "PRAGMA busy_timeout = 5000; PRAGMA synchronous = NORMAL;".to_string();
Do we really need multiple options?
Can't we just use one option, and if empty set some defaults determined by the connection type?
Since we can only have one database type at all per running application.

2022-04-27 06:36 UTC, jjlin commented on src/config.rs
> +        sqlite_conn_init:       String, false,  def,    "PRAGMA busy_timeout = 5000; PRAGMA synchronous = NORMAL;".to_string();
It could be done that way, but then it's not as clear to the user what the default is for each database type. Since pragmas are database-specific, you can also end up with cases where the user sets init statements for one database, then switches to another database and inadvertently carries over the incompatible init statements.

2022-04-28 08:58 UTC, BlackDex commented on src/config.rs
> +        sqlite_conn_init:       String, false,  def,    "PRAGMA busy_timeout = 5000; PRAGMA synchronous = NORMAL;".to_string();
That kinda same goes for the `DATABASE_URL` parameter. While that does implicate the type of the database it self within the string, it still is one variable. If a user is going to switch from one db-type to an other, that does take some manual effort. And with that manual effort i think changing the `init` config should be part of it.

In reality, how often do people change there database type and would also have the init configured manually if we already provide a sane default.

Documenting the default per type, and stating it will use the default only for that type seems more logical to me.

I find adding 3 more configuration items which are mutually exclusive anyways based upon the database type is to much and only clutters the configuration more then it already is.

2022-04-29 07:25 UTC, jjlin commented on src/config.rs
> +        sqlite_conn_init:       String, false,  def,    "PRAGMA busy_timeout = 5000; PRAGMA synchronous = NORMAL;".to_string();
As I alluded to earlier, the main advantage of separate config options is that the defaults are *self-documenting*. From the admin page, the user can literally see what the default would be, straight from the source of truth. (There are not really useful defaults you could have for `database_url` in the MySQL/PostgreSQL cases, so that's a key difference.)

With a single config option, the obvious default is the empty string, to indicate that the real default is to be determined elsewhere. This makes things more magical for the average user, who must now take on faith that the docs are up-to-date. To users who doesn't read the docs closely or undertand English well, it may even give the impression that the default is simply the empty string (i.e., no connection init).

As far as adding clutter goes, you either have extra lines to define config options along with their defaults, or extra lines documenting what the defaults are for each database type. I don't see a substantial difference there.

That said, I understand why having less config options "feels" cleaner -- I'm just pointing out why I don't see it as a clear win in this case. I also don't feel as strongly about it as you seem to, so I've changed it to the single config approach to move things forward.

2022-04-29 16:15 UTC, BlackDex commented on src/config.rs
> +        sqlite_conn_init:       String, false,  def,    "PRAGMA busy_timeout = 5000; PRAGMA synchronous = NORMAL;".to_string();
Well, I'm always open for discussion about anything. And i might appear to be a bit harsh about this, but i just want to minimize the already bloated config options.

With the latest commit it looks ok for me :).
Very nice addition, since i do think some people could really benefit from this.
And with the async code, for SQLite it was needed in some situations.

Thx!

2022-04-29 16:16 UTC, BlackDex approved these changes

2022-05-11 20:21 UTC, merged

2022-05-11 20:22 UTC, dani-garcia commented
With this merged we can probably consider removing some of the uses of crate::util::retry() which I think was added to solve this "Database locked" issue as well.

2022-05-11 20:44 UTC, BlackDex commented
That depends. If this was only for sqlite, the probably yes.
It could also happen with mysql when deleting and adding ciphers are done at the same time and a lock is on a table of course.