Adding "UserEnabled" and "CreatedAt" member to the json output of a User
dani-garcia/vaultwarden pull request #2523
Opened 2022-06-01 13:34 UTC by Lowaiz

Adding "UserEnabled"  and "CreatedAt" member to the json output of a User in the `admin/users` and `admin/users/<ID>` web routes.

2022-06-01 14:57 UTC, BlackDex requested changes
I'd rather not add those items there, since these are also used to return the user object to the Bitwarden clients.
It is better to add them to the generated json output within `admin.rs` instead.

Same goes for #2524, and in that case, i would probably suggest to merge them into one PR instead of two different ones.

2022-06-01 17:03 UTC, BlackDex commented
Since the rest of the json is CamelCase i think it is best to keep that the same in this case.

2022-06-02 08:28 UTC, Lowaiz commented
Here is the Camel Case !

2022-06-02 09:09 UTC, BlackDex commented
Could you squash the commits into one commit? Else it will clutter the git-history a bit.
You could do that with (from the top of my head)
```bash
git reset --soft HEAD~4
git commit -a
git push origin +add_disabled_member_to_json_user
```
That should reset the commits to the starting point you were, and leave the changes you made.
Then you can commit that again, and do a force push so the latest commit will be the only commit here :) .

2022-06-02 09:44 UTC, Lowaiz commented
Squash done and thank you for the commands.

2022-06-02 12:50 UTC, BlackDex requested changes

2022-06-02 12:50 UTC, BlackDex commented on src/api/admin.rs
> +    const DT_FMT: &str = "%Y-%m-%d %H:%M:%S %Z";
I think it is better to move this `const` and all the others with the same value outside of the functions and place it near the other global `const` at line 80.

2022-06-02 13:15 UTC, BlackDex commented
The build fails because it's not formatted correctly.
I suggest to install `pre-commit` and use that.
See: https://pre-commit.com/

This repo already has the correct pre-commit config there, all you need to do after you installed it is run `pre-commit install`, then run the `--reset soft` again and do a commit, this will check everything which is needed for the PR to be valid.

2022-06-02 18:36 UTC, BlackDex approved these changes

2022-06-04 17:19 UTC, merged