Use a temporary redirect
dani-garcia/vaultwarden pull request #2715
Opened 2022-08-29 10:22 UTC by RealOrangeOne

Fixes #2448

2022-08-29 10:32 UTC, williamdes approved these changes

2022-08-29 12:28 UTC, BlackDex commented
This could cause issues, as i already explained in the post you linked too.
A 301 could still redirect using the same POST/PUT method instead of using the required GET we need to happen (This could cause a recursion, which most browser will tend to stop after x amount of time).
Also. there is an other issue reported here: #2712 which states that it actually should be a 401, which i think would be better.
And the `too many requests` should also be different, it should be a `429` for example.

So, as this PR is currently I would not tend to approve it.
If this can be changed to have the correct error codes like suggested in #2712, that would be great :).

2022-08-29 12:35 UTC, BlackDex requested changes

2022-08-29 12:35 UTC, BlackDex commented on src/api/admin.rs
> +        return Err(Flash::error(Redirect::temporary(admin_url(referer)), "Too many requests, try again later."));
This should actually be a `429`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

2022-08-29 12:35 UTC, BlackDex commented on src/api/admin.rs
> +        Err(Flash::error(Redirect::temporary(admin_url(referer)), "Invalid admin token, please try again."))
This should be a `401`:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2022-08-29 12:35 UTC, BlackDex commented on src/api/admin.rs
> +        Ok(Redirect::temporary(admin_url(referer)))
This should still be a `303`, since method function only reacts to a `POST` and we need it to turn into a `GET`.

It is also stated to only use `302` for `GET` and `HEAD`, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302

And also see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303

2022-08-29 12:35 UTC, BlackDex commented on src/api/admin.rs
> +    Redirect::temporary(admin_url(referer))
This would be fine, since here we respond to a `GET` request, and a `302` here would be fine.

2022-08-29 12:37 UTC, BlackDex commented
There probably need to be some changes in how the response will be displayed to the user, because we currently use Flash Messages for this, which seem to only support redirects and no other status codes.

2022-08-30 07:53 UTC, RealOrangeOne commented on src/api/admin.rs
> +        return Err(Flash::error(Redirect::temporary(admin_url(referer)), "Too many requests, try again later."));
I think these codes all still need to be redirects of some sorts. These error-specific status codes will only work when it's an API call. If this were changed to a 429, then the user would never see the flash message, as they'd never end up back on the admin page for it to show up.

2022-08-30 07:57 UTC, BlackDex commented on src/api/admin.rs
> +        return Err(Flash::error(Redirect::temporary(admin_url(referer)), "Too many requests, try again later."));
That is why i mentioned there are more code changes needed for this to fully work.
Instead of a Flash Message, it needs to return the HTML it self.

Since the template already has it there with the `{{error}}` value. It shouldn't be that hard to fix though i think.

2022-09-06 15:20 UTC, BlackDex commented
@RealOrangeOne I have created a PR which should solve this, I added you as a Co-Author since you initiated this change.
I marked it to have this one closed when that PR has been excepted and merged.

2022-09-08 15:46 UTC, closed without merging