Lock accounts after X login failures, configurable
dani-garcia/vaultwarden pull request #2747
Opened 2022-09-16 21:14 UTC by Willena

I saw this feature request in #246 

The implementation reuse the user enabling feature to lock the account. It simply automatically disable the user when the number of retries is reach. When locked, only an admin can re-enable the user account.

A new column has been added to the user schema to store the number of failed attempts.
It is configurable with the `login_max_retry` configuration key. The default value is 0 which disable automatic account locking

*Any remarks tips and comments are welcomed as I'm not yet familiar with rust and currently trying to learn it*

2022-09-16 21:32 UTC, williamdes commented on migrations/mysql/2022-09-15-002500_add_login_attempts/up.sql
> +ALTER TABLE users ADD COLUMN invalid_login_count INTEGER NOT NULL DEFAULT 0;
I would say it's an unsigned integer
Not sure how this project handles integers

2022-09-16 22:23 UTC, BlackDex requested changes
While overall i think it looks ok. I'm not sure if i would approve this. I haven't searched for it yet, but I remember that I have declined something similar like this because this could be abused. If i know your mail address i can lock you out from your own account, which i think is a very bad option.

Also, there already is a rate limit for logins active by default which prevents brute force attempts.

I did add some remarks, but that's more for learning, because I tend more to not having this merged my self.

2022-09-16 22:23 UTC, BlackDex commented on src/api/identity.rs
> +    }
It's probably best if this is only saved when the count isn't 0, else it would trigger an unnecessary save action.

2022-09-16 22:23 UTC, BlackDex commented on migrations/mysql/2022-09-15-002500_add_login_attempts/up.sql
> +ALTER TABLE users ADD COLUMN invalid_login_count INTEGER NOT NULL DEFAULT 0;
Not sure from the top of my head if that will work nicely with diesel<>multiple db backends.

2022-09-20 19:47 UTC, Willena commented
> While overall i think it looks ok. I'm not sure if i would approve this. I haven't searched for it yet, but I remember that I have declined something similar like this because this could be abused. If i know your mail address i can lock you out from your own account, which i think is a very bad option.
> 
> Also, there already is a rate limit for logins active by default which prevents brute force attempts.
> 
> I did add some remarks, but that's more for learning, because I tend more to not having this merged my self.

I totally understand your point of view. Maybe the feature should be removed from the "[META] Feature request" issue. 
It was quite a simple feature and as I'm learning Rust I thought it was a good candidate. 

Just to add details, the implementation keeps the ratelimiter check before checking and update the number of tries. 

I'm not against closing the PR if you think it will never be integrated.

2022-10-15 12:09 UTC, BlackDex commented
I'm going to close this as I think this could be abused in a wrong way.
There already is a rate-limiter available for the login attempts which I think should be enough.

2022-10-15 12:09 UTC, closed without merging