Impl the "org API key" and "Public API" needed to use "Bitwarden Directory Connector"
dani-garcia/vaultwarden pull request #2907
Opened 2022-11-10 12:50 UTC by Kurnihil

Hello, 
I've started with the org-api-key branch of BlackDex [https://github.com/BlackDex/vaultwarden/tree/org-api-key](url)
And added what was needed to use the "Bitwarden Directory Connector".

I'm willing to continue with the implementation of the public API,
but before doing that I would like that somebody else look at the code.

I've tested it locally but for sure some more testing is needed.

2022-11-14 10:34 UTC, williamdes approved these changes

2022-12-12 23:12 UTC, tessus commented
BlackDex marked his branch and the commit as WIP. What you usually do, if you want to add or change code, is create a PR in BlackDex's repository.

2022-12-12 23:42 UTC, BlackDex commented
@tessus is missing some context, since i had contact with @Kurnihil regarding this, and i only created a starting point to help them further.

I haven't had any time yet to take a good look at this. And it does need to at least get a rebase especially since the last merge spree.

2022-12-12 23:44 UTC, tessus commented
Ah, I see. In this case I apologize for my comment.

2023-01-03 15:20 UTC, hudsonventura commented
Will this pull request be accepted? I hope so =D

2023-01-03 15:34 UTC, BlackDex commented
> Will this pull request be accepted? I hope so =D

Not in the current state, as it needs to be rebased, and we still need to test it of course.

2023-01-16 08:42 UTC, Kurnihil commented
I will try to rebase in the next few days, work permitting.
Sorry to have dropped it since now

2023-02-05 19:31 UTC, BlackDex commented
I did a quick test today, and using the latest available version of the Directory-Connector and a local LDAP deployment seems to work great as far as i can tell, it will create the users, add them as invited to the org.

So, apart from rebasing this PR, i think it at least works. Ill have to do some code-checking maybe later on.

2023-02-05 20:54 UTC, BlackDex requested changes

2023-02-05 20:54 UTC, BlackDex commented on src/db/models/user.rs
> +        }
This could be a bit less complex i think. And it will also look a bit more nice.

```suggestion
    let mut ext_id: Option<String> = None;
    if let Some(external_id) = external_id {
        if !external_id.is_empty() {
           ext_id = Some(external_id);
        }
    }
    self.external_id = ext_id;
```

2023-02-05 20:54 UTC, BlackDex commented on src/db/models/collection.rs
> +                }};
Is this something similar like #3108?

2023-02-05 20:54 UTC, BlackDex commented on src/db/models/collection.rs
> +                direct || indirect
Is this something similar like #3108?

2023-02-05 20:54 UTC, BlackDex commented on src/api/core/public.rs
> +    LargeImport: bool,
Is there a reason this is not used? Of so, maybe add that as a comment?
If I'm correct, Bitwarden uses this for 2000+ users in a single run.

2023-03-17 21:11 UTC, mkrauser commented
I've tested this successfully with Google Workspace

Thanks you for this, I hope it gets merged soon!

2023-06-10 16:18 UTC, BlackDex commented
I have an updated version of this PR in #3568 .

2023-06-13 07:05 UTC, closed without merging