Update config comment to reflect rfc8314.
dani-garcia/vaultwarden pull request #2911
Opened 2022-11-12 21:14 UTC by skid9000

TL;DR : Port 465 with implicit TLS for SMTP isn't outdated since RFC 8314

As stated in [RFC 8314](https://tools.ietf.org/html/rfc8314) : 
![image](https://user-images.githubusercontent.com/26208369/201494637-a9d70f67-89f9-4d89-b84d-c65b0ae2755a.png)

Also as stated [here](https://github.com/iredmail/iRedMail/issues/22#issuecomment-731779992) 

The IANA registry has been modified to register port 465 for native tls smtp connections : 

![image](https://user-images.githubusercontent.com/26208369/201494695-21b8f7a2-3243-44a6-80d2-93a46f67f399.png)

2022-11-12 21:37 UTC, tessus commented on .env.template
> +# SMTP_PORT=587          # Ports 587 (submission), 465 (submissions) and 25 (smtp) are standard without encryption and with encryption ports, 587 use STARTTLS (Explicit encryption) and 465 use native
No, this change is wrong.

The sentence `Ports 587 (submission), 465 (submissions) and 25 (smtp) are standard without encryption` is wrong.

465 is NEVER without encryption. The TLS handshake happens upon connection establishment. There is never unencrypted data flow.

This is correct for 587 and 25, because traffic is unencrypted until the STARTTLS command is sent.

```suggestion
# SMTP_PORT=587          # Ports 587 (submission) and 25 (smtp) are standard without encryption and with encryption via STARTTLS (Explicit TLS). Port 465 (submissions) is used for encrypted submission (Implicit TLS).
```

2022-11-12 21:39 UTC, skid9000 commented on .env.template
> +# SMTP_PORT=587          # Ports 587 (submission), 465 (submissions) and 25 (smtp) are standard without encryption and with encryption ports, 587 use STARTTLS (Explicit encryption) and 465 use native
Ah right, i typed that a little too fast.

Thanks for noticing it !

2022-11-12 21:40 UTC, tessus commented on .env.template
> +# SMTP_PORT=587          # Ports 587 (submission), 465 (submissions) and 25 (smtp) are standard without encryption and with encryption ports, 587 use STARTTLS (Explicit encryption) and 465 use native
You're welcome.

2022-11-15 09:53 UTC, BlackDex requested changes
The change looks ok. But this also needs to be change inside the `config.rs` file.
https://github.com/dani-garcia/vaultwarden/blob/7a7673103fb180098f18abe77b75ba085710b559/src/config.rs#L591

2022-11-15 09:55 UTC, BlackDex approved these changes

2022-11-27 20:59 UTC, merged