Update settings description
dani-garcia/vaultwarden pull request #2928
Opened 2022-11-21 14:56 UTC by karbobc

Update description from `login` to `admin` in admin page.

`Read-Only Config`
![image](https://user-images.githubusercontent.com/55901895/203086126-99f22617-4343-42c7-87db-03e811f0a1ce.png)

2022-11-21 15:00 UTC, BlackDex requested changes

2022-11-21 15:00 UTC, BlackDex commented on src/config.rs
> +        /// Max burst size for admin requests |> Allow a burst of requests of up to this size, while maintaining the average indicated by `admin_ratelimit_seconds`
Then, it actually should be `admin login` instead. Because now it implies on all admin requests, which is not the case.

2022-11-21 15:10 UTC, BlackDex commented on src/config.rs
> +        /// Max burst size for admin requests |> Allow a burst of requests of up to this size, while maintaining the average indicated by `admin_ratelimit_seconds`
the latter

2022-11-21 15:11 UTC, BlackDex commented on src/config.rs
> +        /// Max burst size for admin requests |> Allow a burst of requests of up to this size, while maintaining the average indicated by `admin_ratelimit_seconds`
Also, this probably needs to be changed in the template: https://github.com/dani-garcia/vaultwarden/blob/7a7673103fb180098f18abe77b75ba085710b559/.env.template#L305

2022-11-21 15:19 UTC, karbobc commented on src/config.rs
> +        /// Max burst size for admin requests |> Allow a burst of requests of up to this size, while maintaining the average indicated by `admin_ratelimit_seconds`
I'll update it at the same time.

2022-11-21 15:24 UTC, karbobc commented on src/config.rs
> +        /// Max burst size for admin requests |> Allow a burst of requests of up to this size, while maintaining the average indicated by `admin_ratelimit_seconds`
> Also, this probably needs to be changed in the template:
> 
> https://github.com/dani-garcia/vaultwarden/blob/7a7673103fb180098f18abe77b75ba085710b559/.env.template#L305

This doesn't seem to need an update.

2022-11-22 13:49 UTC, BlackDex commented on src/config.rs
> +        /// Max burst size for admin requests |> Allow a burst of requests of up to this size, while maintaining the average indicated by `admin_ratelimit_seconds`
Why not? It says `admin`, and not `admin login`. Would be best to keep both items consistent not?

2022-11-22 14:07 UTC, karbobc commented on src/config.rs
> +        /// Max burst size for admin requests |> Allow a burst of requests of up to this size, while maintaining the average indicated by `admin_ratelimit_seconds`
You're right, I will update it later.

2022-11-27 21:01 UTC, merged