Admin password reset
dani-garcia/vaultwarden pull request #3116
Opened 2023-01-06 14:44 UTC by sirux88

Since i'd like to use the admin reset password functionality within my instance I implemented the missing "Reset Master Password" policy and the needed functions

There are two points that (maybe) need improvment:

- Auto-enrollment won't work for instances without email enabled
- Bitwarden's reference implementation logs out the user to reset after resetting the password. I haven't found a api/method for this and also don't know how to implement

As i'm not used to programming in rust please feel free to comment and throw any improvements concering syntax.
All other improvements are welcome aswell

2023-01-06 16:16 UTC, BlackDex requested changes
Thanks for the contribution.
In general, since i haven't looked at the code that good yet.

You mentioned that it will not work without email being enabled.
In that case, please add restrictions and check if mail is enabled with `if CONFIG.mail_enabled() {`
and prevent this policy from being activated at all.
And, also check if the policy is enabled when an admin tries to use this feature, mail is still enabled, and not turned of afterwards. Maybe even prevent this policy from being active in that case?
That way we can prevent issue reports, and you can return an error message stating mail has to be enabled.

In regards to logging the user out. I have a PR open which helps with that for at least the web-socket enabled clients (#3076). But other then that, depending on if they need a hard logout/refresh from the user, you can use the `user.reset_security_stamp()` that will invalidate there security stamp, and will prevent any further valid communication from any client.

2023-01-07 11:20 UTC, sirux88 commented
Concerning logging out:

> In regards to logging the user out. I have a PR open which helps with that for at least the web-socket enabled clients (#3076). But other then that, depending on if they need a hard logout/refresh from the user, you can use the `user.reset_security_stamp()` that will invalidate there security stamp, and will prevent any further valid communication from any client.

1. Since resetting the password relies on `user.set_password` `user.reset_security_stamp()` is already been executed. Therefore this should be fine for non-websocket-enabled clients
2. I added your mentioned web-socket logout within my latest commit. 
Seems to me like the default behavior of at least web-vault

2023-01-07 11:23 UTC, BlackDex commented
>
> 2. I added your mentioned web-socket logout within my latest commit.
>    Seems to me like the default behavior of at least web-vault

That is true for the one you are currently using. But desktop client and browser extensions will now also receive the logout request, else they would in the end act upon the reset of the security stamp, but this is a bit nicer i think.

2023-01-07 11:41 UTC, sirux88 commented
> You mentioned that it will not work without email being enabled.
In that case, please add restrictions and check if mail is enabled with if CONFIG.mail_enabled() {
and prevent this policy from being activated at all.

Let me clarify a bit what I ment with "auto-enrollment":
The restriction I mentioned is only about auto-enrollment-feature. Auto-enrollment means newly invited users get enrolled automatically while accepting the invation. This is implemented within org-endpoint `/organizations/<org_id>/users/<_org_user_id>/accept`
On email-disabled-instances this endpoint is never gone to be hit. As a consequence reset-password can't be enrolled

Manual enrollment can always be done. Also in email-disabled instances. 
So there's no need to disable the policy at all for email-disabled instances.

2023-01-07 11:41 UTC, sirux88 commented on src/api/core/organizations.rs
> +
I already added a check on email-disabled instances. While setting the policy, an error is thrown if auto-enrollment is enabled on those instances preventing its usage

2023-01-07 12:56 UTC, sirux88 commented on src/api/core/organizations.rs
> +                        }
> And, also check if the policy is enabled when an admin tries to use this feature, mail is still enabled, and not turned of afterwards. Maybe even prevent this policy from being active in that case?
That way we can prevent issue reports, and you can return an error message stating mail has to be enabled.

I added a check that is preventing existing user invitation to current org if auto-enrollment is enabled but mailing is disabled.
This state can be reached if mailing was enabled while setting up the policy and disabling mailing afterwards.
I think this was what you ment.

2023-01-07 13:06 UTC, sirux88 commented on src/api/core/organizations.rs
> +                        }
I put the check aswell for non existing users if they get invited. They habe the same restrictions.

2023-01-07 13:18 UTC, sirux88 commented on src/api/core/organizations.rs
> +                        }
I refactored the stuff I did in my latest commit

2023-01-09 14:47 UTC, BlackDex commented on src/api/core/organizations.rs
> +                        }
While I still have not looked at this yet, but could you fix the clippy warnings `cargo clippy --features sqlite,mysql,postgresql` ? 
You can also install pre-commit and enable it for this repo so all checks are done before you commit :).

2023-01-09 19:15 UTC, sirux88 commented on src/api/core/organizations.rs
> +                        }
If I should do a rebase to current main, please tell me

2023-01-15 17:44 UTC, GeekCornerGH requested changes
You should rebase your PR

2023-01-16 15:49 UTC, sirux88 commented
Rebase done @GeekCornerGH

2023-01-17 20:45 UTC, BlackDex requested changes

2023-01-17 20:45 UTC, BlackDex commented on src/api/core/organizations.rs
> +
This is probably a nicer option. Which also does some type-checking.
It also prevents from checking the `policy_data` if mail is enabled. This saves some checking and converting cycles.

```suggestion
    if pol_type_enum == OrgPolicyType::ResetPassword && data.enabled && !CONFIG.mail_enabled() {
        if let Some(policy_data) = &data.data {
            if policy_data["autoEnrollEnabled"].as_bool().unwrap_or(false) {
                err!("Autoenroll can't be used since it requires enabled emailing")
            }
        }
    }
```

2023-01-17 20:45 UTC, BlackDex commented on src/api/core/organizations.rs
> +    //Nevertheless reset password is fully fuctiontional in settings without mailing by manual enrollment
Please add a space after the `//` 😄

2023-01-17 20:45 UTC, BlackDex commented on src/api/core/organizations.rs
> +        //Deserializing from "serde_json::from_value" won't work with current scope
Same here regarding the `//`

2023-01-19 18:52 UTC, sirux88 commented on src/api/core/organizations.rs
> +
I had something similar in the first place but I struggeld a bit with Rust.
Thanks for the improvement. I took it as you suggested

2023-02-03 16:53 UTC, BlackDex requested changes
Some small changes on items i see right now.
I haven't tested the code yet.

2023-02-03 16:53 UTC, BlackDex commented on migrations/mysql/2023-01-06-151600_add_reset_password_support/up.sql
> +ADD COLUMN reset_password_key VARCHAR(255);
Bitwarden uses `longtext` for this, we use `text` for all the other key columns.
I suggest to change this to `TEXT` to prevent issues with long keys.

2023-02-03 16:53 UTC, BlackDex commented on src/api/core/organizations.rs
> +    nt.send_user_update(UpdateType::LogOut, &user).await;
Please update this to `nt.send_logout()`;

```suggestion
    nt.send_logout(&user, None).await;
```

2023-02-03 17:23 UTC, BlackDex requested changes

2023-02-03 17:23 UTC, BlackDex commented on src/api/core/organizations.rs
> +) -> EmptyResult {
This function needs to check if `CONFIG.mail_enabled()` at the start of the function, and deny a password reset if not enabled. This could be a security risk when an admin in some way is able to disable this.

I might even say that we should send the mail first, if that is successful then reset the password, else don't even reset the password at all, since that also could cause a security issue.

It might even be better to do this during the `get_reset_password_details` function. That way it should prevent the UI from continuing i think.

Maybe you need to put some other `CONFIG.mail_enabled()` checks at some functions to prevent security issues regarding the password reset?

2023-02-03 17:24 UTC, BlackDex commented on migrations/mysql/2023-01-06-151600_add_reset_password_support/up.sql
> +ADD COLUMN reset_password_key VARCHAR(255);
I just tested the code, and my keys are bigger then 255.

2023-02-04 12:30 UTC, sirux88 commented on migrations/mysql/2023-01-06-151600_add_reset_password_support/up.sql
> +ADD COLUMN reset_password_key VARCHAR(255);
I changed this as suggested. Don't know why I did this in the first place and only for mysql.
Sorry for that

2023-02-04 12:30 UTC, sirux88 commented on src/api/core/organizations.rs
> +    nt.send_user_update(UpdateType::LogOut, &user).await;
Changed as suggested

2023-02-04 12:48 UTC, sirux88 commented on src/api/core/organizations.rs
> +) -> EmptyResult {
I changed a couple of think to get along with what you suggested.
I refactored two check routines and added those to the relevant methods for password resetting. 

Since the additional checks now exclude using reset password policy in email-disabled instances at all I ended up in blocking reset password policy (on email disabled instances) while setting it (an error is thrown).
This may disappoint users but in my eyes security goes first for that functionality

2023-02-04 12:48 UTC, sirux88 commented on src/api/core/organizations.rs
> +) -> EmptyResult {
Is there a chance to hide a policy conditionally @BlackDex? 
I don't see any endpoint that queries available policies (`"/organizations/<org_id>/policies")` only fetches the once that exist in database context not in general) or any other way to do this

2023-02-05 09:05 UTC, BlackDex requested changes
Some quick items i saw just now. Will try to further test and check later today.

2023-02-05 09:05 UTC, BlackDex commented on src/api/core/organizations.rs
> +    Ok(())
A `match` would be better suited here. Now all if statements are always processed while only one should be needed.

```suggestion
    match headers.org_user_type {
        UserOrgType::Owner => Ok(()),
        UserOrgType::Admin if target_user.atype <= UserOrgType::Admin => Ok(()),
        _ => err!("No permission to reset this user's password"),
    }
```

2023-02-05 09:12 UTC, BlackDex commented on src/api/core/organizations.rs
> +) -> EmptyResult {
You can hide that policy by setting https://github.com/dani-garcia/vaultwarden/pull/3116/files#diff-1fbd2918c7f409ef277132370231b3fb9646fe76f7661af3eeead167540ec671R162 to `false` if mail is disabled.

That should solve at least the checking during the enabling of the policy. I also think that it will prevent the interface from even showing the option to reset a users password if that is set to false.

Then the only thing still needed to be done is make sure the password isn't reset if the mail was unable to be sent, to prevent the users from not knowing it was reset.

2023-02-05 15:50 UTC, sirux88 commented on src/api/core/organizations.rs
> +) -> EmptyResult {
> You can hide that policy by setting https://github.com/dani-garcia/vaultwarden/pull/3116/files#diff-1fbd2918c7f409ef277132370231b3fb9646fe76f7661af3eeead167540ec671R162 to `false` if mail is disabled.
> 
> That should solve at least the checking during the enabling of the policy. I also think that it will prevent the interface from even showing the option to reset a users password if that is set to false.

Yeah you are right. Setting 'UseResetPassword' to false (conditionally by 'CONFIG.mail_enabled()') hides the policy.
Therefore I removed the check within setting the policy (as you mentioned aswell)

2023-02-05 15:52 UTC, sirux88 commented on src/api/core/organizations.rs
> +    Ok(())
much better than mine

2023-02-05 16:00 UTC, BlackDex approved these changes
Great! Looks nice, and seems to work fine during my tests.
Thanks for the contribution!

2023-02-05 16:03 UTC, sirux88 commented on src/api/core/organizations.rs
> +) -> EmptyResult {
> Then the only thing still needed to be done is make sure the password isn't reset if the mail was unable to be sent, to prevent the users from not knowing it was reset. Because all other items are already hidden.

Is https://github.com/dani-garcia/vaultwarden/pull/3116/files?diff=unified&w=0#diff-4a9695da74664125793a066394e03e68892b306081e00dc7861f2da1145b0c48R2539-R2543 not enough?

I put sending the email before resetting the password itself. The error thrown should interrupt processing if the email could not be sent.

One single point would remain, if the email won't get delivered by the email server. 
But I think we can't add any protection against that since it is out of vaultwarden's scope

2023-02-05 16:09 UTC, BlackDex commented on src/api/core/organizations.rs
> +) -> EmptyResult {
I think it's fine right now. We can't ensure the mail is delivered indeed. But we at least tried to be to be as certain as possible.

2023-02-12 17:38 UTC, dani-garcia approved these changes

2023-02-12 17:38 UTC, merged

2023-02-12 17:39 UTC, dani-garcia commented
Thanks!