add support for system mta though sendmail
dani-garcia/vaultwarden pull request #3147
Opened 2023-01-16 10:07 UTC by soruh

This PR enables using `lettre`'s `SendmailTransport` in Vaultwarden.

It adds two configuration options:
    - `USE_SENDMAIL` wether to use sendmail instead of directly connecting to a SMTP server
    -  `SENDMAIL_COMMAND` what sendmail command to use. By default the one from the `$PATH` is used, but I think there are cases where it makes sense to specify a different one

Supporting the system MTA allows for more flexible mail configuration without too much effort and does not require packaging any sendmail client as assumed in #2198.

While there are other usecases like sending through a local mailserver without having to create a dedicated SMTP Account as mentioned in #2198, my specific usecase for this is the following:

I have msmtp configured with an account that all applications use without me having to paste the SMTP configuration and credentials into each of their configs and allows me to only have to maintain the one SMTP configuration instead of potentially forgetting one (not fun).

Testing can be done as follows:

```bash
> sudo pacman -S msmtp-mta
> sudo tee /etc/msmtprc << EOF
defaults

account default
auth on
from <from>
host <hostname>
password <passowrd>
tls on
user <username>
EOF
> tee .env << EOF
USE_SENDMAIL = true
SMTP_FROM = "bitwarden@tld"
EOF
> cargo run [...] # run vaultwarden
```

log into vaultwarden, click
User icon in top right > account settings > security > Two-step login > Email > Manage > Send Email

2023-01-17 19:34 UTC, BlackDex commented on src/config.rs
> +            if cfg.smtp_username.is_some() ^ cfg.smtp_password.is_some() {
Is there a reason why you changed the expression here from `!=` to `^`?

2023-01-17 19:34 UTC, BlackDex commented on src/config.rs
> +            if cfg.smtp_host.is_some() ^ !cfg.smtp_from.is_empty() {
Is there a reason why you changed the expression here from `==` to `^`?

2023-01-17 19:47 UTC, BlackDex requested changes
I think there are some adjustments missing here: https://github.com/dani-garcia/vaultwarden/blob/9991563573ea43b997da47a62bbb83669c667462/src/config.rs#L1046-L1049

2023-01-17 19:47 UTC, BlackDex commented on src/config.rs
> +        sendmail_command:              String, true,   option;
Please adjust the comments so that it will look better in the admin interface.
It needs to be a short identifier separated by `|>` followed by a description.
Is is done for `smtp_ssl` for example.

2023-01-17 20:14 UTC, soruh commented on src/config.rs
> +        sendmail_command:              String, true,   option;
Fixed in [41faff5](https://github.com/dani-garcia/vaultwarden/pull/3147/commits/41faff5ec789df635d6af9b65ffd0eea73617757)

2023-01-17 20:14 UTC, soruh commented
> I think there are some adjustments missing here:
> 
> https://github.com/dani-garcia/vaultwarden/blob/9991563573ea43b997da47a62bbb83669c667462/src/config.rs#L1046-L1049

Fixed in [41faff5](https://github.com/dani-garcia/vaultwarden/pull/3147/commits/41faff5ec789df635d6af9b65ffd0eea73617757)

2023-01-17 20:33 UTC, soruh commented on src/config.rs
> +            if cfg.smtp_host.is_some() ^ !cfg.smtp_from.is_empty() {
I had originally had changed a lot more here only to notice that it wasn't necessary so this is what is left of that. 
Both are equivalent, but in my mind XOR much easier to reason about than bool == bool (which is why I changed it to understand the code better). I'm happy to revert this if you want.

2023-01-17 20:33 UTC, soruh commented on src/config.rs
> +            if cfg.smtp_username.is_some() ^ cfg.smtp_password.is_some() {
same as above

2023-01-17 20:47 UTC, BlackDex requested changes
Could you btw also add these variables to the `.env.template` with the same comments :)

2023-01-17 21:13 UTC, soruh commented
Oh, I missed that. Might be because it was hidden :)

2023-01-20 15:32 UTC, BlackDex commented on src/config.rs
> +            if cfg.smtp_host.is_some() ^ !cfg.smtp_from.is_empty() {
I think it is just what someone perverse on using. I actually find the `!=` and `==` a bit more clear. Though, in the end for the compiler it doesn't matter in this case 😄 .

2023-01-20 15:38 UTC, BlackDex requested changes
Ok, i just tested this locally, and it seems to work fine.

Though it does add extra config items, i do think this could be useful for some people.
I know it has been requested in the past. And since there are more and more standalone builds made of Vaultwarden, like for Arch Linux, Alpine, Nixos, FreeBSD, Void etc... this could be useful.

There is just one item i think we may need to address. If someone provides `SENDMAIL_COMMAND` i think it should be the full path to the executable, and therefor, i think we should validate if that file exists or not during the config validation. This will prevent users from configuring this variable, but a non working environment.

Other then that, LGTM.

2023-01-20 15:47 UTC, soruh commented
Thank you, that's a good point. I'll add that when I get home.

2023-01-20 16:44 UTC, soruh commented
It looks like the `SENDMAIL_COMMAND` is untimately passed into tokio::process::Command so if it's an absolute path it will just be executed but if it's not it will be looked up in the `$PATH`. I see two options to check validity:
- force the command to be an absolute path and check if the file exists and is executable
- allow commands in the `$PATH` and figure out a way to check if the command is valid (like spawning a tokio::process::Command with the command and checking for ENOENT)

I think the latter is definitely more involved, but there could be use cases where it's needed. Do you have any preference, or a better way to do this?

2023-01-20 16:59 UTC, soruh commented
I think I would prefer forcing an absolute path

2023-01-20 17:01 UTC, BlackDex commented
I would say the first. Make a path mandatory to be absolute.
For one, it feels safer to me and if someone wants to override it, they probably know the full path.

Checking if it is executable is going to be difficult. That isn't supported on Windows. And probably to much i think.

2023-01-20 17:04 UTC, soruh commented
Great, I agree. I'll implement that when I'm home then.

2023-01-20 18:23 UTC, soruh commented
[07f754b](https://github.com/dani-garcia/vaultwarden/pull/3147/commits/07f754b8b10bdb1105e921523b7917d2fe34c01b) adds the check. If you think the check for executability is too complicated I can remove it again.

2023-01-23 06:38 UTC, jjlin commented on .env.template
> +# Wether or not to send mails through sendmail
```suggestion
# Whether to send mail via the `sendmail` command
```

2023-01-23 06:38 UTC, jjlin commented on src/config.rs
> +        /// Use Sendmail |> Wether or not to send mails through sendmail
Same comment as in `.env.template`

2023-01-23 06:38 UTC, jjlin commented on src/config.rs
> +                if !path.is_absolute() {
Just FYI, it doesn't seem like lettre requires this to be an absolute path. If it's just a command (like the default value of `sendmail`), it uses the one found via `PATH`.

2023-01-23 06:38 UTC, jjlin commented on src/config.rs
> +        use_sendmail:                  bool,   true,   def,     false;
This variable could potentially be removed by inferring whether `sendmail` is desired based on whether `sendmail_command` is set. In that case, setting `smtp_host` and `sendmail_command` should probably be made mutually exclusive.

2023-01-23 06:38 UTC, jjlin commented on src/mail.rs
> +                    debug!("Sendmail Client error: {:#?}", e);
I know it was already like this before, but it's not clear to me why `Client` is arbitrarily capitalized here (same with `Response` and `Encryption`, but not `timeout`). It might be good to normalize this while you're changing this code anyway.

2023-01-23 07:20 UTC, soruh commented on src/config.rs
> +                if !path.is_absolute() {
Yes, unfortunately it is very hard to validate that a command exists in the `$PATH` (see comment above). If you know of a good way to do this, that'd be great. Especially as the default will very often be the `sendmail` from the `$PATH` which may not exist if `sendmail` is not installed.

2023-01-23 07:21 UTC, soruh commented on src/config.rs
> +        use_sendmail:                  bool,   true,   def,     false;
I feel like actually setting `SENDMAIL_COMMAND` is the exception rather than the rule and enabling sending mails via sendmail by specifying explicitely a `sendmail command` which is just `sendmail` seems very counterintuitive to me...

2023-01-23 07:22 UTC, soruh commented on src/mail.rs
> +                    debug!("Sendmail Client error: {:#?}", e);
Fixed in [2f247d8](https://github.com/dani-garcia/vaultwarden/pull/3147/commits/2f247d84a9dc4e401e1eecd24f5b25b63c5b191f)

2023-01-23 07:22 UTC, soruh commented on .env.template
> +# Wether or not to send mails through sendmail
Fixed in [7cc583c](https://github.com/dani-garcia/vaultwarden/pull/3147/commits/7cc583c37e3e58435f6e1250fac8e83c6d97a956)

2023-01-23 07:22 UTC, soruh commented on src/config.rs
> +        /// Use Sendmail |> Wether or not to send mails through sendmail
Fixed in [7cc583c](https://github.com/dani-garcia/vaultwarden/pull/3147/commits/7cc583c37e3e58435f6e1250fac8e83c6d97a956)

2023-01-23 07:54 UTC, jjlin commented on src/config.rs
> +                if !path.is_absolute() {
I'm not sure validation at startup is really required (the command could disappear after startup anyway, so one would hope there would still be a useful error message if that were to happen). But if you really want to do this check on a non-absolute path, https://crates.io/crates/which would probably do the job.

2023-01-23 08:14 UTC, BlackDex commented on src/config.rs
> +                if !path.is_absolute() {
That is why we determined we want it to be an absolute path.
And i think that validation at startup is wanted, we check a lot to prevent issues later on. That someone can remove or uninstall the binary is in the there responsibility. But if we can prevent issued at startup i would prefer that, it's just a simple check during validation, thats all.

2023-01-23 08:23 UTC, BlackDex commented on src/config.rs
> +        use_sendmail:                  bool,   true,   def,     false;
I agree with @soruh. The option to configure the sendmail binary isn't mandatory. We could also say, we only support the sendmail command and thats it. And people need to make sure it's located somewhere within the $PATH and be done with it, so not checking for a binary would be my preferred option instead of the other way around.

Also, stating to use this and not validating if the command exist as you mentioned before sounds a bit strange to me. That would be counter productive in my opinion.

2023-01-23 14:01 UTC, soruh commented on src/config.rs
> +                if !path.is_absolute() {
I mean it _is_ somewhat unfortunate that we can't check if a `sendmail` client is actually installed when the user sets `USE_SENDMAIL=true` but no `SENDMAIL_COMMAND` which will be the most common use case... The [which](https://crates.io/crates/which) crate does seem pretty lightweight, but I really can't make the decision if an extra dependency is worth it here...

The alternative of just trying to run the command and check if we get `ENOENT` seems mostly reasonable but since we don't know the implementation specific detail of what the installed sendmail client will do when called without arguments it feels pretty janky to me...

2023-01-25 21:57 UTC, soruh commented
I have just pushed [82452b3](https://github.com/dani-garcia/vaultwarden/pull/3147/commits/82452b3b2f8b49275f99e0048ce50217088be484) which adds the check using the `which` crate. If there is a consensus on what to do we can either revert it for the old behavior or keep it.

2023-02-02 16:09 UTC, soruh commented
I feel like it would be unfortunate for this to get stuck on something that feels pretty minor to me. I would really like this to be in the next version when it is released as I need it myself :). Is there a way a consensus can be found for this? Maybe a compromise of not using the which crate for now, but having the configuration description be more adamant about having `sendmail` installed would be acceptable?

2023-02-02 17:22 UTC, BlackDex commented
I might have some time to check this this evening (UTC). But you do need to rebase this PR it looks like.

2023-02-02 17:26 UTC, soruh commented
Do you know if there is a way for github to automatically squash PR commits or should I clean up the commit history a bit?

2023-02-02 17:29 UTC, BlackDex commented
Not that i know. I do stuff like that via the cli with a `reset --soft`.

2023-02-02 19:10 UTC, BlackDex requested changes

2023-02-02 19:31 UTC, soruh commented on src/config.rs
> +    }
You're absolutely correct, should be fixed now

2023-02-02 20:52 UTC, BlackDex approved these changes

2023-02-02 20:52 UTC, BlackDex commented on src/config.rs
> +            }
While i do not think Windows builds will be there much (if at all), and also want to use sendmail, then you need to fix the executable here, since Windows has `.exe` as a suffix. I suggest to use https://doc.rust-lang.org/std/env/consts/constant.EXE_SUFFIX.html which would be set to `.exe` when build for Windows, and should be empty for Linux.

`which` seems to work on a Windows build, so that should be fine.

2023-02-02 20:54 UTC, BlackDex requested changes

2023-02-02 20:54 UTC, BlackDex commented on src/config.rs
> +            }
While i do not think Windows builds will be there much (if at all), and also want to use sendmail, then you need to fix the executable here, since Windows has `.exe` as a suffix. I suggest to use https://doc.rust-lang.org/std/env/consts/constant.EXE_SUFFIX.html which would be set to `.exe` when build for Windows, and should be empty for Linux.

`which` seems to work on a Windows build, so that should be fine.

2023-02-02 21:06 UTC, soruh commented on src/config.rs
> +            }
[50bb24e](https://github.com/dani-garcia/vaultwarden/pull/3147/commits/50bb24e34c534a2b8693bdc8ddf77d8f57a0e566) does a bit more copying than strictly necessary, but since it's only run once. I think the readability outweighs using Cow etc. here.

2023-02-02 21:39 UTC, BlackDex commented on src/config.rs
> +            }
And it's run during config changes, but that is also not done a lot.

2023-02-02 21:40 UTC, BlackDex approved these changes

2023-02-02 21:46 UTC, soruh commented
Thank's alot for your help on this @BlackDex!

2023-02-12 17:40 UTC, dani-garcia approved these changes

2023-02-12 17:58 UTC, soruh commented
Curious that git thinks there is a conflict here. I think it assumes my new function is the same as the function added on main. I've rebased it now...

2023-02-12 18:22 UTC, dani-garcia commented
Yeah, I had trouble with git conflicts while trying to batch merge all the PR's manually, not sure why. Ended up merging them one by one.

We've just relicensed the project as AGPL but this PR was started before the license change was merged, so i'd appreciate if you can add your comment to the relicensing agreement, even if it's just a small formality by now:
https://github.com/dani-garcia/vaultwarden/discussions/2450

Thanks for your contribution!

2023-02-12 18:38 UTC, soruh commented
[done](https://github.com/dani-garcia/vaultwarden/discussions/2450#discussioncomment-4950651)

P.S.: It should probably say:
```patch
-And i hereby grant the Vaultwarden project team to re-license Vaultwarden
+And I hereby grant the Vaultwarden project team permission to re-license Vaultwarden
```

2023-02-12 18:40 UTC, merged