Fix Javascript issue on non sqlite databases
dani-garcia/vaultwarden pull request #3167
Opened 2023-01-24 22:35 UTC by BlackDex

When a non sqlite database is used, loading the admin interface fails because the backup button is not generated.
This PR is solves it by checking if the elements are valid.

Fixes #3166

2023-01-25 05:33 UTC, stefan0xC requested changes

2023-01-25 05:33 UTC, stefan0xC commented on src/static/scripts/admin_diagnostics.js
> +    document.getElementById("gen-support")
I don't think this second `document.getElementById("gen-support")` necessary?

2023-01-25 05:33 UTC, stefan0xC commented on src/static/scripts/admin_settings.js
> +    if (checkbox) {
Not sure if this can fail but I think the `if (checkbox) {` should be before the call on `onChanged` ?

2023-01-25 05:52 UTC, BlackDex commented on src/static/scripts/admin_settings.js
> +    if (checkbox) {
It shouldn't fail but it also doesn't harm to move indeed.

2023-01-25 05:53 UTC, BlackDex commented on src/static/scripts/admin_diagnostics.js
> +    document.getElementById("gen-support")
That's what you get after a long day of working and no much sleep haha.

2023-01-25 10:31 UTC, BlackDex commented on src/static/scripts/admin_diagnostics.js
> +    document.getElementById("gen-support")
and there are some more issues i think. Need to do some more testing on this :).
Thanks for checking.

2023-01-26 19:35 UTC, BlackDex commented on src/static/scripts/admin_diagnostics.js
> +    document.getElementById("gen-support")
Made it more robust now.

2023-01-26 19:36 UTC, BlackDex commented on src/static/scripts/admin_settings.js
> +    if (checkbox) {
Same as above, i made it more robust now.

2023-02-12 17:47 UTC, dani-garcia approved these changes

2023-02-12 17:48 UTC, merged