Generate distinct log messages for regex vs. IP blacklisting.
dani-garcia/vaultwarden pull request #3231
Opened 2023-02-07 10:12 UTC by kpfleming

When an icon will not be downloaded due to matching a configured blacklist, ensure that the log message indicates the type of blacklist that was matched.

2023-02-07 10:32 UTC, BlackDex approved these changes

2023-02-07 10:34 UTC, BlackDex commented
Hmm, wait, it looks like it will only cache `Some()` results. That kinda defeats the whole caching for non-blocked items.

2023-02-07 10:47 UTC, BlackDex requested changes

2023-02-07 10:47 UTC, BlackDex commented on src/api/icons.rs
> +#[cached(key = "String", convert = r#"{ domain.to_string() }"#, size = 16, time = 60, option = true)]
Please remove the `option = true` for `cached` here.
That causes None responses to be ignored, which is not what we want.

2023-02-07 10:53 UTC, kpfleming commented on src/api/icons.rs
> +#[cached(key = "String", convert = r#"{ domain.to_string() }"#, size = 16, time = 60, option = true)]
Will do; I had added it at point to work around a different issue which is no longer present.

2023-02-07 10:54 UTC, BlackDex approved these changes

2023-02-12 17:43 UTC, dani-garcia approved these changes

2023-02-12 17:43 UTC, merged