WIP: Admin token hash support
dani-garcia/vaultwarden pull request #3289
Opened 2023-02-28 22:18 UTC by BlackDex

WIP to support hashed admin token passwords.
Needs some extra testing and documentation updates.

Adding support for the following formats:

```bash
ADMIN_TOKEN='$6$VI56UPFMshTx1AdJ$HwxN4BREpH.....'
ADMIN_TOKEN='$6$rounds=10000$02b4db5b8cac85b5.....'
ADMIN_TOKEN='$argon2i$v=19$m=4096,t=3,p=1$Saf.....'
ADMIN_TOKEN='$argon2d$v=19$m=4096,t=3,p=1$drh.....'
ADMIN_TOKEN='$argon2id$v=19$m=4096,t=3,p=1$ds.....'
```

2023-02-28 22:29 UTC, williamdes commented on src/api/admin.rs
> +        Some(t) if t.starts_with("$6$") => sha_crypt::sha512_check(token.trim(), t.trim()).is_ok(),
is there no standard crate for such detection?

2023-02-28 22:34 UTC, dani-garcia commented
Is there a particular reason to support both SHA512 and argon? We don't need to keep backwards compatibility here so we can just force the more secure hashing algorithm.

Should we add some tool, either in the CLI or the admin page to generate these hashes? Or are we just going to instruct the users to do `sudo apt install argon2; argon2 <your_password>`?

2023-02-28 23:03 UTC, BlackDex commented
> Is there a particular reason to support both SHA512 and argon? We don't need to keep backwards compatibility here so we can just force the more secure hashing algorithm.
> 
> Should we add some tool, either in the CLI or the admin page to generate these hashes? Or are we just going to instruct the users to do `sudo apt install argon2; argon2 <your_password>`?

That is actually why i added the scrypt sha512. That can be done by openssl for example. Though it doesn't support custom iterations, while mkpasswd does.

OWASP says argon2 first, then scrypt, even before pbkdf2.

An other reasons is, that i don't know the impact of Argon2 on low grade hardware. While sha512 would be faster in those cases, and maybe less memory.

I don't want to add any extra binaries and dependencies into the container it self.

I was thinking about providing a cli option into Vaultwarden it self to generate a hash maybe. That shouldn't be to hard, and it's built-in without extra binaries, and should work on all environment's i think.

2023-02-28 23:05 UTC, JCBird1012 commented
If the server is to be expected to validate hashes and run Argon2 itself, I’d be mindful that some users run Vaultwarden in memory constrained environments (e.g. Raspberry Pis) - I’d say keeping SHA512 around for those users who may not have much memory leeway to run Argon2 is a good idea.

2023-02-28 23:28 UTC, jjlin commented
> That is actually why i added the scrypt sha512. That can be done by openssl for example. Though it doesn't support custom iterations, while mkpasswd does.
> 
> OWASP says argon2 first, then scrypt, even before pbkdf2.

BTW, scrypt and "SHA-crypt" aren't the same thing, or even similar. scrypt is more comparable to Argon2, while "SHA-crypt" is comparable to the original/ancient Unix crypt algorithm (basically just replacing DES or MD5 with newer hash algorithms from the SHA family).

2023-02-28 23:33 UTC, BlackDex commented
> > That is actually why i added the scrypt sha512. That can be done by openssl for example. Though it doesn't support custom iterations, while mkpasswd does.
> > OWASP says argon2 first, then scrypt, even before pbkdf2.
> 
> BTW, scrypt and "SHA-crypt" aren't the same thing, or even similar. scrypt is more comparable to Argon2, while "SHA-crypt" is comparable to the original/ancient Unix crypt algorithm (basically just replacing DES or MD5 with newer hash algorithms from the SHA family).

I think most, if not all Linux distros today use scrypt sha512 with the default 5000 rounds.

2023-02-28 23:53 UTC, jjlin commented
I'm just trying to clarify that what you're calling "scrypt sha512" is not at all related to the scrypt that's recommended by OWASP.

From https://manpages.debian.org/unstable/libcrypt-dev/crypt.5.en.html, `$6$` is `sha512crypt` (based on the old Unix crypt algorithm), and `$7$` is `scrypt` (relatively recent design by Colin Percival).

2023-03-01 02:17 UTC, tessus commented
> I think most, if not all Linux distros today use scrypt sha512 with the default 5000 rounds.

Or `yescrypt` which is built upon scrypt and can do both algorithms.

2023-03-01 05:47 UTC, BlackDex commented
> I'm just trying to clarify that what you're calling "scrypt sha512" is not at all related to the scrypt that's recommended by OWASP.
> 
> From https://manpages.debian.org/unstable/libcrypt-dev/crypt.5.en.html, `$6$` is `sha512crypt` (based on the old Unix crypt algorithm), and `$7$` is `scrypt` (relatively recent design by Colin Percival).

Sorry, you are right.
Those are not related in any way indeed.

Still, to generate a `sha512crypt` with already installed tools on the OS is more likely then `scrypt` or `yescrypt` for example.

2023-03-01 06:46 UTC, stefan0xC commented
> I was thinking about providing a cli option into Vaultwarden it self to generate a hash maybe. That shouldn't be to hard, and it's built-in without extra binaries, and should work on all environment's i think.

Something like

```rust
diff --git a/src/main.rs b/src/main.rs
index cd17a2f5..f03d6f25 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -141,6 +141,17 @@ fn parse_args() {
     } else if pargs.contains(["-v", "--version"]) {
         println!("vaultwarden {version}");
         exit(0);
+    } else if let Ok(Some(p)) = pargs.opt_value_from_str::<&str, String>("--password") {
+        use argon2::{
+            password_hash::{rand_core::OsRng, SaltString},
+            PasswordHasher,
+        };
+        let salt = SaltString::generate(&mut OsRng);
+        let argon2 = argon2::Argon2::default();
+        if let Ok(password_hash) = argon2.hash_password(p.as_bytes(), &salt) {
+            println!("{password_hash}");
+        }
+        exit(0);
     }
 }
```

Then we would not need a dependency on `sha-crypt`? And users don't have to install `argon2` (unless they want to mess with the default parameters).

Also we might want to consider deprecating (or removing) support for `ADMIN_TOKEN` in plain text so we don't store unhashed passwords.

2023-03-01 08:34 UTC, BlackDex commented
> Then we would not need a dependency on `sha-crypt`? And users don't have to install `argon2` (unless they want to mess with the default parameters).
> 

The sha-crypt is there because I know a lot of systems support generating these kind of PHC tokens out-of-the-box.
And for very low-grade hardware where Argon2 might be to much maybe.
This is also for stuff like automated deployments etc... Also, it is way better then the current plain/text we support right now.

Maybe adding PBKDF2 is also an option, because that is what we currently use already to hash the master-password-hash we receive from the Bitwarden clients. But as far as i can tell, there arn't any out-of-the-box tools to generate a PHC string for this. So that would mean we need to build that in into Vaultwarden to generate, and hence does not provide the easy tools as for `sha512crypt`

Adding the CLI option is nice if you already have Vaultwarden running or you can use `docker run`.
But if you want to prepare a PHC string upfront, a tool like `openssl passwd` or `mkpasswd` can be used.
For example, `mkpasswd` on Ubuntu 20.04 only supports `sha512crypt` as the most secure method.

> Also we might want to consider deprecating (or removing) support for `ADMIN_TOKEN` in plain text so we don't store unhashed passwords.

I think it is to soon for deprecating/removing this since we have had this for a long time already. Removing this would break a lot of environments. We could however notify the users that they have a plain/text ADMIN_TOKEN and provide some documentation on how to generate a new one.

In the future it might be a nice thing to play with WASM and provide a way to generate this within the admin interface without sending the password plain/text (besides HTTPS) to the server for example to generate the PHC string.

2023-03-01 14:50 UTC, stefan0xC commented
> And for very low-grade hardware where Argon2 might be to much maybe.

Can the `argon2` crate detect if a given hash does not meet it's runtime requirements? If so we should probably check that when parsing the config?

Adding such a check would make sense anyway someone with an existing password that happens to start with `$6$` will not be surprised either.

> We could however notify the users that they have a plain/text ADMIN_TOKEN and provide some documentation on how to generate a new one.

Adding such a deprecation notice (in the `Some(t) =>` case) to discourage the users is what I meant by deprecating.

> In the future it might be a nice thing to play with WASM and provide a way to generate this within the admin interface without sending the password plain/text (besides HTTPS) to the server for example to generate the PHC string.

Once we add support for hashed password's setting a password via the admin panel should probably not save the password in plaintext either.

2023-03-01 19:58 UTC, tessus commented
> Adding such a check would make sense anyway so someone with an existing token that happens to start with $6$ will not be surprised either.

`$6$` is sha512

afaik the Linux hashing does not have a number or letter assigned for argon. The options in `login.defs` are `MD5`, `SHA256`, `SHA512`, `BCRYPT`, `YESCRYPT`, `DES`. The default on Fedora is yescrypt (`$y$`), the default on Debian is sha512 (`$6$`) and yescrypt is not yet available in Debian.

2023-03-01 21:01 UTC, BlackDex commented
Before everything goes on and on regarding the hashing type to be selected.
I have thought about this a bit more and spoken with @dani-garcia about it, and we decided to **not** add `sha512crypt`, and just use `Argon2`. I will create an extra flag for Vaultwarden to be able to generate an acceptable hash.

2023-03-01 21:18 UTC, tessus commented
> In the future it might be a nice thing to play with WASM

I think the webclient uses WASM for argon. Should be possible to use as a template.

2023-03-01 21:53 UTC, stefan0xC commented
> > Adding such a check would make sense anyway so someone with an existing token that happens to start with 6 will not be surprised either.
> 
> `$6$` is sha512
> 

A bit moot now but Just to clarify: I was talking about the hypothetical case if my `ADMIN_TOKEN` would happen to be `$6$abc123`  then the suggested change would make the admin interface inacessible ` because the check would run `sha_crypt::sha512_check(token.trim(), t.trim()).is_ok(),` (which would presumably always fail) and not `crate::crypto::ct_eq(t.trim(), token.trim()),`

2023-03-02 18:18 UTC, BlackDex commented
I Think it should be almost finished. Want to do some testing on low-grade hardware.

Please provide your comments on the current state 😄 .

2023-03-02 18:42 UTC, tessus commented
```
Generate an Argon2id PHC string using the 'bitwarden' preset:

Password:
Verifying - Password:
Passwords do not match
```

I would add a newline between Verifying and Passwords do not match.

```
Generate an Argon2id PHC string using the 'bitwarden' preset:

Password:
Verifying - Password:

ADMIN_TOKEN='$argon2id$v=19$m=65540,t=3,p=4$fOB3HJ7sDhWviGHa8/HkpxFXEmtkdtHRLh68ZyiRs6k$nq5B623SF5uGqYU0LzvaJ7ybsH2RBSclxZbQb3BmW64'

Generation of the Argon2id PHC string took: 186.600603ms

```

I'd remove the last empty line, after Generation of ...

2023-03-02 18:48 UTC, tessus commented
Not sure, if this is necessary, but would it make sense to add a warning in the admin interface, if the token is not hashed?

2023-03-02 20:05 UTC, stefan0xC requested changes

2023-03-02 20:12 UTC, BlackDex commented on src/main.rs
>          USAGE:
It isn't very uncommon actually. Alsoz personally i like a bit more space from the left side of the screen, maybe 8 spaces is a bit much, but not directly at the beginning in my opinion.

2023-03-02 20:15 UTC, BlackDex commented on src/main.rs
> +            let password_verify = rpassword::prompt_password("Verifying - Password: ").unwrap();
I actually took this from `passwd` ;).
But `Retype` or maybe even `Confirm` would be better.

2023-03-02 20:16 UTC, BlackDex commented on src/main.rs
> +            owasp               19MiB, 2 Iterations, 1 Thread
I my self prefer a bit of indent, as noted above.

2023-03-02 20:25 UTC, stefan0xC commented on src/main.rs
>          USAGE:
Okay. I could create a separate issue for this. 8 spaces just seemed extreme to me and all programs I checked did not have any indentation.

2023-03-02 20:26 UTC, BlackDex commented on src/api/admin.rs
> +            }
Well, you would need to hugely break the PHC string before it will report an issue. While i do agree a check (and notice about unhashed token) should be done during startup, it isn't foolproof i think. Renaming `ADMIN_TOKEN` is out of the question, that would one break existing installs, second if we want to add an other hashing the name doesn't fit again. And adding a new variable is also not an option.

We could maybe add a lazy global, or something for the params to stay loaded and serve it via config maybe. Ill have to look at it.

2023-03-02 20:29 UTC, BlackDex commented on src/main.rs
>          USAGE:
Creating a separate issue will not change my mind haha.
Also, i have a feeling that @dani-garcia feels a bit the same as me regarding this.

I'm not against having less indent, but not fully removing it in my opinion.

2023-03-03 11:09 UTC, BlackDex commented on src/api/admin.rs
> +            }
I do not see a clean way for just parsing the hash once, and let admin.rs use the parsed version.
I also do not see a huge issue in validating it twice and acting upon that with a proper message in the logs.
Any issue should have been catched already during startup or config validation anyways.

2023-03-03 12:36 UTC, BlackDex commented on src/main.rs
>          USAGE:
After looking at it a bit longer and checking an tool i created my self, i seem to be a hypocrite in this case hehe.
So, i did remove all the indent spaces as mentioned.

2023-03-03 15:58 UTC, BlackDex commented
Thanks for all the comments and suggestions.
Please take a look again, thanks!

2023-03-03 16:56 UTC, tessus commented
Once last thing. ;-) Now there should be an empyty line between the hash and the info message:

```
Generate an Argon2id PHC string using the 'bitwarden' preset:

Password:
Confirm Password:

ADMIN_TOKEN='$argon2id$v=19$m=65540,t=3,p=4$b1oYgp3jGHSD56xmm40PVdOT9VhZ0ds8OJ1FuJ/vfMg$/aFZBQ6Edqyi/wjklGP/TW6REAfjwWKu5c0XbP6PHiQ'
Generation of the Argon2id PHC string took: 173.168728ms
```

should be:

```
Generate an Argon2id PHC string using the 'bitwarden' preset:

Password:
Confirm Password:

ADMIN_TOKEN='$argon2id$v=19$m=65540,t=3,p=4$b1oYgp3jGHSD56xmm40PVdOT9VhZ0ds8OJ1FuJ/vfMg$/aFZBQ6Edqyi/wjklGP/TW6REAfjwWKu5c0XbP6PHiQ'

Generation of the Argon2id PHC string took: 173.168728ms
```

The empty line after `Generation of ...` was removed so that is great. 👍 

Thanks for also fixing the other one I mentioned (password mismatch).

2023-03-03 18:51 UTC, tessus commented on src/static/scripts/admin_settings.js
> +function checkAdminToken() {
While during startup it only checks the validity and if it is argon when the admin token is not disabled.

But I think, here it just checks the token.

e.g. I have one set, but it is disabled. I don't have a problem to either remove it or change it to an argon2 hash.

I am just saying that for the sake of consistency it should also check here, whether it is disabled or not.

Unless I didn't read the code correctly, in which case I apologize in advance.

2023-03-03 19:04 UTC, BlackDex commented on src/static/scripts/admin_settings.js
> +function checkAdminToken() {
I think you are correct. That would be best and more consistent indeed.

2023-03-03 21:51 UTC, tessus commented on src/main.rs
> +                    ADMIN_TOKEN='{password_hash}'\n\
```suggestion
                    ADMIN_TOKEN='{password_hash}'\n\n\
```
There should be and empty line between `ADMIN_TOKEN` and `Generation...`.

It makes it more legible and it easier to copy and paste.

2023-03-03 21:54 UTC, BlackDex commented on src/main.rs
> +                    ADMIN_TOKEN='{password_hash}'\n\
Ah that was there, missed that thx for supporting.

2023-03-04 15:15 UTC, BlackDex commented on src/static/scripts/admin_settings.js
> +function checkAdminToken() {
done

2023-03-04 15:15 UTC, BlackDex commented on src/main.rs
> +                    ADMIN_TOKEN='{password_hash}'\n\
Done

2023-03-05 03:55 UTC, tessus reviewed
Works great. And thanks for the changes.

2023-03-06 19:53 UTC, dani-garcia approved these changes

2023-03-06 20:12 UTC, merged