feat: Implement Push Notifications sync
dani-garcia/vaultwarden pull request #3304
Opened 2023-03-04 10:34 UTC by GeekCornerGH

# Implements the Push Notification feature
#### Resolves #2469

[Push-demo.webm](https://user-images.githubusercontent.com/45696571/222894552-109e3c34-e9b2-44a0-9474-304123f78b0a.webm)

Special thanks to @samb-devel for your help

## WARNING:
To avoid confusion, uuid column from device table was renamed to identifier, and a new table uuid is created. The migration has been tested on a sqlite database, but should work on MariaDB and Postgres too. The resulting database is not backwards compatible. I might have forgotten to swap "uuid" and "identifier" at some places in the code, apologies for that.

## How to test:
Get your keys from [the Bitwarden website](https://bitwarden.com/host)
Set environment variables to the required values:
```env
PUSH_ENABLED=true
PUSH_INSTALLATION_ID=CHANGEME
PUSH_INSTALLATION_KEY=CHANGEME
```
PUSH_RELAY_URI is already configured to use default Bitwarden server.
Start the server, then test.

This was my first shot at Rust.

2023-03-04 11:20 UTC, stefan0xC commented
Thanks for the contribution. I have not looked at the changes yet but can you run `cargo fmt` and fix the errors reported by `cargo clippy` so the automatic checks won't fail?

2023-03-04 14:43 UTC, GeekCornerGH commented
> Thanks for the contribution. I have not looked at the changes yet but can you run `cargo fmt` and fix the errors reported by `cargo clippy` so the automatic checks won't fail? 

Sure thing, will do it later

2023-03-04 19:48 UTC, GeekCornerGH commented
Removed pretty much every error.
If someone can suggest changes to remove the last 2 ones, feel free to do so, not sure how to resolve them (removing return throw an error about response type for instance)

2023-03-05 12:54 UTC, VarChar42 commented on src/push.rs
> +pub async fn push_logout(user: &User, acting_device_identifier: Option<String>, conn: &mut crate::db::DbConn) {
Some functions don't check for the 'push_enabled' config value at the beginning. Is this intentionally?

2023-03-05 13:33 UTC, GeekCornerGH commented on src/push.rs
> +pub async fn push_logout(user: &User, acting_device_identifier: Option<String>, conn: &mut crate::db::DbConn) {
Fair question, I guess I forgot to add back the function checking for enabled configuration :(

2023-03-05 15:09 UTC, BlackDex requested changes
I'm looking at the code right now.
At a first glance the code looks ok, but have not looked detailed at it.

First things that i notice are the following.
There are two migrations done on the database, while that could be done in one go, which would make a `down.sql` a bit easier I think, and probably wanted.

Also, i have not checked what the effects are yet of this change, since there is a primary key on the old `UUID` and `USER_UUID` combined. I don't know if that will break stuff with this rename.
I still tend do keep `uuid` as is, and use `push_token` as a new column. Even though that deviates from upstream Bitwarden. But we can put that into the comments at the object.

I also see a lot of extra calls being done in regards to pushing these notifications.
Now every function which has a `nt.send...` also has a `push_...` in there.
Can't we merge this in some way and just have one entry point for sending out changes?
Like, and the `push::` to the `notifications.rs` file?
That would solve future notification updates or additions to just add one, instead of two calls every time.

2023-03-05 15:32 UTC, BlackDex requested changes

2023-03-05 15:32 UTC, BlackDex commented on migrations/mysql/2023-02-18-133907_create-new-uuid-table/up.sql
> +ALTER TABLE devices ADD uuid TEXT NOT NULL DEFAULT "00000000-0000-0000-0000-000000000000";
Does this really need to have a default? I'd rather have no default for this.
If we really want this to be a valid uuid, we need to solve this a different way. And that is why i think we need to rename this to `push_uuid` instead, and have it optional.
That way we can check if it is set or not.

2023-03-05 15:32 UTC, BlackDex commented on src/api/core/accounts.rs
> +    if device.uuid == *"00000000-0000-0000-0000-000000000000".to_string() {
If we change this to an optional db field, there is no need to do a string checking here, which is kinda expensive compared to checking for an `Option`

2023-03-05 15:32 UTC, BlackDex commented on src/db/models/user.rs
> +    #[derive(Clone)]
Is this really needed? I think it works just fine without having this derive.

2023-03-05 15:32 UTC, BlackDex commented on src/api/notifications.rs
> +#[derive(Clone, Copy, Eq, PartialEq)]
This can probably also be solved if we merge the push and notify calls into one.
Then you could either change `ut` in `push.rs` to be an `i32` or we need to make sure we can cast/convert from an `&UpdateType` to an `i32`. Kinda the same as we do for the event logging.

2023-03-05 15:39 UTC, BlackDex commented on src/api/notifications.rs
> +#[derive(Clone, Copy, Eq, PartialEq)]
Or, now that i think if, that might be an issue too. Ill have to check a bit better.

2023-03-05 15:44 UTC, BlackDex commented on src/api/notifications.rs
> +#[derive(Clone, Copy, Eq, PartialEq)]
I Think what a small modification we could re-define `ut` as an `i32` and pass it by reference for one, and let it consume by the other.

2023-03-05 15:51 UTC, GeekCornerGH commented on src/db/models/user.rs
> +    #[derive(Clone)]
Good question, might forgot to remove it from debug tests

2023-03-05 19:11 UTC, GeekCornerGH commented on src/db/models/user.rs
> +    #[derive(Clone)]
Putting in resolved as this is fixed in my local branch

2023-03-06 17:17 UTC, BlackDex requested changes
Some more reviews from my side.
I haven't fully checked everything detailed though.

2023-03-06 17:17 UTC, BlackDex commented on src/config.rs
> +        push_relay_uri:         String, false,  def,    "https://push.bitwarden.com".to_string();
Is this actually configurable, what are the alternatives?
Else we are probably better of having this not configurable.

2023-03-06 17:17 UTC, BlackDex commented on src/push.rs
> +    };
Maybe `if let Err(e) = get_reqwest_client()` is better suited here then a match which doesn't do anything with the `Ok` result here.

2023-03-06 17:17 UTC, BlackDex commented on src/push.rs
> +    auth_header.push_str(&PUSH_TOKEN.lock().unwrap().access_token);
```suggestion
let auth_header = format!("Bearer {}", &PUSH_TOKEN.lock().unwrap().access_token);
```

2023-03-06 17:17 UTC, BlackDex commented on src/push.rs
> +});
I think an `RwLock` would be better here. A `Mutex` will lock reads and writes, while an `RwLock` will only lock during writes, which will only occur when the push relay token is expired.

See https://docs.rs/tokio/latest/tokio/sync/struct.RwLock.html (Though i do not know if the tokio RwLock can be used here, else use std).

2023-03-06 17:18 UTC, GeekCornerGH commented on src/push.rs
> +    };
Just ignores if there is an error, was meant to pass clippy tests

2023-03-06 17:19 UTC, GeekCornerGH commented on src/push.rs
> +    };
Yep, my bad

2023-03-06 17:20 UTC, GeekCornerGH commented on src/push.rs
> +    params.insert("client_secret", &client_secret);
This pr contains my first lines of rust, so I used stackoverflow and other websites :/

2023-03-06 17:45 UTC, BlackDex commented on src/push.rs
> +    params.insert("client_secret", &client_secret);
Ah, no prob. Just wondered if there was a specific reason. But, an array would be enough i think.
```rust
let params = [
    ("grant_type", "client_credentials"),
    ("scope", "api.push"),
    ("client_id", &client_id),
    ("client_secret", &client_secret)
];
```

2023-03-06 17:57 UTC, BlackDex commented on src/push.rs
> +    };
An error from what/where? You can just use `return;` here i think instead of this.
Because you now check if there is an Err from an Ok. Which will never happen.

2023-03-06 20:06 UTC, dani-garcia commented on src/push.rs
> +});
As far as I know, as long as you aren't holding the lock guard between await points, using the std locks is fine, I remember that being mentioned somewhere in the tokio docs. I think it should be there still somewhere.

We're only ever swapping values into the mutex so I don't think it'll matter much whether we use sync/async or mutex/rwlock.

That said, we should avoid unnecessary locks and unlocks, like there is on here:
https://github.com/dani-garcia/vaultwarden/blob/59da014e86f181531d3ff9ec5b3830c3bc6e19e8/src/push.rs#L66-L74

And replace it with something like this  (Haven't actually tested the code, just wrote it by hand now):

```rust
let valid_until = {
    let lock = PUSH_TOKEN.lock().unwrap();

    *lock.valid_until = Instant::now()
    .checked_add(Duration::new((json_pushtoken.expires_in / 2) as u64, 0)) // Token valid for half the specified time
    .unwrap();

    *lock.access_token = json_pushtoken.access_token;

    lock.valid_until.saturating_duration_since(Instant::now()).as_secs()
};
debug!("Token still valid for {}", valid_until);
```
Note how i've stored the lock guard inside an inner {} block, to make sure it gets dropped in the end. That way we are saving some lock/unlock cycles.

2023-03-06 20:16 UTC, BlackDex commented on src/push.rs
> +});
Doesn't the Mutex locks also on reads? In case of multiple push events they could be waiting on the other.

2023-03-06 20:27 UTC, dani-garcia commented on src/push.rs
> +});
Yes, but the lock is very short lived (we are only replacing a variable and that's it), so the chance of two events trying to lock the mutex at the same time is very low, and even when it happens, they would only lock it for a very short time.

At our scale I don't think the distinction between mutex and rwlock is going to cause any performance difference at all.

2023-03-06 20:38 UTC, dani-garcia commented on src/push.rs
> +});
For what it's worth, here's how i'd do it with a rwlock, and also returning the access token to avoid having to do another lock/unlock cycle (not tested):
```rust
pub async fn get_auth_push_token() -> ApiResult<String> {
    static PUSH_TOKEN: Lazy<RwLock<LocalAuthPushToken>> = Lazy::new(|| {
        RwLock::new(LocalAuthPushToken {
            access_token: String::new(),
            valid_until: Instant::now(),
        })
    });

    let push_token = PUSH_TOKEN.read().unwrap();
    if push_token.valid_until.saturating_duration_since(Instant::now()).as_secs() > 0 {
        debug!("Auth Push token still valid, no need for a new one");
        return Ok(push_token.access_token.clone());
    }
    drop(push_token); // Drop the read lock now

    let installationid = CONFIG.push_installation_id();
    let mut client_id = "installation.".to_string();
    let client_secret = CONFIG.push_installation_key();

    client_id.push_str(&installationid);

    let mut params = HashMap::new();
    params.insert("grant_type", "client_credentials");
    params.insert("scope", "api.push");
    params.insert("client_id", &client_id);
    params.insert("client_secret", &client_secret);

    let res = match get_reqwest_client().post("https://identity.bitwarden.com/connect/token").form(&params).send().await {
        Ok(r) => r,
        Err(e) => err!(format!("Error getting push token from bitwarden server: {e}")),
    };

    let json_pushtoken = match res.json::<AuthPushToken>().await {
        Ok(r) => r,
        Err(e) => err!(format!("Unexpected push token received from bitwarden server: {e}")),
    };

    let mut push_token = PUSH_TOKEN.write().unwrap();
    push_token.valid_until = Instant::now()
        .checked_add(Duration::new((json_pushtoken.expires_in / 2) as u64, 0)) // Token valid for half the specified time
        .unwrap();

    push_token.access_token = json_pushtoken.access_token;

    debug!("Token still valid for {}", push_token.valid_until.saturating_duration_since(Instant::now()).as_secs());
    Ok(push_token.access_token.clone())
}
```
Then you can do:

```rust
 let auth_push_token = get_auth_push_token().await?;

    //Needed to register a device for push to bitwarden :
    let data = json!({
        "userId": user_uuid,
        "deviceId": device.uuid,
        "identifier": device.identifier,
        "type": device.atype,
        "pushToken": device.push_token
    });

    let mut auth_header = "Bearer ".to_string();
    auth_header.push_str(&auth_push_token);

    get_reqwest_client()
        .... the rest
```

2023-03-07 08:34 UTC, GeekCornerGH commented on src/push.rs
> +    };
idk, clippy complained about that :(

2023-03-07 11:43 UTC, BlackDex commented on src/push.rs
> +});
With v1.65.0 as MSRV, you can even get rid of `Lazy` now i think 😉

2023-03-10 21:43 UTC, BlackDex commented on src/api/core/accounts.rs
> +async fn get_known_device(email: String, identifier: String, mut conn: DbConn) -> JsonResult {
Thanks @justindbaur for letting us know. This probably need to be fixed outside of this PR I think. And we probably need to support both for a while.

2023-03-11 19:22 UTC, samb-devel commented on src/push.rs
> +});
I'm trying to implement this and would need your support here. I have the following error message attached to each line implementing a route, for instance in `admin.rs` on the line:
`#[post("/users/<uuid>/deauth")]`

```
future cannot be sent between threads safely
within `[async block@src/api/admin.rs:382:1: 382:32]`, the trait `std::marker::Send` is not implemented for `std::sync::RwLockReadGuard<'_, LocalAuthPushToken>`
required for the cast from `[async block@src/api/admin.rs:382:1: 382:32]` to the object type `dyn futures::Future<Output = Outcome<rocket::Response<'__r>, rocket::http::Status, rocket::Data<'__r>>> + std::marker::Send`
```

Could you please help ? Thanks in advance

2023-03-11 19:32 UTC, BlackDex commented on src/push.rs
> +});
Try to use RwLock from tokio.

2023-03-13 07:46 UTC, samb-devel commented on src/api/notifications.rs
> +#[derive(Clone, Copy, Eq, PartialEq)]
We worked on other parts and just started that one. What would make more sense? To have both `push.rs` and `notifications.rs` merged into the same file? If you could briefly describe the best architecture on how to manage those calls and in which file they should be, we'll give a look. Thanks

2023-03-13 09:47 UTC, GeekCornerGH commented on src/config.rs
> +        push_relay_uri:         String, false,  def,    "https://push.bitwarden.com".to_string();
You can using env variables

2023-03-13 09:55 UTC, BlackDex commented on src/config.rs
> +        push_relay_uri:         String, false,  def,    "https://push.bitwarden.com".to_string();
I bet you can. But I actually mean is this something you can change to something else, and have it all still work?
What are the alternatives if there are any. Because, if there arn't any alternatives, its better to NOT have this as a config option.

2023-03-13 19:24 UTC, GeekCornerGH commented on src/config.rs
> +        push_relay_uri:         String, false,  def,    "https://push.bitwarden.com".to_string();
Oh you're talking about the push_relay_uri option? I thought you were talking about the whole config block. Anyways this was on the official server so I added it there :)

2023-03-13 19:47 UTC, BlackDex commented on src/config.rs
> +        push_relay_uri:         String, false,  def,    "https://push.bitwarden.com".to_string();
I understand, but is there any other server you can configure and have it all still working?? I don't think it is of use to have this configuarble.

2023-03-14 06:58 UTC, GeekCornerGH commented on src/config.rs
> +        push_relay_uri:         String, false,  def,    "https://push.bitwarden.com".to_string();
Fair question, and to be honnest, I don't know haha, I can remove it if you want

2023-03-14 07:25 UTC, stefan0xC commented on src/config.rs
> +        push_relay_uri:         String, false,  def,    "https://push.bitwarden.com".to_string();
As far as I've looked into it, it won't work as because self-hosted servers have ["to relay their messages through the Bitwarden cloud-hosted instance. [Because] only Bitwarden is allowed to send notifications to the store-distributed Android and iOS mobile applications"](https://contributing.bitwarden.com/architecture/push-notifications/mobile/). 

Not sure how difficult it would be to setup your own push relay (and get the mobile clients to work). I imagine it would be rather tedious.

Would it make sense to have this as an internal configuration option so it's theoretically possible to configure this to another URL? (Only asking because it's also a [configuration option in Bitwarden server](https://bitwarden.com/help/configure-push-relay/))

2023-03-14 12:09 UTC, dpinse commented on migrations/mysql/2023-02-18-125735_push_uuid_table/up.sql
> +ALTER TABLE devices CREATE COLUMN push_uuid TEXT;
MariaDB errors out with a migration syntax error should be `ALTER TABLE devices ADD COLUMN push_uuid TEXT;`

2023-03-14 12:11 UTC, dpinse requested changes
MariaDB migration fails with synax error, should be `ALTER TABLE devices ADD COLUMN push_uuid TEXT;`

2023-03-14 14:15 UTC, BlackDex commented on migrations/mysql/2023-02-18-125735_push_uuid_table/up.sql
> +ALTER TABLE devices CREATE COLUMN push_uuid TEXT;
I think this should still be changed to be one file, which is not done yet.
Do you have a more detailed message maybe?

2023-03-14 16:12 UTC, dpinse commented on migrations/mysql/2023-02-18-125735_push_uuid_table/up.sql
> +ALTER TABLE devices CREATE COLUMN push_uuid TEXT;
[2023-03-14 12:11:43.582][panic][ERROR] thread 'main' panicked at 'Error running migrations: QueryError(DieselMigrationName { name: "2023-02-18-125735_push_uuid_table", version: MigrationVersion("20230218125735") }, DatabaseError(Unknown, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE COLUMN push_uuid TEXT' at line 1"))': src/db/mod.rs:471
   0: std::backtrace::Backtrace::create
   1: vaultwarden::init_logging::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys_common::backtrace::__rust_end_short_backtrace
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: vaultwarden::db::mysql_migrations::run_migrations
   9: vaultwarden::db::DbPool::from_config
  10: vaultwarden::main::{{closure}}
  11: tokio::runtime::park::CachedParkThread::block_on
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  13: tokio::runtime::runtime::Runtime::block_on
  14: rocket::async_main
  15: vaultwarden::main
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal
  19: main

2023-03-14 16:27 UTC, GeekCornerGH commented on migrations/mysql/2023-02-18-125735_push_uuid_table/up.sql
> +ALTER TABLE devices CREATE COLUMN push_uuid TEXT;
Good to know, could you test on Postgres too?

2023-03-14 20:42 UTC, tessus commented on migrations/mysql/2023-02-18-125735_push_uuid_table/up.sql
> +ALTER TABLE devices CREATE COLUMN push_uuid TEXT;
`CREATE COLUMN` is not a valid SQL statement. @dpinse is correct, it must be `ADD COLUMN`.

2023-03-14 20:47 UTC, tessus commented on src/config.rs
> +        push_relay_uri:         String, false,  def,    "https://push.bitwarden.com".to_string();
I think it makes sense adding it as an internal config option. This makes it more future-proof, in case bw allows to specify a relay at one point.
But I don't have any say, so my opinion is probabaly moot. ;-)

2023-03-15 22:18 UTC, BlackDex commented
@GeekCornerGH , my apologies already for my changes, hope it won't be to hard to merge hehe.

2023-03-16 05:30 UTC, tessus reviewed
The SQL statements are wrong. I am not sure how they ever ran successfully during a migration.

The proper statement is `ALTER TABLE bla ADD COLUMN ...`

2023-03-16 05:30 UTC, tessus commented on migrations/postgresql/2023-02-18-125735_push_uuid_table/up.sql
> +ALTER TABLE devices CREATE COLUMN push_uuid TEXT;
```suggestion
ALTER TABLE devices ADD COLUMN push_uuid TEXT;
```

2023-03-16 05:30 UTC, tessus commented on migrations/sqlite/2023-02-18-125735_push_uuid_table/up.sql
> +ALTER TABLE devices CREATE COLUMN push_uuid TEXT;
```suggestion
ALTER TABLE devices ADD COLUMN push_uuid TEXT;
```

2023-03-16 05:30 UTC, tessus commented on migrations/mysql/2023-02-18-125735_push_uuid_table/up.sql
> +ALTER TABLE devices CREATE COLUMN push_uuid TEXT;
```suggestion
ALTER TABLE devices ADD COLUMN push_uuid TEXT;
```

2023-03-16 06:07 UTC, GeekCornerGH commented
Wooops, I guess git didn't caught the changes 😂 I'll rebase anyways

2023-03-16 21:49 UTC, tessus commented on src/main.rs
> +            # It looks like you enabled Push Notification feature, but you didn't configured the   #\n\
```suggestion
            # It looks like you enabled Push Notification feature, but you didn't configure the    #\n\
```

Apart from the fact that this should go in `config.rs`, there's also a typo.

2023-03-16 22:04 UTC, tessus commented on src/main.rs
> +            # value. Make sure the installation id and key from https://bitwarden.com/host are     #\n\
Apart from the fact that this should go in `config.rs`, there's also a typo and I have improved the wording.

```suggestion
            # It looks like you enabled Push Notification feature, but didn't configure it         #\n\
            # properly. Make sure the installation id and key from https://bitwarden.com/host are  #\n\
```

I hope the border (the `#`s) is aligned, because github splits the lines, even in unified view.

2023-03-17 15:06 UTC, GeekCornerGH commented
@tessus since GitHub won't allow me to request 2 reviewers at one time, I just tag you haha, is everything fine now?

2023-03-17 18:49 UTC, tessus reviewed
I think there are still 2 points outstanding, from other reviewers:

1. don't add an option in config.rs for `PUSH_RELAY_URI` (or at least it should not be public for now)
2. merge the function calls

ad 1) currently there is only one push server and setting it to anything other than the bw address won't work. It is too error prone to allow users to change this value. However, in the code the variable should still be used, since bw might introduce other servers or allow customers to setup their own push server (which would also require a change in he client code).

ad 2) currently there are always 2 fuction calls, as an example:

```
send_folder_update(...)
push_folder_update(...)
```

If I understood BlackDex's comment correctly, the second call should be added to the first one:

```
fn send_folder_update(...) {
    original code;
    
    if (PUSH_ENABLED) {
        push_folder_update(...);
    }
}
```

But I am not the right person to review the entire PR. Someone who actually knows Rust (I only dabble with it) and the code base will hvae to do a proper review.

2023-03-18 13:43 UTC, samb-devel commented
Thank you @tessus for your remarks.

@BlackDex : could you please confirm that the code suggested by @tessus is what you inteded? Can we simply call `push_folder_update(..)` from within `send_folder_update` which is inside the `impl WebSocketUsers` block without any problem?

Thank you in advance for your feedback

2023-03-18 13:50 UTC, BlackDex commented
> Thank you @tessus for your remarks.
> 
> @BlackDex : could you please confirm that the code suggested by @tessus is what you inteded? Can we simply call `push_folder_update(..)` from within `send_folder_update` which is inside the `impl WebSocketUsers` block without any problem?
> 
> Thank you in advance for your feedback

My main point is i don't like to have two functions being called at all those functions while using the same arguments.
I actually have not yet looked into the best way to do this. Maybe we need to create an overlay on both, so that in the future it could be easy to add a new way.

But i do think the `nt` can be used for both to simplify and consolidate this.

2023-03-18 14:08 UTC, samb-devel commented
@BlackDex thanks for the answer. I get your point. My main concern is that we're not very deep into rust development, We're happy to learn and do, we just need a bit of guidance on the best practices and on how Vaultwarden may develop.

Does it make sense to keep push calls and websocket notifications in two separate files, or should we merge them `push.rs` and `notifications.rs`?
Do you see any possible issue in calling the `push_folder_update` from within the `impl WebSocketUsers` block, or are there issues of any kind and that should be avoided?

2023-03-22 23:37 UTC, tessus commented
> Does it make sense to keep push calls and websocket notifications in two separate files, or should we merge them `push.rs` and `notifications.rs`?

I think this is up to you. Everyone has their preference. I don't see an issue to have 2 files. I suspect other reviewers would have already objected otherwise.

> Do you see any possible issue in calling the `push_folder_update` from within the `impl WebSocketUsers` block, or are there issues of any kind and that should be avoided?

Personally I'd just go for it. It's just a bit of refactoring. But BlackDex also mentioned that a wrapper might be beneficial. However, as a first step, I'd just try adding it to the impl block and see what happens. ;-)

2023-03-23 18:47 UTC, BlackDex commented
> @BlackDex thanks for the answer. I get your point. My main concern is that we're not very deep into rust development, We're happy to learn and do, we just need a bit of guidance on the best practices and on how Vaultwarden may develop.
> 
> Does it make sense to keep push calls and websocket notifications in two separate files, or should we merge them `push.rs` and `notifications.rs`? Do you see any possible issue in calling the `push_folder_update` from within the `impl WebSocketUsers` block, or are there issues of any kind and that should be avoided?

While I would like to consolidate this to make it a bit more simple. It isn't something i would trip over for an approval on my side. It can be optimized later when tested by others.

2023-03-24 06:17 UTC, GeekCornerGH commented
Talking about testing, while implemented, I couldn't get Send Notifications to work, while I had the same issue on the official server fyi

2023-03-26 13:57 UTC, BlackDex requested changes

2023-03-27 08:38 UTC, GeekCornerGH commented on src/api/core/accounts.rs
> +    Ok(())
I guess it is needed. Else, it won't compile at all.

2023-03-28 14:32 UTC, BlackDex requested changes

2023-03-28 14:32 UTC, BlackDex commented on src/api/core/accounts.rs
> +    Ok(())
I mean, you removed function from an other file, and there this function returned a JSON.
Now it doesn't return a JSON anymore, just an EmptyResult (aka 200).

I'm not sure if this is correct. It could be. But i just wondered because it did before.

2023-04-01 17:08 UTC, GeekCornerGH commented
Marking this as ready for review, since I can't reproduce issues I got on my windows pc on a Linux laptop

2023-04-02 23:47 UTC, tessus reviewed
The PR hasn't changed since last time.

The function calls are still separate.

2023-04-03 20:27 UTC, stefan0xC requested changes
While looking at the code I noticed a few smaller and some bigger issues and thus have some suggestions and also a few questions. Not that since I don't have a hosting id and key from Bitwarden I could not actually test if the push notifications work. But running it **without** the feature enabled I noticed that there are some checks missing:

```
[2023-04-03 22:23:16.325][request][INFO] PUT /api/ciphers/e9d45f5f-f619-43c9-9f36-f70f573f303e
[2023-04-03 22:23:16.333][reqwest::connect][DEBUG] starting new connection: https://identity.bitwarden.com/
[2023-04-03 22:23:16.339][trust_dns_proto::xfer::dns_handle][DEBUG] querying: identity.bitwarden.com A
[2023-04-03 22:23:16.339][trust_dns_resolver::name_server::name_server_pool][DEBUG] sending request: [Query { name: Name("identity.bitwarden.com"), query_type: A, query_class: IN }]
[2023-04-03 22:23:16.339][trust_dns_resolver::name_server::name_server][DEBUG] reconnecting: NameServerConfig { socket_addr: 127.0.0.53:53, protocol: Udp, tls_dns_name: None, trust_nx_responses: false, bind_addr: None }
[2023-04-03 22:23:16.339][trust_dns_proto::xfer][DEBUG] enqueueing message:QUERY:[Query { name: Name("identity.bitwarden.com"), query_type: A, query_class: IN }]
[2023-04-03 22:23:16.339][trust_dns_proto::udp::udp_client_stream][DEBUG] final message: ; header 49878:QUERY:RD:NoError:QUERY:0/0/0
; query
;; identity.bitwarden.com. IN A

[2023-04-03 22:23:16.339][trust_dns_proto::udp::udp_stream][DEBUG] created socket successfully
[2023-04-03 22:23:16.356][trust_dns_proto::udp::udp_client_stream][DEBUG] received message id: 49878
[2023-04-03 22:23:16.357][trust_dns_resolver::error][DEBUG] Response:; header 49878:RESPONSE:RD,RA:NoError:QUERY:2/0/0
; query
;; identity.bitwarden.com. IN A
; answers 2
identity.bitwarden.com. 177 IN A 104.18.13.33
identity.bitwarden.com. 177 IN A 104.18.12.33
; nameservers 0
; additionals 0

[2023-04-03 22:23:16.357][trust_dns_resolver::error][DEBUG] Response:; header 49878:RESPONSE:RD,RA:NoError:QUERY:2/0/0
; query
;; identity.bitwarden.com. IN A
; answers 2
identity.bitwarden.com. 177 IN A 104.18.13.33
identity.bitwarden.com. 177 IN A 104.18.12.33
; nameservers 0
; additionals 0

[2023-04-03 22:23:16.681][trust_dns_proto::xfer::dns_exchange][DEBUG] io_stream is done, shutting down
[2023-04-03 22:23:16.681][vaultwarden::api::push][ERROR] Unexpected push token received from bitwarden server: error decoding response body: missing field `access_token` at line 1 column 26
[2023-04-03 22:23:16.681][vaultwarden::api::push][DEBUG] Could not get the auth push token: {"ErrorModel":{"Message":"Unexpected push token received from bitwarden server: error decoding response body: missing field `access_token` at line 1 column 26","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Unexpected push token received from bitwarden server: error decoding response body: missing field `access_token` at line 1 column 26","Object":"error","ValidationErrors":{"":["Unexpected push token received from bitwarden server: error decoding response body: missing field `access_token` at line 1 column 26"]},"error":"","error_description":""}
```

So before this gets merged I think we should check if there are no unintended side effects like this when this feature is **not** enabled.

2023-04-03 20:52 UTC, tessus commented
> So before this gets merged I think we should check if there are no unintended side effects like this when this feature is not enabled.

I don't want to be a stickler, but I did mention the following change:

```
fn send_folder_update(...) {
    original code;
    
    if (PUSH_ENABLED) {
        push_folder_update(...);
    }
}
```

This would have solved this issue already, since the `push_*` functions don't test for the service being enabled....

2023-04-04 04:45 UTC, GeekCornerGH commented on src/api/admin.rs
> -    save_result
Would make more sense to group both call in the first place, as database access is needed for push

2023-04-04 04:48 UTC, GeekCornerGH commented on src/api/core/accounts.rs
> +}
It was implemented in the server code. So I added it there too, in order to have it ready in case it get implemented somewhere

2023-04-04 04:50 UTC, GeekCornerGH commented on src/db/models/device.rs
> +    pub async fn find_push_device_by_user(user_uuid: &str, conn: &mut DbConn) -> Option<Self> {
Figured out that's how Bitwarden official server works

2023-04-04 05:20 UTC, stefan0xC commented on src/db/models/device.rs
> +    pub async fn find_push_device_by_user(user_uuid: &str, conn: &mut DbConn) -> Option<Self> {
I don't think [this is how the official server works](https://contributing.bitwarden.com/architecture/push-notifications/mobile#using-the-push-token-to-send-notifications-to-the-device). I've checked where this is called and let me clarify my point: This function is only used used when clearing the token from the `/admin` page via `deauth_user`. However this function only unregisters the result of this function (i.e. the first one it finds) and then it deletes all Devices for a user. However, according to my understanding it should be possible to add multiple push devices.

2023-04-04 05:24 UTC, stefan0xC commented on src/api/admin.rs
> -    save_result
I don't understand your explanation. I might be wrong but I think the order is intended to do the operation first and only then notify the user. If the notification fails the operation will not be executed.

2023-04-08 19:39 UTC, Zoruk commented
@GeekCornerGH Do you want some help to clean up your MR and fix the requested changes ?

2023-04-09 06:41 UTC, GeekCornerGH commented
Most changes aren't pushed yet, they are on my local branch. But thanks for your help. If you want to make wrapper, feel free to make a pull request to my GitHub branch

2023-04-14 22:53 UTC, stefan0xC commented on src/api/admin.rs
> -    save_result
@GeekCornerGH After thinking about it some more (and talking about it in the matrix chatroom) I think I might have been wrong about this and your explanation about the order makes a lot more sense now. Sorry for the inconvenience. :pensive: 
(The unregistering of only 1 device still seems wrong though.)

2023-04-30 16:20 UTC, BlackDex requested changes
In overall i think it looks nice (but i think i have mentioned that before).
Some small adjustments to be done I think. Though I did not yet builded this PR and gave it a test run my self, so I can't comment on that yet.

It also needs a rebase (as already mentioned on Matrix).

2023-04-30 16:20 UTC, BlackDex commented on src/api/core/accounts.rs
> +    let token = data.0.data.PushToken;
```suggestion
let data = data.into_inner().data;
let token = data.PushToken;
```

2023-04-30 16:20 UTC, BlackDex commented on src/api/push.rs
> +        if let Some(device) = Device::find_by_uuid_and_user(d.as_str(), &user.uuid, conn).await {
```suggestion
        if let Some(device) = Device::find_by_uuid_and_user(&d, &user.uuid, conn).await {
```

2023-04-30 16:20 UTC, BlackDex commented on src/api/push.rs
> +#[allow(non_snake_case)]
This can be removed i think

2023-04-30 16:20 UTC, BlackDex commented on src/api/push.rs
> +    if send.user_uuid.is_none() {
Maybe a good idea too also add the check if push is enabled or not?

```suggestion
    if !CONFIG.push_enabled() || send.user_uuid.is_none() {
```
That prevents the code from continuing and in the end still being aborted.

2023-04-30 16:20 UTC, BlackDex commented on src/api/push.rs
> +    let device = match Device::find_by_uuid_and_user(acting_device_uuid, &folder.user_uuid, conn).await {
Add an if check here if push is enabled or not, will prevent database lookups if not enabled in the first place.

2023-04-30 16:20 UTC, BlackDex commented on src/api/push.rs
> +    let data = json!({
Add an if check here if push is enabled or not.

2023-04-30 16:20 UTC, BlackDex commented on src/api/push.rs
> +    let data: JsonValue;
Add an if check here if push is enabled or not, will prevent database lookups if not enabled in the first place.

2023-04-30 16:20 UTC, BlackDex commented on src/api/push.rs
> +    if cipher.organization_uuid.is_some() {
Add an if check here if push is enabled or not, will prevent database lookups if not enabled in the first place.

2023-04-30 16:20 UTC, BlackDex requested changes
In overall i think it looks nice (but i think i have mentioned that before).
Some small adjustments to be done I think. Though I did not yet builded this PR and gave it a test run my self, so I can't comment on that yet.

It also needs a rebase (as already mentioned on Matrix).

2023-04-30 16:20 UTC, BlackDex requested changes
In overall i think it looks nice (but i think i have mentioned that before).
Some small adjustments to be done I think. Though I did not yet builded this PR and gave it a test run my self, so I can't comment on that yet.

It also needs a rebase (as already mentioned on Matrix).

2023-04-30 16:20 UTC, BlackDex requested changes
In overall i think it looks nice (but i think i have mentioned that before).
Some small adjustments to be done I think. Though I did not yet builded this PR and gave it a test run my self, so I can't comment on that yet.

It also needs a rebase (as already mentioned on Matrix).

2023-04-30 16:20 UTC, BlackDex requested changes
In overall i think it looks nice (but i think i have mentioned that before).
Some small adjustments to be done I think. Though I did not yet builded this PR and gave it a test run my self, so I can't comment on that yet.

It also needs a rebase (as already mentioned on Matrix).

2023-04-30 18:10 UTC, tessus commented on src/api/push.rs
> +    let data = json!({
@BlackDex I don't think this is necessary, since it is only called when push is enabled. or am I missing something here?

```
        if CONFIG.push_enabled() {
            push_user_update(ut, user).await;
        }
```

This is also true for the other function as far as I can tell...

2023-05-01 15:05 UTC, tessus commented
@GeekCornerGH It seems you are merging main into your PR. You need to rebase it. Currently your PR has so many changes that do not even belong to this PR that it makes reviewing it a real mess. e.g. you added 2 commits. None of them had anything to do with BlackDex's review. But I had to read all of it to find that out, and I might have missed somthing since BlackDex had quite a few comments.

2023-05-01 15:17 UTC, GeekCornerGH commented
> @GeekCornerGH It seems you are merging main into your PR. You need to rebase it. Currently your PR has so many changes that do not even belong to this PR that it makes reviewing it a real mess. e.g. you added 2 commits. None of them had anything to do with BlackDex's review. But I had to read all of it to find that out, and I might have missed somthing since BlackDex had quite a few comments.

I'm in fact using rebase, not merge. Also I missed BlackDex's comments, as my phone didn't showed the reviews themselves. Checking this rn

2023-05-01 15:24 UTC, tessus commented
> I'm in fact using rebase, not merge.

This is very strange then. Maybe I clicked on the wrong button. I think I clicked on `Compare` instead of the `Files changed` button at the top.

In that case my apologies. My bad.

2023-05-01 15:34 UTC, GeekCornerGH commented on src/api/push.rs
> +    if send.user_uuid.is_none() {
Already done [here](https://github.com/dani-garcia/vaultwarden/blob/4ec5334a77d471dd8f6082f482b80b785e4f65e0/src/api/push.rs#L271)

2023-05-01 15:34 UTC, GeekCornerGH commented on src/api/push.rs
> +    let data = json!({
Check is done [here](https://github.com/dani-garcia/vaultwarden/blob/4ec5334a77d471dd8f6082f482b80b785e4f65e0/src/api/push.rs#L271)

2023-05-01 16:03 UTC, GeekCornerGH commented on src/api/push.rs
> +#[allow(non_snake_case)]
Deserialize is required fyi

2023-05-07 01:36 UTC, tessus commented on src/db/models/device.rs
> +                .first::<DeviceDb>(conn)
I guess this is the last issue that has to be resolved, correct?

2023-05-13 19:51 UTC, tessus commented on src/db/models/device.rs
> +                .first::<DeviceDb>(conn)
@GeekCornerGH I saw that you pushed a change a while back, but you are using `.first::` in the query.
This only returns one record. Shouldn't the query return all records (devices that belong to user X)?
Then you can iterate over those records and clear the token.

2023-05-22 11:57 UTC, BlackDex commented on src/db/models/device.rs
> +                .first::<DeviceDb>(conn)
@GeekCornerGH I quickly tested it today, and this is not working. You need to extract all `push_tokens` and send it to each push_token. Else only one device will receive an update, and the other will not.

I tested this with two identical Virtual Android Devices, just one device receives this update.
So this definitely needs some work.

2023-06-10 10:43 UTC, GeekCornerGH commented
Latest changes were tested against 2 cloned AVD, running the latest apk 2023.05.0

2023-06-10 15:21 UTC, BlackDex requested changes

2023-06-10 15:21 UTC, BlackDex commented on src/api/admin.rs
> +    nt.send_logout(&user, None, &mut conn).await;
Is there a reason for this to be at the top right now?
It was at the bottom before?
I'm not really seeing a good reason for this to be here actually.

2023-06-10 15:21 UTC, BlackDex commented on src/config.rs
> +        push_relay_uri:         String, false,  def,    "https://push.bitwarden.com".to_string();
This currently isn't an internal config, and if we keep it here, i would also suggest to put it back into the `.env.template`, just to make it match everything.

So, I'm fine leaving it here, but then also add it to the `.env.template` file again,

2023-06-10 15:21 UTC, BlackDex commented on .env.template
> +
Please add the `push_relay_uri` env here again, since we seem to keep it in the config anyways. Not mentioning it here will not help. Just add a good comment to mention that it is the default, and shouldn't be changed at all, unless there are special reason too.

2023-06-10 15:21 UTC, BlackDex commented on src/api/core/accounts.rs
> +// On upstream server, both PUT and POST are declared.
If there also is a `PUT`, then i would suggest to add this also. Why leave it out? Might be that they use it somewhere for some reason?

Could be done the same as for `post_device_token` and `put_device_token`.

2023-06-10 15:23 UTC, BlackDex commented
Looks nice, some final tweaks i think.

2023-06-10 19:10 UTC, GeekCornerGH commented on src/api/admin.rs
> +    nt.send_logout(&user, None, &mut conn).await;
Indeed there is a reason. Calls between websockets and push got merged, so we have first to send logout, before unregistering push devices.

2023-06-10 19:18 UTC, GeekCornerGH commented on src/api/core/accounts.rs
> +// On upstream server, both PUT and POST are declared.
The post request was actually above.

2023-06-10 19:23 UTC, tessus commented on src/api/core/accounts.rs
> +    clear_device_token(uuid, conn).await
To make it consistent with previous function names, shouldn't this be named `clear_device_token_put`?

Btw, great job. I can't wait to see this merged!

2023-06-10 21:01 UTC, BlackDex approved these changes

2023-06-10 23:33 UTC, tessus commented on src/api/core/accounts.rs
> +    clear_device_token(uuid, conn).await
BlackDex already approved it, so please ignore my comment.

2023-06-11 05:12 UTC, BlackDex commented on src/api/core/accounts.rs
> +    clear_device_token(uuid, conn).await
While that would be better, and it still can be changed, it isn't a major issue.

Also i would like @dani-garcia look on this whole PR first too.

2023-06-11 11:38 UTC, BlackDex approved these changes

2023-06-12 18:17 UTC, dani-garcia approved these changes

2023-06-12 21:45 UTC, merged

2023-08-25 21:38 UTC, tetsumaki commented
I think you should delete `EXPOSE 3012` from many Dockerfile here : https://github.com/dani-garcia/vaultwarden/tree/main/docker

2023-08-25 22:01 UTC, BlackDex commented
> I think you should delete `EXPOSE 3012` from many Dockerfile here : https://github.com/dani-garcia/vaultwarden/tree/main/docker

For now we don't, since we need a transition from the old to the new way of websockets. And we don't want to break current installations.

2025-09-25 20:01 UTC, TryAnixx commented
its not working for me: https://github.com/dani-garcia/vaultwarden/issues/6328 can somebody help?