Add support for `/api/devices/knowndevice` with HTTP header params
dani-garcia/vaultwarden pull request #3329
Opened 2023-03-11 05:38 UTC by jjlin

Upstream PR: https://github.com/bitwarden/server/pull/2682

2023-03-11 07:27 UTC, BlackDex requested changes

2023-03-11 07:27 UTC, BlackDex commented on src/api/core/accounts.rs
> +        let email = if let Some(email) = req.headers().get_one("X-Request-Email") {
This value is base64 encoded. Shouldn't we decode that here?

2023-03-11 19:56 UTC, jjlin commented on src/api/core/accounts.rs
> +        let email = if let Some(email) = req.headers().get_one("X-Request-Email") {
Sigh, forgot about that. Thanks.

2023-03-11 20:35 UTC, BlackDex approved these changes

2023-03-15 21:03 UTC, dani-garcia approved these changes

2023-03-15 21:03 UTC, merged