support `/users/<uuid>/invite/resend` admin api
dani-garcia/vaultwarden pull request #3397
Opened 2023-03-30 12:26 UTC by nikolaevn

This PR adds new admin endpoint and action button in admin ui to resend invitation link to user (only by email, if smtp enabled).

2023-03-30 12:45 UTC, BlackDex commented on src/api/admin.rs
> +        }
Also, you need to run a `cargo fmt` 😉

2023-03-30 13:09 UTC, nikolaevn commented on src/api/admin.rs
> +        }
> Maybe we should also check if the user is in an `invite` state here. Else someone could call this endpoint bypassing the javascript check. Just to be sure we do not send an invite to an already active user.

Its not so trivial to do that, because User hasn't `status` - its [marked with todo](https://github.com/dani-garcia/vaultwarden/blob/main/src/db/models/user.rs#L230):
```
        // TODO: Might want to save the status field in the DB
        let status = if self.password_hash.is_empty() {
            UserStatus::Invited
        } else {
            UserStatus::Enabled
        };
```

Do we **really** need this check?

2023-03-30 13:26 UTC, BlackDex commented on src/api/admin.rs
> +        }
I Think we do. And how hard is it to do the following?
```rust
 if let Some(user) = User::find_by_uuid(&uuid,&mut conn).await {
        if CONFIG.mail_enabled() && user.password_hash.is_empty() {
            mail::send_invite(&user.email, &user.uuid, None, None, &CONFIG.invitation_org_name(), None).await
        } else {
            err!("User already activated there account")
        }
  }
```

Or something in those lines.

2023-03-30 13:43 UTC, nikolaevn commented on src/api/admin.rs
> +        }
I agree with you. Maybe it is better to extract "todo" as new method and use it?

2023-03-30 14:08 UTC, stefan0xC requested changes

2023-03-31 10:41 UTC, BlackDex commented on src/api/admin.rs
> +        }
That `todo` is not to create a method/function for it. But to actually store the state in the database instead of abusing the `password` field and check if it is empty or not. For now i would suggest to just check if `is_empty()` is triggered, and if so, continue sending the email, else report the user is already activated.

2023-03-31 11:04 UTC, nikolaevn commented on src/api/admin.rs
> +        }
I've added check with `is_empty()`.

2023-04-01 14:33 UTC, BlackDex approved these changes

2023-04-02 13:21 UTC, dani-garcia approved these changes

2023-04-02 13:21 UTC, merged