Revert setcap, update rust and crates
dani-garcia/vaultwarden pull request #3403
Opened 2023-03-31 11:52 UTC by BlackDex

- Revert #3170 as discussed in #3387
  In hindsight it's better to not have this feature
- Update Dockerfile.j2 for easy version changes.
  Just change it in one place instead of multiple
- Use `apk update` before running `apk add`
- Updated to Rust to latest patched version
- Updated crates to latest available

2023-03-31 16:09 UTC, jjlin commented
For the record, I disagree with the characterization that it's "better" not to have #3170 just because a handful of users who are fixated with dropping all possible privileges (even though they haven't presented any practical downside to keeping `NET_BIND_SERVICE`) feels strongly about it. Having stronger feelings and being more vocal doesn't make them more right.

2023-03-31 16:29 UTC, jjlin commented
IMO, that argument is even more hypothetical than the "hypothetical" users that #3170 is supposed to benefit, but if that's your opinion, that's fine.

2023-03-31 17:56 UTC, BlackDex commented
Both arguments apply. Not just one or the other.
I don't think it's security theater.
Also arguing that Docker already has this feature built in is a bad argument, since docker isn't the only container platform.

Anyways, main reasons are breaking change and security.

2023-04-02 10:32 UTC, williamdes approved these changes

2023-04-02 11:55 UTC, stefan0xC requested changes

2023-04-02 11:55 UTC, stefan0xC commented on docker/Dockerfile.j2
> +    && apk update && apk add --no-cache \
Why do we need to update the package index? I thought `apk add --no-cache` is sufficient to fetch and automatically remove the package index? :thinking:

2023-04-02 12:11 UTC, BlackDex commented on docker/Dockerfile.j2
> +    && apk update && apk add --no-cache \
I could be wrong, but i think the `--no-cache` means not caching the packages locally. And the update ensures the latest version info is pulled. During my test i thought i noticed without the update, it downloaded older versions of the packages instead of the latest patched versions.

2023-04-02 12:29 UTC, stefan0xC commented on docker/Dockerfile.j2
> +    && apk update && apk add --no-cache \
@BlackDex as far as I've looked into it the alpine image ships with an empty `/var/cache/apk/` directory and running `apk add --no-cache`  apparently fetches the index too:

```bash
/ # apk add --no-cache tree
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
(1/1) Installing tree (2.0.4-r0)
Executing busybox-1.35.0-r29.trigger
OK: 7 MiB in 16 packages
/ # ls -l /var/cache/apk/
total 0
```

2023-04-02 12:33 UTC, BlackDex commented on docker/Dockerfile.j2
> +    && apk update && apk add --no-cache \
We have to check the images used for the other architectures of that is the same.

2023-04-02 12:46 UTC, stefan0xC commented on docker/Dockerfile.j2
> +    && apk update && apk add --no-cache \
It's the same in sofar that the `/var/cache/apk` directories of those images are also empty (I've just mounted the image but I did not run them). I mean if they were not I would probably consider it a bug of the image as almost all best practices regarding alpine images recommend this way of installing packages.

2023-04-02 13:21 UTC, BlackDex commented on docker/Dockerfile.j2
> +    && apk update && apk add --no-cache \
Thanks for checking!
I removed it :)

2023-04-02 13:39 UTC, merged