Update deb to Bookworm, fix vulnerabilities linked to bullseye image
dani-garcia/vaultwarden pull request #3434
Opened 2023-04-08 19:18 UTC by mysther

Fix high vulnerabilities CVE-2021-3847, CVE-2023-23914, CVE-2022-27385, CVE-2019-8457, CVE-2022-42916 and 268 others vulnerabilities.

Reported by grype tool

2023-04-08 19:28 UTC, BlackDex commented
Bookworm is not yet released as stable by Debian.
I rather keep using the current stable release bullseye.

It probably won't take long for a final Bookworm release as they are on RC1 right now.

2023-04-08 19:49 UTC, mysther commented
Ok thanks for your reply, I'll see how I can help you on the topics you mentioned.

2023-04-08 19:51 UTC, BlackDex commented
> Ok thanks for your reply, I'll see how I can help you on the topics you mentioned.

Nothing much to do. My Alpine/Musl build images are already available with OpenSSL v3 and PostgreSQL v15 😉

2023-04-08 20:48 UTC, williamdes commented
I'd say we keep this PR open in draft state so the work is not lost and we can rebase it?

2023-04-12 14:17 UTC, BlackDex requested changes
I'm fine with keeping this open. But that would also mean some more changes to be done.
1. All the `runs-on:` need to be changed to `22.04` in the workflow files at `.github/workflows`
2. The Alpine images need to use the `-openssl3` tagged images ( See: https://github.com/BlackDex/rust-musl/#openssl-v30 )
3. The Alpine images need to use the v15 PostgreSQL library instead of the default v11 ( See: https://github.com/BlackDex/rust-musl/#using-a-dockerfile )

This needs to be done, else OpenSSL and PostgreSQL will not match (or too big a difference) the versions in the Debian container images which could lead to unexplained issues between tests and the releases.

2023-07-20 07:51 UTC, BlackDex commented
I'm going to close this as a duplicate of #3573 and the other reasons given above.
Also, a new Rust version has been released for which #3573 also has changes to make that work.

Besides that, still thanks for the PR! We appreciate all the help.

2023-07-20 07:51 UTC, closed without merging