fix missing password check while manual reset password enrollment
dani-garcia/vaultwarden pull request #3632
Opened 2023-07-02 07:16 UTC by sirux88

While enrolling reset password as user the web interface forces to type the password to authenticate oneself.
In its current state the backend doesn't check the password. Therefore a random passord can be used for authentification.

This PR solves this issue.

2023-07-03 20:37 UTC, BlackDex requested changes

2023-07-03 20:37 UTC, BlackDex commented on src/api/core/organizations.rs
> +                if !user.check_valid_password(&password) {
No need to define `user` here as a new variable.
You can just use:

```suggestion
    if reset_request.ResetPasswordKey.is_some() {
        match reset_request.MasterPasswordHash {
            Some(password) => {
                if !headers.user.check_valid_password(&password) {
```

2023-07-03 20:37 UTC, BlackDex commented on src/api/core/organizations.rs
> +    log_event(log_id, org_user_id, org_id, user.uuid.clone(), headers.device.atype, &headers.ip.ip, &mut conn).await;
This change is not needed by just using the `headers.user` above.

2023-07-04 17:03 UTC, sirux88 commented
@BlackDex 
let me know if I shall squash the commits

2023-07-04 17:14 UTC, BlackDex approved these changes

2023-07-04 18:55 UTC, dani-garcia approved these changes

2023-07-04 18:55 UTC, merged