US or EU Data Region Selection
dani-garcia/vaultwarden pull request #3752
Opened 2023-08-04 15:06 UTC by toto-xoxo

Following https://github.com/dani-garcia/vaultwarden/discussions/3731

Add the possibility of choosing between data region us or eu for push notifications

2023-08-04 15:11 UTC, RealOrangeOne commented on src/config.rs
> +        };
Suggestion: Instead of switching just the TLD, switch the entire hostname. It's a little more code duplication, but much easier to read, and easier to maintain should upstream decide to switch it in future on something other than TLD.

2023-08-04 15:36 UTC, BlackDex commented on src/config.rs
> +        };
I also think it is better to have two manually configurable options such as `push_relay_uri` and `push_identity_uri` which both default to there `.com` defaults like it is for Bitwarden Self-Hosted, and have people configure it them selfs.
As @RealOrangeOne already mentioned, they could change both items, or even add an Asian region for that matter.
Keeping these options a bit more flexible would be better.

Maybe some validation could be added to make sure they start with `https` and are a valid URI/URL.

2023-08-04 15:52 UTC, toto-xoxo commented on src/config.rs
> +        };
the default variables are already defined to .com but I don't rewrite the full URL every time.

Default
.com

.env to region us
.com

.env to region eu
.eu

.env to invalid region
.com

users can still write their own variable with `push_relay_uri` and `push_identity_uri` (actually identity_uri but i can rename it)

The question is should I duplicate the URL each time or change the domain extension?

2023-08-04 16:11 UTC, BlackDex commented on src/config.rs
> +        };
This would add more complexity by allowing custom URI's and region selection.

Better to just have one way.
And yes i would suggest to rename it to `push_identity_uir` to keep all together.

2023-08-04 16:13 UTC, toto-xoxo commented on src/config.rs
> +        };
you mean I should give up the idea of region? I was going for it because of the discussion we had. https://github.com/dani-garcia/vaultwarden/discussions/3731#discussioncomment-6598973

2023-08-04 17:59 UTC, toto-xoxo commented
Hey I've done some change let me know what do u think !

2023-08-04 21:47 UTC, williamdes commented on .env.template
> -# PUSH_RELAY_BASE_URI=https://push.bitwarden.com
You could keep this ENV for users that want to have a custom push server, that said I am not sure my advice is good.

2023-08-08 13:51 UTC, lnchan commented on src/config.rs
> +        let push_relay_uri = cfg.push_relay_uri.to_lowercase();
URIs are case-sensitive, this could cause issues for case-sensitive HTTP servers/reverse-proxies if a path is specified

2023-08-08 13:51 UTC, lnchan commented on src/config.rs
> +        let push_identity_uri = cfg.push_identity_uri.to_lowercase();
Same here

2023-08-08 13:51 UTC, lnchan commented on src/config.rs
> +                _ => "https://push.bitwarden.com".to_string(), // Default to "us" region
Why default to the US region?

2023-08-08 14:08 UTC, BlackDex commented
Having thought about this a bit further.

Either we force the URI's and not have anything configurable for the users except the region, thus `EU` or `US`.
Or, we keep it a bit more flexible, and only provide the `PUSH_RELAY_URI` and `PUSH_IDENITY_URI` including the `/connect/token`.
So no `PUSH_RELAY_REGION`.

The default would be `.com` and not `.eu` since `.com` was the only option before.
There should be good comments into the `.env.template` and the `config.rs` so it will be clear on what to fill in.
Probably best if we supply the options people can fill in which are the defaults from Bitwarden, and if they want to use something else, it's up to them.

I actually tend a bit more towards the latter option, because of the flexibility, also in case Bitwarden is going to change.
Or, maybe someone even builds there own Bitwarden client with there own Android/iOS messaging endpoints.

2023-08-22 08:10 UTC, mightyBroccoli commented on src/config.rs
> +        let push_relay_uri = cfg.push_relay_uri.to_lowercase();
URI are actually case-insensitive, at least if you're going by the RFC:
https://www.rfc-editor.org/rfc/rfc3986#section-3.1
I would assume servers that rely on the URI casing, are in the wrong on this one.

2023-08-22 08:42 UTC, sorcix commented on src/config.rs
> +        let push_relay_uri = cfg.push_relay_uri.to_lowercase();
You're linking to the **scheme** part, which is case insensitive. You can use `https://` or `HTTPS://` as you wish. The **path** is case sensitive.

2023-11-18 13:49 UTC, williamdes commented on .env.template
> -# PUSH_RELAY_BASE_URI=https://push.bitwarden.com
@toto-xoxo 
In fact my proposal to use a custom server was discussed here: https://github.com/dani-garcia/vaultwarden/discussions/2469

2023-11-18 13:51 UTC, williamdes requested changes
I am also with @BlackDex to keep it fully flexible in the `.env` file

Other related discussion about custom push notifications servers: https://github.com/dani-garcia/vaultwarden/discussions/2469

> I actually tend a bit more towards the latter option, because of the flexibility, also in case Bitwarden is going to change.
Or, maybe someone even builds there own Bitwarden client with there own Android/iOS messaging endpoints.

Exactly !

2023-11-23 13:08 UTC, toto-xoxo commented
Implemented requested change. Not sure if this is what you want @BlackDex waiting for your feedback

2023-11-23 13:26 UTC, BlackDex commented
@toto-xoxo  There seems to be a conflict with the .env.template.
Looks like the rebase/merge with main is not done correctly.

2023-11-23 13:36 UTC, williamdes approved these changes
Looks much nicer and easier to maintain

Any thoughts ~~@BlackDex~~ @dani-garcia ?

2023-11-23 13:37 UTC, williamdes commented on .env.template
> +
```suggestion
```

You can directly apply this with GitHub

2023-11-23 13:53 UTC, williamdes commented on .env.template
> +
```suggestion
```
I guess this one too is not related to this PR

2023-11-23 14:14 UTC, williamdes commented on .env.template
> -
now that you rebased the last commits should be dropped..

2023-11-23 14:39 UTC, toto-xoxo commented
everything should be good now check @BlackDex @williamdes

2023-12-15 16:34 UTC, BlackDex approved these changes
Looks good to me this way.

2023-12-15 17:11 UTC, williamdes commented on src/config.rs
> +        let push_relay_uri = cfg.push_relay_uri.to_lowercase();
@BlackDex should the to lower be removed?
Anyway, if users put wrong URLs it's their wish and problem

2023-12-15 17:21 UTC, BlackDex commented on src/config.rs
> +        let push_relay_uri = cfg.push_relay_uri.to_lowercase();
Well, if it doesn't matter if users put in with our without capitals, then this check is fine too be sure it starts with https i think. It doesn't change the value

2023-12-15 17:47 UTC, williamdes commented on src/config.rs
> +        let push_relay_uri = cfg.push_relay_uri.to_lowercase();
Ah yes okay it's a check
Sorry I  missed that

2023-12-19 12:32 UTC, williamdes approved these changes

2023-12-20 20:46 UTC, SuperSandro2000 commented on .env.template
> +# vim: syntax=ini
```suggestion
# vim: syntax=ini

```

2023-12-31 14:30 UTC, BlackDex approved these changes

2024-01-01 14:50 UTC, dani-garcia approved these changes

2024-01-01 15:01 UTC, dani-garcia approved these changes
Had to solve some merge conflicts, thanks!

2024-01-01 15:01 UTC, merged