Fix #3624: fix manager permission within groups
dani-garcia/vaultwarden pull request #3754
Opened 2023-08-04 19:27 UTC by matlink

Fix #3624 by checking if the user is member of a group that has access to the collection.

2023-08-04 22:30 UTC, stefan0xC commented
What if a Manager is member of a group with access to all collections?

2023-08-05 09:56 UTC, matlink commented
> What if a Manager is member of a group with access to all collections?

you are write, we lack something since in this case the manager cannot edit the collection. I'm looking into it, thanks =)

2023-08-05 10:22 UTC, matlink commented
@stefan0xC This d282b32d79dea870a54f7020a764b277702c4e54 should do the job.

2023-09-08 07:53 UTC, farodin91 commented
Any progress?

2023-09-08 08:02 UTC, BlackDex commented
It has to be checked first. Did not had time yet to validate. Working on other issues when i have the time.

2023-10-25 10:35 UTC, stefan0xC requested changes
Sorry, it took me a bit but I've finally had time to review your changes.

I think the comments and the naming of some variables/functions could be improved to make it more obvious why something is done so the changes are easier to review. I've added some suggestions for your changes but this probably applies to other variables and comments as well.

With the renamed variables I think it is easier to see how your approach could be improved upon. I.e. instead of returning the two lists of member ids and later checking if they contain the uuid of the current user, we really only care if `user_org` has full access via a group or if not, if they have access to a given collection via a group. So we could make two functions that check

1. if the given user_org has full access to an organization (either directly or via a group) 
2. if the given user_org is a member of a group assigned to the given collection.

2023-10-25 10:40 UTC, stefan0xC commented on src/api/core/organizations.rs
> +            || user_org.access_all
Also it's not necessary to check `all_access_group_uuids.contains(&user_org.uuid)` in each for loop as the result would not change. So you can start with combining it beforehand (i.e. by setting `let has_full_access = user_org.access_all || all_access_group_uuids.contains(&user_org.uuid)` and then inside the for loop change the starting value to `let mut assigned = has_full_access` and if it's not assigned at this point check if the user is a member of a group assigned to the given collection.

2023-12-31 14:43 UTC, BlackDex commented
@matlink, could you rebase and address the items mentioned by @stefan0xC?
Looks ok for the rest of it i think.

2023-12-31 15:25 UTC, matlink commented
@BlackDex will do ;)

2024-01-01 19:36 UTC, matlink commented
@BlackDex @stefan0xC I've made the changes you requested and rebased. Needs further testing ;)

2024-01-01 19:52 UTC, stefan0xC commented on src/api/core/organizations.rs
> +        assigned = !assigned && has_collection_access_via_group.contains(&user_org.uuid);
I think this is wrong. It should be 
```suggestion
        if (!assigned) {
            assigned = has_collection_access_via_group.contains(&user_org.uuid);
        }
```

2024-01-01 20:26 UTC, stefan0xC commented on src/api/core/organizations.rs
> +        assigned = !assigned && has_collection_access_via_group.contains(&user_org.uuid);
As one liner it should be `A || B` (which is only false if both A and B are false) not `!A && B` (which is only true if A is false and B is true) so you could write it as
```suggestion
        assigned = assigned || has_collection_access_via_group.contains(&user_org.uuid);
```

2024-01-04 20:25 UTC, stefan0xC requested changes
Thanks for taking the time. After taking another look at the whole change set again I found one thing (besides the formatting which you can fix by simply running `cargo fmt`) that should really be changed in this PR, because I think it's important to not do more work than is necessary and also not have side effects from a disabled feature.

Another thing that should be changed too is the one comment I suggested you remove previously because we do the checks earlier in the code:

1. check if the current user has direct access to all collections either via their membership
2. or (if groups are enabled) if the current user is a member of a group with direct access to all collections
3. and then for each collection check if the current user is assigned to the given collection
4. and (if groups are enabled and only if it's necessary) we also check if the current user has access to the given collection via a group

Otherwise it looks good to me. (I mean I think that 2. and 4. could be further improved upon but that can just as well be done in a separate PR.)

2024-01-05 07:08 UTC, stefan0xC commented
I've taken the liberty to create a PR of my own https://github.com/matlink/vaultwarden/pull/1

2024-01-06 01:36 UTC, stefan0xC approved these changes
@BlackDex Can you review/test the changes? 🙈

2024-01-27 21:56 UTC, BlackDex requested changes

2024-01-27 21:56 UTC, BlackDex commented on src/api/core/organizations.rs
> +    let has_full_access_to_org = user_org.access_all || has_full_access_via_group;
This can probably be a bit more efficient.
Currently there is a query done to check if the user has full access via the group.
But, that is not needed when the user already has full access.

Probably this should work (not tested):
```suggestion
    let has_full_access_to_org = user_org.access_all || (CONFIG.org_groups_enabled() && GroupUser::has_full_access_by_member(org_id, &user_org.uuid, &mut conn).await);
```

2024-01-27 22:49 UTC, BlackDex commented
And, it needs a rebase of course.
I tested it btw, including my suggestion, that seems to work fine.

2024-02-15 19:57 UTC, fthobe commented
Hey Guys, I don't want to put pressure on you people, but do you think we can nudge this one over the finish line? I would literally send you pizza :))))

2024-02-16 05:42 UTC, matlink commented
So I just need to rebase?

2024-02-16 06:00 UTC, BlackDex commented
> So I just need to rebase?

@matlink no see my request.
And a rebase too of course.

2024-02-17 07:25 UTC, matlink commented
@BlackDex I've applied you suggestion.
it looks like the rebase went well, no conflict.
Keep me in touch if needed.
Cheers,

2024-02-17 07:30 UTC, BlackDex commented
> @BlackDex I've applied you suggestion. it looks like the rebase went well, no conflict. Keep me in touch if needed. Cheers,

@matlink well, a small item. The code isn't formatted correctly.
Run a `cargo fmt` and that should be fixed.

2024-02-17 12:52 UTC, matlink commented
> @matlink well, a small item. The code isn't formatted correctly. Run a `cargo fmt` and that should be fixed.

Done.

2024-02-17 12:53 UTC, BlackDex approved these changes

2024-02-27 14:29 UTC, fthobe commented
Hey, can this be merged now? The issue seems to be resolved to everybody's satisfaction. If testing is needed I would volunteer.

2024-03-17 21:11 UTC, merged