WIP: Multiple domains support
dani-garcia/vaultwarden pull request #3870
Opened 2023-09-09 07:41 UTC by BlockListed

Fixes #2690 

Very WIP PR, I just want some feedback about my approach for now.

I am planning to go with the allowed domains approach, since its much simpler than the organizations support.

Overview:
- We create 2 Hashmaps, which map the Host header to either Domain or Origin.

Future:
- Change JWT system to create tokens, which work for a single domain.

2023-09-09 08:02 UTC, BlackDex commented
My first question would be, why change `Host` to `Domain`?
That is not how the header is called.

And a dev tip, install and activate `pre-commit`, that will help fixing issues before committing 😄

2023-09-09 08:09 UTC, BlockListed commented
> first question would be, why change `Host` to `Domain`? That is not how the header is called.
> 
> And a dev tip, install and activate `pre-commit`, that will help fixing issues before committing 😄

## Host
Because it definitely isn't a host.
```rust
format!("{protocol}://{host}")
```
This is a base URL, I would agree with you, that domain might also not be the correct term, but domain is the term used for the config.
It is used when creating URLs and it was very confusing. (for me at least)

## Pre-Commit
I ran cargo clippy, I know it's definitely not finished yet, but I'm not gonna put in all that work and find out at the end, that my approach is fully incompatible with the vision/goals of the project maintainers.

2023-09-09 08:12 UTC, stefan0xC commented
> Because it definitely isn't a host.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

2023-09-09 08:15 UTC, BlockListed commented
> > Because it definitely isn't a host.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host

It does not store a host. It stores a base url.

If it stored a host the extractor would be:
```rust
let headers = ...;

if let Some(host) = headers.get_one("X-Forwarded-Host") {
    host
} else if let Some(host) headers.get_one("Host") {
    host
} else {
    panic!("invalid http request");
}
```
But it's not, the extractor gets a URL from a combination of protocol, host and path (from config.domain()).

2023-09-09 08:17 UTC, BlackDex commented
Ot definitely isn't a domain, a domain is the last 2 (or 3) parts.
So, a domain is `vaultwarden.org`, a host is `vault.vaultwarden.org`, so what we are receiving is actually a host.

2023-09-09 08:19 UTC, BlockListed commented
> Ot definitely isn't a domain, a domain is the last 2 (or 3) parts. So, a domain is `vaultwarden.org`, a host is `vault.vaultwarden.org`, so what we are receiving is actually a host.

I know, but the precendent is set in `config.rs`

```
/// Domain URL |> This needs to be set to the URL used to access the server, including 'http[s]://'
/// and port, if it's different than the default. Some server functions don't work correctly without this value
domain:                 String, true,   def,    "http://localhost".to_string();
```
This definitely isn't a domain, but that's what the precedent says.

2023-09-09 08:20 UTC, BlackDex commented
> > Ot definitely isn't a domain, a domain is the last 2 (or 3) parts. So, a domain is `vaultwarden.org`, a host is `vault.vaultwarden.org`, so what we are receiving is actually a host.
> 
> I know, but the precedent is set in `config.rs`
> 
> ```
> /// Domain URL |> This needs to be set to the URL used to access the server, including 'http[s]://'
> /// and port, if it's different than the default. Some server functions don't work correctly without this value
> domain:                 String, true,   def,    "http://localhost".to_string();
> ```
> 
> This definitely isn't a domain, but that's what the precedent says.

I understand, but the location where you changed it has nothing to do with config, but with the headers.

2023-09-09 08:23 UTC, BlockListed commented
> > > Ot definitely isn't a domain, a domain is the last 2 (or 3) parts. So, a domain is `vaultwarden.org`, a host is `vault.vaultwarden.org`, so what we are receiving is actually a host.
> > 
> > 
> > I know, but the precedent is set in `config.rs`
> > ```
> > /// Domain URL |> This needs to be set to the URL used to access the server, including 'http[s]://'
> > /// and port, if it's different than the default. Some server functions don't work correctly without this value
> > domain:                 String, true,   def,    "http://localhost".to_string();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This definitely isn't a domain, but that's what the precedent says.
> 
> I understand, but the location where you changed it has nothing to do with config, but with the headers.

So then the correct term would be BaseURL right??
Because what the `Host` / `Domain` struct stores is definitely not a host.

I renamed it, because in the optimal situation (the domain is configured) the struct Stores the value from the `domain` configuration variable.

But all I really want to know is if this approach, not implementation, vibes with the project vision.

2023-09-09 08:26 UTC, BlackDex commented
But, maybe we need to wait for the whole picture. But because we didn't do it correctly in one place, doesn't mean we shouldn't at others or improve. Else we should just make it more clear using comments for other developers maybe. But i would prefer to use the right naming where possible when we adjust the code.

2023-09-09 08:31 UTC, BlackDex commented
There are some issues. Mails can be sent without any HTTP connection, so there must be one main host/domain in the config which will be used in those cases. Using a different host/domain for mails when there is a HTTP connection will become confusing.

So, the only location where i think it will be useful for are MFA and attachments/sends.

2023-09-09 08:33 UTC, BlockListed commented
> There are some issues. Mails can be sent without any HTTP connection, so there must be one main host/domain in the config which will be used in those cases. Using a different host/domain for mails when there is a HTTP connection will become confusing.
> 
> So, the only location where i think it will be useful for are MFA and attachments/sends.

That's why I added `pub fn main_domain(&self) -> String` to `Config`, it should probably be more clear in the configuration though which domain is the main one.

2023-09-09 13:51 UTC, BlockListed commented
Checks are passing now, but I still have some cleanup to be done. Probably will do it tomorrow, then it should be ready for review.
## To do (at least):
- Remove purposeful breaking changes
- Re-add domain_origin / domain_path options
- Do proper error handling for `HostInfo`

## Behaviours
- Emails always use the first domain
- JWT issuer is always the first domain's origin

2023-09-09 18:25 UTC, BlockListed commented
From my perspective I would say this is ready to review.

2023-10-07 06:07 UTC, BlockListed commented
@BlackDex Sorry for the ping, but is anything gonna happen with this PR. Because if not, it should probably just be closed.

2023-10-07 06:18 UTC, BlackDex commented
It has to wait for a check. As i mentioned in a few other pr's I'm busy with other stuff (for this project). But i just don't have much time currently.

Just be patient and my comments (or other people's comments) will follow eventually.

2024-08-28 18:40 UTC, BlackDex commented
I still think naming of a few items is still off and could be changed to better match the RFC naming.
It's true that `DOMAIN` is probably not the correct name here either, and `HOST` is also wrong, and it should actually be `URL` or even better `ABSOLUTE_URL`.

Some items could be moved to `config.rs` to prevent calling functions every time to extract the right value.
And, i just noticed we actually should not allow configuring the domain via the admin interface since we use that for static lazy loaded JWT Issuers, which should be changed if the domain is changed, or the main domain is switched.

So all in all a lot of items to address i think.

@BlockListed If you still want to work on this let me know and i will add more specific comments to the code.
Else i tend to close this PR for now.

2024-08-28 18:45 UTC, BlockListed commented
> I still think naming of a few items is still off and could be changed to better match the RFC naming. It's true that `DOMAIN` is probably not the correct name here either, and `HOST` is also wrong, and it should actually be `URL` or even better `ABSOLUTE_URL`.
> 
> Some items could be moved to `config.rs` to prevent calling functions every time to extract the right value. And, i just noticed we actually should not allow configuring the domain via the admin interface since we use that for static lazy loaded JWT Issuers, which should be changed if the domain is changed, or the main domain is switched.
> 
> So all in all a lot of items to address i think.
> 
> @BlockListed If you still want to work on this let me know and i will add more specific comments to the code. Else i tend to close this PR for now.

Yeah, I'd still be willing to work on the PR.

2024-08-28 20:18 UTC, BlackDex requested changes
Ok, have added some comments on some items which i think are mainly an issue.

But in general i think this needs to be revisited on how to solve this.

We want to prevent as much as possible to calculate the the full URL like `https://domain.com/vault` or `https://vault.domain.com` or the origin all the time during every call.

For the JWT/MFA this probably need to be dynamic too.
If i use WebAuthn or Duo, i would want to be able to login using those methods via all allowed domains, not only the main one.

Sending emails (especially the ones automated) can of course only be from the main domain. But some of course could be from the domain which the user logged-in on is using. While I'm not fully sure that is what we want though. Force the main domain here does sound more logical in general.

Some quick thoughts maybe.
A hashmap which could quickly match a domain to an origin
Mabye also for path, to match/fetch it for the specific domain.

Also, i have not checked the actual functionally.

2024-08-29 11:50 UTC, Timshel commented
Hey

So I'm the contributor maintaining the OpenID Connect PR  (https://github.com/dani-garcia/vaultwarden/pull/3899) and I'm wondering how both feature would interact. 

For the SSO, the config is global (As opposed to official Bitwarden where it's per Organization) since I believe it makes more sense in the context of smaller deployment.

The easiest solution would probably be that all domains still use the same SSO, but I'm guessing some user will want more integration between both feature.

On the other end integrating both feature at the organization level would make it closer to how it works in Bitwarden and might allow reusing things like [Domain Verification](https://bitwarden.com/help/domain-verification/) (which appear heavily linked to SSO but probably not 100% since it's in a separate config section).
But this would mean quite a lot of added complexity and maintainers would have to decide if it makes sense for the project.

2024-09-02 13:59 UTC, BlockListed commented
Yeah I've got some stuff on my plate right now.  Will try to start making changes on the weekend. Sorry for not making that more clear.

2025-02-22 02:53 UTC, Neustradamus commented
@BlockListed: Any progress on it?

2025-02-22 07:45 UTC, BlockListed commented
> @BlockListed: Any progress on it?

I've turned a lot busier than I expected. Resulted in me kinda forgetting, will try to do some work this weekend.

2025-02-22 09:23 UTC, BlockListed commented on src/config.rs
> +pub fn extract_url_origin(url: &str) -> String {
This needs to be public, so we can get the domain origin from an HTTP "Referer" header.

2025-02-22 09:38 UTC, BlockListed commented on src/config.rs
> +        domain_path:            String, false,  auto,   |c| extract_url_path(c.domain.split(',').next().expect("Missing domain"));
Don't quite remember, but pretty sure I realized this wouldn't be feasible, but will have a look.

2025-02-22 09:45 UTC, BlockListed commented on src/auth.rs
I just have a feeling, that a misconfiguration might result in unexpected behavior with regard to the extract domain.

2026-03-05 11:25 UTC, Tekka27 commented
Just a quick follow up - is there any update on the status of this issue? **It would solve my problem** 👯‍♂️

2026-03-05 11:32 UTC, MigasSec commented
Hi! Any updates on this? This feature would be very helpful for my setup. Thanks! 🚀

2026-03-19 08:34 UTC, jeroenhabets commented
Perhaps someone can chime in on the exact status but I read two impediments for merging:
1. Proper email support
2. OIDC

### 1. Email
According to @BlackDex 's [comment on Issue #2690 ](https://github.com/dani-garcia/vaultwarden/issues/2690#issuecomment-2487782197) made _after_ the last major activity by @BlockListed in 2024
> Which still doesn't solve the domain for the emails in this case.

AFAICT [d0d63a7](https://github.com/dani-garcia/vaultwarden/pull/3870/commits/d0d63a7b34fadd12cb5bb10c8e2105c63c153450) in 2025 does not seem to address this, so I suspect the multi-domains for emails are not addressed fully in this PR yet. 

### 2. OIDC
Not sure if the changes _after_  @BlackDex 's Aug'24 comment on this PR https://github.com/dani-garcia/vaultwarden/pull/3870#issuecomment-2322126784 has been fully address by @BlockListed work in 2025 as I don't see a comment multi-domain OIDC is working now.

2026-04-06 16:31 UTC, BlackDex commented
Since this PR is way to old now to be merged or tired to rebase, and my concerns are still not addressed regarding default domains, etc... I'm going to close this one.

If someone want's to attempt a new blow at this, it might be good to start a Discussion first in the Ideas section and discuss what would be needed for this to work so that the scope would be clear before someone takes an attempt.

2026-04-06 16:31 UTC, closed without merging

2026-05-14 19:03 UTC, Neustradamus commented
@BlockListed: Have you progressed on your PR?