Yet another SSO PR using OpenID Connect
dani-garcia/vaultwarden pull request #3899
Opened 2023-09-18 10:25 UTC by Timshel

First of all sorry for opening yet another PR but I'd like to be able to push modifcation to allow and facilitate review.

This is based on previous PR (#2787, #2449 and #3154) with work done by @pinpox, @m4w0lf, @Sheap, @bmunro-peralex, @tribut and others I probably missed sorry.

This PR add support for OpenId Connect to handle authentication to an external SSO.
This introduce another way to control who can use the vault without having to use invitation or an LDAP.

A master password is still required and not controlled by the SSO (depending of your point of view this might be a feature ;).  A key connector to remove this could be added but is not planned in this PR.

## Usage 

This should be agnostic to the SSO used as long as it support client secret authentication and expose an OpenID Connect Discovery endpoint. (I'm testing it with Keycloak at the moment, a demo test stack is avaible [README.md](https://github.com/Timshel/vaultwarden/blob/sso-support/test/oidc/README.md))

Added some documentation at the root of the project [SSO.md](https://github.com/Timshel/vaultwarden/blob/sso-support/SSO.md) that could be later moved to the wiki.

I made some additionnal modification in my [main branch](https://github.com/Timshel/vaultwarden/blob/main/README.md) to allow for easier testing (modified Docker image to use prebuilt patched front-end).

On front-end modification, I made patched versions available at [Timshel/oidc_web_builds](https://github.com/Timshel/oidc_web_builds). Two versions are available : 
 
 - One only restore the SSO login button 
 - Other one additionally :
    - set `#sso` as the default redirect url and remove some unnecessary logic
    - allow organization invitation to survive sso redirection
 
Only the first one is expected to be merged since only change compatible with the non-sso version will be accepted.

## Issues

As mentionned in the previous PR one of the main issue is the inability for the organization invitation to work with the SSO redirection. Two solutions are available 
  
  - A config `SSO_ACCEPTALL_INVITES` which change the logic to auto-accept pending invitation when a user log (a modified mail without invitation link notify the user of it). 
    As replied by @blackdex in https://github.com/dani-garcia/vaultwarden/pull/3154#issuecomment-1722188415 another solution might be possible.
  - A front-ent [patch](https://github.com/Timshel/oidc_web_builds/blob/master/oidc_invite.patch) which change the `Typecript`. As mentionned in the reply this is not expected to be merged due to forseen issues in maintenance.

## **:warning::warning: :warning:  If you have issues or need help testing the PR  :warning: :warning:  :warning:**
Please open issues in [Timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues) in order to keep the discussion here focused on merging this work. Of course if you believe your issue is important mention this PR so a reference will be visible.

But please try to keep commenting in this PR to a minimum to keep it legible, the previous one has over 200 comments ...

2023-09-25 20:56 UTC, hqnna commented
Any update on this?

2023-09-28 10:23 UTC, derfabianpeter commented
Super happy to see this PR being worked on. We (ayedo.de) would be willing to offer a sponsoring to prioritize this PR if that helps! Just reach out.

2023-09-28 17:09 UTC, Timshel commented
Just added a configuration example for [Gitlab](https://gitlab.com/) which might be one of easiest way to test this PR :).

2023-09-29 18:21 UTC, AkechiShiro commented
Hi @Timshel, thanks for your amazing and prolonged work on this feature, is this PR close to be in a ready merge-able state or is there a lot of work left?

2023-09-29 21:59 UTC, Timshel commented
Mainly waiting for maintainer review/feedback now :).

2023-09-30 14:53 UTC, ruben-herold commented
@Timshel thx for your work!!! Hope this will be integrated soon

2023-10-04 00:24 UTC, pellux-network commented
Hoping this gets merged soon!

2023-10-04 09:22 UTC, AkechiShiro commented
Tagging some maintainers for review on this PR, if they have the available time resource to do so @BlackDex @dani-garcia

2023-10-04 10:36 UTC, BlackDex commented
I do not have much time actually.

Also, I'm a bit puzzled with all the different SSO PR's.
And I am a bit hesitant to merge one if that for some reason could break the other or has a totally different way of working.
I'm not sure what to do here because i see people want something like this, but there are multiple ways of getting this working it looks like.

One way would be to create a semi-supported release branch which contains SSO support, but that could get messy keeping it up-to-date. What do you think @dani-garcia ?

2023-10-04 10:48 UTC, Timshel commented
? As mentioned this is the continuation of the previous PRs, it all rely on  [openidconnect](https://docs.rs/openidconnect/latest/openidconnect/). All of those PR are based on the previous ones when the previous PR owner stopped maintaining it. 

I can´t  speak for the owner of previous PRs but I believe this make all the others redundant. You could probably close the previous one referencing this one and encourage their owner to reopen if something is missing.

Thanks @bmunro-peralex for closing his PR to make things more legible and of course for his work which is present in this PR :).

2023-10-04 11:15 UTC, xoxys commented
Why not finally add at least one way to support OIDC? You can also flag it as preview feature or something like this to get feedback from the community, but not getting this feature into Vaultwarden after multiple PRs were provided by the community without a review or without getting merged for months until the authors then gave up feels wrong to me for an open source project.

2023-10-04 11:31 UTC, BlackDex commented
> Why not finally add at least one way to support OIDC? You can also flag it as preview feature or something like this to get feedback from the community, but not getting this feature into Vaultwarden after multiple PRs were provided by the community without a review or without getting merged for months until the authors then gave up feels wrong to me for an open source project.

Well, because One way could be a different way then the others, or could cause a lot of other changes needed to be done if they do not match, or maybe even could overlap and do something totally different. 49 FIles are changed, so I'm not going to be happy if there needs to be major rework done because of adding this feature which is not fully working/supported.

You have to keep in mind that this could break other code in some way. But as said before, i do not have much time to check and validate this. And this is a huge PR and a lot of testing needs to be done, and i this is not specifically on my prio list for now actually. That is why i mentioned a special branch, which builds this version with a different tag and not fully supported in terms of issues with the login from my side.

2023-10-04 11:44 UTC, Timshel commented
> Well, because One way could be a different way then the others, or could cause a lot of other changes needed to be done if they do not match, or maybe even could overlap and do something totally different.

@BlackDex  I'll insist but there is no other way (At least not in the currently opened PRs). All those PR are based on the previous ones. They got more refined each time as someone picked-it up.

2023-10-04 13:27 UTC, tschuyebuhl commented
is there any way one can help with testing? or anything that can be done to help get this merged?

2023-10-04 15:49 UTC, isaiah-v commented
I've been watching the progress of this feature. I can't wait for it, but out of curiosity, how does decryption work with this feature? Is it still client side? How do you now decrypt without knowing the password?

2023-10-04 16:05 UTC, Timshel commented
@isaiah-v as mentioned a master password is still required. There is no change on this point.

2023-10-06 07:42 UTC, Timshel commented
@BlackDex thinking on it I don´t think the semi-supported branch is a good idea.

Main issue for people running this branch is that there might be some change in the migrations that might force to correct DB state manually. Even if it's not difficult (cf [Timshel/vaultwarden#db-migration](https://github.com/Timshel/vaultwarden/tree/main#db-migration)), integrating in a separate branch would not help with this.

Additionally unless you grant me commit rights it means that this would make it more complicated for me to support it and if you have no time for review I can't see how you would semi-support it.

It's important to note that the `SSO_ENABLED` config act as feature flag, the impact on the non sso version is quite low so merging this should have a low risk for the non sso users.

In the end if people are not running it at the moment it might be because they are waiting for an easier way to run this (but I made updates on [main@Timshel/vaultwarden](https://github.com/Timshel/vaultwarden/tree/main) to make it easier) but I would expect it's mainly because they are waiting for it to be reviewed, a solution without any review would not be worth much ...

Since I'm running this myself I will maintain this branch/PR, and will continue to update [main@Timshel/vaultwarden](https://github.com/Timshel/vaultwarden/tree/main) with anything I can think of to help people running it. As mentioned before if you have any question don't hesitate but please open it on [Timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues) to prevent spamming here (of course mention this PR if you think your issue is important).

In my opinion the next step is for it to be reviewed and then integrated (maybe without being promoted at first).

2023-10-06 13:40 UTC, AkechiShiro commented
I will definitely try to host the branch of your fork that contains sso-support and see if I run into any issues, I will report them on your repo @Timshel

2023-10-09 06:43 UTC, daanschenkel commented
+1, please merge!

2023-10-10 13:06 UTC, griefie commented
It seems that there is a lot of hesitation on investing time into reviewing this and i can understand this. However - the longer the delay the bigger the diff guys. The branch clearly works and simply needs a bit more love. Besides it already looks like a lot of work went into this and the older preceding branches. Why not make it a beta build? Even 2.0.0-beta? The closer it is to the main stream, the quicker will be the feedback and the improvement. Let's not forget this is open source, where ideas thrive and not corporate where ideas die ;)

2023-10-10 13:08 UTC, derfabianpeter commented
We're still happy to sponsor this PR if it helps

2023-10-23 07:18 UTC, realSaltyFish commented
Currently the email address is used as a new user's default "name" (shown in the screenshot below). It is better to take the `name` field in the `profile` scope returned by the OIDC authority. Can this be implemented?
![image](https://github.com/dani-garcia/vaultwarden/assets/64259296/c399fe5b-da9f-464b-a4b0-251d38045ee4)

2023-10-24 12:13 UTC, Timshel commented
@BlackDex Hey [fixed](https://github.com/dani-garcia/vaultwarden/pull/3899/commits/9ce3d5f699c5d2673d7a77d52309f890c5415751) an issue with the upgrade to  [jsonwebtoken=9.0.0](https://github.com/dani-garcia/vaultwarden/blob/ecb31c85d68202f9d215c8ce12939158fb858af9/Cargo.lock#L1551):  

 -  https://github.com/Keats/jsonwebtoken/pull/332 make the audience mandatory 

 No idea if it might not have an impact in [auth.rs](https://github.com/dani-garcia/vaultwarden/blob/main/src/auth.rs#L52).
 
 @realSaltyFish Hey, good suggestion but had a quick look and initially decided to go with `preferred_username` which is also in the `profile` scope (if missing fallback to the `email`).
 After looking at the spec again the `name` appeared to be a better option but when testing it it's harder to handle since it's [localized](https://docs.rs/openidconnect/latest/openidconnect/core/type.CoreUserInfoClaims.html#method.name) in [openidconnect](https://docs.rs/openidconnect/latest/openidconnect/index.html) and when testing with the minimum `keycloak` config I use it's empty so might stay with `preferred_username` for now.

2023-10-24 15:21 UTC, BlackDex commented
> @BlackDex Hey [fixed](https://github.com/dani-garcia/vaultwarden/pull/3899/commits/9ce3d5f699c5d2673d7a77d52309f890c5415751) an issue with the upgrade to [jsonwebtoken=9.0.0](https://github.com/dani-garcia/vaultwarden/blob/ecb31c85d68202f9d215c8ce12939158fb858af9/Cargo.lock#L1551):
> 
>     * [Reject tokens when claims has an aud, none expected Keats/jsonwebtoken#332](https://github.com/Keats/jsonwebtoken/pull/332) make the audience mandatory
> 
> 
> No idea if it might not have similar issue in [auth.rs](https://github.com/dani-garcia/vaultwarden/blob/main/src/auth.rs#L52).
> 
> @realSaltyFish Hey, good suggestion but had a quick look and initially decided to go with `preferred_username` which is also in the `profile` scope (if missing fallback to the `email`). After looking at the spec again the `name` appeared to be a better option but when testing it it's harder to handle since it's [localized](https://docs.rs/openidconnect/latest/openidconnect/core/type.CoreUserInfoClaims.html#method.name) in [openidconnect](https://docs.rs/openidconnect/latest/openidconnect/index.html) and when testing with the minimum `keycloak` config I use it's empty so will stay with `preferred_username` for now.

We do not use `aud` as far as i know, so that shouldn't be an issue.

2023-10-24 22:25 UTC, realSaltyFish commented
> @realSaltyFish Hey, good suggestion but had a quick look and initially decided to go with preferred_username which is also in the profile scope (if missing fallback to the email).
After looking at the spec again the name appeared to be a better option but when testing it it's harder to handle since it's [localized](https://docs.rs/openidconnect/latest/openidconnect/core/type.CoreUserInfoClaims.html#method.name) in [openidconnect](https://docs.rs/openidconnect/latest/openidconnect/index.html) and when testing with the minimum keycloak config I use it's empty so will stay with preferred_username for now.

@Timshel Thanks for your reply! FYI I use Authentik and its default property mapping sets `preferred_username` to the *username*, while `name` is the display name. Can you elaborate a bit more on how localization makes it harder to handle? Using `preferred_username` already provides enough flexibility (Authentik allows creating custom mappings) but otherwise falling back to `name` might still makes more sense.

2023-10-25 07:29 UTC, Timshel commented
@realSaltyFish nothing crazy but would probably need :

- First read the locale from the user, the `accept-language`  is probably set by the front-end.
- Then if it's missing or there is no value probably fallback to a default server locale (vaultwarden is mainly hardcoded english I believe)
- But it would be better to have this default in the conf and not just hardcoded in place. 
- And this conf would probably make sense to not be specific to the SSO logic (I don't believe there is one already).

So this would make this PR a little bit more complicated (which it really doesn't need ^^) and for now you are the only one who requested the feature so I'm a bit hesitant to implement it :).

2023-11-09 10:44 UTC, Blackclaws commented
It would be great to see this officially merged to the main repository. From a cursory test it seems that it works as advertised. The organization invite problem might be something that we need a definite solution for before more people open issues about it (or we just document it very well).

2023-11-09 11:53 UTC, Timshel commented
> What I haven't tried yet is if it works to migrate users from standard accounts to SSO if the names/emails match.

@Blackclaws as long as the `email` match there should be no issue, both login method can work at the same time with `SSO_ONLY=false` config.

Issues might arise with 2FA solutions, I tested email and TOTP and had no issue, someone reported that there is [some](https://github.com/Timshel/vaultwarden/issues/3) with Duo (need a phone number to test, will try to test it with a temporary number).

2023-11-09 19:26 UTC, mandree95 commented
Would be awesome seeing this getting merged. One option could be to enable this as a preview feature to gather more feedback and test results.
If I understand correctly, this is PR is awaiting review, right?

2023-11-10 02:45 UTC, germanbravouy commented
Would be great to have this PR merged, im using vaultwarden with internal accounts and it would help a lot for user management that this can be integrated through OIDC to a SSO (like Keycloak)

2023-11-10 15:26 UTC, Ontahm commented
@germanbravouy  I'm definitely with you on this one

However, you could just build your own docker image from the fork.

I just did, it works like a charm when you read and understand the comments on this PR to solve the minor issues.

I highly approve the merge as well though. It's never good to use custom images. Maybe format this into an F.A.Q. format for those that might miss the thread ?

In the meanwhile, thanks  you so much @Timshel  for the work on this, it helped me a lot and I'm so grateful for your changes !

2023-11-10 15:28 UTC, Ontahm reviewed
I did not really go deep into the code, but I tried the docker image with the changes and the benefits are so much higher than the little issues encountered when adding users. It works like a charm for me and I would highly encourage the merge.
@dani-garcia  I solved my issue and I'm using the custom image for now, but please consider merging this PR and leave perfection for later

2023-11-10 15:53 UTC, germanbravouy commented
@Ontahm what issues? As im aware the only issue is the one affecting DUO 2FA users right?

As @Timshel explained, integrating OIDC works perfectly for internal users already created if the email of the internal user matches with the oidc user email attribute.

2023-11-12 21:40 UTC, realSaltyFish commented
I have been using custom images for several months without any big issue, but it is a lot of extra work to keep the custom images up to date. Would really love to see this merged.
This line of PRs has been around for over a year now, and given the huge number of people eager to see it merged, why not just merge it now and leave small 2FA issues for bug fix releases later? An imperfect implementation is at least better than nothing...

2023-11-12 22:45 UTC, BlackDex commented
> I have been using custom images for several months without any big issue, but it is a lot of extra work to keep the custom images up to date. Would really love to see this merged. This line of PRs has been around for over a year now, and given the huge number of people eager to see it merged, why not just merge it now and leave small 2FA issues for bug fix releases later? An imperfect implementation is at least better than nothing...

Well, good to know that you have a working production environment, i do wonder if you are using this specific PR, or others this PR is derived from?

Also just merging this is not a good idea, There are probably a few items which need to be changed (for one this PR is in need of a new rebase, and i saw some changed files which doesn't make sense).

Besides that, some of these changes also changed code touching other login methods, account creation and validation etc...
All those items need to be carefully checked and validated they do not effect currently running systems which are in production, or break stuff if someone enables this feature.

It is always good to know if people are using a custom build version of Vaultwarden using this PR and having no issues, that will help in determining if this PR is a working solution or not.

I hope i have some time (and energy) to check this PR my self in a more in-depth look soon, but i can not promise anything.

2023-11-13 03:27 UTC, realSaltyFish commented
> i do wonder if you are using this specific PR, or others this PR is derived from?
I have been using #3154 since July, until this PR took it over. I made some ad-hoc runtime frontend patches by injecting javascript at the reverse proxy, but thanks to @Timshel these are no longer needed. I am now running the branch from this PR, with Timshel's webvault patching commit cherry-picked.

Is there a list of specific things to check and validate? I can do these testing as well to make sure it doesn't break existing logic.

2023-11-13 12:10 UTC, Timshel commented
> i saw some changed files which doesn't make sense

@BlackDex  if you remember those I'll check again :)

2023-11-13 15:31 UTC, maxulm commented
Where has the SSO-Login-Button gone?
![image](https://github.com/dani-garcia/vaultwarden/assets/19280402/3681c81c-21a4-40e7-8e9f-1091e87d19cd)

2023-11-13 15:42 UTC, Timshel commented
@maxulm please open an issue there https://github.com/Timshel/vaultwarden/issues

2023-11-13 16:05 UTC, maxulm commented
> @maxulm please open an issue there https://github.com/Timshel/vaultwarden/issues

Ok, done : https://github.com/Timshel/vaultwarden/issues/6

2023-11-14 12:34 UTC, markkrj commented
I've been following SSO PRs for some time now, but abstained from commenting, as I have nothing to add. But I have to say that I think it has little chance of being merged. This project has mainly two maintainers. @BlackDex already said he has little interest in it as he has no use for SSO, and @dani-garcia, since ~April, seems to be working for Bitwarden, which has kind of a conflict of interest with this feature, as SSO is in their enterprise offering. I think we would only see this feature in a fork, which is a shame, because it always end up fragmenting the community...

2023-11-14 16:35 UTC, BlackDex commented
> I'm truly sorry to hear about your dog. My dog was diagnosed with CKD just recently. It's disheartening to feel that there's little we can do to help them.

Indeed, i have a cat with the same condition, the right food helps a lot btw :). Hope it will be under control soon.

> 
> Anyway, a didn't mean to sound rude, or anything. I know maintaining an open source software like this is often a thankless job, and I'm very grateful that there are people like you guys, who dedicate your own time to it. But I feel that the time of people who spent their time contributing should be respected also, and some times, there is no transparency from maintainers wether some feature is wanted, or will ever get merged, for whatever reason.

No prob, if that is what the users/contributors feel then it's best to have it spoken out. That is also why i reacted to it that it is not something we want to block or not merge. It's just a huge PR, 52 files changes over 2100 lines of codes changed, logic changes etc.. It's not that simple. Same btw for some other long standing issues/PR's regarding groups, it's a pain to fully test it and have a nice working solution.

2023-11-14 17:48 UTC, LightningManGTS commented
I've been running this for a few weeks now with no real issues. There are things like inviting users I have to test still. But otherwise everything appears business as usual. For reference I'm running vaultwarden in a LXC using tteck's script modified to point at the fork instead. 

Regarding the issue with the traditional DUO integration. I'm not sure how much Dev time is worth looking into it, and should probably be prepared to be removed from Vaultwarden anyways, See for the EOL on the traditional prompt: https://help.duo.com/s/article/7839?language=en_US

SSO or the Universal prompt is the "future" of DUO integration. As far as I'm aware there is no upstream update from bitwarden regarding a replacement for the traditional prompt for the universal one outside of a single forum post here: https://community.bitwarden.com/t/support-for-duo-universal-prompt/37017/11

A master disable and lock out for the traditional DUO integration when SSO is enabled would serve just as well. Its unlikely you would have the traditional duo prompt setup when you would setup SSO through DUO instead.

2023-11-15 23:36 UTC, BlackDex requested changes
I have not tested it, and not fully checked everything, these were just some items i noticed quickly.

2023-11-16 11:27 UTC, Timshel commented on src/api/core/organizations.rs
> +async fn list_policies_invited_user(org_id: String, userId: String, mut conn: DbConn) -> JsonResult {
`userId` is a query parameter, I don't believe there is case matching on those ?
Made a quick search if it was a field `#[rocket(from = "someParam")]`  but in this case the `#[allow(non_snake_case)]` seem simpler no ?

2023-11-16 11:38 UTC, Timshel commented on src/api/identity.rs
> +        "ResetMasterPassword": user.password_hash.is_empty(),
Testing again it does not appear to be needed to trigger the `set-password` enrollment.
So I will just revert.

2023-11-24 22:33 UTC, ict-one-nl commented
Guys, great to see all this work! This is an absolute must have for enterprise usage. 

I'm working at an university that's looking into a central password management solution and Vaultwarden would be a viable option. Especially since I reached out to Bitwarden support and were very supportive of Vaultwarden / open source. We were kind of worried that they would feel threatened, but this doesn't seem the case at all. 

What would you need to complete support for OIDC/SAML? We probably could contribute a formal pentest of the final solution. If more is needed, what would it be?

2023-11-27 09:11 UTC, dasJ commented on SSO.md
> + - `SSO_KEY_FILEPATH` : And optional public key that can be used to authenticate the SSO during the exchange flow.
Not too thrilled about this. Neither the name nor the description show that this has anything to do with JWTs. I thought this was for verifying the TLS certificates of the OP

2023-11-28 15:53 UTC, Timshel commented on SSO.md
> + - `SSO_KEY_FILEPATH` : And optional public key that can be used to authenticate the SSO during the exchange flow.
Good catch, thx :).

2023-11-29 20:03 UTC, misilot commented
> Pushed a fix for DUO 2fa, tested it using Duo Mobile and the Push solution.

Was this a fix to support Universal Prompt in Vaultwarden, or disabling it, if SSO is enabled?

2023-11-29 22:18 UTC, LightningManGTS commented
> > Pushed a fix for DUO 2fa, tested it using Duo Mobile and the Push solution.
> 
> Was this a fix to support Universal Prompt in Vaultwarden, or disabling it, if SSO is enabled?

The fix was when DUO traditional prompt comes up instead of it failing to match the user in DUO it not correctly goes through after SSO. If you setup users for SSO and they still have the traditional prompt enabled they need to still go in and disable it themselves as there is no global on/off switch for users. The support for the universal prompt is an upstream issue with Bitwarden. It can probably be done at the Vaultwarden level but it would have to be implement it from scratch. Unless Bitwarden/Vaultwarden adds additional/different behavior, it would still likely be at the user level where it can be enabled.

From a Dev standpoint on Bitwarden/DUO they may not care or want to do anything about adding Universal Prompt support when SSO is already working in Bitwarden with DUO.

2023-11-29 22:19 UTC, misilot commented
Ok, thanks for clarifying! If this made it in, we wouldn't have an issue since we could require MFA from the SSO standpoint :)

2023-12-08 11:17 UTC, Timshel commented
@BlackDex Hey just to be sure should I resolve the review comments or will you do it after checking the changes ? (Every fix are in the latest commit https://github.com/dani-garcia/vaultwarden/pull/3899/commits/8cb654d1bbbf7fcf48134e3dd3fbbd8aa3279898).

2023-12-19 17:39 UTC, binaryfire commented
Now that all other SSO PRs have been consolidated into this one and closed, it might be worth renaming this one?

2023-12-20 21:18 UTC, Avsynthe commented
Good God it looks like we're almost there. It's finally happening!

2023-12-20 21:24 UTC, ict-one-nl commented
If you have a testing branche and some  instructions  I'm happy to test the solution!

2023-12-20 22:12 UTC, kosssi commented
@ict-one-nl the documentation is [here](https://github.com/dani-garcia/vaultwarden/pull/3899/commits/0e1dcd8c199cdc82ef11c6da0e48e3bd4c76099d) I push my generate Docker image on the [Docker Hub](https://hub.docker.com/r/simonc/vaultwarden) with the latest commit [2c9352a](https://github.com/dani-garcia/vaultwarden/pull/3899/commits/2c9352af3d3bd252b16805715c3c48de91d51c9d) ;)

2023-12-21 10:39 UTC, SystemFuchs commented
> @ict-one-nl the documentation is [here](https://github.com/dani-garcia/vaultwarden/pull/3899/commits/0e1dcd8c199cdc82ef11c6da0e48e3bd4c76099d) I push my generate Docker image on the [Docker Hub](https://hub.docker.com/r/simonc/vaultwarden) with the latest commit [2c9352a](https://github.com/dani-garcia/vaultwarden/pull/3899/commits/2c9352af3d3bd252b16805715c3c48de91d51c9d) ;)

Hi @kosssi, in the Docker Hub there seems to be an older version or is it already updated?

2023-12-21 15:38 UTC, kosssi commented
Oups I'm sorry it's [2e4ed3b](https://github.com/Timshel/vaultwarden/commit/2e4ed3b77afed0f1194503185adaa5124cada1f3) the last commit of the [main branch](https://github.com/Timshel/vaultwarden)

2023-12-21 18:29 UTC, Timshel commented
Hey,
Some good news, with the `v2023.12.0` release https://github.com/bitwarden/clients/pull/5733 landed and fix part of the organization invitation problem :). The leftovers in the [patch](https://github.com/Timshel/oidc_web_builds/blob/master/oidc_invite.patch) are now quite trivial.
Still need to run the `override` build from https://github.com/Timshel/oidc_web_builds.

2023-12-22 14:48 UTC, Timshel commented
Latest commit add the ability to optionally configure the master password policy  ([cf](https://github.com/Timshel/vaultwarden/blob/d801ae93bb6fbfd65278ce4c9f4df07457b4a828/.env.template#L376)) :
```
{
    "enforceOnLogin": false,
    "minComplexity": 3,
    "minLength": 12,
    "requireLower": false,
    "requireNumbers": false,
    "requireSpecial": false,
    "requireUpper": false
}
```

You'll need to run a front-end based on the `v2023.12.0` version (latest from [dani-garcia/bw_web_builds](https://github.com/dani-garcia/bw_web_builds) or [Timshel/oidc_web_builds](https://github.com/Timshel/oidc_web_builds)). 

:warning:  The [default](https://github.com/Timshel/vaultwarden/blob/sso-support/docker/Dockerfile.debian#L29) docker image still depends on the `v2023.10.0`. Not sure why the `v2023.12.0` has not been integrated in `main`, it's possible there is some issue.

2023-12-22 20:26 UTC, fabsau commented
I just successfully tested it with Google Workspace and the simonc/vaultwarden:latest image. Thank you so much for putting the effort in. You can't believe how happy I am about this!
It is working as expected, and I'm glad you allowed to skip the masterpassword step.

Any plans to employ autojoin an organization and passing through the OU groups to Vaultwarden groups? To my knowledge, there is not any group functionality in vaultwarden, so I think this might be out of scope?

In case anybody is interested, here is a short tutorial on how to set it up with Google Workspace:
1. In the Google Cloud Console you need to have a project and visit “APIs and services” and then “credentials”.
2. Create an OAuth client ID credential by pressing “Create credential”, select “Webapplication” as Application type, set for the authorized redirect URI “https://your_vaultwarden_url.com/identity/connect/oidc-signin” and hit save.
3. Use the client_id and secret from the Cloud Console for the SSO_CLIENT_ID and SSO_CLIENT_SECRET variables.
4. Done

2023-12-24 00:29 UTC, Timshel commented
Hey,
So just wrote some code to add user to organizations using an optional `groups` claim.  It's very basic (way less powerful than the connector) : 
 - Allow to configure an optional `scope` (default is `groups`)
 - It needs to add a `groups` claim to the token
 - The organizations need to be created manually
 - On a login if an Organization name match one of the returned `groups` then it will added with the `User` role.
 - Status will either be `Invited` or `Accepted` depending on the `SSO_ACCEPTALL_INVITES` conf.
 - An admin will need to confirm the invitation.
 - On creation if a user is associated with an existing Org then the master password policy will be used if one exists instead of the hard coded one.
 
 It's not very polished atm, will work on it a bit more next week, it's available on [Timshel/vaultwarden/main](https://github.com/Timshel/vaultwarden/tree/main).
 Since it adds complexity I don't expect to include it in this PR, it would be added in a following PR.
 
 :warning: Since it won´t be included here please if you have some feedback/issues comment there : [Timshel/vaultwarden/issues](https://github.com/Timshel/vaultwarden/issues)
 
 Happy Holidays.

2023-12-24 12:43 UTC, ict-one-nl commented
> I just successfully tested it with Google Workspace and the simonc/vaultwarden:latest image. Thank you so much for putting the effort in. You can't believe how happy I am about this! It is working as expected, and I'm glad you allowed to skip the masterpassword step.
> 
> Any plans to employ autojoin an organization and passing through the OU groups to Vaultwarden groups? To my knowledge, there is not any group functionality in vaultwarden, so I think this might be out of scope?
> 
> In case anybody is interested, here is a short tutorial on how to set it up with Google Workspace:
> 
> 1. In the Google Cloud Console you need to have a project and visit “APIs and services” and then “credentials”.
> 2. Create an OAuth client ID credential by pressing “Create credential”, select “Webapplication” as Application type, set for the authorized redirect URI “https://your_vaultwarden_url.com/identity/connect/oidc-signin” and hit save.
> 3. Use the client_id and secret from the Cloud Console for the SSO_CLIENT_ID and SSO_CLIENT_SECRET variables.
> 4. Done
> 
> Edit: I just discovered the Directory Connector, set it all up and enabled "org_groups_enabled":true," in the config. just got about 400 users imported and set up all the permissions. WOW

Trying to test out things as well :) Which SSO_AUTHORITY did you use for Google?  Using https://accounts.google.com/.well-known/openid-configuration gives me a 

`{"ErrorModel":{"Message":"Failed to discover OpenID provider: Server returned invalid response: HTTP status code 404 Not Found","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Failed to discover OpenID provider: Server returned invalid response: HTTP status code 404 Not Found","Object":"error","ValidationErrors":{"":["Failed to discover OpenID provider: Server returned invalid response: HTTP status code 404 Not Found"]},"error":"","error_description":""}`

2023-12-24 13:20 UTC, Timshel commented
@ict-one-nl the openid lib add the `.well-known/openid-configuration` part so for google I believe you only need `SSO_AUTHORITY=https://accounts.google.com`.

2023-12-24 14:02 UTC, ict-one-nl commented
That works, thanks! This is one for the docs and maybe implement either a check plus error and thus quitting, or fixing it automatically, but give an info notice in the logs?

Another one that caught me off guard: 

- Logging in
- Error at Google: redirect_uri=https://domain//identity/connect/oidc-signin
- Because of env var: DOMAIN=https://domain/
- Mind the trailing / that's causing the error; one for the docs but maybe also handle it more gracefully or at least log it?

Something that strikes me as a bit odd and different from other SSO implementations, I have:

```
env{
             name = "SSO_ENABLED"
             value = "true"
          }
          env{
             name = "SSO_ONLY"
             value = "true"
          }
```

But in the first screen there is room for an emailaddress (user: huh, this was SSO right? Why do I need to fill this in?), the in the second screen the SSO button appears but you can also fill in a password. 

Would have anticipated that the SSO-button would be either present at the first screen or since we are forcing SSO that the user would have been redirected immediately.  I also would have anticipated that the email/password login would be completely gone since SSO_ONLY = true. No need for the emailaddress/password combo. It is confusing that the user seems to be able to login with a non-SSO account but that the option to create an account is missing.

But let me stress: [it's working!!! ](https://www.youtube.com/watch?v=_ElWlUr_tw8)

2023-12-24 14:20 UTC, craigwitter commented
At least on regular enterprise bw, you always get the email prompt and then
can choose sso or password. Sso can be required for regular users, but
admin users can always login with password as a backdoor if sso is broken.


On Sun, Dec 24, 2023, 9:03 AM Sander van de Geijn ***@***.***>
wrote:

> That works, thanks! This is one for the docs and maybe implement either a
> check plus error and thus quitting, or fixing it automatically, but give an
> info notice in the logs?
>
> Another one that caught me off guard:
>
>    - Logging in
>    - Error at Google: redirect_uri=
>    https://domain//identity/connect/oidc-signin
>    - Because of env var: DOMAIN=https://domain/
>    - Mind the trailing / that's causing the error; one for the docs but
>    maybe also handle it more gracefully or at least log it?
>
> Something that strikes me as a bit odd and different from other SSO
> implementations, I have:
>
> env{
>              name = "SSO_ENABLED"
>              value = "true"
>           }
>           env{
>              name = "SSO_ONLY"
>              value = "true"
>           }
>
> But in the first screen there is room for an emailaddress (user: huh, this
> was SSO right? Why do I need to fill this in?), the in the second screen
> the SSO button appears but you can also fill in a password.
>
> Would have anticipated that the SSO-button would be either present at the
> first screen or since we are forcing SSO that the user would have been
> redirected immediately. I also would have anticipated that the
> email/password login would be completely gone since SSO_ONLY = true. No
> need for the emailaddress/password combo. It is confusing that the user
> seems to be able to login with a non-SSO account but that the option to
> create an account is missing.
>
> But let me stress: it's working!!!
> <https://www.youtube.com/watch?v=_ElWlUr_tw8>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dani-garcia/vaultwarden/pull/3899#issuecomment-1868523935>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADDNYG7K432HQRQC2QPOKG3YLAY2DAVCNFSM6AAAAAA44PS52CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNRYGUZDGOJTGU>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-12-26 11:26 UTC, williamdes commented on src/api/core/organizations.rs
> +// Since the VW SSO flow is not linked to an organization it will be called with a dummy or undefinned `org_id`
```suggestion
// Since the VW SSO flow is not linked to an organization it will be called with a dummy or undefined `org_id`
```

2023-12-27 13:16 UTC, ict-one-nl commented
Tested it with the Google OIDC implementation, that's working like a charm. I'm now in the process of connecting it to our corporate AzureAD config to test that one.

2023-12-27 18:40 UTC, Kofl commented
> Tested it with the Google OIDC implementation, that's working like a charm. I'm now in the process of connecting it to our corporate AzureAD config to test that one.

Had no luck with AzureAD (now renamed to Entra ID) too to non-standard implementation on the Microsoft end.
https://github.com/Timshel/vaultwarden/issues/8

But with Keycloak as identity broker it finally worked out. Cant find for the PR to go live.

2023-12-27 18:47 UTC, modem7 commented
> > Tested it with the Google OIDC implementation, that's working like a charm. I'm now in the process of connecting it to our corporate AzureAD config to test that one.
> 
> Had no luck with AzureAD (now renamed to Entra ID) too to non-standard implementation on the Microsoft end.
> https://github.com/Timshel/vaultwarden/issues/8
> 
> But with Keycloak as identity broker it finally worked out. Cant wait for the PR to go live.


Authentik also has non-standard implementation as well. Just in case people need to test.

2023-12-27 18:53 UTC, Kofl commented
> Authentik also has non-standard implementation as well. Just in case people need to test.

Yes. So far Timshel confirmed his tests worked fine with Authelia and  Authentik on my https://github.com/Timshel/vaultwarden/issues/8

2023-12-27 19:06 UTC, Timshel commented
Small clarification :).

For Keycloak and Authentik there is some demo `docker-compose` [here](https://github.com/Timshel/vaultwarden/tree/main/test/oidc). Did not test the Authentik stack with latest chance but I expect it will still works :), need to add it to the tests.

For Authelia I believe @kosssi tested it and confirmed it works but I did not directly tested it ^^.

2023-12-27 19:15 UTC, JohnCMoon commented on SSO.md
> +To use an external source of authentication your SSO will need to support OpendID Connect :
Nit: typo here:
```suggestion
To use an external source of authentication your SSO will need to support OpenID Connect :
```

2023-12-27 23:55 UTC, sandervandegeijn commented
> > Tested it with the Google OIDC implementation, that's working like a charm. I'm now in the process of connecting it to our corporate AzureAD config to test that one.
> 
> Had no luck with AzureAD (now renamed to Entra ID) too to non-standard implementation on the Microsoft end. [Timshel#8](https://github.com/Timshel/vaultwarden/issues/8)
> 
> But with Keycloak as identity broker it finally worked out. Cant wait for the PR to go live.

That would be a shame, Azure is a big big idp in the corporate world. I'm working for Wageningen University and we (and AFAIK every other University in the Netherlands) are using AzureAD.

Is there a way around this?
Can we fix this in code?
What is the problem exactly? 

I can try to use our premier support to get support from Microsoft on this. A workaround would solve it short term, preferably in code, implementing a federated proxy is not ideal.

2023-12-28 00:07 UTC, Timshel commented
@sandervandegeijn can we keep the discussion around Entra in the already opened issue plz.

2023-12-28 00:08 UTC, ocdi commented
I'm using entraid successfully power my comments here https://github.com/Timshel/vaultwarden/issues/8

2023-12-28 00:24 UTC, sandervandegeijn commented
> @sandervandegeijn can we keep the discussion around Entra in the already opened issue plz.

Sorry missed that one!

2023-12-28 09:02 UTC, williamdes approved these changes
The code looks nice, I found some typos with by [browser spelling check extension](https://chromewebstore.google.com/detail/webpage-spell-check/mgdhaoimpabdhmacaclbbjddhngchjik)

2023-12-28 09:02 UTC, williamdes commented on test/oidc/README.md
> +To procede with an SSO login after you enter the email, on the screen prompting for `Master Password` the sso button should be visible.
```suggestion
To proceed with an SSO login after you enter the email, on the screen prompting for `Master Password` the SSO button should be visible.
```

2023-12-28 23:25 UTC, SystemFuchs commented
Thank you all for your efforts. Just got it working with Zitadel OIDC

2024-01-03 01:50 UTC, zeddD1abl0 commented
Works perfectly so far with Authentik.

2024-01-04 20:24 UTC, VincentSC commented
> Works perfectly so far with Authentik.

> Thank you all for your efforts. Just got it working with Zitadel OIDC

Did you also test with mobile app and browser plugin?

2024-01-04 20:42 UTC, sandervandegeijn commented
Has anyone tried it with the ios-app and AzureAD? The app on my mac works perfectly, but iOS just throws an error "can't login".

2024-01-04 21:11 UTC, SystemFuchs commented
> > Works perfectly so far with Authentik.
> 
> > Thank you all for your efforts. Just got it working with Zitadel OIDC
> 
> Did you also test with mobile app and browser plugin?

Tested Zitadel successfully with mobile app & browser plugin

2024-01-05 21:03 UTC, Timshel commented
Hey,

[Recently](https://github.com/Timshel/vaultwarden/commit/c323546c9c0708ceac8489c9c6146c0bf6bf4a61) improved the state and error handling for the oidc flow :
 - Passed the `state` defined by the `Bitwarden` client in the oidc flow to remove the need to store it in a cookie.
 - Added the `oidc-signin?<error>&<error_description>` endpoint even if there is no really good way to display errors.
  Added a conf `SSO_AUTH_FAILURE_SILENT` to either return a json error or just ignore it and silently redirect to the root.

Found a way to better display the error but it relies on :
 - Another [patch](https://github.com/Timshel/oidc_web_builds/blob/master/oidc_sso_errors.patch) to the web front to display errors on the `/connect/token` endpoint.
 - Wrapping the error as a JWT to pipe it as the  oidc `code` to pass trough the Bitwarden client logic and return the error later on when `/connect/token` is called (https://github.com/Timshel/vaultwarden/commit/d28cd70dfcebea6ec09f2039c166e47f51ccbb5d).

For now since it relies on another frontend patch and it's a bit janky it's only on the `main` branch.

2024-01-08 09:12 UTC, sandervandegeijn commented
I was using the simonc/vaultwarden:latest to test, but that hasn't been updated for the last three weeks. Is there a docker image that's holding the current code I can use to test everything again?

2024-01-08 09:26 UTC, VincentSC commented
> I was using the simonc/vaultwarden:latest to test, but that hasn't been updated for the last three weeks. Is there a docker image that's holding the current code I can use to test everything again?

Strangely enough, this repo only contains arm-Dockers in https://github.com/dani-garcia/vaultwarden/tree/main/docker - I got the same problem, and expected some basic `docker_build.sh` to exist. But this discussion should be a separate issue/PR.

2024-01-08 09:48 UTC, BlackDex commented
> > I was using the simonc/vaultwarden:latest to test, but that hasn't been updated for the last three weeks. Is there a docker image that's holding the current code I can use to test everything again?
> 
> Strangely enough, this repo only contains arm-Dockers in https://github.com/dani-garcia/vaultwarden/tree/main/docker - I got the same problem, and expected some basic `docker_build.sh` to exist. But this discussion should be a separate issue/PR.

I would recommend reading the readme a bit better.

2024-01-08 19:54 UTC, sandervandegeijn commented
Fantastic, thanks. Tested the apps again, found an issue with AzureAD: https://github.com/Timshel/vaultwarden/issues/12

2024-01-09 12:52 UTC, Timshel commented
Latest push is to fix a regression which broke redirection on Ios and Android.

2024-01-09 15:24 UTC, VincentSC commented
What is the main advantage over "SIGNUPS_DOMAINS_WHITELIST"?

2024-01-09 16:36 UTC, rizlas commented
Hi @VincentSC , your comment does not involve this issue.

Here the link to the documentation https://github.com/dani-garcia/vaultwarden/wiki/Disable-registration-of-new-users#restricting-registrations-to-certain-email-domains

2024-01-09 16:42 UTC, VincentSC commented
My question was what SSO actually does, as the master key is not in the SSO.

It allows to block a user, and restrict to a certain domain. Blocking a user would only be handy with a shared vault, not all passwords. Domain restrictions are handled somewhere else.

So am I missing what the value of SSO here is?

2024-01-09 16:46 UTC, Timshel commented
@VincentSC 

> So am I missing what the value of SSO here is?

I think it's clear there is some interest, so probably yes.

From the PR text :
> Please open issues in [Timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues) in order to keep the discussion here focused on merging this work.

 ....

2024-01-10 13:32 UTC, blazp7 commented
Image [1.30.1-2](https://hub.docker.com/layers/oidcwarden/vaultwarden-oidc/1.30.1-2/images/sha256-b59b93faec2136a733a0af2c38a5d6fbef7ab15b77d8439d00b41e29e8e6490e?context=explore) tested and working with Authentik, however is disappointing that we still need master password on each unlock. SSO providers already offer strong authentication methods, imo the master password should only be required for offline unlock.

2024-01-10 13:42 UTC, BlackDex commented
> Image [1.30.1-2](https://hub.docker.com/layers/oidcwarden/vaultwarden-oidc/1.30.1-2/images/sha256-b59b93faec2136a733a0af2c38a5d6fbef7ab15b77d8439d00b41e29e8e6490e?context=explore) tested and working with Authentik, however is disappointing that we still need master password on each unlock. SSO providers already offer strong authentication methods, imo the master password should only be required for offline unlock. I have tried this env var but nothing changed that i could notice `SSO_MASTER_PASSWORD_POLICY = '{"enforceOnLogin":false}';`

That isn't possible without extra tools. Bitwarden has a keyconnector tool which does exactly that.

2024-01-10 13:45 UTC, sandervandegeijn commented
There is another very good reason for this: the master password is used for the encryption of the password vault. I like it very much that we don't have the keys to all vaults :)

2024-01-10 14:10 UTC, VincentSC commented
> That isn't possible without extra tools. Bitwarden has a keyconnector tool which does exactly that.

This is why I asked about the value of this extension. I found about the [Key Connector](https://bitwarden.com/help/about-key-connector/) and started to think about the usages, and then could only think of domain-restrictions. Its code can be found [here on Github](https://github.com/bitwarden/key-connector). Meanwhile I did look more into it, so hopefully this helps others with the same question to get some answers...

My assumption is that Key Connector works like [Hashicorp's Vault](https://www.vaultproject.io/). Such software can be used to provide a public key to e.g. SSHD+PAM, as is described in this blog post [Identity based SSH with Vault and Keycloak](https://drpdishant.medium.com/identity-based-ssh-with-vault-and-keycloak-part-1-3-47ab2181ceae). The same way this can be used to provide keys to Vaultwarden.

Once OIDC works with Vaultwarden, then support for Hashicorp Vault (and/or Key Connector and/or something else) could be implemented next. It needs one step extra to request the key (or to ask for the password, when it fails), as can be seen in the mentioned blog post. But first: get OICD working smoothly. :)

2024-01-10 14:17 UTC, VincentSC commented
> There is another very good reason for this: the master password is used for the encryption of the password vault. I like it very much that we don't have the keys to all vaults :)

See my previous message. Just like using Keycloak+Vault can be used for SSH, and thus Vault has all access to *all* users on all servers. Some people like the convenience, while others don't trust it well enough. 2FA could be an answer here: when Vault is used, then 2FA is mandatory.

2024-01-10 14:27 UTC, Lurkars commented
I know my comment is also spammy, but I want to remind, that we don't need to discuss the SSO functionality here. It's it a well defined Bitwarden enterprise function which this PR is aiming to implement. There is a use case for it. If it's not your use case, don't try to change the functionality here. There are people (like me) just waiting this to be fully functional and merged to use it as defined for Bitwarden.

2024-01-17 20:03 UTC, sandervandegeijn commented
Great to see the ongoing work - would love to help and test some more. Where can I find the most up to date docker images? https://hub.docker.com/r/oidcwarden/vaultwarden-oidc/tags where references in another issue, but these seem loosely related to what is going on here.

2024-01-17 20:18 UTC, Timshel commented
Hey,

A big update to add the refresh token logic (thx @rizlas for noticing that the session was not expiring).

Main changes include:
 - Set correct expiration time to VaultWarden jwt `access_token`.
 - Add a VaultWarden jwt refresh token to store auth method, expiration and when using sso the refresh_token.
 - For password login flow set the VW refresh_token expiration to ~1year (extended each time we refresh the access_token); I believe it never expired before.
 - Add the sso refresh token logic to retrieve updated refresh_token and acces_token
 - Change the refresh_login to return a 401 on errors to trigger a logout.

#### :warning:  BitWarden client will try to refresh the access_token if it's remaining lifespan is under 5minutes; ensure that your Access Token lifespan is greater otherwise you'll have issues (it'll start spamming the refresh endpoint and you'll end-up disconnected due to race condition).

Not all actions will trigger a check/refresh of the token, so you'll be able to copy password even when expired, navigating back to the vault will trigger a check and possible logout.

It's probably not the best tested release at the moment ^^ (did not check again 2FA flow and org invite but they should not be impacted).
Should update the `main` branch and docker images with this change tomorrow.

@sandervandegeijn it's related ^^ cf: [Timshel/vaultwarden](https://github.com/Timshel/vaultwarden/tree/main#docker)

2024-01-17 23:37 UTC, BlackDex requested changes
I did aome further checking, not yet finished, but this is what i found so far for now.

2024-01-17 23:37 UTC, BlackDex commented on src/api/identity.rs
> +    match auth::refresh_tokens(&refresh_token, conn).await {
I'm missing the `device.save(conn)` call to update when the device was last used.
I checked all the other functions being called but wasn't able to find it, i might have missed it of course.

2024-01-17 23:37 UTC, BlackDex commented on src/api/identity.rs
> +    let _ = auth::AuthMethod::Password.check_scope(data.scope.as_ref())?;
No need for `let _ =`, that can be removed.

2024-01-17 23:37 UTC, BlackDex commented on src/api/identity.rs
> +    let _ = auth::AuthMethod::Sso.check_scope(data.scope.as_ref())?;
No need for `let _ =`, that can be removed.

2024-01-17 23:37 UTC, BlackDex commented on src/api/identity.rs
> +    use auth::AuthMethod::{OrgApiKey, UserApiKey};
I would suggest to set this at the top and change the calls to these same mod's within the `_user_api_key_login` and `_organization_api_key_login` functions.

2024-01-17 23:37 UTC, BlackDex commented on src/db/models/org_policy.rs
> +    }
What is the reason for creating a function for this?
It doesn't seem to be used more often, and because of that, it probably should just stay within the `to_json` function i think.

2024-01-18 10:41 UTC, Timshel commented on src/api/core/organizations.rs
> +}
My understanding is that the `identifier` is not the `org_id`.
In the case of VaultWarden this identifier will either be [hardcoded](https://github.com/Timshel/vaultwarden/blob/95fae132bb8d2a16567ee18369a373cca65210fe/src/api/core/organizations.rs#L801) as `vaultwarden` or the user will input a random value.

So I think it's better to just return `"Id": org_id,`.

Note, I wrote an implementation of it in a [commit](https://github.com/Timshel/vaultwarden/commit/5a522b7b46443f8f96a54a7a41b05c30c69997ea) which add support to automatically add user to orgs. 
The main gain is that if a user is part of an org then when creating an account the correct master password policy is used. But since it added complexity I preferred to keep it out of the PR for now.

2024-01-18 10:57 UTC, Timshel commented on src/api/identity.rs
> +    use auth::AuthMethod::{OrgApiKey, UserApiKey};
Wanted to prevent line wrapping in the following code while not globally importing `OrgApiKey` since without the `AuthMethod` it's a bit vague, there is an `OrganizationApiKey` for example in the same global scope.

Tested again and with a global import of `AuthMethod` and adding the `AuthMethod` prefix the code still do not wrap, so I removed this local import.

2024-01-18 11:04 UTC, BlackDex commented on src/api/identity.rs
> +    match auth::refresh_tokens(&refresh_token, conn).await {
So, basically you say, it isn't updated anymore now right?

That will become an issue, since we want to know when a device was last used, that is the whole reason for running that `.save` on it.

2024-01-18 11:17 UTC, Timshel commented on src/api/identity.rs
> +    match auth::refresh_tokens(&refresh_token, conn).await {
Ok will revert.

2024-01-18 18:26 UTC, BlackDex requested changes
I did some more checking. Still have not yet checked `identity.rs` and `sso_nonce.rs` and  `sso.rs`
Those take a bit more time.

Also, in the final PR, some of the `tests` files can be removed.
And a PR for the `bw_web_vault` needs to be created to allow SSO of course.

2024-01-18 18:49 UTC, Timshel commented on src/api/core/two_factor/duo.rs
> +// Email needs to be normalized before comparison with auth_user below (usually should come from DB).
I added the `usually should come from DB` part, the rest was already present on a `&email.to_lowercase()`.
Since the [patch](https://github.com/dani-garcia/vaultwarden/pull/3899/commits/9355591aa03319e2d8c6c1b9de2147d74bab64c6) switched to using the `user.email` directly the normalization was not necessary anymore but though the warning still applied.

2024-01-18 19:19 UTC, Timshel commented
> Also, in the final PR, some of the tests files can be removed.

Just to be clean there is two things in tests :
 - the `docker-compose` which easily allow to run/debug an sso stack (I use it to run a just Keycloak when debugging)
   I think this should stay somewhere.
 - the Playwright integration test scenario
   I think it could be a start to add more (it's just an sso onboarding then subsequent login atm), but if there is no interest I'll remove it. 
  
  >And a PR for the bw_web_vault needs to be created to allow SSO of course.
  
  Yep, I can prepare a PR, was wondering with the [patch](https://github.com/Timshel/oidc_web_builds/blob/master/oidc_invite.patch) being quite simple now to fix Organization invit do you think it might be integrated ? 
  I think it's worth-it since it's really simple and would allow to remove the `sso_acceptall_invites` logic which was added to circumvent the issue (which include some logic and an email body).

2024-01-19 13:57 UTC, Timshel commented
Hey a heads-up, as mentioned in https://github.com/Timshel/vaultwarden/issues/14

> Hum, it appears I made some over-specific implementation, it's not specified in the spec that the refresh_token is a JWT.
> Will make some change:
> - It appears it's optional so will make it so
> - Will change the logic to continue trying to extract an expiration date if it's a JWT and otherwise fallback to something like 1 year.

2024-01-20 23:24 UTC, BlackDex reviewed
Some more checks i was able to do.
Any comments i made also apply on other sections where the same code layout is used of course, i might have missed some.

2024-01-20 23:24 UTC, BlackDex commented on src/sso.rs
> +        let _ = jsonwebtoken::decode::<serde_json::Value>(token, &self.debug_key, &self.debug_validation)
This `let _ =` can be removed.

2024-01-20 23:24 UTC, BlackDex commented on src/sso.rs
> +
Maybe this looks better using `unwrap_or_else` instead of a match.
Codewise it probably doesn't matter that much, but it does simplify it, since no checking for the Ok() part is needed.

2024-01-20 23:24 UTC, BlackDex commented on src/sso.rs
> +
Same here as above, converting it to `unwrap_or_else`.

2024-01-20 23:24 UTC, BlackDex requested changes
Some more checks i was able to do.
Any comments i made also apply on other sections where the same code layout is used of course, i might have missed some.

2024-01-21 11:57 UTC, Timshel commented on src/sso.rs
> +
I think I tried but got : 
> expected struct `UserInfoClaims<_, _>` found enum `Result<_, error::Error>`

If I understand correctly the `return` of the macro is applied to the `unwrap_or_else` closure.  Any way to work around it ?

2024-01-21 12:04 UTC, Timshel commented on src/sso.rs
> +        let _ = jsonwebtoken::decode::<serde_json::Value>(token, &self.debug_key, &self.debug_validation)
Here without it the compiler complain of: 
> warning: unused `Result` that must be used

2024-01-21 12:22 UTC, Timshel commented
@BlackDex any input on my previous comment ?

----
> Also, in the final PR, some of the tests files can be removed.

Just to be clear there is two things in tests :
 - the `docker-compose` which easily allow to run/debug an sso stack (I use it to run a local Keycloak when debugging)
   I think this should stay somewhere.
 - the Playwright integration test scenario
   I think it could be a start to add more (it's just an sso onboarding then subsequent login atm), but if there is no interest I'll remove it. 
  
  >And a PR for the bw_web_vault needs to be created to allow SSO of course.
  
  Yep, I can prepare a PR, was wondering with the org invite fix [patch](https://github.com/Timshel/oidc_web_builds/blob/master/oidc_invite.patch) being quite simple do you think it might be integrated ? 
  I think it's worth-it since it's really simple and would allow to remove the `sso_acceptall_invites` logic which was added to circumvent the issue (which include some logic and an email body).

2024-01-22 16:29 UTC, BlackDex commented on src/sso.rs
> +        let _ = jsonwebtoken::decode::<serde_json::Value>(token, &self.debug_key, &self.debug_validation)
Well, the decode can fail here too for some reason. If that happens, you will never know the specific reason i think.
If that doesn't matter for some reason, then the `let _ =` should be fine, otherwise it's better to match the outcome and check if it's an `Err` or `Ok`.

2024-01-22 16:49 UTC, Timshel commented on src/sso.rs
> +        let _ = jsonwebtoken::decode::<serde_json::Value>(token, &self.debug_key, &self.debug_validation)
Yes, in this case it's called only when the default decode failed with the goal of adding additional debug information. Since we already are in the context of a logged error I think it's not useful to report this error.

2024-01-22 16:56 UTC, Timshel commented
Hey latest commit is in the context of this issue : https://github.com/Timshel/vaultwarden/issues/16.
It appears the web application does not like not having a `refresh_token` so made sure there is always one.

Additionally when the app trigger a refresh token call outside of the expiration window if there is no refresh_token then we call the user info endpoint to check that the access token is still valid.

And added a little bit of doc on the session lifetime: [SSO.md#session-lifetime](https://github.com/Timshel/vaultwarden/blob/sso-support/SSO.md#session-lifetime)

2024-01-22 20:40 UTC, BlackDex commented on src/sso.rs
> +
Hmm indeed. Doesn't seem to be a nice way around it.
Lets leave it as is then :)

2024-01-23 16:14 UTC, div1spawncamper commented
Hi everyone! 

Hi @dani-garcia @BlackDex @Timshel your work is hugely appreciated over here. My small company is trying to drop post-it notes for storing passwords and this is the only solution that could manage SSO in a cool way (BW/VW is the best self-hosted password manager hands down) and I've just seen this PR which would help us out immensely.

I'm sorry to bump this up after everyone has already spoken up but please, if there's anything we can do for the merge to be completed, let us know! We'll gladly help with whatever. 

Thanks again for your work and dedication :)

2024-01-26 13:05 UTC, Timshel commented
Hey

Heads up latest release of the Bitwarden WebVault (`web-v2024.1.2`) and derivative will be incompatible with this PR since an endpoint path changed. Will update it when the `vault_version` change in [DockerSettings.yaml](https://github.com/dani-garcia/vaultwarden/blob/main/docker/DockerSettings.yaml).

On the [main](https://github.com/timshel/vaultwarden) and [oidc_web_builds](https://github.com/Timshel/oidc_web_builds) front had some fun and made a new `experimental` version to stop sending and storing the master password hash in db. More work/test is needed on the web-front part and no idea if it's viable for mobile apps. Some doc [here](https://github.com/timshel/vaultwarden#experimental-version).

As usual if you have issues/questions please open it in [Timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues).

2024-01-27 07:42 UTC, BlackDex commented
Well, web-vault 2024.1.2 is now in main so you can change the endpoints.

2024-01-29 00:26 UTC, alexsalex commented
when this will be merged?

2024-01-29 15:00 UTC, Timshel commented
Latest change is to correctly encode the redirection parameters and add a `debug` log.
Additionally removed the `SSO_AUTH_FAILURE_SILENT` since it didn't make sense on mobile.

2024-01-30 13:24 UTC, compgeniuses commented
this is interesting new addition into vaultwarden

2024-01-30 13:43 UTC, shuuryou commented
> It seems that there is a lot of hesitation on investing time into reviewing this and i can understand this.

I'd personally wager that there's an understanding with the folks at Bitwarden that specific enterprise features will not get added and in return they leave this project alone. You could argue that anyone using Vaultwarden wouldn't pony up cash for Bitwarden anyway, but this project still cuts into their revenue. I'd assume that SSO is the one of these features that they'd not want to see here, hence no desire to merge it.

Take my comment for what it is though: baseless conjecture that'll either get me downvoted to death, hidden as off topic, or banned from the repo for speaking out the forbidden. I don't know. In any case, that's what it feels like to me following this PR passively for a long time. 

But people are putting in their time and energy into this project for free, so I'm in no position to demand anything to happen. Neither is anyone else.

2024-01-30 13:51 UTC, binaryfire commented
> I'd personally wager that there's an understanding with the folks at Bitwarden that specific enterprise features will not get added and in return they leave this project alone. You could argue that anyone using Vaultwarden wouldn't pony up cash for Bitwarden anyway, but this project still cuts into their revenue. I'd assume that SSO is the one of these features that they'd not want to see here, hence no desire to merge it.

If you'd taken the time to check the most recent comments you'd have seen that @BlackDex has been very active in reviewing @Timshel's commit's and that rapid progress is being made, especially over the last few weeks. Perhaps you forgot to click the "Load more" button

<img width="257" alt="image" src="https://github.com/dani-garcia/vaultwarden/assets/5361908/7e7393d1-6dd1-4a25-8b8e-f14d4b2b2bd2">

2024-01-30 14:00 UTC, shuuryou commented
> If you'd taken the time to check the most recent comments you'd have seen that @BlackDex has been very active in reviewing @Timshel's commits and that rapid progress is being made, especially over the last few weeks.

I take it all back then. My bad. Sorry if I offended anyone. That wasn't my intention.

2024-01-30 15:31 UTC, compgeniuses commented
@shuuryou alot of work seems to be going into this PR, and hopefully, would be a fantastic new eyar present for all to enjoy

2024-01-30 15:50 UTC, sandervandegeijn commented
I have contacted Bitwarden about this in the past, their reply was very friendly and open minded:

```
Thank you for choosing Bitwarden and for reaching out to the support team.

Bitwarden is extremely pleased with the resounding success of Vaultwarden and all other projects that have emerged from Bitwarden's original work. We take immense pride in witnessing the vibrant development and positive impact these initiatives have within the community.
​
We are committed to our original approach and vision. We will continue to provide unwavering support to projects that stem from Bitwarden's efforts, as long as they uphold the highest standards of security implementation and adhere to the licenses that govern our work.
​
The collaborative spirit and dedication exhibited by the community only reinforce our belief in the power of open-source collaboration. We are excited to see how these projects continue to evolve, driving innovation while maintaining the core principles that underpin Bitwarden's philosophy.
​
Both Bitwarden and Vaultwarden are open source. However it is important note that we as Bitwarden will not be able to offer support for Vaultwarden based implementations. You will need to get in touch with Vaultwarden community to get help for any kind of troubleshooting. 
​
Let us know if there is anything else we can do for you.
```

I'm not that worried.

2024-01-31 11:01 UTC, Timshel commented
I'll unburry an old comment with questions.
----
> Also, in the final PR, some of the tests files can be removed.

Just to be clear there is two things in tests :
 - the `docker-compose` which easily allow to run/debug an sso stack (I use it to run a local Keycloak when debugging)
   I think this should stay somewhere.
 - the Playwright integration test scenario
   I think it could be a start to add more (it's just an sso onboarding then subsequent login atm), but if there is no interest I'll remove it. 
  
  >And a PR for the bw_web_vault needs to be created to allow SSO of course.
  
  Yep, I can prepare a PR, was wondering with the org invite fix [patch](https://github.com/Timshel/oidc_web_builds/blob/master/oidc_invite.patch) being quite simple do you think it might be integrated ? 
  I think it's worth-it since it's really simple and would allow to remove the `sso_acceptall_invites` logic which was added to circumvent the issue (which include some logic and an email body).

2024-02-01 14:49 UTC, Timshel commented
Hey decided to squash most of the commits since it was quite long. 
Kept individual commit for the third review and after since it might be easier this way.

2024-02-01 15:23 UTC, BlackDex commented
> I'll unburry an old comment with questions.
> 
> > Also, in the final PR, some of the tests files can be removed.
> 
> Just to be clear there is two things in tests :
> 
> * the `docker-compose` which easily allow to run/debug an sso stack (I use it to run a local Keycloak when debugging)
>   I think this should stay somewhere.
> * the Playwright integration test scenario
>   I think it could be a start to add more (it's just an sso onboarding then subsequent login atm), but if there is no interest I'll remove it.
> 
> > And a PR for the bw_web_vault needs to be created to allow SSO of course.
> 
> Yep, I can prepare a PR, was wondering with the org invite fix [patch](https://github.com/Timshel/oidc_web_builds/blob/master/oidc_invite.patch) being quite simple do you think it might be integrated ? I think it's worth-it since it's really simple and would allow to remove the `sso_acceptall_invites` logic which was added to circumvent the issue (which include some logic and an email body).

If that patch does not influence the whole workings/flow without SSO, i think it is fine.

2024-02-01 16:18 UTC, rizlas commented
Hi @Timshel, just a quick question. I want to setup and test **only** the content of this PR, should I use images from https://hub.docker.com/r/oidcwarden/vaultwarden-oidc/tags or build an image from `sso-support` branch?

Others: sorry for the notification 🙏🏻

2024-02-03 14:02 UTC, Timshel commented
> If that patch does not influence the whole workings/flow without SSO, i think it is fine.

The patch should have no impact on the non sso version. As such I removed the `sso_acceptall_invites` logic which become unnecessary.
At the same time removed the playwright scenarios since I don't believe there was an interest.

@rizlas if you want only the content of this PR then you'll have to build/modify the docker image from the branch.
For the Org invite issue you'll need to use latest release of the [oidc_web_builds](https://github.com/Timshel/oidc_web_builds/releases/download/v2024.1.2-4/oidc_button_web_vault.tar.gz) which include the patch.

2024-02-03 14:06 UTC, BlackDex commented
@Timshel, i do have interest in the Playwright stuff actually.
I only need to find time (or someone else) to make it work with the web-vault on more aspects. It could help in finding new/changed endpoints more quickly with new web-vaults. We could even let Github do the testing i think.

2024-02-03 15:49 UTC, compgeniuses commented
is there any other pending matter, or are we good to have this PR merged,,

Also, for the playwright stuff,  we could have them added later on.. dont you think @BlackDex

2024-02-03 15:53 UTC, BlackDex commented
I still have to check this PR's changes.
And, i actually have not yet tested the SSO implementation my self yet.

Only checked the code, and mostly if it still works without SSO enabled.
And i have a few items left on my list to check and verify.

So, until that is done, it's not merge-able from my point of view.

Regarding Playwright, that can be added later, but there was already some work done, and i just merely mentioned that i was interested though :).

2024-02-03 16:01 UTC, Timshel commented
> Regarding Playwright, that can be added later, but there was already some work done, and i just merely mentioned that i was interested though :).

Will revert the revert (^^) with some improvement for it to be more usable for non-sso flow.

2024-02-04 15:59 UTC, Timshel commented
So brought back some improved playwright tests (some part of the setup would gain to be handled by a build tool but didn't want to add another tool).

Adding password auth tests made me realize that even when disabled the SSO the sso flow could progress quite far without errors, so added more checks and errors.

2024-02-04 17:02 UTC, compgeniuses commented
WOnderful additions, @Timshel the dedication to this feature is nx

2024-02-06 14:19 UTC, Timshel commented
So latest push include

- A bugfix of a leftover when `access_token` were always handled as JWT. Was triggered when calling to refresh tokens without a `refresh_token`.
- A new config `SSO_AUTHORIZE_EXTRA_PARAMS` to allow to add the needed authorize parameters to obtain a `refresh_token` with Google Auth.
- A new config `SSO_AUTH_ONLY_NOT_SESSION` to fallback to the default session handling, might be useful for those unable to obtain `refresh_token` (ex: with Unifi Identity Enterprise).
- More details in the [SSO.md](https://github.com/Timshel/vaultwarden/blob/main/SSO.md) doc.

2024-02-12 09:16 UTC, compgeniuses commented
@BlackDex what do we have now pending, from your end or from @Timshel

2024-02-12 09:44 UTC, BlackDex commented
Patience mainly 😉

2024-02-12 10:58 UTC, compgeniuses commented
> Patience mainly 😉

they Say Patience is a virtue, I have built 12 modules for a software in 2 weeks, because i coulnt wait till they were made available, and i needed them... (just a bythe way)

Needless to say you're doing a wonderful job in maintaining this project.

2024-02-12 11:22 UTC, JonnyBDev commented
> they Say Patience is a virtue, I have built 12 modules for a software in 2 weeks, because i coulnt wait till they were made available, and i needed them... (just a bythe way)

Feel free to use the SSO-branch from Timshel to use the feature. But I'd rather wait a few more weeks than having some open doors in my code for a software that's the entrance to my passwords, btw :)

2024-02-12 11:29 UTC, sandervandegeijn commented
I have to discuss it internally, but I can probably promise we are willing to invest in a formal security test of vaultwarden. Has this been done in the near past? Should we concentrate on the whole solution or just on the newly added SSO module? We have partners that specialise in testing these kinds of web applications.

Only drawback is that we can't get the combination of AzureAD and the iOS app to work.

2024-02-15 18:22 UTC, Timshel commented
Hey

So a biggest update than expected, wanted just to move the `roles` and `groups` claims to the id token for the `main` branch and looked again at the id token validation.

Realized that the claims [verification](https://github.com/ramosbugs/openidconnect-rs/blob/53a82e673ba88b916144932a181b4f597e57eab7/src/verification.rs#L258C15-L258C87) done by `openidconnec` was way more advanced and switched to it.

Had some impact on the `sso_nonce` table since we needed to be able to retrieve the nonce before reading the Idtoken instead of checking it post decode. So added the `state` to be able to retrieve it.

Since nothing is easy the `state` is present when redirected from the sso but the client does not send it back when calling the state endpoint. So end-up creating a JWT to wrap the `code` and `state` to be able to use it. Used the same logic to alternatively wrap the potential `error` and `error-description` but a front-end [patch](https://github.com/Timshel/oidc_web_builds/blob/master/oidc_sso_errors.patch) is till needed to display those.
 
Additionally read a report on [caddy sso plugin](https://blog.trailofbits.com/2023/09/18/security-flaws-in-an-sso-plugin-for-caddy/) and wondered if the first point could be applied to the `redirect_uri` given by the client. Not sure if/how it could be exploited but decided to use hard-coded values (taken [from](https://github.com/bitwarden/server/blob/main/src/Identity/IdentityServer/ApiClient.cs)).

On the config change side :
 - removed `SSO_KEY_FILEPATH`, the `openidconnec` should make this obsolete.
 - Added `SSO_DEBUG_TOKENS` to control logging the Id/Access/Refresh tokens.
 
 Lastly Mastodon [patched](https://github.com/mastodon/mastodon/security/advisories/GHSA-vm39-j3vx-pch3) this week an account Takeover due to email change. This PR is susceptible to it too but the severity is lower since the Master password is still needed to unlock the vault. 
 Still will have a look to put the email association behind a config since I believe it might still be useful but switching to using a different id would probably allow to support changing the mail.
 
 :warning: so a big update, tested it with web/android and with Keycloak / Google and Gitlab but update with caution :).

2024-02-15 19:05 UTC, sandervandegeijn commented
Which version of the docker container should I use?

2024-02-16 07:32 UTC, Timshel commented
Hey,
Heads-up there is an issue with some migration (`postgres` or `mysql` ) had only tested ` sqlite`.

2024-02-16 17:03 UTC, BlackDex requested changes
Still not fully tested it functionallity wise, but some small pointers.
I think it looks nice.

Ill do some more checking when i can.

2024-02-16 17:03 UTC, BlackDex requested changes
Still not fully tested it functionallity wise, but some small pointers.
I think it looks nice.

Ill do some more checking when i can.

2024-02-16 18:02 UTC, Timshel commented on src/main.rs
> +                    runtime.spawn(db::models::SsoNonce::delete_expired(pool.clone()));
I was thinking of trash as a general category and didn´t want to add yet another config :).
Impact is really low since after 10min they are ignored, and won't accumulate too much since once the auth is working only incomplete flow should generate leftovers.

But will add a config if you prefer :)

2024-02-16 18:15 UTC, BlackDex commented on src/main.rs
> +                    runtime.spawn(db::models::SsoNonce::delete_expired(pool.clone()));
No, it actually is the trash of all the vaults, and people can set it to not remove it.

Not cleaning the Nonce's shouldn't be tied to that.

2024-02-16 21:05 UTC, misilot commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
An example from Azure is 24 hour days for a single page app, and 90 days for all others
https://learn.microsoft.com/en-us/entra/identity-platform/refresh-tokens#token-lifetime

2024-02-16 21:31 UTC, BlackDex commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
Well, what happens here, the refresh token gets refreshed after 2 hours, now it will take 356 days (which is also a strange number, you probably mend 365 days i think.

So, the token will be refreshed every 2 hours in the old situation, which is fine i think. But in the current changes it will take 356 days before the token expires.

Bitwarden it self uses 1 day if I'm correct: https://github.com/bitwarden/server/blob/b866353d2cdbc2dffc6d90b5a9ceeca5ab058c17/src/Identity/IdentityServer/ApiClient.cs#L19

They store this in the database and not use a JWT for this though.
So at least someone needs to refresh there token every day.

With 356 days, i can keep the vault open for a very very long time, before there is even a check done if it still has access.

2024-02-16 21:35 UTC, BlackDex commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
Actually, the correct lifetime of the token is a few lines lower, which is 1 hour.

2024-02-17 09:15 UTC, Timshel commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
As far as I understand the `refresh_token` used to be the [device.refresh_token](https://github.com/dani-garcia/vaultwarden/blob/bb2412d0339e1da5dee99fc566a2b2aab5d2808c/src/api/identity.rs#L289) which never expired ? So when I set the ~1year (will fix the 356) I selected a value which appeared long enough to me.
Additionally this delay is extended each time the user ask for a new access token (so it works more like an idle time and could easily be shorter).

I did not change the access token default validity just [renamed](https://github.com/dani-garcia/vaultwarden/blob/bb2412d0339e1da5dee99fc566a2b2aab5d2808c/src/auth.rs#L15) it.

Note this is used only for non-sso login or when using the config `SSO_AUTH_ONLY_NOT_SESSION`.

For a default sso login the `refresh_token` and `access_token` lifetime will be controlled by it (when unknown for the refresh token it default to one year but it just mean the call to the refresh endpoint will fail instead of just not making the call if we knew it was already expired).

On the length the year is nothing extravagant, for example the `refresh_token` obtain from GoogleAuth with the `offline_access` scope has an idle lifetime of [six months](https://developers.google.com/identity/protocols/oauth2). But I agree it could be shorter, just made it this long since as I understand it replaced something with no expiration. 

Lastly I don´t believe this influence the lock status of the vault only when the user is Log-out. Which I believe in non sso VaultWarden you almost never want to do since it mainly mean forcing the user to input his email again (With the exception of the 2FA flow).

Note that the refresh token is still tied to a [device](https://github.com/Timshel/vaultwarden/blob/e7350c0114292ebdebb8cf5ac49e17745f5c98e6/src/auth.rs#L1043) As it was done [before](https://github.com/dani-garcia/vaultwarden/blob/bb2412d0339e1da5dee99fc566a2b2aab5d2808c/src/api/identity.rs#L102C53-L102C58).
But I realize that in both case we are not checking that the retrieved device match the one associated with the current session.

2024-02-17 11:33 UTC, compgeniuses commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
12 hours or less is a bad idea, some power users, (and these are actually the ones using pwd managers) tend to have sessions and browser tabs open for longer than 24 hours normally. i think something like 24-72 hours should be fair, ofcourse there are other ways within the system that mitigates risks, so why complicate workflows and the purpose for hwihc someone uses the password manager at all?

I am using a password manager, so that i dont have to type my passwords everytime.

2024-02-17 11:39 UTC, BlackDex commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
Well i haven't heard any complaints yet, and currently it's 2 hours. Also, keeping it open and using it will extend the expiration time if I'm correct, so that shouldn't be a problem then. So increasing it will not benefit anything except for malicious usage.

2024-02-17 12:09 UTC, thomasdba commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
why not give user an option ?

2024-02-17 12:13 UTC, sMteX commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
I'm aware I know nothing of security standards but could the length be configurable? So the operator of the Vault could say "hey, I'm taking the responsibility for the possibility of attack, but let's make the token valid for longer so people don't have to relogin as much"? Just asking

2024-02-17 12:52 UTC, spresse1 commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
As a user, I would also like this to be configurable, if possible. I am a somewhat unusual use case, but my VaultWarden server is only accessible when connected to my home network, so the risk of an attacker having long-term access is very low (at least, without also being able to exfiltrate the encrypted vaults). The security/convenience balance in my case is different and I'd like to be able to adapt this setting to that. I fully understand that my case is not going to be the default and support a secure-by-default setting.

2024-02-17 12:56 UTC, spresse1 commented
One question on documentation: Is there interest in documenting OIDC-specific configuration that users may want to be aware of? For example, I found that keycloak defaults expired all my tokens after 10 hours, forcing a new sign-in. I decided to configure VaultWarden to ask for the "offline" scope, which has allowed me to go much longer between full SSO signins. I'm mostly using master-password reentry to provide security on-device.

Should this be documented? I'm happy to make the documentation changes for this, but wanted to ask if there was interest first.

2024-02-17 12:57 UTC, sMteX commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
To be fair, I'm just lazy and easily annoyed 😅 so I'd prefer having to login like once a day, twice at most. I'd very much appreciate having that option, but ultimately we'll conform to whatever you decide to do as it's better than not having this feature at all.

2024-02-17 12:58 UTC, FreeMinded commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
Please keep it secure by default! 2 hours is fine. If you make it configurable the then keep the default at high security.

2024-02-17 13:04 UTC, BlackDex commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
@sMteX, So, how often do you need to login then? With my browser extension i only need to unlock once after i start the browser, and that is an unlock, not a login.

And via the web-vault, i actually do not use it that often for a longer period of time, and that also defaults to lock after 15m, which you can of course configure your self, and if i'm correct, it will refresh just fine if you are a heavy user. Else you need to login.

2024-02-17 13:14 UTC, sMteX commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
@BlackDex Oh, I wasn't aware of that difference. I have no problem with logging in often when interacting with the web vault (as I'm not often administrating the passwords). However I find myself using the Firefox extension a lot, and *that* would be annoying to me having to unlock frequently. Does that make more sense?

2024-02-17 13:30 UTC, sMteX commented
I think any documentation or settings you don't have to spend time to figure out on your own is useful @spresse1

2024-02-17 15:31 UTC, BlackDex commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
Do you already experience this right now? if not, then all keeps the same and just as secure without changing the refresh token to be allowed valid for months.

2024-02-17 16:12 UTC, codyro commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
You can add knobs everywhere, but it doesn't mean you should. Security software should avoid adding too many “foot guns.” 

@BlackDex is 100% right on his stance here. Thanks for keeping a critical eye out.

2024-02-17 16:33 UTC, binaryben commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
My view is don't change the timeout settings from what we have currently, for now at least. This PR is for adding SSO and should be limited to that. Keep it in line with existing conventions. They can potentially be changed if there is enough demand for it, but campaign for it in a seperate PR/feature request if you want the knob added. I think @BlackDex comment that no one has been complaining so far is very noteworthy. I also err on the side of security over convenience (to an extent of course, but the threshold isn't triggered here imho).

I understand it can be annoying to have to type the password every X time period when it locks, but at the same time, we should be using a PW manager so we only have to remember one secure password, not to reduce the security of using passwords in general.

Whilst I am expressing a strong opinion here, I do want to counterbalance/soften that a bit by thanking everyone who is working hard to bring the feature to fruition. It is incredibly appreciated and I can't wait to be able to use SSO with Vaultwarden.

2024-02-17 17:25 UTC, Timshel commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
@BlackDex  I don´t understand isn't the `refresh_token` the `device.refresh_token` ([password login](https://github.com/dani-garcia/vaultwarden/blob/bb2412d0339e1da5dee99fc566a2b2aab5d2808c/src/api/identity.rs#L289) / r[efresh](https://github.com/dani-garcia/vaultwarden/blob/bb2412d0339e1da5dee99fc566a2b2aab5d2808c/src/api/identity.rs#L122C10-L122C23)) ?
Which is set [once](https://github.com/dani-garcia/vaultwarden/blob/bb2412d0339e1da5dee99fc566a2b2aab5d2808c/src/db/models/device.rs#L66) and never updated ?

Did I miss something ?

2024-02-17 17:38 UTC, Timshel commented
@spresse1 yep any documentation is welcome, but for Keycloak you don't need the `offline` scope you can change the `refresh_token` max lifetime. I believe :
 - for refresh token : `Realm settings / Sessions / SSO Session Max` 
 - for access token: `Realm settings / Tokens / Access token Lifespan`

 I will add-it to the documentation.

2024-02-17 18:06 UTC, BlackDex commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
It's about https://github.com/dani-garcia/vaultwarden/blob/bb2412d0339e1da5dee99fc566a2b2aab5d2808c/src/api/identity.rs#L97

That now generates a token which is valid for ~1year.
There might need to be added some more checks here looking at it more closely, but it's difficult to read on a small screen hehe.

But, that is what looks like getting changed from 2h to 1y.
Probably not what we want.

2024-02-17 18:20 UTC, Timshel commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
I don´t  understand what you are talking about ?

Unless I misunderstood something the  `_refresh_login` used to  return :
 - A base64 `refresh_token` which never changed / expired  which is used to call the `_refresh_login`
 - A JWT `access_token` with an expiration time of 2h
 
 Unless I made a mistake, this PR change it to now return :
  - A JWT `refresh_token` with a validity of a [year](https://github.com/Timshel/vaultwarden/blob/e7350c0114292ebdebb8cf5ac49e17745f5c98e6/src/auth.rs#L1020C31-L1020C55) (which as I mentioned before I set so long since it replaced something which did not expire) 
  - A JWT `access_token` with an expiration time of [2h](https://github.com/Timshel/vaultwarden/blob/e7350c0114292ebdebb8cf5ac49e17745f5c98e6/src/auth.rs#L204)

2024-02-17 18:54 UTC, LightningManGTS commented
I'm definitely thinking there is some confusion here regarding what's being affected. For example in the version of the pr I downloaded last week, allowing DUO to control the token expiration limited it to me being able to set it 1 hour and no more. When the token expired it fully logged out the extension instead of just locking the vault. Locking the vault is the default functionality when you close the browser or when the time for it being unlocked expires. There needs to be a clear distinction here between logged out and locking 

Personally I have it set to require users to log in after 8 hours from last login in other applications (assuming the session is not being maintained longer by being open.) 

It should also probably be noted that when logging in with SSO it closes the extension after completing and then requires the user to open the extension to then put the master password in to unlock it. This likely do to normal bitwarden also having users employ a secret database for handling the master password step for the user when they are using SSO. After this key connector should probably be looked into as a new repository project (as on premise it's technically a sperate application) https://bitwarden.com/help/about-key-connector/

There's also something about trusted devices which I'm less familiar with as a concept.

2024-02-17 19:21 UTC, BlackDex commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
As said before, I'm not having all clear from the top of my head. But besides that, i think a year is too much. Of changing, then maybe a bit better. I did thought it already send out a refresh token with a limited lifespan, i can be wrong of course.

But, besides that, if we are going to change it, and it was indefinitely right now, i would still prefer a lower amount, then do it a bit better right away. We might need to check how that impacts other clients too. And maybe to stay on a safe side it could be like a few days or max a month or so? Then later on, not this pr, we can check how to improve this security wise.

Sorry if I'm coming over a bit harsh here. But i don't want to create a security issue or possible attack vector here.

2024-02-17 19:30 UTC, Timshel commented on src/auth.rs
> +pub static DEFAULT_ACCESS_VALIDITY: Lazy<Duration> = Lazy::new(|| Duration::hours(2));
As i mention I don't care about the length just wanted to clarify the misunderstanding around the fact that it replaced something with no expiration in case I missed something.

Additionally as I mentioned this value is more of an idle timer since with each refresh a new refresh token is generated with a new expiration date. So it should be possible to set something low like a week and as long as the user used VaultWarden during this time then the refresh token will be extended.

As you mention will need to confirm it working the same way with different clients but I expect/hope it will :).

2024-02-18 13:39 UTC, Timshel commented
Hey
Heads-up with the switch to using `openidconnec` to validate claims I missed that's it's not [recommended](https://github.com/ramosbugs/openidconnect-rs/issues/25) to reuse the same client for a long time.

Will push an update but in the mean time without some periodic restart you might end-up with Id token validation starting to fail after some time. 
Note: Checking the cache-control of `.well-known/openid-configuration` Keycloak and Gitlab return no-cache and Google 1h.

2024-02-18 15:36 UTC, Timshel commented
Latest updates :
 - Reduce default `refresh_validity` to 7 days (reset with each `access_token` refresh, so act as an idle timer).
   Apply to non sso login and SSO which return a non JWT token with no expiration information.
 - Roll the already present `Device.refresh_token` which will invalidate past `refresh_token` (SSO and non SSO login).
   Though on it during the discussion, opened a [PR](https://github.com/dani-garcia/vaultwarden/pull/4364) to add it to the main too.
 - Remove the `openidconnect` cache since it's not [recommended](https://github.com/ramosbugs/openidconnect-rs/issues/25).

For those using the release `1.30.2-7` should be ready in ~1h.

2024-02-20 13:16 UTC, DenuxPlays commented
Are they any estimetations on when this will be merged?

2024-02-20 13:32 UTC, BlackDex commented
> Are they any estimetations on when this will be merged?

No.

2024-02-20 18:11 UTC, Timshel commented
I added some playwright tests for account creation and login on all db. Created a separate [PR](https://github.com/dani-garcia/vaultwarden/pull/4369) for it.
So I rebased everything here on top of it :).

2024-02-25 03:17 UTC, KenMacD commented
Just testing this on Nix with Kanidm. It appears to be working but it looks like  PKCE isn't used. I know that's less of a concern where the secret is kept on the server, but [Kanidm does still recommend it](https://kanidm.github.io/kanidm/stable/frequently_asked_questions.html#why-is-disabling-pkce-considered-insecure).

This could probably be a 'later' thing. In the mean time for anyone else that runs in to the issue you'll want to:

```
kanidm system oauth2 warning-insecure-client-disable-pkce CLIENT_NAME --name admin 
```

2024-02-25 11:53 UTC, Timshel commented
@KenMacD hey made an [issue](https://github.com/Timshel/vaultwarden/issues/33) with my though on the subject :).
Will add the disable pkce bit to the SSO doc.

Thanks :)

2024-02-26 21:07 UTC, Timshel commented
@KenMacD Added PKCE support controlled by `SSO_PKCE`.

It's off by default for now but will probably turn it on later unless some issues arise.
Tested on Keycloak, Authentik, Google Auth  and Gitlab and had no issue.

Usual suspect for issues is Azure with stuff like [this](https://learn.microsoft.com/en-us/answers/questions/218113/openid-connect-authorization-code-flow-with-proof) which may cause issue.

2024-02-29 17:51 UTC, Timshel commented
Had to rollback the cache used for the `openidconnec` client since it introduced failures (it never expired and created issues when the JWT signing keys were rolled).

So added it back (disabled by default) with a configuration to control the expiration time. 

More information: https://github.com/Timshel/vaultwarden/blob/sso-support/SSO.md#client-cache

2024-03-05 00:00 UTC, spatical commented
I've been running this branch for my small dev team's vaultwarden instance since the last commit and the SSO feature has been working for us.

2024-03-05 00:21 UTC, WesleyBryie commented
> I've been running this branch for my small dev team's vaultwarden instance since the last commit and the SSO feature has been working for us.

Would you say that this branch is stable for a single user then?

2024-03-05 06:29 UTC, sandervandegeijn commented
Since the connection with azure has been fixed it's been fine here 👍

2024-03-05 14:44 UTC, WesleyBryie commented
just dropped in the sso supported docker container, everything instantly worked just the same, what I am wondering though, is it intentional to still require the master password AND vaultwarden's 2FA? or is it supposed to bypass those? Would enabling Force SSO work there?

2024-03-05 17:12 UTC, Timshel commented
For those using the Docker file from this branch modified the [start.sh](https://github.com/dani-garcia/vaultwarden/pull/3899/commits/04732d8baa65bcc9b74a8ffbee82dfee153b0265) to check the env `SSO_ENABLED` to display or not the SSO button.

I think it's better than to display the button to those not using SSO, and it's transparent to those using Docker. It requires those deploying SSO any other way to run the `sed` during their setup, but I don't think it's too much of an overhead.

@WesleyBryie from the opening comment of the PR :

> A master password is still required and not controlled by the SSO (depending of your point of view this might be a feature ;). A key connector to remove this could be added but is not planned in this PR.

and 

>  Please open issues in [Timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues) in order to keep the discussion here focused on merging this work.

For the 2FA part made no change to it, should continue to use the configuration set by the user (I can't test all the providers, but hopefully they still should work).

Unsure what you mean by Force SSO:
 - `SSO_ONLY` will just disable the ability to log with only the Master Password without going through the SSO flow
 - `SSO_EXPERIMENTAL_NO_MASTER_PWD` (from `main`) is not the best named, it's an experiment to stop sending/storing the Master Password to/in the server, but it's still required to unlock the vault.

2024-03-05 17:16 UTC, WesleyBryie commented
My bad, I had figured it was reasonable for this to go here. The Force SSO option is in the Admin panel.

2024-03-05 17:51 UTC, misilot commented
> For the 2FA part made no change to it, should continue to use the configuration set by the user (I can't test all the providers, but hopefully they still should work).

Is there a way to override the 2FA within Vaultwarden. This would be beneficial if the SSO used already manages / requires MFA.

2024-03-05 18:17 UTC, Timshel commented
@WesleyBryie  A yes it's the `SSO_ONLY` config, I changed the description.

Not sure how the maintainers decide what is displayed in the admin page, For now updated it to remove anything that control the sso config itself.

@misilot I'm not aware of anything and not planned on my side.

2024-03-06 07:25 UTC, compgeniuses commented
i think this is the longest running PR on an opensource project.

2024-03-08 16:23 UTC, Timshel commented
Hey

Hopefully the latest important change :).
I mentioned recently there was a [CVE](https://github.com/mastodon/mastodon/security/advisories/GHSA-vm39-j3vx-pch3) on Mastodon for account takeover. Made me realize that this PR had the same issue even if scope was even more limited since the Master password would still be required.

But still since it's not recommended to rely on the email added another table (`sso_users`) to store the SSO provider identifier (Kept it separate since it's only used on login).  Association on email is still possible but only for non-existing SSO identifier, and it's controlled by `SSO_SIGNUPS_MATCH_EMAIL` (on by default).

Concerning email change, discovered that the email is part of the `key`, so only the user can make the change. Decided to just send an email on login if the emails stopped matching between Vaultwarden and Provider.

Wrote a bit more details [there](https://github.com/Timshel/vaultwarden/blob/sso-support/SSO.md#account-and-email-handling).
And updated the revert DB [procedure](https://github.com/Timshel/vaultwarden?tab=readme-ov-file#revert-to-default-vw) to return to a default Vaultwarden.

2024-03-13 01:33 UTC, TheRealGramdalf commented
> Concerning email change, discovered that the email is part of the `key`, so only the user can make the change. Decided to just send an email on login if the emails stopped matching between Vaultwarden and Provider.

My apologies if I'm missing context here (just saw this at a glance and thought I'd pop my thoughts here), but this is what the `sub` claim is for - this is guaranteed to be immutable and user-unique as per the openid spec, so any provider that supports OIDC should expose it - and if it doesn't, then it's not actually spec compliant, and the issue would be with them, not vaultwarden.

2024-03-14 14:22 UTC, phoenixbackups commented
What are we supposed to use for the organization identifier?

2024-03-20 15:55 UTC, Timshel commented
Hey,
Rebased on top of `main` and updated to support latest change from `chrono`.

But I recently was able to claim the `timshel` repository on docker :tada: 
So sadly for you it means I moved the project to [hub.docker.com/r/timshel/vaultwarden](https://hub.docker.com/r/timshel/vaultwarden/tags) :)
And I deciced to move the `experimental` stuff out of main and it will be available in [hub.docker.com/r/timshel/oidcwarden](https://hub.docker.com/r/timshel/oidcwarden/tags).

2024-03-20 18:27 UTC, sandervandegeijn commented
Cool :) do we have any idea what still needs to be done to get this merged?

2024-03-20 19:27 UTC, compgeniuses commented
i beleive a significant amount of work has already been done, and equally Timshel has been available to sort and solve any matters arising.

the core maintainers are significantly held up since, well... alot of work

unfortunately, with every wait to merge, the implementor gets new ideas to imporve the PR, thereby increasing even more the time required to assess the works. so ends up becoming chicken and eg situation.

Hopefully the time would be available and all this would be available to all of us.

you should note the docker build by timshel has all the bells and whistels, and you can use it, some people have used it in prod and no complains so far.

2024-03-20 19:30 UTC, sandervandegeijn commented
We have been running this in a test environment, no complaints at all. But to use this in production we would like to do a formal penetration test by a commercial security vendor and give the results back to the community. But with the code still under active development this is not the right for this, we're waiting for a stable build to be released :)

2024-03-22 10:35 UTC, sandervandegeijn commented
Yeah I understand, but it's easier to explain the costs when we're doing it on Vaultwarden as a whole with the SSO-support included :)

2024-03-25 16:13 UTC, rafalkrupinski commented
@sandervandegeijn expects a stable build to start penetration tests;
@Timshel expects penetration tests before merging the PR...

Do we have a another chicken and egg situation?
May I suggest making a release candidate, so it can get tested and become the release after it passes?

2024-03-25 16:19 UTC, sandervandegeijn commented
That could be acceptable yes, but we still would like to know if this has a proper chance of being merged with the main Vaultwarden project before pentesting it. If the PR get's rejected that's a waste of resources and money from Dutch tax payers :)

2024-03-25 16:22 UTC, Timshel commented
@rafalkrupinski what are you talking about ? I'm not the one merging the PR and I only said it would help ...
As for an RC without review it's not better than the docker image I'm publishing.

2024-03-26 08:51 UTC, rafalkrupinski commented
> @rafalkrupinski what are you talking about ? I'm not the one merging the PR and I only said it would help ... As for an RC without review it's not better than the docker image I'm publishing.

That's the point. Someone who wants to spend money on certification might not want to do so for a contributors unofficial image. RC would constitute a solid(er) intention to merge, given the certification passes.

2024-03-26 13:56 UTC, LightningManGTS commented
> > @rafalkrupinski what are you talking about ? I'm not the one merging the PR and I only said it would help ... As for an RC without review it's not better than the docker image I'm publishing.
> 
> That's the point. Someone who wants to spend money on certification might not want to do so for a contributors unofficial image. RC would constitute a solid(er) intention to merge, given the certification passes.

I'm pretty sure there is some massive misconceptions as to who is responsible for creating new branches or setting up a RC in this repository. @blackdex or other maintainers with the correct permissions would need to create a new branch merging the changes in this PR. Currently the changes are being reviewed when blackdex or someone else has time. Until then @Timshel is doing an excellent job maintaining his fork and even spent some time to get his own docker library to make it easier to deploy his fork. Said fork is going to be the closest thing to a RC as we can get for now.

on that @Timshel keep up the good work!

2024-03-26 16:52 UTC, rafalkrupinski commented
Sorry for causing confusion, I don't know who's responsible for what around here.

I meant to suggest potential solution between sandervandegeijn and the project maintainers.

2024-03-28 14:32 UTC, allanian commented
+1, please merge!

2024-03-28 20:53 UTC, sandervandegeijn commented
> > > @rafalkrupinski what are you talking about ? I'm not the one merging the PR and I only said it would help ... As for an RC without review it's not better than the docker image I'm publishing.
> > 
> > 
> > That's the point. Someone who wants to spend money on certification might not want to do so for a contributors unofficial image. RC would constitute a solid(er) intention to merge, given the certification passes.
> 
> I'm pretty sure there is some massive misconceptions as to who is responsible for creating new branches or setting up a RC in this repository. @BlackDex or other maintainers with the correct permissions would need to create a new branch merging the changes in this PR. Currently the changes are being reviewed when blackdex or someone else has time. Until then @Timshel is doing an excellent job maintaining his fork and even spent some time to get his own docker library to make it easier to deploy his fork. Said fork is going to be the closest thing to a RC as we can get for now.
> 
> on that @Timshel keep up the good work!

THanks for the reply and @Timshel for all the hard work indeed. But I suppose this won't be a permanent fork, the intend is to merge it?

2024-03-29 02:07 UTC, binaryben commented
Please lock comments to existing commenters? Here for updates, not for every "please merge?" and "how long?" comment.

2024-03-29 05:42 UTC, SadmL commented
I don't think that's locking comments is good idea, coz that happends pretty rare. May be just mark this kind of comments like off-topic?

2024-03-29 06:31 UTC, nibblerrick commented
> Please lock comments to existing commenters? Here for updates, not for every "please merge?" and "how long?" comment.

I see why you want that and I can totally understand that. But I think it's better to create awareness for giving a thumbs up to the merge comment and explain that "+1"-like comments aren't a good way. It seems to me, many just don't know how much this can bother others subscribed to the issue.
Just my 2 cents.

And for the PR: very nice work, thanks for the work and effort!

2024-03-29 06:43 UTC, binaryben commented
> I don't think that's locking comments is good idea, coz that happends pretty rare. May be just mark this kind of comments like off-topic?

Definitely not uncommon for long running PRs, especially when there is a public fork to manage actual issues.

> It seems to me, many just don't know how much this can bother others subscribed to the issue.

💯! I also think some people think continuing to ask will make it go faster. If anything, it'll go slower.

> And for the PR: very nice work, thanks for the work and effort!

Yeh, this project in it's entirely constantly blows me away in terms of the quality. This PR is no exception. Major kudos to @Timshel and those whose work came before. And to @BlackDex and the other maintainers doing reviews.

2024-03-29 07:45 UTC, SadmL commented
I think if Github have a RSS feed for PRs that might prevent some "+1"-like comments. I understand that for most part they comes from newbie users which don't know what is actually RSS is, but anyway...
I use self-hosted [RSS-Bridge](https://github.com/rss-bridge/rss-bridge) to have one, coz it convenient to me.

2024-04-01 15:37 UTC, Timshel commented
Hey
Just released `1.30.5-7` to fix a migration issue on `mysql`, had only tested on `mariadb` and forgot that `unique` would hit the `key` error on `TEXT`.
So modified the migration creating the `sso_users` table and switched the  `identifier` to `VARCHAR(768)`, the max value before hitting the `max key lenth is 3072 bytes` limit. 
This should be sufficient in almost all cases but still under the theorical limits (`identifier` is the concatenation of `iss` with the `sub`; the `sub` is limited to 255 chars which leave some margin for the less defined `issuer`).

If you are running `mariadb` then the modified migration will not run again, and you will keep the column defined as `TEXT`. In case you want to be more iso then you'll need to manually run:

```sql
ALTER TABLE sso_users MODIFY identifier VARCHAR(768) NOT NULL UNIQUE;
```

To ensure that it does not happen again I modified the Playwright tests to run against `mysql` in addition to `mariadb`.

2024-04-15 14:32 UTC, Timshel commented
Latest commit disable rolling the device token since had too many issues with the latest clients making refresh calls in parallel

It will be in `1.30.5-8` but be aware it's on top of latest main and with the new web-vault version.

2024-04-21 21:45 UTC, dasunsrule32 commented
I'm only using sqlite, is that supported as well?

2024-04-25 10:52 UTC, sandervandegeijn commented
I'm planning a meeting with our pentest partner about pentesting Vaultwarden. Do we have any idea about a timeline when this will be merged in the main Vaultwarden project? Doesn't matter if it's in a week, a month or 6 months, but I would like to give a rough estimation to be able to plan the test.

We would like to test the SSO-part but also ask to do a white box test of the project as a whole.

2024-04-29 15:10 UTC, Timshel commented
Just rebased and squashed commits; no change outside some doc fix/improvements.

2024-05-17 12:45 UTC, Ornias1993 commented
Honestly, At this point I'm sincerely starting to agree with the previously stated feeling that, even though they deny it, maintainers try to appease Bitwarden by ignoring this.

It just so "happens" that their personal interest, aligns with the interest of  the Bitwarden corporation which also just "happens" to be the maintainers employer.

I could accept the initial response, but when they respond and they yet-again go completely dark on such a major feature inclusion... That's at least very sus.

Honestly, I view that as a major conflict of interest and something I actively prevent in project I maintain. Begging the question if Vaultwarden shouldn't be moved to its own Github Organisation and the people with conflict-of-interest shouldn't step-down from management positions.

2024-05-17 13:11 UTC, Timshel commented
As far as I'm aware only the creator of the project is employed by Bitwarden not the most active maintainers.

And I won't say I'm overjoyed at the pace of the review but it's far from being the only PR not merged/reviewed while probably being the most complex one. And you probably overestimate how important this feature is; while there is over 50 peoples tracking it in the end I can see less than a 1000 docker pull on dockerhub. Vaultwarden is at over 100M+ ...

In the end I'm always thankful of the job done by maintainers; the only thing I would ask would be to inform me if there was no plan to merge it (I don't believe it's the case); outside of it I'll wait.

As far as a conflict it's possible there is one; but it all comes down to who is ready to spend some time to maintain the project. I don't believe the license prevent you from creating a fork, you'll probably just have to rename it. 
So if you setup such an org I'll be happy to open a PR against this new project too.

2024-05-17 13:17 UTC, binaryfire commented
@Timshel Just one point regarding 50+ people tracking the issue but only having 1000 pulls on Docker Hub. I think the no of GitHub followers is a much better indicator of interest in this feature (which IMHO is huge).

I’m guessing the vast majority of us aren’t using the non-official Docker build at all, and are just waiting for it to be merged into the main build. That’s the only reason the no. of pulls is low.

2024-05-17 13:32 UTC, sandervandegeijn commented
> @Timshel Just one point regarding having 50+ people tracking the issue but only having 1000 pulls on Docker Hub. I think the no of GitHub followers is a much better indicator of interest in this feature (which IMHO is huge).
> 
> I’m guessing the vast majority of us (like me) aren’t using the non-official Docker build at all, and are just waiting for it to be merged into the main build. That’s the reason the no. of pulls is low.

That applies to us as well, I cannot justify to deploy such a crucial piece of software from a (no offence @Timshel !) tiny fork. We are waiting for it to be merged and are willing to invest ±10k in a formal pentest of the solution as a whole.

As far as Bitwarden goes, I have contacted them about their views on Vaultwarden and the reply was nothing short of heartwarming. I didn't read any reservations in their reply whatsoever. This also was important for us to make the investment into implementing this software.

So we are very thankful for all the hard work of both @Timshel and the maintainers of the Vaultwarden project. Keep it going guys!

2024-05-19 12:49 UTC, compgeniuses commented
@BlackDex there is a reason most projects have a beta release, then a release candidate, then a release, then a patch release.

The e is also a tendancy in a lot of opensource projects for PR that took alot of time and effort to the contributors to become stale, especially when for some reasons, the originator of the PR, is no longer available to issue quick fixes and updates, just because it took way too long. I understand and everyone does, Maintaining Opensource Projects is not easy, however while this is the case, we also need to take note of and appreciate the actions and works of the originator of the masive PR. it is my beleive, together with many people, that Having this PR merged, and potentially a BEta release, would potentially and significantly apply alot more support to the overall project, than simply stating, its not merged because we are not yet sure. 
Already 1k people are downloading the @Timshel build and have been using and stated it works great, ofcourse we cant take their words for it 100%, but since vaultwarden have 100M+ downloads as stated, wouldnt having this available in a future release provide a much larger audience for testing and reporting, and that way, if there are any issues, they will be identified and fixed much ealier. we are lucky that VW is using Rust, as Opposed to NodeJs and its JS brothr, otherwise, this PR would be Dead, due to how libraries work on those languages. Lets all the mindful of all efforts taken by other people. If I dedicated 1 month to build something, i would appreciate if someone dedicated a day to look at what i did, overall this are jus tmy sentiments, and in no way meant to rub on anyone

2024-05-19 13:03 UTC, Ornias1993 commented
> @BlackDex there is a reason most projects have a beta release, then a release candidate, then a release, then a patch release.
> 
> The e is also a tendancy in a lot of opensource projects for PR that took alot of time and effort to the contributors to become stale, especially when for some reasons, the originator of the PR, is no longer available to issue quick fixes and updates, just because it took way too long. I understand and everyone does, Maintaining Opensource Projects is not easy, however while this is the case, we also need to take note of and appreciate the actions and works of the originator of the masive PR. it is my beleive, together with many people, that Having this PR merged, and potentially a BEta release, would potentially and significantly apply alot more support to the overall project, than simply stating, its not merged because we are not yet sure. Already 1k people are downloading the @Timshel build and have been using and stated it works great, ofcourse we cant take their words for it 100%, but since vaultwarden have 100M+ downloads as stated, wouldnt having this available in a future release provide a much larger audience for testing and reporting, and that way, if there are any issues, they will be identified and fixed much ealier. we are lucky that VW is using Rust, as Opposed to NodeJs and its JS brothr, otherwise, this PR would be Dead, due to how libraries work on those languages. Lets all the mindful of all efforts taken by other people. If I dedicated 1 month to build something, i would appreciate if someone dedicated a day to look at what i did, overall this are jus tmy sentiments, and in no way meant to rub on anyone

Yes, for big PRs n like this that already have some testing and review put in the proactive way is taking over the PR into a BETA  branch

2024-05-19 13:11 UTC, BlackDex commented
@compgeniuses you do now most people have a life and a day job besides opensource projects like this right? I do this on my spare time, which i have unfortunately little of lately (as explained above). Spending a day is not that easy as you think.

Having an alpha, beta or an rc will not really help as you already can see above, people seem to be waiting for this to be merged and released in stable. Also, having more then stable and testing also means more work, which is probably also not what we want.

Also, in any case, I'm not for blindly merging something even though people are already using it. I'm not saying that @Timshel's code is bad or has issues, it's just not good practice in my opinion.

Once reviewed it will end up into testing, and later in stable.

As a side note. I want to point out that I also have A PR open in this project which still isn't merged, and also at other projects. Sometimes it takes a longer time.

2024-05-19 13:26 UTC, Ornias1993 commented
> As a side note. I want to point out that I also have A PR open in this project which still isn't merged, and also at other projects. Sometimes it takes a longer time.

"it takes a longer time", which **VERY** often means PR's don't get rebased continuesly and the original author disappearing... at which point I doubt you're also going to rebase it unless it's in a Vaultwarden-Managed branch.

That's the point why people promote taking this over in an official testing branch: As the burden to rebase gets put on the community instead of the generosity of the original author.

2024-05-19 13:44 UTC, BlackDex commented
> > As a side note. I want to point out that I also have A PR open in this project which still isn't merged, and also at other projects. Sometimes it takes a longer time.
> 
> "it takes a longer time", which **VERY** often means PR's don't get rebased continuesly and the original author disappearing... at which point I doubt you're also going to rebase it unless it's in a Vaultwarden-Managed branch.
> 
> That's the point why people promote taking this over in an official testing branch: As the burden to rebase gets put on the community instead of the generosity of the original author.

You do understand that also a lot of times once a PR is merged people leave it over to the maintainers, and if something is broken with such a huge feature they expect the maintainers to fix it.

Currently i only see 2 mainline maintainers, 1 owner and a few recurring maintainers. I do hope @Timshel tends to stick around 😄, not only for SSO stuff, but also other items.

2024-05-19 15:08 UTC, Timshel commented
As I mentioned before I'm against a beta branch since I would probably lose the ability to update/maintain it.

And I don't understand the peoples who want this integrated without review; if you don't care about review then just use the current build ...

2024-05-19 17:05 UTC, binaryben commented
At risk of looking like the start of another XZ story… 😅 @Timshel, do you have any time to help maintain Vaultwarden after this gets merged? Very fair concern that you’d lose the ability to maintain it if merged as a beta. Maybe getting yourself onboard as a maintainer would help alleviate those concerns all around if @BlackDex and @dani-garcia were supportive? No stress on my part if it’s not feasible for any of you to consider… I’m content waiting since I’m not able to contribute myself

2024-05-20 14:44 UTC, Timshel commented
Since I'm using it after it's merged I'll still be around and able to help if needed.
As for the maintaining part lately I'm not doing much just rebasing when needed and improving the documentation.

Anyway just rebased on lastest from `main` and made a testing release with the `v2024.5.0` front-ent if some of you want to test it.

2024-05-20 14:53 UTC, BlackDex commented
> > Since I'm using it after it's merged I'll still be around and able to help if needed.
> > As for the maintaining part lately I'm not doing much just rebasing when needed and improving the documentation.
> > Anyway just rebased on lastest from `main` and made a testing release with the `v2024.5.0` front-ent if some of you want to test it.
> 
> Is there an accompanying docker build available to use to test it?

Checkout this PR and follow the instructions in the docker directory.

2024-05-20 15:04 UTC, Timshel commented
> Is there an accompanying docker build available to use to test it?

If you mean the `v2024.5.0` yes the [build](https://github.com/Timshel/vaultwarden/deployments/main) is in progress  and it should be available as `testing` in [docker-hub](https://hub.docker.com/r/timshel/vaultwarden/tags) and [ghcr.io](https://github.com/Timshel/vaultwarden/pkgs/container/vaultwarden) once finished.

2024-05-20 15:09 UTC, Ornias1993 commented
@Timshel I'm willing to use my resources as a TrueCharts maintainer to offer your "beta" container as an option for testing to all our users if you like :)

2024-05-20 15:13 UTC, Timshel commented
@Ornias1993 not sure what this would entail but if you want to discuss it please open an issue in [timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues).

2024-05-20 15:22 UTC, Ornias1993 commented
> @Ornias1993 not sure what this would entail but if you want to discuss it please open an issue in [timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues).

Nothing on your side at all, no worries...
It just means for us to expose it to our est 10k+ users

2024-05-20 15:42 UTC, Timshel commented
> please open an issue in [timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues).

@Ornias1993 in general I tend not to respond when people ignore this but.

Even if I have nothing to do I hope you will consider the following considerations :

 - `Vaultwarden` is not my project, I don't believe the team had issues with me publishing it with this name on docker to ease testing. I would be more warry of calling it `TimShel - SSO BETA` ...
 - Please ensure that issues regarding SSO are open in [timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues)
 - I have no interest in debugging Helm-Charts
 
 Anyway once again if you want to discuss the subject further please as mentioned in the PR itself and my previous comment open an issue. I would like to try to keep the discussion here focused around merging this.

2024-05-20 18:00 UTC, Ornias1993 commented
> > please open an issue in [timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues).
> 
> @Ornias1993 in general I tend not to respond when people ignore this but.

I'm not opening an issue there, because there is nothing to say.
I just am telling you that i'm trying to support you by adding more testers for you. TBH, I expected more of a "thank you".

> * `Vaultwarden` is not my project, I don't believe the team had issues with me publishing it with this name on docker-hub to ease testing. I would be more warry of calling it `TimShel - SSO BETA` ...

I've no idea what you're trying to say here. But thats how I decided to flag it for our users.
If you've a problem with that you can reach out to our team. But that doesn't belong here.

> * Please ensure that issues regarding SSO are open in [timshel/vaultwarden](https://github.com/Timshel/vaultwarden/issues)

Thats a good point, luckily we always advice users to report issues to use directly first

> * I have no interest in debugging Helm-Charts

There is nothing to debug, no worries and we actively advice users to report issues with us first. 
We run this Helm chart for ages and there is nothing special about your container.

That being said: if there is anything to debug, that is also quite important information, because that means the code build into your docker container has unexpected deviating behavior in things like permission and networking (the primary two causes of issues), which automatically makes it worthwhile. But I don't expect such a thing after code verification.


----

TLDR:
Its not about Helm Charts or anything, it's about getting more people on more platforms to test the code so we can get more feedback into this thread and get this merged.

2024-05-20 20:43 UTC, rizlas commented
I'm running vaultwarden in kubernetes with and without @Timshel just fine. No problem in the dockerization.

Helm charts, on the other hand, can be a source of errors if the templating is incorrect or something else.  It is not uncommon to find errors in bitnami's charts.

I guess that helm here is completely off topic.

2024-05-21 02:55 UTC, binaryben commented
> TBH, I expected more of a "thank you".

Thank you Mathijs, Daniel and Tim for this incredible project and PR. @Ornias1993 you are borderline advertising and being rude after a valid request to move the convo elsewhere. You then go on to make a similar point yourself (see quote below). Not sure how you can expect thanks with an attitude like that. Tim is well within expected practices to have questions and concerns.

> But that doesn't belong here.

Exactly.

2024-05-21 07:52 UTC, mejo- commented
> Thank you Mathijs, Daniel and Timshel for this incredible project and PR.

Full agreement, thanks so much :heart: 

>  @Ornias1993 you are borderline advertising and being rude after a valid request to move the convo elsewhere. 

Phew, why so rude? @Ornias1993 just communicated that they're going to provide a HelmChart based on this PR and that this will result in more testing of it. That's a great contribution in my opinion. I think the communication between him and Timshel was a bit led by missunderstanding. Everyone, please assume good faith :wink:

2024-05-21 08:19 UTC, binaryben commented
> That's a great contribution in my opinion

On the face of this POV, sure - I agree. Expecting gratitude only without any further comments is concerning though, especially after disregarding a simple request to move the convo to a better location. Maintaining OSS is hard. Respecting an authors simple request for something that make their lives easier is kind of a basic decency. I tolerate a lot and almost always assume good faith, but will still call out unneeded disrespect. I think there is more nuance in the reply to Timshel that you may not see? It smells of entitlement, which is a massive problem in OSS. Not the convo for here though, so let's move on.

2024-05-21 08:29 UTC, mgundelfinger commented
> Not the convo for here though, so let's move on.

This should be the main takeaway here. If anyone has anything else to add or think they need to defend themselves or call out others: Don't. Do it privately if you must, but this here just isn't the place for that. I'm sure we'd much rather get notifications from this thread that are about the PR itself 💜

2024-05-21 08:38 UTC, Ornias1993 commented
> I'm running vaultwarden in kubernetes with and without @Timshel additions just fine. No problem in the dockerization.

Cool, I'll work on throw the Timshel additions up on my cluster this week to test them out and document the process.

> Helm charts, on the other hand, can be a source of errors if the templating is incorrect or something else. e.g. It is not uncommon to find errors in bitnami's charts.

Agreed, thats why I look forward to testing how-well this runs as a "drop-in-replacement".
I'll write some automated tests right away to ensure it's pushed through our testing stack as well.

2024-05-23 15:41 UTC, sandervandegeijn commented
I have met with our penetration testing partner today. We will receive a quote to:

- Do a black box test
- Do a white box test
- Do an audit on the hosting environment

With the emphasis on the white box test. Rust is an odd one for them, but they are looking into it. We can't submit the whole report to the community but we can share the individual issues that they might find. If they quote is reasonable we will execute the test when the merge has been done.

2024-05-23 17:05 UTC, Ornias1993 commented
> We can't submit the whole report to the community

May I ask why?
It might be worthwhile to have a version with everything user-specific carefully redacted...

2024-05-23 18:31 UTC, sandervandegeijn commented
Long story short: legal stuff. Can't do too much about that, but you can trust us to share all relevant details with the community. That's in everybody's best interest including ours :)

Forgot to mention, there will be focus on the OIDC as well of course.

2024-05-24 13:05 UTC, FabioSpagna commented
Hello,

Do you have any idea when this option will be available in the main project?

I believe that all checks have been passed and it just needs a double check.

This feature would help avoid some of my headaches.

Thank you,
Fabio

2024-05-24 14:18 UTC, Ornias1993 commented
> Hello,
> 
> Do you have any idea when this option will be available in the main project?
> 
> I believe that all checks have been passed and it just needs a double check.
> 
> This feature would help avoid some of my headaches.
> 
> Thank you, Fabio

How about you put some effort in and actually read the last dozen or two responses here?
If its so important to you, you could put in that minimal effort.

2024-05-24 14:30 UTC, FabioSpagna commented
> > Hello,
> > Do you have any idea when this option will be available in the main project?
> > I believe that all checks have been passed and it just needs a double check.
> > This feature would help avoid some of my headaches.
> > Thank you, Fabio
> 
> How about you put some effort in and actually read the last dozen or two responses here? If its so important to you, you could put in that minimal effort.

I've asked because I didn't fund a clear answer. (I'm very sorry in case it was present)
However, based on what you wrote, I can understand that the answer is "NO", there isn't any plan.
Fabio

2024-06-13 14:07 UTC, KornKalle commented
I have just set up the oidc fork via Helm. Kudos for the good work @Timshel. Everything seems to be running fine about the sole SSO Authentication.

But for my use-case (a medium-sized NGO with potentially ~4k users) it is not going far enough and keeps things too complicated for us. 
I don't really see the benefit of adding OIDC authentication here, as there is currently no possibility to "seamlessly" enroll users.
It is fine and understandable that users still need to set a master password (though we would be also fine when there would be another solution), but the rest of the flow is doubling the work you usually want to handle via an IDP to my understanding including the deprovisioning of groups.
Currently we would still to create an organization manually beforehand and the user/org admin still needs to confirm the invitation. This is redundant for our use case as application access and group/org membership is handled centrally through our IDP, so it should be straightforward to add a user to a group with Vaultwarden access on our IDP side to grant access to the respective organization vaults (and also being able to revoke access).

Let me know if I can help you with anything our I can provide further details. Unfortunately, I am not familiar with Rust development.

2024-06-13 14:56 UTC, jonathanmohamed commented
@KornKalle I agree with you.
Most things we can get by with. We only have ~80 users. Needing to confirm each user is not ideal, or from a logical (from a user flow perspective). If I have already sent an invite to them, it should auto add them, since the link in the email invite is tokenized and only for that email to join the org.

In your case it is for sure not feasible at a large scale of 4k users.

Keyconnector (unlocking the vault with SSO) is something I already requested in his branch, but he needs more people to have an interest in it before he invests time into it.

I've been clear about offering a donation for that feature.

Essentially, what we want is SAML, and this PR is strictly SSO. And I completely understand that was not the intention of this PR.

2024-06-13 17:51 UTC, rizlas commented
I also add that @Timshel already developed things like "invite auto accept" and sso roles but they are not gonna be into this PR.

As said multiple times there is already enough work to be checked and I think it is enough for the scope of vaultwarden (for now).

2024-06-14 06:42 UTC, KornKalle commented
Yes, for the sake of keeping it reviewable and integration this is a very good first step. Thanks for the information @Timshel, I will have a look at it

2024-06-24 08:42 UTC, sandervandegeijn commented
> Long story short: legal stuff. Can't do too much about that, but you can trust us to share all relevant details with the community. That's in everybody's best interest including ours :)
> 
> Forgot to mention, there will be focus on the OIDC as well of course.

Our pentest-partner will send us the quote in the coming week so I could use some sort of a timetable to reserve the time on their side. I truly don't care if it's tomorrow or in three months, anything is fine, but is it possible to provide a rough ETA on when this will be merged?

From experience: functionality wise we are very happy with the build from @Timshel - it's working like a gem.

2024-06-26 08:21 UTC, Timshel commented
I would say expected since it's a merge commit with multiple co-authors that I'm rebasing (It's the initial work done by various authors of previous PRs).

2024-07-08 20:41 UTC, Timshel commented
Latest push is just to integrate the `Playwright` change I made in the other PR.

2024-07-10 18:55 UTC, Timshel commented
Hey,

`1.31.0-1` should be available based on Vaultwarden `1.31.0`.

2024-07-24 15:57 UTC, sandervandegeijn commented
Android, iOS stable client & webinterface: works fine. Tried the Firefox/Chrome integrations (stable), fine as well!

2024-07-24 17:02 UTC, Trinnik commented
I think that mixed environments are not handled optimally. In order for a mixed environment to work, you have to allow email+master password sign-in. There isn't any way to force SSO users to login with SSO only and only use email+master for non-SSO users.

As a side note, the Linux desktop client (Flatpak) works great for me. SSO redirects to browser and back, master password unlock works, can add and retrieve secrets. When closing and reopening, it asks for my master password as usual and unlocks the vault.

2024-07-24 20:04 UTC, Timshel commented
> There isn't any way to force SSO users to login with SSO only and only use email+master for non-SSO users. Maybe that's just a limitation of the Bitwarden web vault.

Not a limitation, just never really considered this use case. I saw allowing the email+password more as a way to bypass potential issues (Ex: desktop client on windows).

You can create an issue for it if you want, will take a look if there is more interest (would probably not add it to the PR but might end-up in the docker image).

2024-07-24 20:46 UTC, sandervandegeijn commented
Can we help out further? We are willing to invest time to help get this PR merged. Maybe open a bunch of issues to be tested in your forked repo where people can contribute on the issues?

2024-08-08 09:13 UTC, sandervandegeijn commented
Okay, we finally got a quote from another pentest partner because the firest one didn't have the expertise to test a Rust application. The quote is for a pentest with this scope:

> 2.1 Scope and Methodology
> 
> The WUR intends to deploy the open-source project Vaultwarden university-wide as a password vault, once the functionality for Single Sign-on (SSO) is correctly and securely implemented. For this reason, the primary focus of this penetration test will be the SSO component. For instance, is it possible to access another user's data through this functionality?
> 
> Additionally, the test will investigate the level of access required to the database or Kubernetes Pods to retrieve a large number (or all) of the stored passwords. The backend code will be examined to ensure that the various API endpoints sufficiently check user authorization and to identify other vulnerabilities as defined by the OWASP API Testing Guide. The Web GUI frontend code will be scrutinized for vulnerabilities related to the OWASP Testing Guide.
> 
> A method for conducting penetration tests on web applications based on the OWASP Testing Guide will be used:
> [OWASP Testing Guide](https://owasp.org/www-project-web-security-testing-guide/stable/)
> This method ensures adequate depth and consistency in testing. It provides an approach that ensures comprehensive testing, while also allowing for technology-specific tests where necessary. For more information on our methodology, refer to the appendix 'Service Description'.
> 
> The test will be conducted in the acceptance environment, with the targets to be provided later via email by the Client. The tasks will be carried out from our office or from a home location of our employees.
> 
> The outcomes of the penetration test will be compiled by our professionals into a report, including sufficient evidence for the findings and recommendations on how these vulnerabilities can best be remedied or otherwise mitigated.

Feedback is always welcome, you can mail it to sander.vandegeijn@wur.nl

The pentest itself will take about a week in man hours and they can start in September (or later). We can share the results with the community. When we have an ETA for the merge I will contact them to execute the pentest.

2024-08-11 17:29 UTC, BlackDex requested changes
I have a few items which could be better i think.
Hopeing to do some testing shortly.

2024-08-11 17:29 UTC, BlackDex commented on src/db/models/organization.rs
> +            // "UseKeyConnector": false, // Not supported
These should be converted to use the lowercase `u` in to start.

2024-08-11 17:29 UTC, BlackDex commented on src/api/core/accounts.rs
> +    org_identifier: Option<String>,
This could be commented out instead of setting `allow(dead_code)` if it is not used anywhere.
Will also lower the object size.

2024-08-12 08:47 UTC, Timshel commented on src/config.rs
> +        _duo_akey:              Pass,   true,  option;
Not sure why I would have changed it, maybe a rebase mistake :(.
Made a quick pass over the PR again hopefully there should not be other.

2024-08-12 09:49 UTC, Timshel commented on .env.template
> +# SSO_AUTHORIZE_EXTRA_PARAMS="
@BlackDex I'm guessing I should probably change this multiline mapping.
Switching to use query parameters format is probably the most logical (using `&`)

2024-08-13 10:16 UTC, Timshel commented on .env.template
> +# SSO_AUTHORIZE_EXTRA_PARAMS="
Made the switch, kept the multiline support (make it backward compatible) even if not really advertised.

2024-08-13 10:43 UTC, BlackDex commented on .env.template
> +# SSO_AUTHORIZE_EXTRA_PARAMS="
We might want to remove the multi-line parsing right before we merge this maybe?
That way you do not have to make any changes yet on your side, and we can force people who switch to the Vaultwarden container once merged to use query parameters.

2024-08-13 10:52 UTC, Timshel commented on .env.template
> +# SSO_AUTHORIZE_EXTRA_PARAMS="
Unless you anticipate to have to support lines in the config value I would just keep it since it add almost no overhead to the helper function (just a simple `.lines()`).

2024-08-13 15:03 UTC, BlackDex requested changes

2024-08-13 15:03 UTC, BlackDex commented on src/config.rs
> +        sso_enabled:                    bool,   true,   def,    false;
This should probably not be editable. The main reason is the check for it during the docker start.sh script.
That is just run once and will of course only work for the embedded web-vault within the container images we build. But it could cause confusion if someone enables it, and then the login option is not there.

While I'm also for not having that check done within the startup script and just change this within the web-vault by default though. But then still, not sure if we want this feature to be runtime editable, but without the startup change it will shouldn't be an issue though.

2024-08-13 15:57 UTC, BlackDex commented
I did some quick testing without SSO enabled at all.
It seems to work just fine from my point of view which at least indicates it should not cause issues for existing environments with the SSO options disabled.

I have not yet checked the SSO features at all.

2024-08-14 01:45 UTC, FlattusBlastus commented
> > I did some quick testing without SSO enabled at all.
> > It seems to work just fine from my point of view which at least indicates it should not cause issues for existing environments with the SSO options disabled.
> > I have not yet checked the SSO features at all.
> 
> Great to hear!
> 
> Any idea yet what SSO Provider you plan to use to test with yet? I use Authelia which is pretty easy to setup and works with this pr.

Any chance you would post your Authelia settings?

2024-08-14 15:12 UTC, FlattusBlastus commented
Thanks!!!

On Wed, Aug 14, 2024, 3:40 AM Daniel ***@***.***> wrote:

> I did some quick testing without SSO enabled at all.
> It seems to work just fine from my point of view which at least indicates
> it should not cause issues for existing environments with the SSO options
> disabled.
> I have not yet checked the SSO features at all.
>
> Great to hear!
> Any idea yet what SSO Provider you plan to use to test with yet? I use
> Authelia which is pretty easy to setup and works with this pr.
>
> Any chance you would post your Authelia settings?
>
> Here you go. I removed all the credentials from the file. The nice thing
> about authelia is there's also a script in the authelia repo that can walk
> you through setup and generate a configuration for you.
>
> The vault.domain.com OIDC entry is what I use for vaultwarden.
>
> I use authelia behind traefik.
> Example Authelia.txt
> <https://github.com/user-attachments/files/16611674/Example.Authelia.txt>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dani-garcia/vaultwarden/pull/3899#issuecomment-2288413821>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASVVEUD4WQK7MQTJ3ARA6DTZRMX2NAVCNFSM6AAAAAA44PS52CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBYGQYTGOBSGE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-08-14 19:30 UTC, flo-mic commented
Thanks @Timshel for maintaining this PR, great job!

Happy to see that this PR makes progress. As it is now going into further review and testing, I would like to offer some support if needed. 

If one of the maintainer needs an additional SSO provider beside of Authelia, I can easily setup additional realms within a Keycloak instance. In case this is needed for completing testing and get this merged, happy to support and provide a test sso provider via private messages.

2024-08-18 11:45 UTC, dfunkt requested changes
Just an initial round of reviewing the files, most (if not all) changes are cosmetic.
Another change that I'd suggest is to transition from the old compose v1 syntax: ```docker-compose``` to the v2 one: ```docker compose```
https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2

2024-08-18 12:45 UTC, almereyda commented
Please note that switching the Compose version can have unintended side-effects and could be considered a separate feature request for a future cycle, as it does not only affect the OIDC SSO, but also all other existing users of Vaultwarden. For those a clean upgrade path must be provided:

- What do existing installations have to do to regain compatibility?
- What if the host system is so old, that the Go Compose plugin with ` ` between the commands cannot be installed and users are forced to the legacy Python Compose with `-`?
- Will state be easily transferable from v1 to v2?

Just to keep in mind these questions that have come up in the past when performing a Compose manifest upgrade.

2024-08-18 12:56 UTC, dfunkt commented
The docker compose upgrade suggested only affects the Playwright part of the PR, which previous Vaultwarden installs do not have at all. And Playwright is only used for testing, it's not a dependency of Vaultwarden itself.

2024-08-18 13:39 UTC, BlackDex commented
We already need a relatively new version of docker/buildx to build and run the Vaultwarden containers. Versions which already not support the old `docker-compose` by default anymore and all use the `compose plugin` which is called via `docker compose`

2024-08-22 12:57 UTC, Timshel commented
Should be fixed with `1.32.0-2` :).

2024-08-23 14:00 UTC, Timshel commented
Made some improvement on the Playwright tests and updated the OIDC test env.
Added a [Maildev](https://github.com/timshel/maildev) service to easily to test OIDC with emails: [playwright/README.md#openid-connect-test-setup](https://github.com/Timshel/vaultwarden/blob/sso-support/playwright/README.md#openid-connect-test-setup)

2024-08-27 10:47 UTC, mimi0000oo commented
Hello, is there any update on this pull? 
I see that there is some progress, but i don't know how close is it to the actual merge in the main project.
Is it possible to give an ETA?

Thank you very much for contributing with this issue!

2024-09-05 15:11 UTC, Rainson12 commented
I have tested it with entra id and it worked fine. Amazing work! 

It would be great
* when SSO_ORGANIZATIONS_INVITE=true and smtp is set, to automatically invite the user to the org without additional email being sent, the admin anyways needs to confirm the user
* when SSO_ONLY=true and the starting page is being opened to automatically forward to the oidc provider instead of having the login screen first where one needs to enter its email and then clicking continue and then clicking Enterprise Single Sign-on since its anyways not possible to just login with your mail and masterpassword.

2024-09-05 18:03 UTC, Rainson12 commented
> @Rainson12 for the second point you can test with `SSO_FRONTEND=override` should be closer to what you want.

thats indeed much better, thanks a lot!

2024-09-06 12:11 UTC, Timshel commented
@Rainson12 there is an open issue more or less on the subject, please continue the discussion [there](https://github.com/Timshel/vaultwarden/issues/48).

Still for some clarification, auto accept was added to bypass the org invitation bug then removed when it become unnecessary.  It was requested again but for now I did not add-it back mainly because in the case of a new user the Org check is done before the user set a new password/obtain a key; And confirming an accepted user with no key resulted in a broken state :(.

Of course the check could be split in two places, but then the code would be quite janky since you would need to stay in the invited state first but without sending the invited email since you expect to automatically switch to `accepted` later-on.

I believe some guards were added, and now you can't confirm a user with no key, but if I remember correctly no error message is displayed :(. Still if I ever add it again it will probably be this way; will have to check it again.

And for clarification it would not change the scope of this PR since I'm trying to keep the scope of this already too big of a PR to a minimum and the org handling is already not present here but only in `timshel/main` and the docker distribution.

2024-09-13 18:47 UTC, Timshel commented
Hey,

So next week this PR would become one-year-old, but progress on getting it merge is still slow.
Earlier in the year I activated the sponsor feature and without being prompted some of you made a donation, thanks a lot :). But I won't be able to continue like this.

While the amount of work needed to keep-up with Bitwarden can vary and even if the core of the feature is stable there is still quite a bit of improvement and I would enjoy continuing working on it :).

So I decided to create a named fork [timshel/OIDCWarden](https://github.com/Timshel/OIDCWarden) to try to see if I can garner more support.

For now, I will be closing this PR since I don't plan to update it in the short term (will probably reopen it later on) while I work on the fork.

Subjects I intend to work are:
 - fixing some parameters left over after redirection.
 - More integration tests (Playwright)
 - Better doc.
 
The first fork release is `v2024.8.3-1` and as the name suggest include/interface with the `v2024.8.3` web-vault release (between the name change and some Organization change proceed with caution ;) ).
 
 If you have any question or feedback don't hesitate over [here](https://github.com/Timshel/OIDCWarden/discussions/1).
 
 Thank you :).

2024-09-13 18:56 UTC, fidelix commented
That's a shame. You can see there is a LOT of interest in this feature.

It would be super appreciated if the maintainers can comment on it.

In any case, thanks for all the work, @Timshel 

Hopefully both implementations remain largely compatible.

2024-09-13 18:57 UTC, sandervandegeijn commented
Okay, I'm thankful for all the work. But forking..why? The merge was getting more likely, the maintainers were actively looking at the code. I got the impression we were almost there. Vaultwarden has recently been audited and we are have a quote for pentesting the oidc functionality.

Still with a lot of appreciation for everything that has been done, this is critical software when deployed in an organization, running a fork maintained by one developer isn't viable for us and I can't justify the cost of a pentest (8k euro ish) on a small fork.

2024-09-13 19:06 UTC, BlackDex commented
I must say that I'm a bit disappointed for closing this.
I'm in the process of testing and no large issues from what i see for now.

But i was also busy with fixing pressing issues with the new clients.
From my opinion it was close for a merge after a new release which would solve most (if not all) issues with the new clients.

It's still up to you @Timshel of course.

2024-09-13 19:18 UTC, BlackDex commented
It looks like I re-opened it. But not to my knowledge (else I'm sorry for doing so, as it is not up to me to decide this)

Also, i think a named fork will only cause more confusion and also harms opensource in general in my opinion by scattering the landscape.

Anyways, if i did re-opened it, I'm sorry, if you still want to close it then go ahead, but it would be disappointed.

2024-09-13 19:29 UTC, Jasper-Ben commented
I agree with @sandervandegeijn, I do not think a hard fork is the way to go here. While a lot of people here want this feature quite badly (including myself), I believe only a fraction would be willing to commit themselves to running a small fork in production.

2024-09-13 19:41 UTC, Timshel commented
> Hopefully both implementations remain largely compatible.

@fidelix yep some smaller scope feature were merged recently so I'll continue to contribute :).

@blackdex you did make a quick review again one month ago I believe and mentioned doing some test but after that not much news (which I of course understand since it's not a priority).

Additionally, I made an effort to split some features out of the PR which I believed could be merged first:
 - The playwright PR which had no feedback since May
 - The  JWT Refresh Token part had no comment since April outside some recent ones from someone which I don't believe is a maintainer of the project ? (not that anyone can't comment :)

Additionally, I had limited the scope of the PR so additional PR would have then been needed cf: https://github.com/Timshel/vaultwarden/?tab=readme-ov-file#additionnal-features

> I believe only a fraction would be willing to commit themselves to running a small fork in production.

@Jasper-Ben of course but as I did not believe that the PR was close to a merge and quite a bit of work is still needed. 
The fork is more like a last ditch attempt to gain some support to continue maintaining it, otherwise I will stop. And as I mentioned it's not final, if I manage to obtain some support I would reopen the PR.

Anyway this was the fourth PR on the subject even if the fork flop I might reopen it with minimal effort or maybe someone else will take up the flame :).

2024-09-13 19:50 UTC, sandervandegeijn commented
> @Jasper-Ben of course but as I did not believe that the PR was close to a merge and quite a bit of work is still needed.
> The fork is more like a last ditch attempt to gain some support to continue maintaining it, otherwise I will stop. And as I mentioned it's not final, if I manage to obtain some support I would reopen the PR.

It's a shame that you feel this way. To me it seems there was a ton of support. People were helping with testing different configs and the different BW clients. @BlackDex was looking at the code. The number of replies to this PR is one of the most I've ever seen on Github.

Maybe the glass is half full and we could prevent a fork of the project which is kind of a last resort measure. For more serious installations (I suspect there will be quite a few - SSO is especially useful with larger user bases) a one man fork is not the way to go. Too much risk.

2024-09-13 19:53 UTC, BlackDex commented
I'll say it again I'm very disappointed. 

I also have a PR open (for more then a year) which i probably need to start again which changes the database way of working, mostly because of this PR btw, to prevent a lot of changes in this PR.

It would also have been nice and open if you might have asked either me or @dani-garcia for any update, or tried to contact us via chat to discuss.

Hell, i even mentioned you in a PR regarding CSS which would be useful for this feature, and i mainly had this feature in mine when creating that. That should have indicated something.

I also understand how you might feel for something which is open for this long.

I'm not going to put any more words into this.

2024-09-13 19:54 UTC, yonas commented
I've created PR #4951 for anyone willing to take up where [Timshel](https://github.com/Timshel) left off.

Thanks for all your work on this @Timshel !

2024-09-13 20:41 UTC, dc911x commented
Nothing is lost, all things can be reverted, trust can be regained but action is required.
I've been following this PR for a few months too, sadly I can't contribute as this is out of my scope.

I'll keep following and hoping for this feature for myself en my organisation. Thanks to all who contributed, you have my deepest respect!

2024-09-13 20:43 UTC, doobry-systemli commented
@BlackDex I can understand your frustation. Given that you already spent some time into reviewing the PR and that it got tested extensively by lots of different people, how about the following: You do another review, re-open the PR again and merge it. That way @Timshel can see that their work is regarded and either them or any other person can continue to improve based on their impressive work in this PR.

2024-09-14 05:12 UTC, compgeniuses commented
I understand the frustrations that @Timshel might be having in maintinain, updating, and making tons of changes for over a year, and subsequently, the review process being abit slower.

I also understand @BlackDex perspective on the matter and the disappointment he might feel.

@Timshel has stated, he is very muhc willing to reopen and continue supproting this PR, if there is seen to be activity around getting the feature merged, if that is not the case, then why waste time continuing maintaining a pr, that may not see day of light soon.

We forget one thing, we are all human, and we have limited time on this earth, Have you guys considered this as a factor as well,

so i dont see why someone would hate on @Timshel or feel Bad for his actions.

There is a solution
Simply, Why dont the maintainers, commit to prioritising this PR, and alot more effort be put into it, Since its an extremely large PR, maintained by one person.
I am sure the community would also be willing to put in alot more effort in testing. 

At the current status, I think, it atleast deserves a beta release, once emrged, any other minor changes, could always be handled, as so far, its passed most of the use cases.

Someone from a university, have promised to do a certified PEntasting on Vaultwarden, if this PR gets merged, which i beleive is  a step in the right direction, and would significantly help.

IF alot of people have good will, Why let a good PR DIe.

Fact is: its not upto @Timshel it is actually upto the maintainers, he has already committed. so for the maintainers, if you are getting this done, so be it, if not, he is only being honest.

2024-09-14 05:32 UTC, BlackDex commented
@compgeniuses from my point of view that doesn't mean you need to close a PR and start your own fork, that will not get it merged sooner will it? 

It is up to @Timshel to open or close this specific PR, not to the maintainers. Also, large features like this need to be tested correctly to not break current installations. And there are other considerations here too.

A feature like this should be in testing first for a while. Since we were trying to fix issues with the new clients that had more prio from my perspective. Again, just bluntly closing this after knowingly it was being looked at just doesn't compute for me. A question would be the least that could have been done before closing. 

And also, he could have left the PR open and mentioned not going to work on this specific PR. But that is not what happened. I worked still have been disappointed non the less. 

Anyways, I'm still for adding this with or without this specific PR.

And to be clear, it's his right to fork and abandoned this PR. That is also opensource. It's just not how i envision it and make a product or tool better.

2024-09-14 05:35 UTC, ams0 commented
I, an humble lurker and user of Vaultwarden (and fierce proponent of it at all my clients), and deep admirer for the skills and commitment of both the OP and the mantainers of this project, hereby pledge to financially support both, no matter if this PR stays open or not, or another gets merged or not, via GitHub sponsorship.

May I suggest, as a side note, to move this repo to a new GitHub organization, aptly named Vaultwarden? It will make it look more like a community project rather than a personal one.

2024-09-14 05:49 UTC, compgeniuses commented
@ams0 there is already some works going on into moving these works into an organization. so thats work in progress.

@Timshel could you kindly re-open this PR, @BlackDex and the community would love to see this merged sooner.
Also, forking is not the best of ideas at the moment, for the specific feature. Kindly reconsider

lets all see how we can contribute towards getting this PR merged, and atleast get into beta, atleast

2024-09-14 07:41 UTC, Timshel commented
> if there is seen to be activity around getting the feature merged, if that is not the case, then why waste time continuing maintaining a pr, that may not see day of light soon.

That's not the case, I'm just basically asking for money :).

As those wondering if the PR can continue to cruise along with no change, Bitwarden is always changing last month I rewrote the patch to allow SSO org invitation to work and I expect the following issues will have to be fixed:
 
- The url parameter from the SSO redirection are kept and while not blocked it's king of ugly
- `openidconnect-rs` has started to release alpha version of the next release
- A Vaultwarden PR is in the work to add custom CSS (should allow to easily switch SSO button)
- Then there is the question of the `web-vault`, I was distributing two versions `button` and `override`, The button was the version closest to what I expect will be merged in Vaultwarden but usually peoples prefer the `override` so it would need a bit a discussion on what can be merged.

And there has been important change around collection in Bitwarden which should not impact this PR but might impact the other features I built on top.

As to those asking why fork, well I have been maintaining a fork for almost a year it's named [timshel/vaultwarden](https://github.com/Timshel/vaultwarden) it has its own web-vault build and docker distribution.

So outside of slapping a random icon and a bit of renaming supporting only the fork is less work.
I could have just silently stopped updating the PR but decided to try this ^^. 

Anyway will play around with the `v2024.8.3` built to check the issues around Organization change and other issues then at the end of September will look at my sponsor page and decide what to do next :).

2024-09-14 08:16 UTC, compgeniuses commented
yeah, the changes in vaultwarden that force a PR to also be changed and yet its not yet merged are the most painful things, considering the timelines...

2024-09-14 08:22 UTC, LePresidente commented
As someone who worked on this and got the PR going again, i'm not sure how i feel about (i want money so i'm going to stop working on the PR and close it approach and do my own thing) as it goes pretty much against the whole idea of Open Source. Yes i agree this PR has lagged on for to long, but rather pass on the torch if you don't want to work on it anymore.

2024-09-14 08:35 UTC, compgeniuses commented
@LePresidente its Open, so anyone can even take this one and continue working on it and get it merged.
If the person maintianing, who has been doing it for a while, is currently financially constrained, and yet we still expect him to continue working on it, how is he supposed to survive maintaining it.

He has spoken his mind. Maybe he may not say it, he is financlally constrained, and in that rgeards, needs support to continue working on it, if takes too long, it becomes more expensive, if its merged earlier, the costs are reduced.

2024-09-16 03:33 UTC, alexfornuto commented
I'm just another lurker who's been watching this PR with baited breath for many months. May I humbly suggest that the maintainers of Vaultwarden consider implementing a roadmap, or publicize one that may already exist privately?

It sounds like there was a communication breakdown, with the maintainers thinking this was getting close, and the PR author thinking something different. If the decisions around what work was being prioritized was as public as the code itself, this communication breakdown may be avoided in the future.

2024-09-16 08:37 UTC, tribut commented
I had been maintaining the PR that preceded @Timshel 's work and I want to again take the opportunity to thank everyone involved for the immense amount of time invested.

We have been running some version of this code in (limited) production with 50+ user for well over a year now. Even though the amount of time I can invest varies – which is why @Timshel thankfully took over in the first place – I will gladly make sure that something that can be merged stays available, if that becomes necessary.

@Timshel Not sure how to contact you directly, but if you are interested in some contract-based funding, please get in touch and I'll see what we can do.

2024-09-16 08:48 UTC, Timshel commented
@tribut I just sent you an email :).

2024-09-16 09:33 UTC, Timshel commented
To add some additional clarification on the why of the Fork; to be frank it's a bit of a carrot/stick scheme; while individual users might be happy to run the forked version, as was mentioned by some already running a one-man project in most enterprise or similar context won't be viable. So withholding maintaining the PR is kind of the stick.

I relalize that it could be ankward for the maintainers but I'll make clear the limits of what I'm offering, and of course encourage anyone willing to support my work to support Vaultwarden which work I certainly could not hope to replace.

Lastly, and I should have said this ealier but this in no way reflect on the work done by the maintainers of Vaultwarden, I'm thankful for the monumental amount of work they do maintaining it. And I apologize for the way I communicated and should have reached in advance.

Have a good day :).

2024-09-16 09:56 UTC, sandervandegeijn commented
@Timshel Although I think I understand, but if you needed funding to do the work, you could have just asked instead of forking the project. People already offered funding during the last year. From the university perspective: we prefer to support the project as a whole instead of a single developer. That's why we are contributing the penetration test to the project and offer testing effort to help out.

We have little Rust experience within the IT department, contributing code is difficult for us.

2024-09-17 17:53 UTC, KroniK907 commented
@Timshel 
Do you have a goal in mind for donations or progress that would re-open this PR? 

I've been lurking on this thread for months and was getting excited recently that this might be coming to the main branch soon. Personally, I feel like I'd rather be donating to all the vaultwarden devs to help improve all aspects including this one rather than just the OIDC feature. Overall I wish that I could donate to the project as a whole and support your work that way rather than having to balance my contributions across multiple devs for the same project. 

Generally I have no problem paying for new features that are really useful to me. However, I would like to ensure I'm paying to support the whole platform including the new feature, and not just those developing the feature.

2024-09-18 02:15 UTC, FlattusBlastus commented
@Timshel If you ever get this ball rolling again, I will be very very happy to donate!

2024-09-19 14:28 UTC, FreeMinded commented
@Timshel Thanks for your great work! We really need this feature and therefore I just sent you a significant amount as https://github.com/open-circle-ltd/ 
I mean to support getting this PR merged and not forked.

2024-09-19 15:04 UTC, Timshel commented
So I just reopened the PR, thanks @FreeMinded for the extremely generous donation.
Additionally, I will never close the PR again in such an abrupt manner, and I'm in discussion to ensure funding.

On the PR itself, before closing I had removed the `Playwright` tests to trim it down. @BlackDex would you prefer me to add it back ? Outside of tests one of its use was that it offered an easy way to run a test stack.
Additionally, should I reopen the parent PR I had made: https://github.com/dani-garcia/vaultwarden/pull/4371 ?

2024-09-25 07:47 UTC, Rainson12 commented
@BlackDex  anything happening here?

2024-09-25 08:14 UTC, BlackDex commented
@Rainson12 Not sure why you ask me, I'm not the PR maintainer ;).

@Timshel, regarding your questions.
In general i like the Playwright stuff (not sure i have enough Typescript skills tough), i also know it helps for validating this PR during your code process, so i would recommend to add it again.

We can also add a GitHub Actions run for this which is allowed to break for now for example, but that still might help.

I'm still for adding this PR to the next `testing` phase after a new release has been created. I just hope you will then still continue working on bugs and optimizing the code 😄.

2024-09-25 08:33 UTC, FreeMinded commented
> @Rainson12 Not sure why you ask me, I'm not the PR maintainer ;)

@BlackDex probably because you had not yet reacted to the reopening and the question from @Timshel ;)

I also tried to reach out to you directly but not sure I got the right email. Please contact me if you have a moment.

2024-09-25 09:24 UTC, Rainson12 commented
> > @Rainson12 Not sure why you ask me, I'm not the PR maintainer ;)
> 
> @BlackDex probably because you had not yet reacted to the reopening and the question from @Timshel ;)
> 
> I also tried to reach out to you directly but not sure I got the right email. Please contact me if you have a moment.

exactly this.

@BlackDex please also advice on whether https://github.com/dani-garcia/vaultwarden/pull/4371 should be reopened, I guess @Timshel is waiting for your feedback on this as well.

2024-09-25 10:12 UTC, BlackDex commented
> > > @Rainson12 Not sure why you ask me, I'm not the PR maintainer ;)
> > 
> > 
> > @BlackDex probably because you had not yet reacted to the reopening and the question from @Timshel ;)
> > I also tried to reach out to you directly but not sure I got the right email. Please contact me if you have a moment.
> 
> exactly this.
> 
> @BlackDex please also advice on whether #4371 should be reopened, I guess @Timshel is waiting for your feedback on this as well.

I think  i did that already.

2024-09-25 10:51 UTC, Timshel commented
@BlackDex ok will add the Playwright stuff back.

> I think i did that already.

I'm unsure where ?

2024-09-28 07:37 UTC, binaryben commented
> I think i did that already.

Might have missed it @BlackDex (very understandable as the second question sort of looks like it is just a continuation from the first), but #4371 is a different question to the Playwrite stuff. Unless you're referring to the general feedback of please revert the closings?

2024-10-03 11:22 UTC, FreeMinded commented
@BlackDex @Timshel could you give us status update on this, please.

2024-10-03 11:29 UTC, sandervandegeijn commented
Holding on to the pentest quote as well, got a scoping meeting on November 7th. I'm on holiday, so I've got time to help test stuff as well.

2024-10-03 11:31 UTC, BlackDex commented
Not sure what you expect from me here. I have already posted my comments.

Also, me saying that i like the Playwright stuff does kinda indicate that it is good to open it again, or leave it with this PR, which ever comes first. It might need some more attention or fine-tuning later on. But if we not make that a breaking check (as i already mentioned in my previous comment) then it can be used to test.

And, first we need to release a new stable version before we will merge this at all. Since it now looks like that the `testing` tagged image does solve the issues with the native clients, i do feel it would be safe to release a new stable version shortly, unless people come with a major issue.

2024-10-05 05:18 UTC, micolous commented on SSO.md
> +Otherwise you can disable the PKCE requirement with: `kanidm system oauth2 warning-insecure-client-disable-pkce CLIENT_NAME --name admin`.
Hi, Kanidm-adjacent person here:

While I welcome OIDC support in Vaultwarden, I ask that you please *do not* instruct users on how to disable security features in Kanidm if there is an easy way to make the client behave securely (which it seems like there is).

Kanidm putting `warning-insecure-client` in the command to disable PKCE is there to "encourage" vendors into doing the right thing - it's not intended as a get-out-of-gaol-free card. 😄 

I'm aware of many apps which *don't* implement PKCE, and every time they're documented in the Kanidm, they come with warning labels.

Per [OAuth 2.0 Security Best Current Practice draft as at 2024-06-03, Section 2.1.1](https://www.ietf.org/archive/id/draft-ietf-oauth-security-topics-29.html#section-2.1.1) (emphasis added, slightly abridged):

> Clients MUST prevent authorization code injection attacks (see [Section 4.5](https://www.ietf.org/archive/id/draft-ietf-oauth-security-topics-29.html#code_injection)) and misuse of authorization codes using one of the following options:
>
> * **For confidential clients, the use of PKCE [[RFC7636](https://www.ietf.org/archive/id/draft-ietf-oauth-security-topics-29.html#RFC7636)] is RECOMMENDED,** as it provides strong protection against misuse and injection of authorization codes as described in [Section 4.5.3.1](https://www.ietf.org/archive/id/draft-ietf-oauth-security-topics-29.html#pkce_as_injection_protection) and, as a side-effect, prevents CSRF even in the presence of strong attackers as described in [Section 4.7.1](https://www.ietf.org/archive/id/draft-ietf-oauth-security-topics-29.html#csrf_countermeasures).

[RFC 7636 makes non-PKCE fall-back *optional*](https://www.rfc-editor.org/rfc/rfc7636.html#section-5), and [PKCE is **required** in the current OAuth 2.1 draft](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-11.html#section-10-4.1.1).

I'd also suggest making PKCE the default for Vaultwarden. [PKCE was released 9 years ago](https://datatracker.ietf.org/doc/rfc7636/), so I'd hope that the IdPs which *don't* support it are in the minority... and they could use some "encouragement" too! 😄 

Thanks!

2024-10-05 06:17 UTC, micolous commented on SSO.md
> + - `SSO_SIGNUPS_MATCH_EMAIL`: On SSO Signup if a user with a matching email already exists make the association (default `true`)
Is there a way to migrate to SSO so that they are prompted for their master password, eg:

1. Users access Vaultwarden with a password.
2. Administrator sets up SSO, sets `SSO_ONLY = true`.
3. User logs in with SSO provider for the first time.
4. Vaultwarden detects an account with the same email address, they're prompted for their password to confirm linkage.

That would mean Vaultwarden no longer needs to trust the IdP's provided email address during migration.

2024-10-05 06:17 UTC, micolous commented on src/db/models/user.rs
>      pub const CLIENT_KDF_TYPE_DEFAULT: i32 = UserKdfType::Pbkdf2 as i32;
`User::delete()` should also delete associated `SsoUser` object(s).

2024-10-05 06:34 UTC, micolous commented on src/api/identity.rs
> +            if user.email != user_infos.email {
This should also check that `user_infos.email_verified == Some(true)`, so that Vaultwarden does not have an unverified email.

2024-10-05 08:13 UTC, Timshel commented on SSO.md
> +Otherwise you can disable the PKCE requirement with: `kanidm system oauth2 warning-insecure-client-disable-pkce CLIENT_NAME --name admin`.
Hey,
Having more visibility now I agree and will switch PKCE to true by default (I believe only Zitadel has issues with PKCE + client secret).

2024-10-05 08:27 UTC, Timshel commented on src/api/identity.rs
> +            if !user_infos.email_verified.unwrap_or(true) {
Issue with having set it top `true` is I have no idea of support through the different providers :(.
Will probably switch to using a config with a default set to `false`.

2024-10-05 08:31 UTC, Timshel commented on src/db/models/user.rs
> +                .map(|(user, sso_user)| { (user.from_db(), sso_user.from_db()) })
I believe the `email` is defined with `UNIQUE` in database, will have to check again.

2024-10-05 08:32 UTC, Timshel commented on src/db/models/user.rs
>      pub const CLIENT_KDF_TYPE_DEFAULT: i32 = UserKdfType::Pbkdf2 as i32;
Should be handled by the cascade constraint on the FK, will check again.

2024-10-05 08:37 UTC, Timshel commented on SSO.md
> + - `SSO_SIGNUPS_MATCH_EMAIL`: On SSO Signup if a user with a matching email already exists make the association (default `true`)
Only minor front-end modification are done over the Bitwarden web app at the moment, this would be quite extensive and brittle I believe.

I will note that while an account takeover this way allow gaining access to sensitive information, it does not grant access to the passwords since the Master password is still required.

2024-10-05 08:46 UTC, Timshel commented on src/db/models/user.rs
> +                .map(|(user, sso_user)| { (user.from_db(), sso_user.from_db()) })
There might be more than one results if the user is in the process of changing email and someone already reused it, but I believe that the SSO identifier match should return first. Will check again and probably add some comments.

2024-10-05 08:47 UTC, Timshel commented on src/api/identity.rs
> +            if user.email != user_infos.email {
Will check again but should only be here if the old email was verified and the user already associated.

As to the new email verified or not we cannot change it in Vaultwarden so we just sent an email for the user to start the change email flow in Vaultwarden which will verify the email.

2024-10-07 16:38 UTC, Timshel commented
@micolous thx for the review :).

 Releases should be building, :warning: they will include the following breaking change:
 
- `SSO_PKCE` is now on by default, if you are running Zitadel you'll probably need to set it to `false` since it's incompatible with `CLIENT_SECRET`
- On first SSO login if the provider does not return the email verification status log in will be blocked.
    Check the [documentation](https://github.com/Timshel/vaultwarden/blob/main/SSO.md#on-sso_allow_unknown_email_verification) for more details.

2024-10-08 05:34 UTC, micolous commented on src/api/identity.rs
> +            if user.email != user_infos.email {
The scenario I'm thinking of is:

1. User logs in with OIDC for the first time, and get migrated to an OIDC user with `sub`.
2. User changes email address in IdP.
3. IdP now reports the new email address as "unverified".
4. User logs in to Vaultwarden again. That hits this branch, which will update the email address on the account because it doesn't match the old one, but the IdP did not tell us it verified it.

This means the `SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION` check is only enforced at user sign-up time – you can always make an unverified email change with the IdP after an account is created and has a `sub`.

Also, I don't think this new email address is checked against `CONFIG.is_email_domain_allowed` anywhere for existing users... so it could be set to any domain you liked, even ones where verification may be possible.

2024-10-08 05:34 UTC, micolous commented on src/config.rs
> +        /// Allow email associtation |> Associate existing non-sso user based on email
Spelling: `associtation` -> `association`

2024-10-08 05:34 UTC, micolous commented on src/api/identity.rs
> +            err_silent!("Existing non SSO user with same email")
Error should be: "Existing SSO user with same email"

2024-10-08 05:34 UTC, micolous commented on SSO.md
> + - `SSO_SIGNUPS_MATCH_EMAIL`: On SSO Signup if a user with a matching email already exists make the association (default `true`)
OK, fair enough... within these constraints, I think this should be `false` by default:

* This is a migration mechanism for moving non-SSO accounts to SSO accounts, so isn't needed with a new install which has SSO available from day 1, and also isn't needed after everyone has logged in with SSO once (or some deadline has passed).
* Vaultwarden does not have any way to verify the master password when migrating to SSO, so one has to trust that the IdP's email is actually controlled by the account holder.
* [Matching on email address is not guaranteed to be stable](https://openid.net/specs/openid-connect-core-1_0.html#ClaimStability), so a non-SSO account is vulnerable to account takeover via SSO (regardless of verification status or other issues), similar to [this Mastodon security issue](https://github.com/mastodon/mastodon/security/advisories/GHSA-vm39-j3vx-pch3).
* Enabling this and `SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION` at the same time makes it even more vulnerable to account takeover; so having this default-enabled is undesirable.

It would be nice if there was some way that an administrator could take a list of users and their `sub` from the IdP and a list of users from Vaultwarden, and use that to build a mapping with known-good values.

That way there is no need for any matching at login time at all... users will log in with SSO and their account will already have the `sub` recorded.

This would also allow an administrator to handle the case if a user who has never logged in with SSO changes their email address before signing in with SSO.

2024-10-08 15:26 UTC, Timshel commented on src/api/identity.rs
> +            if user.email != user_infos.email {
> which will update the email address on the account because it doesn't match the old one

As I mentioned this branch does not update the email it only sends an email to notify the user.

2024-10-08 15:53 UTC, Timshel commented on SSO.md
> + - `SSO_SIGNUPS_MATCH_EMAIL`: On SSO Signup if a user with a matching email already exists make the association (default `true`)
I disagree with your assessment: 

> This is a migration mechanism for moving non-SSO accounts to SSO accounts, so isn't needed with a new install which has SSO available from day 1, and also isn't needed after everyone has logged in with SSO once (or some deadline has passed).

Absolutely true but at the same time it does nothing post migration or in a SSO only setting.
And when the admin add SSO login to an existing installation with non SSO user I believe this matching is expected.

> Because Vaultwarden does not have any way to verify the master password when migrating to SSO, one has to trust that the IdP's claim that the email address is actually controlled by the IdP account holder.

Yes, that's why by default signup will be refused if the email is not reported as verified and `SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION` is disabled.

> [Matching on email address is not guaranteed to be stable](https://openid.net/specs/openid-connect-core-1_0.html#ClaimStability), so a non-SSO account may be vulnerable to account takeover via SSO (regardless of verification status or other issues), similar to [this Mastodon security issue](https://github.com/mastodon/mastodon/security/advisories/GHSA-vm39-j3vx-pch3).

Yes I added the `sso_user` table to handle this issue. And this is why post signup the match is done on `iss` + `sub` and not the email.

> Enabling this and SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION at the same time makes it even more vulnerable to account takeover; so having this default-enabled is undesirable.

 `SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION` is not enabled by default. And the documentation on the setting recommend to disable `SSO_SIGNUPS_MATCH_EMAIL` to close the risk of account takeover.
 Of course documentation might be ignored, and I could add a warning during server startup, but I doubt it would be more effective than the documentation.

2024-10-17 16:40 UTC, titouan-joseph commented
> @micolous thx for the review :).
> 
>  Releases should be building, :warning: they will include the following breaking change:
>  
> - `SSO_PKCE` is now on by default, if you are running Zitadel you'll probably need to set it to `false` since it's incompatible with `CLIENT_SECRET`
> - On first SSO login if the provider does not return the email verification status log in will be blocked.
>     Check the [documentation](https://github.com/Timshel/vaultwarden/blob/main/SSO.md#on-sso_allow_unknown_email_verification) for more details.


Hi @Timshel,

I'm amazed by the fact that we should disabled PKCE with zitadel, they implemented the PKCE flow. 
I have tried with grafana and the PKCE configuration and it was working properly.

2024-10-17 18:23 UTC, Timshel commented
@titouan-joseph I have not tested again recently but last time I checked using PKCE was not supported when using client secret, the issue on the subject is still open: https://github.com/zitadel/zitadel/issues/7110.

Since the client is server side it's written with the expectation to use client id and secret. Since pkce is not supported in this case the documentation mention that you might need to disable it. 

I'm aware that it's/was possible to run with PKCE activated and with an empty secret, but it's not really intended/supported, so it will not be mentioned in the doc.

2024-10-24 05:18 UTC, Felitendo commented
Is it possible to migrate a normal Account into a SSO account?

2024-11-06 23:45 UTC, derSoerrn95 commented
What's missing for it to be accepted?

2024-11-11 14:48 UTC, titouan-joseph commented
> @titouan-joseph I have not tested again recently but last time I checked using PKCE was not supported when using client secret, the issue on the subject is still open: [zitadel/zitadel#7110](https://github.com/zitadel/zitadel/issues/7110).
> 
> Since the client is server side it's written with the expectation to use client id and secret. Since pkce is not supported in this case the documentation mention that you might need to disable it.
> 
> I'm aware that it's/was possible to run with PKCE activated and with an empty secret, but it's not really intended/supported, so it will not be mentioned in the doc.

Ok ok, thank you for your response.

I see, yes if it's backend side, we don't have to use PKCE flow, right.  

From what I've seen, with zitadel and integrations with other tools, it's common to set a secret client to null.

2024-11-11 14:54 UTC, sandervandegeijn commented
We will get the final quote for the pentest this week or next week. We have adjusted the scope because of another pentest done recently on Vaultwarden. Is there any timeline for the merge I can communicate to the pentest partner?

2024-11-11 15:02 UTC, BlackDex commented
I think we have tackled the sync issues with the clients 🤞🏻 which makes it more likely to have this merged soon.

It also depends on @Timshel if he thinks it's fine as-is currently and able to act upon issues linked to this.
Then we can have this in testing for a while.

2024-11-11 15:58 UTC, Timshel commented
> It also depends on @Timshel if he thinks it's fine as-is currently and able to act upon issues linked to this.

@BlackDex  It is and I will.

2024-11-11 20:50 UTC, polymo1 commented
> Slightly-OT: The other pentest of Vaultwarden, is it the one from BSI?
> 
> > [📄 Ergebnisbericht - Vaultwarden-Passwortmanager.pdf](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/Studien/P486-Codeanalyse/Vaultwarden-Passwortmanager.pdf?__blob=publicationFile&v=5) (PDF, German), via [BSI - Presse - BSI untersucht Open Source Software KeePass und Vaultwarden](https://www.bsi.bund.de/DE/Service-Navi/Presse/Alle-Meldungen-News/Meldungen/Codeanalyse-KeePass-Vaultwarden_241014.html), 2024-10-14

Is there an English copy to this?

2024-11-19 14:01 UTC, Talkabout commented
Hi guys,

I am also very interested in getting this feature. Hope you can progress with it soon! I assume that it will take some time for the tests to complete before we will see it in a release? Any time frame for that?

Thanks!

2024-11-19 14:27 UTC, BlackDex commented
@Timshel could see if you can use the new Dynamic CSS feature for this PR?
Also, if i'm correct, you need some additional changes on the web-vault side to? If so, there is no PR for that yet.
If you do not need any additional changes, you can use https://github.com/dani-garcia/bw_web_builds/pull/180 to test/verify the Dynamic CSS.

2024-11-19 15:12 UTC, Timshel commented
@BlackDex Yes I intend to switch to it, had a quick look but was waiting for https://github.com/dani-garcia/bw_web_builds/pull/180 to be released.

2024-11-19 15:44 UTC, BlackDex commented
Well, if it is up to me, it's either i try to fix v2024.10.5 to work and have the dynamic-css in there.
If that takes too long or seems rather more difficult, then i tend to go to merge the v2024.6.2 update.

Also, not sure if v2024.10.5 is workable for SSO without too much changes?

2024-11-26 14:57 UTC, Timshel commented
Hey,

Just wanted to mention that discussion for some funding fell through.
As I commented recently I will continue to maintain the PR, but it does mean this will not be a priority (docker distribution might lag behind unless the Vaultwarden release includes some CVE fixes).

Lastly thank you for those who choose to support my work ;).

2024-11-26 15:01 UTC, sandervandegeijn commented
A PR is not meant to be maintained, just to get something done and then merged. What would you need to get this merged?

We can't run a fork of one developer as a production instance, too risky.

2024-11-26 15:47 UTC, Timshel commented
Just received an extremely generous one time sponsor (which I won't mention since I can't confirm with them that it's ok); Thank you :).

This means that:
- I'll build a `web-vault` based on https://github.com/dani-garcia/bw_web_builds/pull/180, test the new CSS templates and release it in `testing`.
- Test a `web-vault` based on top of  Bitwarden `v2024.11.2`
- Start testing the integration of `openidconnect-rs` `4.0.0-rc.1`

2024-11-26 16:12 UTC, BlackDex commented
> > A PR is not meant to be maintained, just to get something done and then merged.
> 
> @sandervandegeijn I understand your point, and I agree that a PR isn't typically meant to be "maintained" indefinitely. However, I'd like to point out that @Timshel opened this PR on June 29, 2023, and the maintainers' detailed feedback or a thorough code review is still pending.

I think i have done some detailed testing and reviewing, but ok not here to debate this (again).

Also, I did asked here https://github.com/dani-garcia/vaultwarden/pull/3899#issuecomment-2486073649 if he could check the web-vault part, since there is no PR at all linked to this PR, and without that merging this would be useless, that is not something you can blame on the maintainers of this project.

And, it's not the look for excuses, but i do hoop people see there are not a lot of maintainers for this project, so if someone wants to help us out during there free time, please fork, code and share!

And the past few months there were CVE's reported, and I do prioritize those over any PR.
Same goes for client issues like with the new native mobile clients (which seem to still be happening sometimes).

Merging this PR while those issues are still there doesn't make it easier to troubleshoot and debug those reported issues. As for some strange reason this PR could have caused some strange side-effect somewhere.

2024-11-26 20:42 UTC, rizlas commented
@sandervandegeijn this pentesting thing, is now like politician saying they will reduce taxes during election time. 😅 Sorry but I don't believe it anymore.

Anyway, I think that both @Timshel and @BlackDex were very clear on how this PR will proceed in the previous comments. I was an early adopter of Timshel's fork and I'm still using it. In the first phases I mainly contributed with feedback and improving suggestions and, as of today, it is almost one year that my deploy is working flawlessly. During the all year I've never post a comment like "pls merge", that's useless, so why people keeps doing it? Use the fork if you really need this or pay BW (or others) if you can't. For example, as a non-profit we couldn't afford any paid solution and we took a gamble with Timshel fork, and it was worth it!

I'm grateful that someone is contributing with money, keeping the whole thing going. 🙏🏻 

Thank you again @Timshel for your fork and @BlackDex for VW.

2024-11-28 18:25 UTC, rudiservo commented
@rizlas pentesting is important, recently some stuff was found in vaultwarden, not very bad stuff but still something that improves the safety and security of all that use the software.
Let's not forget the XZ project fiasco that was or was not state sponsored.

I probably have more sleepiness nights with cybersecurity than having a newborn baby, I miss programming.

Nonetheless I know the issue of accepting a PR this big, Rust is a complex language, yes adding functionality should be easier in one hand but still be safe on the other, maybe the structure needs to be revised, but that is the thing with software development, stuff happens.

Having an OpenSource project like this is fantastic on it's own, having one with so many eyes on it is amazing.

So let's get together and keep communicating so we can get this thing merge.

2024-12-09 22:57 UTC, TheRedCyclops commented
Judging by the release notes it seems that the CVEs have now been fixed, I hope this can be merged for the upcoming release.

2024-12-10 02:17 UTC, micolous commented
@rizlas @TheRedCyclops @rudiservo Please do not comment on PRs unless you are providing reviews or actively contributing to them, as it creates noise for those who are following them. If you wish to show your support for things like this, use reaction emoji on the PR.

2024-12-19 15:22 UTC, oe3gwu commented
I have a naive stupid question. Would it be possible to add a oauth2-proxy before vaultwarden? The proxy could pass for example "X-Forwarded-Email" to vaultwarden. Like it was in the past with open-webui or so.

2024-12-26 19:39 UTC, brunoscota commented
please please please make this real!! Im waiting this for so looong

2024-12-26 20:49 UTC, alfonsrv commented
The real question is if it's actual SSO like with Bitwarden's Key Connector or SSO that still requires a master password like on @Timshel's forked repo

2024-12-26 21:48 UTC, Arbel-arad commented
> The real question is if it's actual SSO like with Bitwarden's Key Connector or SSO that still requires a master password like on @Timshel's forked repo

sign-on and decryption should be independently keyed in my opinion, but maybe there could be another option to link them?

in any case it should be possible to 'not trust' the SSO service.

2024-12-26 22:21 UTC, alfonsrv commented
It's actually not about opinions but the way the Bitwarden web frontend handles decryption without having to maintain a separate fork – this has been brought up multiple times when people tried to implement / asked for SSO support previously; e.g. via LDAP

Actually reading the very [first comment](https://github.com/dani-garcia/vaultwarden/pull/3899#issue-1900628855) of this PR it clearly states the master password will still be required – just in case someone was nagging for a merge because they just read the headline;

> A master password is still required and not controlled by the SSO (depending of your point of view this might be a feature ;). A key connector to remove this could be added but is not planned in this PR.

2024-12-27 00:19 UTC, Timshel commented
I'll add that when I created the issue I was not aware that the [license](https://github.com/bitwarden/key-connector/blob/main/LICENSE.txt) of Bitwarden key connector is quite restrictive. 
So I mentioned it was not planned but in fact it's unlikely that anyone will ever work on it since :

> 2.1 Commercial Module License. Subject to Your compliance with this Agreement, Bitwarden hereby grants to You a limited, non-exclusive, non-transferable, royalty-free license to use the Commercial Modules for the sole purposes of internal development and internal testing, and only in a non-production environment.

2024-12-29 15:27 UTC, stefan0xC requested changes
Well, here's my review of this PR. While I have not found any glaring issues from reading the code I was wondering about some stuff. Some of which I think should be done differently (especially `confirm_user_invitation`)...

I have not looked at the playwright tests again. I think it's okay to merge them as is and improve them once they are merged.

2024-12-30 16:40 UTC, Timshel commented on src/db/models/organization.rs
> +        pub invited_by_email: Option<String>,
Shouldn't be in this PR, will remove it.
It's only used now in the Organization auto invitation.

2024-12-30 16:49 UTC, Timshel commented on src/db/models/organization.rs
> +    pub async fn confirm_user_invitations(user_uuid: &str, conn: &mut DbConn) -> EmptyResult {
Wrote-it to avoid having to run two queries with:

```rust
for user_org in UserOrganization::find_invited_by_user(&user.uuid, &mut conn).await.iter_mut() {
    user_org.status = UserOrgStatus::Accepted as i32;
    user_org.save(&mut conn).await?;
}
```

And it's now used in the sso login too when mail are disabled.

2024-12-30 16:57 UTC, Timshel commented on src/api/core/accounts.rs
> +    let routes: Option<Vec<String>> = Some(routes.iter().map(ToString::to_string).collect());
I think I will just remove it and define it in the `set_password` call.

2024-12-30 17:04 UTC, Timshel commented on src/api/identity.rs
> +    let user_data = match SsoUser::find_by_identifier_or_email(&user_infos.identifier, &user_infos.email, conn).await {
The problem is that the email address returned by the provider might not be the email stored by Vaultwarden.
In that case we want to find the correct user and email him a reminder to update.

Additionally, if `SSO_SIGNUPS_MATCH_EMAIL` is set to `false` we want to only consider the computed `identifier`.

2024-12-30 17:15 UTC, Timshel commented on src/api/identity.rs
> +        Some((user, Some(sso_user))) if sso_user.identifier != user_infos.identifier => {
We return the user matching either the `email` or the `identifier`.

If someone change his email but has not yet updated it in Vaultwarden then someone else could use the old email with the provider and try to usurp the Vaultwarden account.

Storing and using the `identifier` is part of the mitigation to prevent this sort of [cve](https://github.com/mastodon/mastodon/security/advisories/GHSA-vm39-j3vx-pch3).

2024-12-30 17:25 UTC, Timshel commented on src/db/models/user.rs
> +    pub async fn find_by_identifier_or_email(
We can I wrote it initially to prevent having to make two calls.
But later-on modified it to ensure that the identifier result is always first. 

Since we always want to match on the `identifier` first and then only on the email if `SSO_SIGNUPS_MATCH_EMAIL` is activated it probably make sense to break it.

2024-12-30 17:29 UTC, Timshel commented on src/api/core/accounts.rs
> +      "MasterPasswordPolicy": {}, // Required for SSO login with mobile apps
This would make the `SSO_MASTER_PASSWORD_POLICY` not specific to SSO, but I think it would make sense since the policy is global.

Would probably rename the setting to `DEFAULT_MASTER_PASSWORD_POLICY`, might open a separate PR for it.

2024-12-30 17:59 UTC, stefan0xC commented on src/api/identity.rs
> +        Some((user, Some(sso_user))) if sso_user.identifier != user_infos.identifier => {
Get User by email, get SsoUser by identifier. If the `user_uuid` matches or both are `None` everything is fine. If not there are three cases:

a) an SsoUser for the identifier does not yet exist <- depends whether we allow it (`SSO_SIGNUPS_MATCH_EMAIL`).
b) a User account for the mail does not yet exist (`None`) but an SsoUser exists (the `user_uuid` should point to a different existing User). <- User should change their mail back to match the Sso provided one.
c) a User account for the mail exists and SsoUser exists but the `user_uuid` points to a different User.

If I just compare by email and identifier I don't think I'd catch the third case, I'd get the User per mail and join it with the SsoUser by identifier? Your check would not tell me I've got the wrong User, I think.

2024-12-30 18:00 UTC, stefan0xC commented on src/api/identity.rs
> +    let user_data = match SsoUser::find_by_identifier_or_email(&user_infos.identifier, &user_infos.email, conn).await {
>  In that case we want to find the correct user and email him a reminder to update.

That case has to be dealt with, yes. But I have to compare the user_uuid to find out if that's the case, don't I?

2024-12-30 18:34 UTC, Timshel commented on src/api/identity.rs
> +        Some((user, Some(sso_user))) if sso_user.identifier != user_infos.identifier => {
I'm unsure why you mention the `user_uuid`, in the return type the `<User, Option<SsoUser>>` always share the same `user_uuid` the join is done in database.
If the union find a match on the email and on the identifier then only the identifier match is returned.

So then the 3 case left are:
 - I have a user without any SSO association -> do we allow the association or not ?
 - I have a user
     - If it matches the identifier: we found the correct user
     - If the identifier does not match, then it means it's new user (no identifier match) but the email is already used so we will block login.

I think it's clear that what I wrote initially as a small optimization to make only one query has become way too complicated especially since it relies on part of the check being done in the db.

As such as I mentioned in the other comment I will rewrite this by always searching by identifier first and fetch by email only if it's missing.

Since it will be missing only during onboarding it means for most login it will have no impact and the code logic should be cleaner.

2024-12-30 19:24 UTC, stefan0xC commented on src/api/identity.rs
> +        Some((user, Some(sso_user))) if sso_user.identifier != user_infos.identifier => {
Thanks for the explanation. I think I understand your optimization a bit but I still think you have a flaw in your logic: because if "only the identifier match is returned" and you want to differentiate between the cases you cannot check if the identifier is equal but if the email is equal, since the identifier match has been returned.

With a simplified database (where users only has uuid and email and sso_users has only user_uuid and identifier). If I have a user 1 with email A and associated Identifier X and a second user 2 with email B and no associated identifier, your union might return me the following:
1|A|1|X
2|B||

So I'd need to check if A==B to determine whether the User relation matches.

2024-12-30 19:36 UTC, Timshel commented on src/api/identity.rs
> +        Some((user, Some(sso_user))) if sso_user.identifier != user_infos.identifier => {
Not that's really important but in your example if you query with : 
  - identifier X email A  -> return `1|A|1|X` -> login ok
  - identifier X email B -> return `1|A|1|X`  -> login ok (email sent to notify that email has changed).
  - identifier Y email A -> return `1|A|1|X`  -> login fail identifier mismatch
  - identifier Y email B -> 2|B|| -> login ok if association is allowed

2025-01-02 18:26 UTC, Timshel commented
@stefan0xC pushed some fixes (in separate commits for now). Should I close the conversion where we were in agreement, or should I let you do it ?

:warning:  Heads up for those building their own release on top of this branch, a migration was removed, you will need to manually run the down part to return to a clean state:

```sql
ALTER TABLE users_organizations DROP COLUMN invited_by_email;
```

The added column had a default value so even an unmodified Vaultwarden should run without issue but better to return to a clean state.

2025-01-02 18:28 UTC, Timshel commented on src/api/identity.rs
> +        Some((user, Some(sso_user))) if sso_user.identifier != user_infos.identifier => {
Removed the `find_by_identifier_or_email` it's a bit better.

2025-01-02 18:29 UTC, stefan0xC commented on src/api/identity.rs
> +        Some((user, Some(sso_user))) if sso_user.identifier != user_infos.identifier => {
Thanks

2025-01-03 16:19 UTC, Timshel commented on src/api/core/accounts.rs
> +      "MasterPasswordPolicy": {}, // Required for SSO login with mobile apps
In my previous comment I made the supposition it would apply to login without sso since the method existed before this PR, but I'm not sure when it's called outside of the SSO flow.

Additionally, when testing it with SSO the `enforceOnLogin` part does not appear to work since the returned policy appeared to be [ignored](https://github.com/bitwarden/clients/blob/c07454342d020bb8b9c775dbabf3dbad89eb047e/libs/common/src/auth/services/user-verification/user-verification.service.ts#L154).

Still I decided to return the defined policy but only when the SSO is activated.

2025-01-03 16:24 UTC, Timshel commented
@stefan0xC made an additional modification around signups to disable it if the `SSO_ONLY` setting is activated.
Otherwise, a user would be able to create an account but may not be able to log with it.

2025-01-07 19:05 UTC, Timshel commented on src/db/models/organization.rs
> +    pub async fn confirm_user_invitations(user_uuid: &str, conn: &mut DbConn) -> EmptyResult {
Since it's used in two different place I would tend to keep the function. 
Would you prefer that I rewrite the function with find/save ?

2025-01-08 16:03 UTC, Timshel commented
@stefan0xC updated the playwright tests to work with `2024.12.0` web-vault but since you mentioned you had not looked at the tests again I squashed the modifications in the commit adding the tests.
And I closed the discussions where I believe we were in agreement.

For those wanting to test the web-vault in version `2024.12.0` , `testing` should be available in `timshel/vaultwarden` once the build is finished.

2025-01-09 17:04 UTC, Timshel commented
Updated to include `2025.1.0`  based `web-vault`.

2025-01-09 18:13 UTC, stefan0xC commented on src/auth.rs
> +}
I mean, wouldn't it suffice to implement those functions on `AuthMethod` without the trait? Having this as a trait seems like a useless abstraction to me, when this should just work as well :thinking: 
```
impl AuthMethod {
    pub fn scope(&self) -> String {
        match self {
            AuthMethod::OrgApiKey => "api.organization".to_string(),
            AuthMethod::Password => "api offline_access".to_string(),
            AuthMethod::Sso => "api offline_access".to_string(),
            AuthMethod::UserApiKey => "api".to_string(),
        }
    }

    pub fn scope_vec(&self) -> Vec<String> {
        self.scope().split_whitespace().map(str::to_string).collect()
    }

    pub fn check_scope(&self, scope: Option<&String>) -> ApiResult<String> {
        let method_scope = self.scope();
        match scope {
            None => err!("Missing scope"),
            Some(scope) if scope == &method_scope => Ok(method_scope),
            Some(scope) => err!(format!("Scope ({scope}) not supported")),
        }
    }
}
```

2025-01-09 18:30 UTC, stefan0xC commented on src/db/models/organization.rs
> +    pub async fn confirm_user_invitations(user_uuid: &str, conn: &mut DbConn) -> EmptyResult {
I am not sure if this matters in this case as I think this function is specific enough that it does more than setting the `MembershipStatus` so this should be fine. I mean, if we were to use it in another place we might have to review if it's use is okay in that context, e.g. if it's also followed by a https://github.com/dani-garcia/vaultwarden/blob/a5ce1c3c6b5c80b0842832d4980c4c4a0ba5c182/src/api/identity.rs#L259 eventually https://github.com/dani-garcia/vaultwarden/blob/a5ce1c3c6b5c80b0842832d4980c4c4a0ba5c182/src/api/core/accounts.rs#L245
So I don't mind it as much.

2025-01-10 17:01 UTC, Timshel commented on src/db/models/organization.rs
> +    pub async fn confirm_user_invitations(user_uuid: &str, conn: &mut DbConn) -> EmptyResult {
Ok, modified it to check that a row was updated.

2025-01-12 22:16 UTC, gjuuz commented
So I also need to enter the master password when signing in with this SSO?

2025-01-13 04:46 UTC, zeddD1abl0 commented
> So I also need to enter the master password when signing in with this SSO?

Yep. Unless you have another mechanism, this is just another layer of security over the top of the Master Password.

2025-01-13 06:29 UTC, gjuuz commented
> > So I also need to enter the master password when signing in with this SSO?
> 
> 
> 
> Yep. Unless you have another mechanism, this is just another layer of security over the top of the Master Password.

Thanks but the i don't get the benefit of this. Security is always important but in case you provide secure authentication within the sso IDP the master password is not needed anymore to be honest.
Would be great if this is possible any day.

2025-01-13 06:41 UTC, bmunro-peralex commented
I'll relook at the keyconnector stuff i did when i was working on this, though there is no point looking at it till this is merged

2025-01-13 07:12 UTC, rossigee commented
> Thanks but the i don't get the benefit of this.

The benefit is that SSO becomes a kind of 2FA, which is useful in the event that someone is somehow able to obtain your master passphrase.

For example, my SSO service is configured to require hardware keys. If I understand it correctly, this feature means I should now be able to configure VaultWarden to ensure that I have not only my master passphrase (needed to unlock the vault) but also another stronger form of authentication too.

A key connector would improve convenience, but likely lower overall security. Whether you choose to use one or not would depend on your risk appetite.

2025-01-13 07:25 UTC, gjuuz commented
> I'll relook at the keyconnector stuff i did when i was working on this, though there is no point looking at it till this is merged

That would be great !

2025-01-13 07:34 UTC, nlseven commented
> > kind of 2FA, which is useful in the event that someone is somehow able to obtain your master passphrase.
> 
> Yea but 2FA is also available within Vaultwarden itself so why implementing a IDP ?
> 
> Dont understand me wrong its definetly more secure using this extra layer but in larger organizations its not really helpful.

It simply means that instead of an org user needing three passwords (regular account used for corp services, Vaultwarden account password for syncing, and Vaultwarden master password) it brings it down to just the regular corp account and a master password.

Importantly this brings it closer to feature-parity with Bitwarden.

2025-01-13 07:35 UTC, zeddD1abl0 commented
> Dont understand me wrong its definetly more secure using this extra layer but in larger organizations its not really helpful.

I'm not sure what level of "larger organisation" you're specifically talking about, but from my perspective, this gives me 3 controls I can add with relative ease:

1) Enforce login for specific users from specific locations. IDP with country checks? Done.
2) Enforce allowed groups. If the user isn't part of an allowed group their access is gone regardless of their Master Password
3) User decommissioning. If the user can't authenticate to the IDP, they can't log in. Doesn't matter if they know their password or not.

I will admit, the full picture (IDP providing master password) is pretty awesome, but even in its current format, this will provide some very useful tooling for me.

2025-01-13 07:35 UTC, micolous commented
**Friendly reminder (again): there are 101 people watching this PR, and every comment emails everyone. The same questions and comments are coming up repeatedly, which is drowning out status updates.**

This PR implements SSO the same way BitWarden does, with all the same functional constraints. If you have questions about how that works, [you're better off asking BitWarden](https://github.com/bitwarden).

If you have questions or comments about this functionality as it relates to **Vaultwarden**, [please open a discussion](https://github.com/dani-garcia/vaultwarden/discussions) - it's makes it much easier to find your questions, and means people following this PR can focus on status updates.

If you have questions about how SSO works, contact your identity provider's support or sales engineering team.

Thank you. ❤️

2025-01-15 16:38 UTC, Timshel commented
@stefan0xC had another look at `Membership::confirm_user_invitations` and I'm a bit unsure why this in fact exists ?
I believe for admin invitation there is no membership in database and for organization invitation it should be handled in `Organizations::confirm_invite` ?
Additionally, it seems with the new `OrganizationId` change the guard raise an error for an invalid `id` such as `_` used in the admin invitation ?

Different subject for those using Entra I don't remember if there were some trouble with the `email_verified` claim. Could you give some feedback/help in https://github.com/Timshel/vaultwarden/issues/85#issuecomment-2593285276

2025-01-16 17:51 UTC, stefan0xC requested changes
>  Additionally, it seems with the new `OrganizationId` change the guard raise an error for an invalid id such as `_` used in the admin invitation ?

Ah, I was wondering about your code why you've disabled the guard. 
Just tested it and the error is more pronounced (very ugly) but registering an account still seems to work. But yeah, we will have to check if we could make it less ugly. (Maybe by using a fake UUID instead of `_`)

2025-01-16 17:57 UTC, Timshel commented on src/api/core/organizations.rs
> +fn get_master_password_policy(org_id: &str, _headers: Headers) -> JsonResult {
I should be able to inject earlier, will test it.

2025-02-05 19:57 UTC, Timshel commented
Hey,
Upgraded `openidconnect` to `4.0.0`, for now it will be available only in `testing` :).

2025-02-06 17:03 UTC, isJustCat approved these changes

2025-02-10 14:42 UTC, rokx commented
I'm thrilled to see this happen.

2025-02-11 21:23 UTC, Timshel commented
So I tested integrating the new `web-v2025.1.2` web-vault and the org invitation was once again broken for new users.
Decided to stop patching the client and more closely follow the official logic and accept the invitation when setting the master password.

- As such had to bring back the `invited_by_email` in the `Membership` since we only have the org Identifier to resolve the invitation and not all the claims.
- A side effect of the logic is that a user will be enrolled in an invited organization on account creation even when not using the link (it could be changed, but it means the correct policies are used).

:warning:  So between this and the `openidconnect` upgrade, proceed with caution :). :warning:
`1.33.2-1` docker image should be ready in ~1h.

2025-02-14 14:29 UTC, muhammedsoner commented
How long do you anticipate this process will take to be completed?

2025-02-15 11:28 UTC, binaryben commented
Hey all, I am sorry to add another message to the already way too noisy comment section. Could this please be locked to existing collaborators though? Like everyone else, I am very excited for this to land and very grateful to the work done by all (specific shoutout to Timshel for carrying this so wonderfully in it's current attempt). And like almost everyone else, I am also slowly becoming frustrated by the notifications that are not actual, relevant updates.

2025-02-15 13:14 UTC, BlackDex commented
@binaryben That is probably a good idea. If I'm correct @Timshel can still comment here. And i also think people can still review the PR if they want (And please do :) ).

From my point of view i want to merge this after a next patch release to at least have some small other items fixed before we merge this large PR.

I also want to make some other changes, but i only want to start on those after this PR is merged, else @Timshel needs to make a lot of changes too, which i think are not in the scope of this PR just because i want to optimize some code which has large impact.

2025-02-17 15:28 UTC, Timshel commented
> I also want to make some other changes, but i only want to start on those after this PR is merged, else @Timshel needs to make a lot of changes too, which i think are not in the scope of this PR

Thank you ^^, at the same time if there is some issue/PR where the changes are described I may be able to make some modification to prepare for those :).

2025-02-17 18:57 UTC, BlackDex commented
> > I also want to make some other changes, but i only want to start on those after this PR is merged, else @Timshel needs to make a lot of changes too, which i think are not in the scope of this PR
> 
> Thank you ^^, at the same time if there is some issue/PR where the changes are described I may be able to make some modification to prepare for those :).

Nea, it's a combi deal sorta. You can't prepare stuff up-front.

2025-02-25 11:39 UTC, astrakid commented
will this PR be merged in the upcoming days or weeks?

2025-03-06 10:59 UTC, boscorelly commented
hi,
any news about this ?

2025-03-28 10:22 UTC, Timshel commented
Hey
I'm thinking on improving user organization role mapping.
For those interested, opened a discussion on some possible solutions: https://github.com/Timshel/OIDCWarden/discussions/24 
(Opened in `OIDCWarden` but this would apply to both distribution).

2025-04-03 13:07 UTC, Timshel commented
Hey,
Some small modifications/improvements:
 - Added a `sso-identifier` column to the admin user table and the ability to delete it.
 - Mirror [Bitwarden](https://bitwarden.com/blog/configuring-bitwarden-clients-for-offline-access/#staying-logged-in-to-browser-extension-desktop-and-mobile-clients) 90 days session validity (for non sso login or when `SSO_AUTH_ONLY_NOT_SESSION=true`).

2025-05-08 08:11 UTC, hamza86 commented
is there any plan to merge this PR ?

2025-05-23 07:22 UTC, MrCriseas commented
Any Update here?

2025-05-26 20:11 UTC, dani-garcia commented on .env.template
> +## Controls whether users can login using an OpenID Connect identity provider
We should put an empty line between the end of one option and the next one, to make this more readable

2025-05-26 20:13 UTC, dani-garcia commented on SSO.md
> ++openidconnect = { version = "3.5.0", features = ["accept-rfc3339-timestamps"] }
It looks like this PR already adds some features to Vaultwarden to enable these, so I assume patching the Cargo.toml file is not needed anymore?

2025-05-26 20:35 UTC, dani-garcia commented on src/db/models/event.rs
> +    OrganizationUserUnlinkedSso = 1505, // Not supported
The comment should be removed as well

2025-05-26 20:38 UTC, dani-garcia commented on src/config.rs
> +fn internal_sso_issuer_url(sso_authority: &String) -> Result<openidconnect::IssuerUrl, Error> {
These functions should probably all start with `check_` or `validate_` to make it clear what they're doing

2025-05-28 13:21 UTC, boscorelly commented
hi,

@dani-garcia any update about this ? you released a new version 2 days ago, without this PR.
It's a 2 years old PR, without anything done about it.
We are hundreds needing it.

can you give us a word ?

2025-05-28 13:28 UTC, Cameo007 commented
> hi,
> 
> @dani-garcia any update about this ? you released a new version 2 days ago, without this PR. It's a 2 years old PR, without anything done about it. We are hundreds needing it.
> 
> can you give us a word ?

As you might see there were several commits the last time and "We are hundreds needing it" is not very nice against the people working on this PR probably without getting directly paid for it.
I also can't wait to see this feature released but either wait or do something!

2025-05-28 13:29 UTC, rallisf1 commented
Please lock the comments for contributors only.

Having people asking for feedback every few days only distracts everyone. As all PRs, this will be merged when it's ready and you'll get a notification about it.

2025-05-28 13:33 UTC, rafalkrupinski commented
> either wait or do something!

I there was anything to be done, I'm sure there are enough hands here eager to help.

For anyone who wants to use the patched version, Timshell actually maintains a working docker image.

2025-05-28 13:41 UTC, matbgn commented
> As you might see there were several commits the last time and "We are hundreds needing it" is not very nice against the people working on this PR probably without getting directly paid for it.
> I also can't wait to see this feature released but either wait or do something!

I'm sorry, but for example, I proposed a concrete action back on February 6:
https://github.com/dani-garcia/vaultwarden/pull/3899#issuecomment-2640462432 — and it received no response. Seeing a release go out afterward, without any follow-up or acknowledgment, is frankly quite frustrating.

Being in an online environment doesn’t mean we should forgo basic respect and consideration for the people we’re working with. From my personal perspective, the way this has been handled feels disrespectful—particularly towards the work @Timshel has contributed—and reflects poorly on both @BlackDex and @dani-garcia in this context.

Definitely it sounds like it's time for a community split here...

2025-05-28 13:42 UTC, helmut72 commented
Maybe a short sentence to explain why it's still not merged would be better than escalation. We read "sucessful checks" last weeks and wonder why it's not merged.

2025-05-28 14:29 UTC, boscorelly commented
@helmut72 your last response is really strange, because it is What I asked.And you ashamed me.  

2025-05-28 16:38 UTC, boscorelly commented
> Please lock the comments for contributors only.
> 
> Having people asking for feedback every few days only distracts everyone. As all PRs, this will be merged when it's ready and you'll get a notification about it.

I think you must disable notifications about the PR.
You are doing exactly the same thing you don’t want others to do.

2025-05-28 16:40 UTC, boscorelly commented
> > hi,
> > @dani-garcia any update about this ? you released a new version 2 days ago, without this PR. It's a 2 years old PR, without anything done about it. We are hundreds needing it.
> > can you give us a word ?
> 
> As you might see there were several commits the last time and "We are hundreds needing it" is not very nice against the people working on this PR probably without getting directly paid for it. I also can't wait to see this feature released but either wait or do something!

The person on this PR is waiting since september 2023 to see his PR merged.
The only thing « not very nice » is to not merge it.

2025-05-28 21:05 UTC, konradmoesch commented
Nearly 600 comments, and sorry to add one more.
I wonder what the current state is, the PR text and also the readme in the fork also have not been changed for a long time.
@Timshel , could you please give a short status update? Thanks! I lost track like 300 comments ago 😅
Do you need help testing some specific edge cases? Special things regarding clients etc? Missing features? Can I (or someone else in this thread) help you w/ development, specific bugs, testing, documentation, ...?

What are the biggest blockers currently? Or could this PR be merged and it just depends on the owner ore someone else with merge permissions?

Sorry to add more noise, everyone. Please let us all stay kind and stop any (passive) aggressive messages. And lets get back to talking about the content and the work to be done, thanks!

2025-05-29 13:38 UTC, robere2 commented
Hi all,

I agree I want this PR merged, but it's not dead, just waiting for a merge. You can view the fork here for a list of current issues, which may be the main blocker right now: https://github.com/Timshel/vaultwarden/issues
There's also issues on the "live" fork: https://github.com/Timshel/OIDCWarden

If you're looking to help OR the current status, check there! The latest update was last week, with the addition of organization syncing features.

2025-05-29 14:35 UTC, compgeniuses commented
truth of the matter is that, no software is ever ussually complete and fullproof, new features will always be needed, new bugs will always be discovered. otherwise, we never progress. 

I know someone in the community who recently jus tpassed waiting for this. and other scenarios, so, must it be 100% perfect.

2025-05-29 14:51 UTC, CodeMystic21 commented
> 
> I'd personally wager that there's an understanding with the folks at Bitwarden that specific enterprise features will not get added and in return they leave this project alone. You could argue that anyone using Vaultwarden wouldn't pony up cash for Bitwarden anyway, but this project still cuts into their revenue. I'd assume that SSO is the one of these features that they'd not want to see here, hence no desire to merge it.
> 
> Take my comment for what it is though: baseless conjecture that'll either get me downvoted to death, hidden as off topic, or banned from the repo for speaking out the forbidden. I don't know. In any case, that's what it feels like to me following this PR passively for a long time.
> 
> But people are putting in their time and energy into this project for free, so I'm in no position to demand anything to happen. Neither is anyone else.

So true.

Why is everyone gettings their hopes up here???

I know @BlackDex and @dani-garcia  don't want to talk about it.
But this PR will NEVER get merged.

2025-05-29 14:52 UTC, nerdlich commented
Looking at the amount of thumbs down on perfectly sensible posts, I can't help but think that this is a toxic community. There are people with an agenda that are happy to manipulate the conversation in a way to not ever merge this.

2025-05-29 14:57 UTC, CodeMystic21 commented
For all those downvotes, feel free to prove me wrong!

2025-05-29 14:58 UTC, adrianipopescu commented
Let's not have this conversation devolve into conspiracy theories and clean up the comms. Per @robere2's post above, you all have the links where you can see status and even a maintained and up to date soft fork which you can deploy and use right now.

I get being impatient or waiting for years for something, but that's no excuse to call a community toxic for trying to keep this MR's conversations on topic.

So please, take a look at the links from @robere2 and feel free to contribute to the effort. If you just want vw with oidc you have oidcwarden.

Everyone else, sorry for the spam.

2025-05-29 15:04 UTC, CodeMystic21 commented
> Let's not have this conversation devolve into conspiracy theories

This argument works in both directions.
You are creating the conspiracy theory that it's not an issue with bitwarden. Are you involved with them?

Telling the truth is not a conspiracy theory.

Otherwise tell me the reason this PR is not merge for more then 1.5 years.
(+ all the predecessor prs to this ...)

2025-05-29 15:08 UTC, CodeMystic21 commented
How much do you all get for spreading their agenda here?

Maybe my "opinion" can be changed too then.
Would also like it.

2025-05-29 15:09 UTC, rijenkii commented
Jesus fuck just lock this fucking PR already. I subscribed to get notifications about the progress, not to hear people that can't fucking read constantly bitching.

Open the fucking https://github.com/Timshel/vaultwarden/issues and see how progress goes along yourself. It's not stale, stuff gets fixed and implemented every single day.

Stop fucking bitching and implement this yourself if you're so impatient, if you say it must be so easy.

Sorry to the maintainers, but come on. Lock the PR. And remove this and all other abuse comments with it.

2025-05-29 16:17 UTC, dani-garcia commented
Locking for some time as this is getting way too off topic.

I've said it multiple times in other places before, there's no secret conspiracy on why these changes aren't merged, SSO is simply a _massive_ new feature that is very hard to review and maintainers have very limited time, which is usually spent on ensuring that the server stays compatible with the latest apps (which is already hard enough), rather than adding new features that will only increase our maintenance burden. 

This has always been the case since the first SSO PR, which was many years before I even started working with Bitwarden. Moreover, I'm not sure how Bitwarden would benefit from this not being merged, when Timshel/vaultwarden exists and is clearly usable today.

Ultimately, if you as a user want to use SSO or discuss how it's going, go to https://github.com/Timshel/vaultwarden/issues. That's where you'll have the most up to date information. This PR is only for code review of the change being merged. The only thing offtopic comments do is distract everyone, make review even more difficult and make users and maintainers more frustrated.

I will leave this locked for a day or two, and I hope people can understand that the point of a PRs comment section is to do code review and testing. For other topics, you can either go to Timshel/vaultwarden or open a separate discussion thread (please keep it civilized there though). If this continues I'll be forced to keep the PR locked, and that is just a bad outcome for everyone involved.

On a somwhat more positive note, I'm planning to dedicate one week of my summer vacation to test and review these changes to ensure they start moving towards a merge, if only to spare myself from the flood of unnecessary comments.

2025-06-02 22:31 UTC, Timshel commented
Some comment on recent [change](https://github.com/dani-garcia/vaultwarden/pull/3899/commits/e3d66216f66e25d27a017232205c08dec94e0d32), with recent client the 2FA email sending is triggered by the client.

The endpoint was already present but it relied on the `email` and `master_password` sent previously which are missing for the SSO flow.  Additionally, the `device_identifier` was sent but unused, so replaced the logic to identity the user using it.

Issue with this is that for new device login, the device was saved only after passing the 2FA flow and the fact that is was missing was used to identify that it's a new device; but then the sending of the email was failing since the device was missing.
Made the modification to save the device at the start of the login flow, and to identify if the device is new, relied on checking if the create and update date are equal. This is a bit brittle since it relies on the fact that we always and only update the device after a successful login but though it was still better than adding a field just for this check.

-----------

Some comment on the latest release based on `1.34.1`.

Rewrote the organization logic sync (not included in this PR) to allow to sync user membership and groups.
More details here [README.md#organization-sync](https://github.com/Timshel/vaultwarden?tab=readme-ov-file#organization-sync).
Additionally, deprecated/renamed some ENV variable (for the org sync feature), check [README.md#deprecations](https://github.com/Timshel/vaultwarden/blob/main/README.md#deprecations)

And since it had been some time since last release, I wanted to thank the [sponsors](https://github.com/sponsors/Timshel) and the [TU Bergakademie Freiberg](https://tu-freiberg.de/en) which allow me to continue to maintain this PR.
And of course all of this would not be possible without the maintainers of the project :).

2025-06-03 16:14 UTC, Timshel commented
:warning: Hey
Had an issue with tests, some were not run against the correct database :(.
Which made me missed some issue with `postgres` and `mysql`, fixed `postgres` and working on fixing `mysql`, but wait for next release before updating.

2025-06-19 13:17 UTC, PinguDEV-original commented
Is this working? Would love to see it

2025-07-02 12:32 UTC, Timshel commented
Hey,
Just a heads-up, I lost my main sponsor, which means I'll keep this PR updated, but the different releases might start lagging.

2025-07-10 15:42 UTC, compgeniuses commented
> Hey, Just a heads-up, I lost my main sponsor, which means I'll keep this PR updated, but the different releases might start lagging.

what a sad news, i think its  time the main maintainers put some more effort into this PR, and have it integrated into the Main,  i understand that maintaining a PR for this long is not an easy task, with every new changes to the main product that might end up causing issues, forcing new updates to be made to the PR.

this means the sponsor lost hope SMW @dani-garcia got any time this summer, there are many other factors we would like to avoid as a community, as we wait, not to push or being pushy, and i apologise if this offends anyone

2025-07-26 09:57 UTC, Guruleenyc commented
I'm chomping at the bit for OIDC / Authentik support too! 🤞

I'm now using fork: https://github.com/Timshel/vaultwarden , but I'm stuck on a authentik request_uri error...

2025-07-27 07:00 UTC, marzlberger commented
What do you need to make it happen? Time/ressources or money? 
I am willing to donate € to the project if needed. how much do you need?

2025-08-05 11:48 UTC, dani-garcia commented on src/config.rs
> +        /// Regex for additionnal trusted Id token audience |> By default only the client_id is trsuted.
```suggestion
        /// Regex for additionnal trusted Id token audience |> By default only the client_id is trusted.
```

2025-08-05 11:52 UTC, dani-garcia commented on src/config.rs
> +        /// Only sso login |> Disable Email+Master Password login
Minor thing, but we should probably update these comments to use `SSO` in uppercase

2025-08-05 11:55 UTC, dani-garcia commented on src/config.rs
> +        sso_enabled:                    bool,   false,   def,    false;
Is there a reason why this setting is set to `false` so it's not shown in the admin page?

2025-08-05 12:15 UTC, dani-garcia commented on src/config.rs
> +    config
Do we really need to support line breaks as separators? If we just used normal query string syntax we could use the `url` crate, which is already part of the dependencies and avoid having to implement this ourselves:
```rust
url::form_urlencoded::parse(config.as_bytes()).into_owned().collect()
```

2025-08-05 12:19 UTC, dani-garcia commented on Cargo.toml
> +oidc-accept-rfc3339-timestamps = ["openidconnect/accept-rfc3339-timestamps"]
Question: do we expect people to need to enable these two? It seems they just make the client be more loose in what it accepts, would it make sense to just enable it by default?

2025-08-05 12:23 UTC, dani-garcia commented on SSO.md
> +- If set `SIGNUPS_DOMAINS_WHITELIST` is applied on SSO signup and when attempting to change the email.
```suggestion
- If set, `SIGNUPS_DOMAINS_WHITELIST` is applied on SSO signup and when attempting to change the email.
```

2025-08-05 12:24 UTC, dani-garcia commented on SSO.md
We should probably move this file to the wiki, or at least to a `docs` folder. We have too many files in the root repo so I don't think this will have much visibility here.

2025-08-05 12:25 UTC, dani-garcia commented on SSO.md
> +By default the client cache is disabled since it can cause issues with the signing keys.
What kind of issues does it cause?

2025-08-05 12:31 UTC, dani-garcia commented on SSO.md
> +Probably not much hope, an [issue](https://github.com/bitwarden/clients/issues/2606) is open on the subject and it appears that both Linux and Windows are not working.
This github link mentions desktop, and seems fixed. The chrome issue is split into https://github.com/bitwarden/clients/issues/12929

2025-08-05 12:42 UTC, dani-garcia commented on src/api/core/two_factor/email.rs
> +    email: Option<String>,
Is there any case where the clients don't send the email here? I checked all the uses of `postTwoFactorEmail` in clients and they all seem to set it correctly.

2025-08-05 12:49 UTC, dani-garcia commented on src/api/core/accounts.rs
> +    if let Some(client_kdf_iter) = data.kdf_iterations {
We should check that the KDF values are above the minimum, like we do in `post_kdf`. Probably worth extracting the validation to a function.

2025-08-05 12:53 UTC, dani-garcia commented on src/api/core/accounts.rs
> +    if user.password_iterations != CONFIG.password_iterations() {
We should make sure this doesn't allow downgrades
```suggestion
    if user.password_iterations < CONFIG.password_iterations() {
```

2025-08-05 13:00 UTC, dani-garcia commented on src/api/core/organizations.rs
> +#[post("/organizations/domain/sso/details", data = "<data>")]
Do we still need this if it's not used?

2025-08-05 13:27 UTC, dani-garcia commented on src/api/identity.rs
> +    #[form(field = uncased("code"))]
This is different than the others, is there a reason for that? It seems to be building either way which is a bit weird, I think
```suggestion
    #[field(name = uncased("code"))]
```

2025-08-05 13:28 UTC, dani-garcia commented on src/api/identity.rs
> +#[get("/account/prevalidate")]
Seems like ios/android have deleted this one already, and they're using `sso/prevalidate` now.

2025-08-05 13:33 UTC, dani-garcia commented on src/api/identity.rs
> +// cf: https://github.com/bitwarden/clients/blob/8e46ef1ae5be8b62b0d3d0b9d1b1c62088a04638/libs/angular/src/auth/components/sso.component.ts#L68C11-L68C23)
This file has been moved, we should update the link:
https://github.com/bitwarden/clients/blob/80b74b3300e15b4ae414dc06044cc9b02b6c10a6/libs/auth/src/angular/sso/sso.component.ts#L141

2025-08-05 14:27 UTC, Timshel commented on src/config.rs
> +        sso_enabled:                    bool,   false,   def,    false;
I don't know how you decide to include or not in the admin page.
I decided to not include most configuration. But usually kept feature toggling (as such should have kept it :sweat_smile: )

2025-08-05 14:30 UTC, dani-garcia commented on src/config.rs
> +        sso_enabled:                    bool,   false,   def,    false;
Usually I include them in the admin page if the changes apply immediately without restarting the server

2025-08-05 14:36 UTC, Timshel commented on src/config.rs
> +    config
Doesn't make sense anymore, the multiline was mostly for another setting.

2025-08-05 14:47 UTC, Timshel commented on Cargo.toml
> +oidc-accept-rfc3339-timestamps = ["openidconnect/accept-rfc3339-timestamps"]
>  It seems they just make the client be more loose in what it accepts

Yes this should allow some out of spec clients to work, as far as I'm aware:
 - `oidc-accept-rfc3339-timestamps` for `auth0`
 - `oidc-accept-string-booleans` for Entra, mainly the `email_verified` claim.
 
 Since those are well-defined in the spec, I have a personal dislike of providers not following the spec, as such I choose not to activate them. 
 
I don't believe activating them would bring any issues.

2025-08-05 14:48 UTC, Timshel commented on SSO.md
Yes it was just a way to keep it as part of the PR.
Solution might be to move/copy it into the wiki after merging ?

2025-08-05 14:51 UTC, dani-garcia commented on Cargo.toml
> +oidc-accept-rfc3339-timestamps = ["openidconnect/accept-rfc3339-timestamps"]
Yeah, I guess my answer would depend on how many providers are going to not follow the spec, if it's just a couple of obscure/outdated ones, then not enabling this makes sense. If it's a bunch of popular providers we may need to enable it by default, otherwise users won't be able to use our docker images.

Kind of annoying that it's a compile time switch though, if it was a runtime setting this wouldn't be an issue.

2025-08-05 14:53 UTC, dani-garcia commented on SSO.md
Yeah sounds reasonable, I can do it myself in a follow up PR just to try to keep the changes here to a minimum, if you want.

2025-08-05 14:54 UTC, Timshel commented on SSO.md
> +By default the client cache is disabled since it can cause issues with the signing keys.
I'm a bit rusty on the subject but:

In most clients the signing keys are rotated.
Depending on how this rotation is done (does the provider start advertising the new key before using it ?) then a cached client might fail to validate the exchange (this should immediately invalidate the client itself, but at least one user will have a login failure).

2025-08-05 15:00 UTC, Timshel commented on SSO.md
> +Probably not much hope, an [issue](https://github.com/bitwarden/clients/issues/2606) is open on the subject and it appears that both Linux and Windows are not working.
I switched the link and change the wording to just say that some user appear to have issues.

2025-08-05 15:05 UTC, Timshel commented on src/api/core/two_factor/email.rs
> +    email: Option<String>,
I believe at the time I made the change for an SSO 2FA only the device ID was present.

2025-08-05 15:12 UTC, Timshel commented on src/api/core/organizations.rs
> +#[post("/organizations/domain/sso/details", data = "<data>")]
I kept it because I believe in general you keep compatibility with old clients.

But since SSO was not available at the time probably does not make sense.

2025-08-05 15:20 UTC, Timshel commented on src/config.rs
> +        sso_enabled:                    bool,   false,   def,    false;
Ok will make a pass over all settings.

2025-08-05 15:45 UTC, Timshel commented on src/api/core/organizations.rs
> +#[post("/organizations/domain/sso/details", data = "<data>")]
At the same time what is your logic with old mobile version ?

2025-08-05 16:24 UTC, dani-garcia commented on src/api/core/organizations.rs
> +#[post("/organizations/domain/sso/details", data = "<data>")]
The primary goal is to maintain compatibility with old clients and avoid breaking existing setups whenever possible.

However, since this is a new feature that is not in use yet, there's no risk of us breaking older setups and so instead I would lean more on the side of only supporting the newest API, to avoid the extra tech debt.

2025-08-05 19:22 UTC, jmallach commented on src/config.rs
> +        /// Regex for additionnal trusted Id token audience |> By default only the client_id is trusted.
While reading Dani's review, I noticed an extra typo in one of the typo fixes:

additionnal → additional 

@Timshel, there are at least 4 occurrences of this typo in the PR.

Thanks to both for your efforts.

2025-08-06 15:18 UTC, Timshel commented on src/config.rs
> +        /// Regex for additionnal trusted Id token audience |> By default only the client_id is trusted.
thx :)

2025-08-06 16:13 UTC, Timshel commented on src/api/core/two_factor/email.rs
> +    email: Option<String>,
Just checked again and only the `deviceIdentifier` was present.

2025-08-06 16:36 UTC, Timshel commented on src/config.rs
> +        sso_enabled:                    bool,   false,   def,    false;
Switched everything to `true`.
Changing some settings might trigger some short-lived issues (like toggling pkce) but nothing that will persist.

2025-08-06 17:56 UTC, Timshel commented on src/api/core/accounts.rs
> +    if let Some(client_kdf_iter) = data.kdf_iterations {
I moved the logic to a separate function and used it in `_register`,  `post_set_password` and `post_kdf`.
For the registration and `set_password` some fields were set as `Option` but from what I can see it was not necessary:

 - Old [register.request.ts](https://github.com/bitwarden/clients/blob/web-v2025.1.1/libs/common/src/models/request/register.request.ts)
 - [register-finish.request](https://github.com/bitwarden/clients/blob/main/libs/common/src/auth/models/request/registration/register-finish.request.ts)
 - [set-password.request](https://github.com/bitwarden/clients/blob/main/libs/common/src/auth/models/request/set-password.request.ts)
 
 Since I made some modification to the `RegisterData` object maybe I should open a separate PR for this part ?

2025-08-07 21:35 UTC, dani-garcia commented on SSO.md
> +By default the client cache is disabled since it can cause issues with the signing keys.
Nice, that's good to know. Yeah my thinking was that if the issues were easily detectable we could auto enable the cache by default and only disable it when there are issues, but that's probably better left as a future improvement anyway.

2025-08-08 21:22 UTC, merged

2025-08-08 21:31 UTC, sandervandegeijn commented
Truly amazing. Massive thanks to both Timshell and Dani for the work that you guys have put in.

I'll contact our pentest partner to update and finalize the quote for the pentest.

So happy 🥳

2025-08-08 21:43 UTC, rizlas commented
Looking forward to this pentest. The most awaited thing after this merge 👀 

Thanks @Timshel @dani-garcia

2025-08-08 21:46 UTC, FlattusBlastus commented
I've got plans for my weekend now. FANTASTIC WORK FROM ALL.
Congratulations!!!!

On Fri, Aug 8, 2025, 2:33 PM Sander van de Geijn ***@***.***>
wrote:

> *sandervandegeijn* left a comment (dani-garcia/vaultwarden#3899)
> <https://github.com/dani-garcia/vaultwarden/pull/3899#issuecomment-3169356333>
>
> Truly amazing. Massive thanks to both Timshell and Dani for the work that
> you guys have put in.
>
> I'll contact our pentest partner to update and finalize the quote for the
> pentest.
>
> So happy 🥳
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dani-garcia/vaultwarden/pull/3899#issuecomment-3169356333>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASVVEUDPAPIOTVX5MJMNYQT3MUJUDAVCNFSM6AAAAAA44PS52CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTCNRZGM2TMMZTGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-08-08 22:07 UTC, harshavmb commented
I literally installed vaultwarden 30 mins ago. The moment I logged on, I looked for OpenID integration with Zitadel & I found this PR merged. 

Wow!! Just wow.

2025-08-08 23:05 UTC, kocey131 commented
Congratulations and thank you !!!

2025-08-09 01:34 UTC, s83 commented
This is a breakthrough moment for the project. Huge congratulations to the contributors and heartfelt thanks for your dedication🙏

2025-08-09 01:54 UTC, UndyingSoul commented
I just want to shout out how much I appreciate the team behind this PR. I can see how much effort and care was put into this feature, and I'm looking forward to pulling the latest version of the official vaultwarden image with this new OIDC feature.

Great job, and thanks again for your hard work.

2025-08-09 07:43 UTC, rizlas commented
@Timshel what about some features that we discussed back in the days, that will not be part of this PR, like https://github.com/Timshel/vaultwarden#role-mapping? From now on, we should stick and open issue/pr/fe about sso in forks or rejoin also that part here?

Just a quick note: SSO feature wasn't working in the Bitwarden desktop app. I tried it about two weeks ago, and it's working there now, too.

2025-08-09 07:53 UTC, gjuuz commented
> @Timshel what about some features that we discussed back in the days, that will not be part of this PR, like https://github.com/Timshel/vaultwarden#role-mapping? From now on, we should stick and open issue/pr/fr about sso in forks or rejoin also that part here?
> 
> 
> 
> Just a quick note: SSO feature wasn't working in the Bitwarden desktop app. I tried it about two weeks ago, and it's working there now, too.

SSO in the Desktop app is Not working when using chrome. I dont know whether this is a general Bitwarden issue or linked to specific issue with this work.
However when we use Firefox it's working fine and there is an issue opened in the original Bitwarden project but does not seem that there is some progress. It would be very nice to get sso working in the desktop app when using chrome.

2025-08-09 07:56 UTC, rizlas commented
By desktop client i mean https://bitwarden.com/download/#downloads-desktop not browser extensions.

2025-08-09 08:00 UTC, gjuuz commented
> By desktop client i mean https://bitwarden.com/download/#downloads-desktop not browser extensions.

@rizlas 
Yes me too. 
Try changing default browser to Firefox and try sso in the desktop app again.

2025-08-09 08:03 UTC, BlackDex commented
> > @Timshel what about some features that we discussed back in the days, that will not be part of this PR, like https://github.com/Timshel/vaultwarden#role-mapping? From now on, we should stick and open issue/pr/fr about sso in forks or rejoin also that part here?
> > Just a quick note: SSO feature wasn't working in the Bitwarden desktop app. I tried it about two weeks ago, and it's working there now, too.
> 
> @rizlas
> 
> SSO in the Desktop app is Not working when using chrome. I dont know whether this is a general Bitwarden issue or linked to specific issue with this work. However when we use Firefox it's working fine and there is an issue opened in the original Bitwarden project but does not seem that there is some progress. It would be very nice to get sso working in the desktop app when using chrome.

Probably not something this project can fix.

2025-08-09 08:15 UTC, gjuuz commented
> > > @Timshel what about some features that we discussed back in the days, that will not be part of this PR, like https://github.com/Timshel/vaultwarden#role-mapping? From now on, we should stick and open issue/pr/fr about sso in forks or rejoin also that part here?
> 
> > > Just a quick note: SSO feature wasn't working in the Bitwarden desktop app. I tried it about two weeks ago, and it's working there now, too.
> 
> > 
> 
> > @rizlas
> 
> > 
> 
> > SSO in the Desktop app is Not working when using chrome. I dont know whether this is a general Bitwarden issue or linked to specific issue with this work. However when we use Firefox it's working fine and there is an issue opened in the original Bitwarden project but does not seem that there is some progress. It would be very nice to get sso working in the desktop app when using chrome.
> 
> 
> 
> Probably not something this project can fix.

@BlackDex 
Yes but until today I dont know what the issue is and the case opened in the original project is not researched too. 
I can't imagine that people using the original project having this issue as well. For enterprise users sso in the desktop app is mandatory I guess.

2025-08-09 09:05 UTC, Timshel commented
>  I dont know whether this is a general Bitwarden issue

@gjuuz does this mean that you have not tested with an official setup/server ?

2025-08-09 09:08 UTC, gjuuz commented
> >  I dont know whether this is a general Bitwarden issue
> 
> 
> 
> @gjuuz does this mean that you have not tested with an official setup/server ?

@Timshel 

No I mean I dont know if this issue also exists when using Bitwarden officially with enterprise functions included.

I cannot test this because I don't have a Bitwarden subscription.

2025-08-09 09:10 UTC, Timshel commented
@gjuuz In this case don't open [issue](https://github.com/bitwarden/clients/issues/12929) in the official project, they are not supporting alternative server installation and If we found an issue in the official project we are not likely to work on it if we assume the problem is upstream ...

2025-08-09 09:13 UTC, gjuuz commented
@Timshel 
As there is another issue opened in the original project I guess it is a general issue but yea I cannot guarantee this 100% and I need help to find where the issue is coming from.

2025-08-09 09:24 UTC, gjuuz commented
> @gjuuz In this case don't open [issue](https://github.com/bitwarden/clients/issues/12929) in the official project, they are not supporting alternative server installation and If we found an issue in the official project we are not likely to work on it if we assume the problem is upstream ...

@Timshel 
Just asked another colleague they are using official Bitwarden and it's working when using chrome for sso.

2025-08-09 17:56 UTC, TheDarkula commented
Is it possible to have a nested structure for roles?

Comparing this to Open WebUI:

`OAUTH_ROLES_CLAIM` - The claim that contains the roles. Defaults to roles. Can also be nested, for example user.roles.

2025-08-11 07:59 UTC, gjuuz commented
> e excited to try this, the changes will be part of the `vaultwarden/server:testing` image when the builds are done in half an hour or so. There is no set schedule for a stable release yet, but I can imagine it'll probably happen in 2-4 weeks assuming we don't find any critical bugs.

@Timshel @BlackDex 
just tried to switch to the testing build but i noticed that the SSO_FRONTEND='override' is not woring so you wont be redirected to the sso page.
Can you confirm this ?

BR

2025-08-11 11:39 UTC, Timshel commented
Features mentioned [here](https://github.com/Timshel/vaultwarden/tree/main?tab=readme-ov-file#additionnal-features) were not part of this PR, and the equivalent of the `override` client is not expected to be distributed by the `Vaultwarden` team.

2025-08-11 12:22 UTC, gjuuz commented
@Timshel 
thanks for this explaination.

@BlackDex 
is there a possibility to get this implemented ? It would be difficult to explain all people to first complete sso before they can enter their vaultwarden credentials. 
It would be very helpful to redirect the login page to sso only.

2025-08-11 16:18 UTC, TheDarkula commented
@Timshel  I see [here](https://github.com/Timshel/vaultwarden/tree/main?tab=readme-ov-file#organization-invitation) that there is a `SSO_SCOPES` environment variable.
Will there be something like `SSO_ADMIN_CLAIM`/`SSO_USER_CLAIM` for specifying roles?

2025-08-12 06:44 UTC, Timshel commented
@TheDarkula not sure what the env variable are supposed to do, but if you want role mapping I already opened https://github.com/dani-garcia/vaultwarden/pull/6158 to add access to the admin console depending on role and will open one for Organization and groups sync later on.

2025-08-12 12:34 UTC, gjuuz commented
@Timshel 
found something related to the sso issue:

It seems like this has something to do with the url length of the sso callback. Its opening the bitwarden app if i cut the link down to 2046 limit.

2025-08-12 13:17 UTC, Timshel commented
@gjuuz this would explain things since I wrap the `code` in a JWT token to be able to pass more information. 
I'll check if I can't do things differently with latest client version, thx.

2025-08-12 13:38 UTC, gjuuz commented
@Timshel 
Thanks that would be great :)

2025-08-16 15:23 UTC, TheDarkula commented
@Timshel Excellent, thank you! That is exactly what I meant :)

There is one more feature I am after, which is allowing nested roles.

In [Open WebUI](https://docs.openwebui.com/features/sso/#oauth-role-management), they have this:
`OAUTH_ROLES_CLAIM` - The claim that contains the roles. Defaults to roles. Can also be nested, for example user.roles.

Is that what `SSO_ROLES_TOKEN_PATH` is meant for?

2025-08-20 15:53 UTC, Timshel commented
@gjuuz opened https://github.com/dani-garcia/vaultwarden/pull/6205 with the modification to stop wrapping the returned `code` in a JWT Token this should fix the issues around token length.

While working on it realized that the PKCE implementation was wonky.
It was not validating the challenge sent by the Bitwarden clients but generating a challenge server side with does not help much with security. So made the change to validate the Bitwarden challenge before calling the providers, this does mean it will be checked even if `SSO_PKCE` is disabled (Had some issue to pass it to the provider but might have a solution).

If you are running `OIDCWarden` then there is an update with this. 
But the `timshel/vaulwarden` distribution is more or less deprecated since I can't really spend the time to maintain both "fork" and open new PR.

2025-08-20 17:56 UTC, gjuuz commented
> @gjuuz opened #6205 with the modification to stop wrapping the returned `code` in a JWT Token this should fix the issues around token length.
> 
> While working on it realized that the PKCE implementation was wonky. It was not validating the challenge sent by the Bitwarden clients but generating a challenge server side with does not help much with security. So made the change to validate the Bitwarden challenge before calling the providers, this does mean it will be checked even if `SSO_PKCE` is disabled (Had some issue to pass it to the provider but might have a solution).
> 
> If you are running `OIDCWarden` then there is an update with this. But the `timshel/vaulwarden` distribution is more or less deprecated since I can't really spend the time to maintain both "fork" and open new PR.

Hi,
thanks for providing a fix. I am currently on the timshel/vaultwarden distribution and i was wondering about the new SSO_ORG mapping. I tried to check with existing documentation but i couldnt manage to find out how the mapping of a entra id group is linked to org used in vaultwarden. 
Can someone help how this is done in the future ?

2025-09-06 12:29 UTC, prk0ghy commented
@Timshel @dani-garcia  thank you so much, you are amazing!

2025-09-20 11:57 UTC, PrivatePuffin commented
@Timshel does this also allow for backchannel logout from the OIDC provider?

2025-09-25 12:36 UTC, Timshel commented
@PrivatePuffin Not at the moment, It should be possible to roll the device token to invalidate all sessions, might take a look :thinking:.

2025-10-10 09:09 UTC, mdddev commented
> @isaiah-v as mentioned a master password is still required. There is no change on this point.

Hi @isaiah-v , may I ask if this is still the case?

2025-10-10 11:48 UTC, robin-thoni commented
> > @isaiah-v as mentioned a master password is still required. There is no change on this point.
> 
> Hi @isaiah-v , may I ask if this is still the case?

SSO just allows you to download the encrypted version of your vault. So, unless you implement [Key Connector](https://bitwarden.com/help/about-key-connector/) (assuming vaultvarden supports it, which I don't think it does), yes a master password will still be required to decrypt it.

2025-10-10 15:11 UTC, mdddev commented
Thank your for the speedy reply!

2025-10-10 18:25 UTC, dvtkrlbs commented
> > > @isaiah-v as mentioned a master password is still required. There is no change on this point.
> > 
> > 
> > Hi @isaiah-v , may I ask if this is still the case?
> 
> SSO just allows you to download the encrypted version of your vault. So, unless you implement [Key Connector](https://bitwarden.com/help/about-key-connector/) (assuming vaultvarden supports it, which I don't think it does), yes a master password will still be required to decrypt it.

Yes someone needs to add Key Connector support to vaultwarden to be able to ditch master password on SSO setting. If I have time I plan to try an impl. The problem iirc is the key connector binary from bitwarden is limited license so we would need to write a clean room impl of that binary and the endpoints it would require on vaultwarden.

2025-12-02 14:57 UTC, DihaHub commented
Since this is merged and closed, is Key Connector already implemented?

2025-12-02 15:09 UTC, sandervandegeijn commented
Update from our side: pentest is agreed upon and scheduled. We will give the results to the maintainers and if possible publish it publicly.

2025-12-02 15:46 UTC, Timshel commented
@DihaHub, as mentioned, with the license issue I do not plan to work on it and I'm unaware of anyone working on it.

An alternative could be [trusted devices](https://bitwarden.com/help/about-trusted-devices/) (where I believe most of the key handling is done client side, but I could be wrong :sweat_smile:).
But I don't have the support to spend time on it at the moment.

And since I'm already spamming everyone, I'll mention that since `v2025.9.1-1` the web-client from [Vaultwarden](https://github.com/dani-garcia/bw_web_builds) and from [Timshel/oidc_web_vault](https://github.com/Timshel/oidc_web_vault) should be cross compatible.
Might interest those who want to run mainline Vaultwarden but with a default redirection to the `#sso` page (`override` distribution). As always if you encounter any problem don't hesitate to open an issue (moved to [Timshel/OIDCWarden](https://github.com/Timshel/OIDCWarden/))

2025-12-03 11:30 UTC, Timshel commented
@sandervandegeijn I would wait until https://github.com/dani-garcia/vaultwarden/pull/6205 is merged before running the pen-test.

2025-12-09 15:37 UTC, DihaHub commented
> @DihaHub, as mentioned, with the license issue I do not plan to work on it and I'm unaware of anyone working on it.
> 
> An alternative could be [trusted devices](https://bitwarden.com/help/about-trusted-devices/) (where I believe most of the key handling is done client side, but I could be wrong 😅). But I don't have the support to spend time on it at the moment.
> 
> And since I'm already spamming everyone, I'll mention that since `v2025.9.1-1` the web-client from [Vaultwarden](https://github.com/dani-garcia/bw_web_builds) and from [Timshel/oidc_web_vault](https://github.com/Timshel/oidc_web_vault) should be cross compatible. Might interest those who want to run mainline Vaultwarden but with a default redirection to the `#sso` page (`override` distribution). As always if you encounter any problem don't hesitate to open an issue (moved to [Timshel/OIDCWarden](https://github.com/Timshel/OIDCWarden/))

Please excuse my ignorance, but I thought OIDCwarden had been merged into Vaultwarden and is being further developed there. But did I understand correctly that the best solution is still to use OIDCwarden in combination with OIDC_web_Vault?

2025-12-09 18:14 UTC, Timshel commented
@DihaHub depends on what you need, there is still not yet merged features: [Timshel/OIDCWarden#additional-features](https://github.com/Timshel/OIDCWarden?tab=readme-ov-file#additional-features)

2026-02-02 12:15 UTC, sandervandegeijn commented
Pentest is done, it's a long read and I have shared it with the maintainers of Vaultwarden. I can't disclose it integrally because there are too many details about our infrastructure in there. I can share the main findings which are not impactful (good job by the devs and @Timshel !)

<img width="915" height="1014" alt="image" src="https://github.com/user-attachments/assets/f5db268c-f17b-4393-a7c4-3d985f0c2f29" />

Job well done, we are going to deploy this setup to production within a few weeks :)

2026-02-02 12:19 UTC, Timshel commented
@sandervandegeijn I'll note that `SIGNUPS_VERIFY` already exists :).

2026-02-02 12:59 UTC, Rainson12 commented
> @sandervandegeijn I'll note that `SIGNUPS_VERIFY` already exists :).

I also want to note that disabling of local user account registration is possible `SIGNUPS_ALLOWED=false` in such case accounts would be registered automatically when signing in via SSO