Reopen log file on SIGHUP
dani-garcia/vaultwarden pull request #3909
Opened 2023-09-22 16:57 UTC by tobiasmboelz

This change makes Vaultwarden reopen the log file on SIGHUP, enabling proper log rotation without logrotate's copytruncate hack.

2023-09-22 17:49 UTC, williamdes approved these changes
Thank you, I learned something

More reading at https://github.com/tinyproxy/tinyproxy/issues/25#issuecomment-268849637
and Wikipedia

2023-10-07 15:50 UTC, BlackDex requested changes
I have not yet tested this my self, but i think this should work.
Thanks for the contribution.

2023-10-07 15:50 UTC, BlackDex commented on src/main.rs
> +            const SIGHUP: i32 = 1;
It might be a bit long, but maybe removing the custom `const SIGHUP` with `tokio::signal::unix::SignalKind::hangup().as_raw_value()` would be an option?
Not that the signal value will ever change, but still.

So something like:
```suggestion
            const SIGHUP: i32 = tokio::signal::unix::SignalKind::hangup().as_raw_value();
```

2023-10-07 15:50 UTC, BlackDex commented on Cargo.toml
> +reopen = "1.0.3"
I don't think this is needed, it will be included by fern it self.

2023-10-07 16:10 UTC, tobiasmboelz commented on src/main.rs
> +            const SIGHUP: i32 = 1;
That's some wrapper around `libc::SIGHUP`, so IMO it would be cleaner to use `libc::SIGHUP` directly. 

I just didn't use `libc::SIGHUP` or `signal_hook::consts::signal::SIGHUP` (which is mentioned in [the reopen documentation](https://docs.rs/reopen/latest/reopen/)) because I didn't want to add additional dependencies and imports for a single value.

2023-10-07 16:14 UTC, BlackDex commented on src/main.rs
> +            const SIGHUP: i32 = 1;
But that would mean an extra dependency in our Cargo.toml, this doesn't.

2023-10-07 16:55 UTC, tobiasmboelz commented on src/main.rs
> +            const SIGHUP: i32 = 1;
I don't think it's pretty, but fine by me.

2023-10-21 15:13 UTC, BlackDex approved these changes
Works great, thanks!

2023-10-21 15:58 UTC, dani-garcia approved these changes

2023-10-21 15:58 UTC, merged