WIP: Container building changes
dani-garcia/vaultwarden pull request #3958
Opened 2023-10-05 15:26 UTC by BlackDex

Rework the container building.
 - Use `docker buildx bake` instead of custom build/push scripts
 - Just two Dockerfile's one for Debian and one for Alpine
 - Fix openssl-sys version to v0.9.92, higher versions break Alpine builds

Things ToDo:
 - Rework Github Workflow
 - Write some Docker documentation

Please checkout this PR and provide your comments.

2023-10-06 14:12 UTC, BlackDex commented
@stefan0xC and @jjlin i would love to get your input on this.
I still need to work on the github workflow to use bake, hopefully i get that done today, else tomorrow.

2023-10-16 18:19 UTC, stefan0xC requested changes
I have not yet really looked into `docker buildx bake` (except that you have to install the plugin for your docker installation, i.e. with `sudo apt install docker-buildx-plugin` which might be missing from this documentation).

Since I am using `podman` locally I wonder if we could add a script which builds vaultwarden locally with `podman build`, i.e. (based on the `docker/bake.sh` script) running
```bash
podman build --format=docker -f "${BASEDIR}/Dockerfile.debian" "${BASEDIR}/.."
```
will build an image (but it's missing the labels that are set by `docker/docker-bake.hcl` and maybe some other stuff).

Also the built vaultwarden image is missing the git version info. I'm not sure if this is a further limitation of my feeble attempt to getting it to work with podman or if it's a general issue. I'll have to setup a virtual machine to further test the `docker buildx bake` method (my cloud instance that is running docker was not powerful enough to compile Vaultwarden).

2023-10-16 19:04 UTC, stefan0xC commented
Okay, I've compiled it in a virtual machine using `docker/bake.sh` and the version info is missing too:
```bash
$ docker run --rm -ti --name vaultwarden docker.io/vaultwarden/server:testing-amd64 /vaultwarden --version
vaultwarden (Version info from Git not present)
```

2023-10-16 19:22 UTC, BlackDex commented
Hmm, good find, seems `git` is missing from the build image of rust.
An other strange item is that the alpine build does, but, it looks like it's using a wrong version for some reason, the branch name is correct, but not the version.

Ill have to look into this strange item.
With podman, i think installing moby buildkit should be enough with some other commands. Ill see if i can test that also, but my prio was, to have the CI build nicely with the docker tools first.

2023-10-16 19:37 UTC, stefan0xC commented
Installing `git` in the build image solves the issue (the tag is from your repository since I did a fresh clone of your repository):

```
docker run --rm -ti --name vaultwarden docker.io/vaultwarden/server:testing-amd64 /vaultwarden --version
vaultwarden 1.22.2-5c479659 (release-build-revision)
```

2023-10-16 19:42 UTC, BlackDex commented
> Installing `git` in the build image solves the issue with the version number (the tag is from your repository since I did a fresh clone of your repository):
> 
> ```
> docker run --rm -ti --name vaultwarden docker.io/vaultwarden/server:testing-amd64 /vaultwarden --version
> vaultwarden 1.22.2-5c479659 (release-build-revision)
> ```

Ah! That explains it, so, that is ok then.

2023-10-16 20:37 UTC, BlackDex commented on docker/bake.sh
> +    SOURCE_VERSION="${GIT_LAST_TAG}-$(printf '%s' "${SOURCE_COMMIT}" | cut -c 8)"
It indeed does!

2023-10-16 20:44 UTC, BlackDex commented on docker/Dockerfile.j2
> +          tzdata
Noticed some too much indenting in the debian one too.
Thx.

2023-10-16 20:49 UTC, BlackDex commented on docker/Dockerfile.j2
> +FROM --platform=$BUILDPLATFORM docker.io/tonistiigi/xx:master AS xx
That isn't really possible i'm afraid.
The master is the only one working correctly. And there are no tagged releases.
Also, the sha differs per platform, which could be different. That would mean we somehow also need to add all of them. So, not sure how to address that.

2023-10-16 21:17 UTC, stefan0xC commented on docker/Dockerfile.j2
> +FROM --platform=$BUILDPLATFORM docker.io/tonistiigi/xx:master AS xx
Ah, okay. I was just wondering because external dependencies tend to make me a bit uneasy (especially new ones) and being able to pin them to a known version would help alleviate my anxieties a bit (so I know that reviewing something today is not pointless when it changes tomorrow). Since I am not really familiar with our cross compilation requirements I was and still am a bit hesitant to review the changes to our build system. I mean I tend to only test changes to the code locally without checking the docker build system or if something still compiles for different platforms or architectures.

2023-10-19 10:59 UTC, BlackDex commented on docker/Dockerfile.j2
> +FROM --platform=$BUILDPLATFORM docker.io/tonistiigi/xx:master AS xx
btw, i did some checking, and looking a the scripts `xx` contains, there is no difference between the different platforms as far as i can tell. So using only the amd64 platform image should be enough, and therefor we can pin the version by using a digest :)

2023-10-19 14:13 UTC, BlackDex commented
@stefan0xC please check again, i updated everything and as i mentioned on Matrix, there now is a `podman-bake.sh` script which you can use.

2023-10-20 06:25 UTC, stefan0xC reviewed
Thanks for adding a script for `podman` which seems to work just fine.

Wouldn't it be more consistent to call `SOURCE_VERSION` `VW_VERSION` and using the same value as label and inside vaultwarden?

2023-10-20 06:25 UTC, stefan0xC commented on docker/README.md
> +If you want to run a podman built image which is using a different architecture then your host, you need to use the image id which you can see when running `podman images`.<br>
With podman `4.7.1` (Arch Linux) I have no issues running
```bash
podman run --rm --name vaultwarden -v $(pwd)/data:/data:rw --env-file $(pwd)/.env localhost/vaultwarden/server:testing-armv6
```

I'll have to start `systemd-binfmt.service` though, or I'll get an error message:
```
{"msg":"exec container process `/start.sh`: Exec format error","level":"error","time":"2023-10-20T06:08:37.215620Z"}
```

2023-10-20 06:39 UTC, BlackDex commented on docker/Dockerfile.j2
Well using `--build-arg VW_VERSION=${SOURCE_VERSION}` would be pointless i think, since `build.rs` does this already.
But, it of course could be useful for other people or in case the `.git` directory is not there.

We do have this variable there in `build.rs` so would be nice indeed if we make it possible to have that as an arg.

2023-10-20 07:32 UTC, stefan0xC commented on docker/Dockerfile.j2
@BlackDex I think it differs a bit (i.e. `build.rs` will also add the branch name in parentheses).

2023-10-20 17:36 UTC, BlackDex commented on docker/Dockerfile.j2
I also fixed that to make it more the same!

2023-10-20 17:53 UTC, BlackDex commented on docker/README.md
> +If you want to run a podman built image which is using a different architecture then your host, you need to use the image id which you can see when running `podman images`.<br>
Hmm indeed it does. You just do not need to add the `--platform`, that will break it.
Starting binfmt is probably already done, else building the image would have failed.

2023-10-20 17:56 UTC, BlackDex commented
Thanks again @stefan0xC, i think i have addressed all your comments and more.
It should be ready to go now :)

2023-10-20 19:21 UTC, stefan0xC commented on docker/README.md
> +If you want to run a podman built image which is using a different architecture then your host, you need to use the image id which you can see when running `podman images`.<br>
Maybe it has to do with the `debian` image? Cause the build image reports as `linux/arm/v5` variant and not `linux/arm/v6`? (Not sure if this is an issue but that's just something I noticed when testing).

2023-10-20 19:26 UTC, BlackDex commented on docker/README.md
> +If you want to run a podman built image which is using a different architecture then your host, you need to use the image id which you can see when running `podman images`.<br>
It's not an issue, it actually what fixes the armv6 image for Debian.
That is the debian linux/arm/v6 image which uses armel.

So that is all fine. I have tested it also on my Raspberry, and works perfectly fine now, which the current one does not.

2023-10-20 19:36 UTC, stefan0xC commented on docker/README.md
> +If you want to run a podman built image which is using a different architecture then your host, you need to use the image id which you can see when running `podman images`.<br>
Yeah. I mean, starting `podman` with `--platform linux/arm/v5` lets me run the `-armv6` tagged image.

Building the image with docker (in the VM) will report the image as `linux/arm/v6`
```
WARNING: The requested image's platform (linux/arm/v6) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
```

But this might be another weirdness caused by podman.

2023-10-21 16:13 UTC, dani-garcia commented on .github/workflows/build.yml
> +      # TODO: We should not upload these. We should extract Alpine build binaries from the containers and upload them
If we're not pushing the binary artifact here, can we get away with not using `--release` in all the steps to make the whole workflow faster?

Also the previous step on line 204 doing cargo build won't be needed if we don't use the output, we're already doing cargo test with the same feature set.

2023-10-21 16:27 UTC, BlackDex commented on .github/workflows/build.yml
> +      # TODO: We should not upload these. We should extract Alpine build binaries from the containers and upload them
And clippy, which does almost the same indeed.
So a build might be overrated indeed.

There was something which broke during a release build and not dev/debug, but I'm fine setting it back to dev again, saves a lot of time haha.

2023-10-21 16:43 UTC, BlackDex commented on .github/workflows/build.yml
> +      # TODO: We should not upload these. We should extract Alpine build binaries from the containers and upload them
@dani-garcia changed the build workflow to use debug build, and removed the build step, since we indeed do not upload the binaries here anymore, no need for that.

2023-10-22 22:18 UTC, dani-garcia approved these changes

2023-10-22 22:18 UTC, merged