Fix typos
dani-garcia/vaultwarden pull request #3959
Opened 2023-10-05 17:13 UTC by tuhanayim

Fixes typos in the code base, mostly comments.

There's also a typo at https://github.com/dani-garcia/vaultwarden/blob/bc26bfa589c007da9b9be37e1172060f38a948b9/src/api/notifications.rs#L568 but I'm not sure if it is intentional or not, so I left it unfixed for now.

2023-10-05 19:50 UTC, stefan0xC commented
> not sure if it is intentional

It's also upstream (in [bitwarden/clients](https://github.com/bitwarden/clients/blob/7190bad1b0e81c6178b468dcdd8b6e7533ffe7ee/libs/common/src/services/anonymousHub.service.ts#L42) and [bitwarden/server](https://github.com/bitwarden/server/blob/4dcd467a5fb8f99e9644da12dcafa36b14d870d2/src/Notifications/HubHelpers.cs#L76)). So intentional by us, probably not intentional by them. :wink:

2023-10-07 14:20 UTC, BlackDex requested changes

2023-10-07 14:20 UTC, BlackDex commented on src/api/core/organizations.rs
> +// We call those two functions here and combine them our selves.
Shouldn't this be `ourselves`?

2023-10-07 19:06 UTC, tuhanayim commented on src/api/core/organizations.rs
> +// We call those two functions here and combine them our selves.
Correct, my bad.

2023-10-07 19:29 UTC, BlackDex approved these changes

2023-10-08 12:55 UTC, dani-garcia approved these changes

2023-10-08 12:55 UTC, merged