Remove custom WebSocket code
dani-garcia/vaultwarden pull request #4001
Opened 2023-10-25 14:52 UTC by BlackDex

Remove our custom WebSocket code and only use the Rocket code. Removed all options in regards to WebSockets
Added a new option `WEBSOCKET_DISABLED` which defaults too `false`. This can be used to disable WebSockets if you really do not want to use it.

2023-10-26 20:18 UTC, stefan0xC requested changes
Looks mostly good to me. Not sure I'm a fan of the new configuration option name though.

If we don't want to keep the old name (for which I guess there are reasons, i.e. some users would have to change their configuration if they have set the value to false explicitly or saved a `data/config.json` with the old default), I'd rather call it `WEBSOCKETS_ENABLED` instead. I think it would be better to have an affirmative name for booleans as they tend to be easier to reason about (i.e. a feature is enabled when it's true, not when a disable toggle is on).

If we want to communicate that this is an option to disable the feature (to discourage the use) I think we should use the active form `DISABLE_WEBSOCKETS` instead (as we do with a few other configuration options`).

2023-10-26 20:52 UTC, BlackDex commented on .env.template
> +# WEBSOCKET_DISABLED=false
Reuse is a bit strange, since we encouraged people to disable it in the current versions. That would mean instantly breaking websocket support.

Changing it to add a `S` would be fine by me, though I don't think it's syntactically correct.

Also, i think `DISABLE_WEBSOCKET` would be a good alternative.

2023-10-26 20:52 UTC, BlackDex commented on src/api/notifications.rs
> +            self.send_update(auth_response_uuid, &data).await;
Overlooked this I think thx.

2023-10-26 20:58 UTC, BlackDex commented on src/api/notifications.rs
> +        if CONFIG.websocket_disabled() && !CONFIG.push_enabled() {
Yea i thought about that too. I even was thinking about a dummy crate/mod to load that instead.

But maybe a single function which takes care of this is a better option indeed.

2023-10-27 15:14 UTC, BlackDex commented on src/api/notifications.rs
> +            self.send_update(auth_response_uuid, &data).await;
That function does send a push notification, so it should still make a difference between them i think.

2023-11-01 15:58 UTC, tessus commented
The way this is implemented now means that this is a breaking change. If vw follows semantic versioning, the next release will have to be `2.0.0`.

Even if vw didn't follow semantic versioning, a proper BREAKING changelog entry should be added.

2023-11-01 22:46 UTC, SergioBenitez commented on src/api/admin.rs
> +    cookies.remove(Cookie::build((COOKIE_NAME, "")).path(admin_path()));
```suggestion
    cookies.remove(Cookie::build(COOKIE_NAME).path(admin_path()));
```

2023-11-01 22:47 UTC, SergioBenitez commented on src/api/admin.rs
> +                cookies.remove(Cookie::build((COOKIE_NAME, "")).path(admin_path()));
```suggestion
                cookies.remove(Cookie::build(COOKIE_NAME).path(admin_path()));
```

2023-11-03 12:03 UTC, BlackDex commented on src/api/admin.rs
> +                cookies.remove(Cookie::build((COOKIE_NAME, "")).path(admin_path()));
Thx

2023-11-06 21:05 UTC, SergioBenitez reviewed
Nothing too interesting. Looks like a straightforward migration to rc4!

2023-11-06 21:05 UTC, SergioBenitez commented on src/api/notifications.rs
> +    ws: WebSocket,
I think if you make this `mut`, you don't need to rebind it as `mut` inside the `Stream!`. And if that's not the case, we can probably make it so in Rocket.

Also, since I can't leave a comment on code that wasn't changed: there's a lot of rightward drift on this one. I'd probably do bind the stream instead of returning it directly to save one indentation level, something like:

```rust
let stream = rocket_ws::Stream!(ws => {
    ....
});

Ok(stream)
```

But that's just a matter of preference.

2023-11-06 21:16 UTC, BlackDex commented on src/api/notifications.rs
> +    ws: WebSocket,
Thx for your comments.
Ill see what looks better. The mut is good one. Ill test it out.

2024-02-02 23:04 UTC, tessus commented
Can this be merged? I think it makes sense to have this "break" reverse-proxy settings in testing **before** the 1.31.0 is released.

2024-02-02 23:14 UTC, BlackDex commented
We (might) need to release a 1.30.4 first.
Because of #4307, which is fixed now.

But after that (if nothing else pops up), that was the plan.

2024-03-14 23:11 UTC, tessus commented
Ping. ;-) Can a few PRs be merged? The list of PRs id getting longer and longer...

2024-03-17 18:52 UTC, dani-garcia approved these changes

2024-03-17 18:52 UTC, merged