add information about docker-compose.yml to README.md
dani-garcia/vaultwarden pull request #4100
Opened 2023-11-24 23:06 UTC by lumpsoid

- added information on how this can be organized into a docker-compose.yml file for easier interaction.
- added a couple of examples of what happens in docker-compose.yml
- slightly reshaped the text in #Instalation

2023-11-24 23:27 UTC, williamdes commented on README.md
> +```
```suggestion
```yaml
```

2023-11-24 23:27 UTC, williamdes commented on README.md
> +```
```suggestion
```yaml
```

2023-12-02 10:52 UTC, williamdes commented on README.md
> +    image: vaultwarden/server:1.30.0
```suggestion
    image: vaultwarden/server:1.30.1
```

2023-12-02 10:55 UTC, stefan0xC commented on README.md
> +    image: vaultwarden/server:1.30.0
Why not `latest`?

2023-12-03 09:46 UTC, GeekCornerGH requested changes

2023-12-03 09:46 UTC, GeekCornerGH commented on README.md
> +    image: vaultwarden/server:1.30.0
```suggestion
    image: vaultwarden/server:latest
```

2023-12-03 09:46 UTC, GeekCornerGH commented on README.md
> +the left side of `volumes:` is where you can find vaultwarden data on you PC relative to the folder where you store the docker-compose.yml file
```suggestion
the left side of `volumes:` is where you can find vaultwarden data on your PC/server relative to the folder where you store the docker-compose.yml file 
```

2023-12-15 16:28 UTC, BlackDex requested changes
Besides the changes suggested by the others i would also suggest to add the link to the wiki in regards of Docker Compose. It contains a bit more details and that page is easier to update by others too.

So, please also add the following link https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose

2024-01-14 13:03 UTC, williamdes commented on README.md
> +    image: vaultwarden/server:1.30.0
Because it may roll in production major releases without the author noticing.
I prefer range tags: like 1.30 or 1 for example. Alpine linux and other have this

2024-01-14 13:10 UTC, lumpsoid commented on README.md
> +    image: vaultwarden/server:1.30.0
All right, I'll put the changes back in.

2024-01-14 13:24 UTC, BlackDex commented on README.md
> +    image: vaultwarden/server:1.30.0
I don't want to be a pain here. But we do not have range tags. And the current examples all use latest.

It might change in the future, but I would prefer to keep all examples the same, and no usage of versions. A lot of people tend to forget this and assume it will be charged automatically or something.

So i would prefer to keep latest for now.

2024-01-14 13:37 UTC, williamdes commented on README.md
> +    image: vaultwarden/server:1.30.0
Yeah I agree, people forget to upgrade
Both ways it's a pain. Let's keep latest then

2024-01-14 14:24 UTC, closed without merging