Improve file limit handling
dani-garcia/vaultwarden pull request #4242
Opened 2024-01-12 22:52 UTC by dani-garcia

- Add separate Send limit, previously it was using the Attachment limit, which wouldn't work correctly
- Change file sizes in attachment to be i64, both in code and in the database, to limit the amount of number casting
- Switched number operations to use checked operations

Haven't tested MySQL or Postgres but I think the migrations are correct.

2024-01-12 23:34 UTC, BlackDex commented
Code wise looks ok (as usual).
Ill double check the migrations in the morning/afternoon hopefully.

2024-01-13 18:30 UTC, BlackDex commented on src/db/models/send.rs
> +                    total = total.saturating_add(size);
It doesn't benefit to error/panic here at all.
The total will in the end be the max size of i64, which will then be checked by the function which calls this function.

While i do not think someone will ever reach 8389000 TB, i think this will is fine.
We might add a warning if it is this high?

2024-01-13 18:51 UTC, dani-garcia commented on src/util.rs
> +    let Some(mut size) = size.to_f64() else {
We're rounding the numbers to two decimal digits so I don't think some precision loss is going to be a problem in this situation. The formatted number is only used for display purposes too.

2024-01-13 19:50 UTC, BlackDex requested changes

2024-01-13 19:50 UTC, BlackDex commented on migrations/postgresql/2024-01-12-210182_change_attachment_size/up.sql
> +ALTER TABLE attachments MODIFY file_size BIGINT NOT NULL;
This doesn't work for PostgreSQL.

```suggestion
ALTER TABLE attachments
ALTER COLUMN file_size TYPE BIGINT,
ALTER COLUMN file_size SET NOT NULL;
```

2024-01-13 19:52 UTC, BlackDex commented
> For the database migrations, assuming it's possible, should a check be done on the metadata table to ensure there are no rows with negative file sizes? If not, then any existing negative values will continue to incorrectly increase the available limit calculations.

We could search for all values less then 0, and convert them.

2024-01-13 23:06 UTC, BlackDex commented
> > We could search for all values less then 0, and convert them.
> 
> Convert them to simply `0`? Seems fine; although do note this leads to the possibility that a user/organization now may be over their configured limit. Not sure how to solve that. Perhaps in the release notes specify that admins may want to verify attachment limits are not bypassed; and if so, handle that manually by informing users/organizations they need to be removed.

In theory it would be possible to fix all this. All files are on disk of course, and we can match all attachments and send files.
But, it will be the encrypted size. There might be a average percentage increase which we could use to calculate the size.

Though i do think there are probably no users who send negative files sizes to the server.
Scanning all files during startup is probably not the best way to go.

We might be able to create an action in the admin interface to validate all attachments and sends maybe.
That could also check and validate attachments which were delete from disk, but not from the database.

2024-01-26 19:46 UTC, BlackDex approved these changes
lgtm

2024-01-27 01:43 UTC, merged