add information about docker-compose.yml to README.md
dani-garcia/vaultwarden pull request #4243
Opened 2024-01-14 14:36 UTC by lumpsoid

- added information on how this can be organized into a docker-compose.yml file for easier installation.
- added a couple of examples of what happens in docker-compose.yml
- slightly reshaped the text in #Instalation
- add the link to the wiki page "Using Docker Compose"

because of the cleaning of this branch, github closed previous pull request, sorry

2024-01-15 21:15 UTC, williamdes commented on README.md
> +```yaml
why would it not be yaml ?

2024-01-15 21:36 UTC, nemchik commented on README.md
> +```yaml
Adding context (response to the comment that was removed). Just line 62 using `yaml` does not seem correct to me as the contents of the code fence is a directory structure example, not actual yaml. The yaml above for the compose is accurately using `yaml` for its code fence.

2024-01-26 16:20 UTC, BlackDex requested changes
The previous PR had several comments, which do not seem to be addressed here.
Please make sure it is up-to-date with the comments there.

2024-01-29 06:47 UTC, stefan0xC requested changes
I'm not sure if the README is the best place for a `docker-compose.yml` example. Overall I think that the whole sections needs to be rewritten.

2024-01-29 06:47 UTC, stefan0xC commented on README.md
>  Pull the docker image and mount a volume from the host for persistent storage:
I think that you need to rewrite the Installation section as it's currently interrupted by the added subsections, especially because the existing documentation only perfunctorily explains the docker commands.

2024-05-18 16:04 UTC, BlackDex commented
I actually think we should create a better Wiki page on how to use it, and link that in the Readme.
The main reason for this is, what about podman, or other container runtimes?

That would only clutter the whole Readme while that is better suited for a good written Wiki page.
Then we can still mention using docker, docker compose or podman etc.. in the readme and link to that article.

I'm leaning to closing this PR because of this. If you can create a good wiki article, or update an existing one and link to it in this PR then that is also fine :).

2024-06-12 11:40 UTC, TheRsKing commented
just for the record: i updated the wiki a bit and made a subchapter for a minimal docker compose configuration https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose#minimal-template-for-no-reverse-proxy--a-reverse-proxy-configured-by-yourself-caddy-example-below

I wonder if the caddy examples are really necessary, since there is a wonderful wiki for [reverse proxy](https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples)

2024-06-17 13:36 UTC, lumpsoid commented
https://github.com/dani-garcia/vaultwarden/pull/4243#issuecomment-2118867315
> I'm leaning to closing this PR because of this.

don't have any objections and agree with other points.

https://github.com/dani-garcia/vaultwarden/pull/4243#issuecomment-2162794434
@TheRsKing  thank you for helping with simple docker compose configuration

> if the caddy examples are really necessary

for me [it's a great starting point](https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose#caddy-with-http-challenge) if someone is working with this for the first time and has all the configuration on one page, and then if someone wants to do a more complex setup, they can look at the dedicated caddy wiki page.

2024-06-17 13:36 UTC, closed without merging