Update env template file
dani-garcia/vaultwarden pull request #4276
Opened 2024-01-27 12:38 UTC by gzfrozen

- Fix some default parameters which not match the config.rs.
- Categorize settings into sevral sections. Mainly followed the config.rs's structure.

2024-01-27 13:15 UTC, dfunkt requested changes

2024-01-27 13:15 UTC, dfunkt commented on .env.template
> +## The supported codes are 300 (legacy permanent), 302 (legacy temporary), 307 (temporary), and 308 (permanent).
Should be 301 instead of 300.

2024-01-27 13:15 UTC, dfunkt commented on .env.template
> +# ICON_REDIRECT_CODE=301
Default is 302 (https://github.com/dani-garcia/vaultwarden/blob/main/src/config.rs#L532)

2024-01-27 13:24 UTC, gzfrozen commented on .env.template
> +# ICON_REDIRECT_CODE=301
@dfunkt 
Wow, thank you for find out this mistake.
It's weird why I edit this number 😆

2024-01-27 13:48 UTC, dfunkt requested changes

2024-01-27 13:48 UTC, dfunkt commented on .env.template
> +# ICON_DOWNLOAD_TIMEOUT=9
```suggestion
## The default is 10 seconds, but this could be to low on slower network connections
# ICON_DOWNLOAD_TIMEOUT=10
```
https://github.com/dani-garcia/vaultwarden/blob/main/src/config.rs#L538

2024-01-27 13:56 UTC, dfunkt approved these changes

2024-01-27 13:58 UTC, gzfrozen commented
@dfunkt 
I think this wired number decrease mistake is cause by my editor vim binding, which seems Ctrl-X is decrease number.
I will check out the file again.

2024-01-27 14:12 UTC, gzfrozen commented
> @dfunkt I think this wired number decrease mistake is cause by my editor vim binding, which seems Ctrl-X is decrease number. I will check out the file again.

OK I think it is safe for digital derement mistakes.

2024-01-27 14:24 UTC, BlackDex requested changes
Looks ok in general, some sections might be better merged like i suggested in my comments. And some values seem to be missing.

I have not yet checked for other missing values which are currently in the config code.

2024-01-27 14:24 UTC, BlackDex commented on .env.template
> +# ROCKET_WORKERS=10
The workers default isn't 10. It will match `num_cores` by default. Also, best to leave it as default instead of setting this manually. So, maybe best to remove this setting, as it will only be confusing i think.

2024-01-27 14:24 UTC, BlackDex commented on .env.template
> +## See https://rocket.rs/v0.4/guide/configuration/ for more details.
This link can be updated to https://rocket.rs/v0.5/guide/configuration/

2024-01-27 14:24 UTC, BlackDex commented on .env.template
>  # vim: syntax=ini
Please add a empty new-line at the end of the file, that best practice in general.

2024-01-27 14:24 UTC, BlackDex commented on .env.template
> +# AUTHENTICATOR_DISABLE_TIME_DRIFT=false
This is best placed together with the Yubico and DUO settings, since they all fall under the same section, MFA/2FA.

2024-01-27 14:24 UTC, BlackDex commented on .env.template
> +# EMAIL_ATTEMPTS_LIMIT=3
This is best placed together with the Yubico and DUO settings, since they all fall under the same section, MFA/2FA.

2024-01-27 14:24 UTC, BlackDex commented on .env.template
>  ## - PostgreSQL: ""
This comment has nothing to do specifically with the setting bellow.

Also, the defaults are different per Database engine which is used.
MariaDB/Mysql and PostgreSQL are both empty, and for SQLite it is `PRAGMA busy_timeout = 5000; PRAGMA synchronous = NORMAL;`

See: https://github.com/BlackDex/vaultwarden/blob/8b66e3441571fdb71f0610882d1ee47dccc8c0a3/src/db/mod.rs#L231-L238

2024-01-27 14:27 UTC, BlackDex commented on .env.template
> +# ICON_DOWNLOAD_TIMEOUT=9
Probably a `CTRL+x` issue also ;)

2024-01-27 14:55 UTC, gzfrozen commented on .env.template
> +
@BlackDex 
`YUBICO_CLIENT_ID` setting is not missing. 
Line 432, 433 is automatically hiddened by the github review UI I guss.

2024-01-27 14:56 UTC, gzfrozen commented on .env.template
> +
@BlackDex 
Also these settings is not missing. Just hidden by Github review UI.
They are in line 446~448

2024-01-27 14:59 UTC, BlackDex commented on .env.template
> +
Ah, indeed, sorry.

2024-01-27 15:00 UTC, BlackDex commented on .env.template
> +
Indeed sorry.

2024-01-27 15:16 UTC, gzfrozen commented on .env.template
>  ## - PostgreSQL: ""
@dfunkt 
This is also an Github review UI accident.
Line 77~79 is folded.

2024-01-27 15:26 UTC, gzfrozen commented
@BlackDex 
Thank you for your review!
Fixed all metioned problems above. 

A big change is that I merged the Yubico, Duo, Email 2FA settings and other related settings into a big "MFA/2FA settings" section.

2024-01-27 21:43 UTC, BlackDex requested changes
Looks like almost done :)

2024-01-27 21:43 UTC, BlackDex commented on .env.template
>  # EVENT_CLEANUP_SCHEDULE="0 10 0 * * *"
Now that i think of it, it might be better to keep `EVENTS_DAYS_RETAIN` and `EVENT_CLEANUP_SCHEDULE` together.
But still keep the `EVENT_CLEANUP_SCHEDULE` option near (or maybe the last one) in the list of `SCHEDULE` settings.

Else this will be the only one not listed there.
Then we can put the `DAYS` setting just right after the `SCHEDULE` option, since they are related.

2024-01-28 04:06 UTC, gzfrozen commented on .env.template
>  # EVENT_CLEANUP_SCHEDULE="0 10 0 * * *"
OK, fixed👍

2024-01-28 13:14 UTC, BlackDex requested changes
Just some small extra changes to make it a bit better.
But i think this is a good improvement :)
Thanks!

2024-01-28 13:14 UTC, BlackDex commented on .env.template
> +# DOMAIN=https://vw.domain.tld:8443
It might be a good idea to also add a link to the reverse proxy examples on the wiki.
`https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples`

And, the example with a port is maybe not the best one, while it is useful though to indicate that it is possible.
With that in mind, an example with a sub-path is also useful.

So, maybe add a `https://vw.domain.tld` and `https://domain.tld/vw` also with a small comment, and make the one without a port the default `For public server` example.

2024-01-28 13:14 UTC, BlackDex commented on .env.template
> +# ICON_CACHE_NEGTTL=259200
Maybe add here that 2592000 seconds is 30 days? That makes it more clear.

2024-01-28 13:37 UTC, gzfrozen commented on .env.template
> +# DOMAIN=https://vw.domain.tld:8443
Do I also need to add these to wiki pages? Seems related.
https://github.com/dani-garcia/vaultwarden/wiki/Enabling-HTTPS
https://github.com/dani-garcia/vaultwarden/wiki/Running-a-private-vaultwarden-instance-with-Let%27s-Encrypt-certs

2024-01-28 13:42 UTC, BlackDex commented on .env.template
> +# DOMAIN=https://vw.domain.tld:8443
The Enable HTTPS is good i think, the other not so much, and is linked in the first.

2024-01-28 13:51 UTC, gzfrozen commented
> Just some small extra changes to make it a bit better. But i think this is a good improvement :) Thanks!

Thank you for your review! Changes been applied!

2024-01-28 16:49 UTC, BlackDex requested changes

2024-01-28 16:49 UTC, BlackDex commented on .env.template
> +# WEB_VAULT_ENABLED=tru
Spotted a buggy here. Should be `true` 😄

2024-01-29 10:37 UTC, gzfrozen commented on .env.template
> +# WEB_VAULT_ENABLED=tru
Sorry, my bad😆
Fixed it.

2024-01-30 18:15 UTC, dani-garcia approved these changes
LGTM, thanks!

2024-01-30 18:15 UTC, merged