Allow to override log level for specific target
dani-garcia/vaultwarden pull request #4305
Opened 2024-02-01 16:49 UTC by Timshel

Useful for either silencing some target when running in `debug` or switching `debug` only for a specific target,

With this a good chunk of the default overrides could be moved to the conf, cf:

```rust
        // Hide unknown certificate errors if using self-signed
        .level_for("rustls::session", log::LevelFilter::Off)
        // Hide failed to close stream messages
        .level_for("hyper::server", log::LevelFilter::Warn)
        // Silence Rocket `_` logs
        .level_for("_", rocket_underscore_level)
        .level_for("rocket::response::responder::_", rocket_underscore_level)
        .level_for("rocket::server::_", rocket_underscore_level)
        .level_for("vaultwarden::api::admin::_", rocket_underscore_level)
        .level_for("vaultwarden::api::notifications::_", rocket_underscore_level)
        // Silence Rocket logs
        .level_for("rocket::launch", log::LevelFilter::Error)
        .level_for("rocket::launch_", log::LevelFilter::Error)
        .level_for("rocket::rocket", log::LevelFilter::Warn)
        .level_for("rocket::server", log::LevelFilter::Warn)
        .level_for("rocket::fairing::fairings", log::LevelFilter::Warn)
        .level_for("rocket::shield::shield", log::LevelFilter::Warn)
        .level_for("hyper::proto", log::LevelFilter::Off)
        .level_for("hyper::client", log::LevelFilter::Off)
        // Filter handlebars logs
        .level_for("handlebars::render", handlebars_level)
        // Prevent cookie_store logs
        .level_for("cookie_store", log::LevelFilter::Off)
        // Variable level for trust-dns used by reqwest
        .level_for("trust_dns_resolver::name_server::name_server", trust_dns_level)
        .level_for("trust_dns_proto::xfer", trust_dns_level)
        .level_for("diesel_logger", diesel_logger_level)
```

2024-05-13 09:59 UTC, Timshel commented
Any interest in the feature ?

2024-05-18 16:16 UTC, BlackDex commented
It sounds like a nice feature. The only issue i have is, moving all defaults to config also means that either someone has to add all the defaults them self, or we someone need to provide a default and allow them to be overridden via the settings.

I'm also not sure on the multi-line formatting of the config. I would then rather use the standard of Rust it self.
https://rust-lang-nursery.github.io/rust-cookbook/development_tools/debugging/config_log.html

That allows for a general log_level settings as first item (or key less item) and are all comma separated.
That would allow you to keep using the `LOG_LEVEL` env for example and that will not break other instances.
It would then look like `LOG_LEVEL=info,hyper::client=info,handlebars::render=debug` for example.
We could have all defaults in a HashMap, and add or overwrite this with the configured items.

What do you think?

I btw also think this is very useful during development and troubleshooting issues reported by users :).

2024-05-18 16:36 UTC, Timshel commented
I think it all depends on if it's used for the current defaults.

Thinking on it, I believe it might be acceptable if all defaults are set (in `config.rs`) and in `env.template`.
I would expect that if someone then start customizing then they would copy and paste from the template; and if they don't do it then it's not really complicated for them to replicate it by adding the lines that generate too many logs. Additionally, a warning could be added to the release notes.

If used this way then it means it would contain at least 10 values and that's why I decided to make it multiline because I believe it makes it way more legible than a comma separated list.

If it's decided not to use it for the defaults then I believe your solution is better since with less values the comma separated solution would make more sense and risk less conflict due to the multiline.

But since I wrote it initially ^^ I believe the multiline is better since it allows the user to easily override the defaults while keeping a very simple logic in the rust code.

2024-05-18 16:45 UTC, Timshel commented
I was a bit fast with my response, the `Hashmap` you suggest would keep things quite simple while allowing override.

But I think I still prefer the multiline and default included in `env.template` because it makes those default more accessible and visible, as opposed at having to check in the code.

2024-05-18 17:06 UTC, BlackDex commented
The new line has some strange behavior in some environments, that is why I'm a bit against that way. While dotenvy does it correctly now, it might be systemd or other OS environments make it more error prone.

2024-05-21 14:44 UTC, BlackDex reviewed
Looks nice :).
Just a few questions

2024-05-21 14:44 UTC, BlackDex commented on Cargo.toml
> +regex = { version = "1.10.4", features = ["std", "perf", "unicode-case", "unicode-perl"], default-features = false }
Is the `unicode-case` feature really needed?
Isn't it better to parse the `LOG_LEVEL` config to a lowercase by default in the `config.rs` upon loading.
Also, since you seem to convert every part to lowercase anyway in the `init_logging` functon.
If you do it once, then it will save the repeating steps, and probably a faster regex too.

2024-05-21 14:44 UTC, BlackDex commented on src/main.rs
> +    let log_leve_rgx = regex::RegexBuilder::new(&log_level_rgx_str).case_insensitive(true).build()?;
I think adding this regex here as a var is fine, unless it is loaded multiple times. If that is the case, then i would suggest to convert it to a lazy_static. If it is called just once during load, then no problem.

2024-05-21 14:50 UTC, Timshel commented on src/main.rs
> +    let log_leve_rgx = regex::RegexBuilder::new(&log_level_rgx_str).case_insensitive(true).build()?;
Yes `init_logging()` is called only once in `main()`.

2024-05-21 14:52 UTC, BlackDex commented on src/main.rs
> +    let log_leve_rgx = regex::RegexBuilder::new(&log_level_rgx_str).case_insensitive(true).build()?;
Cool, then loading the regex once is fine here :).

2024-05-21 15:00 UTC, Timshel commented on Cargo.toml
> +regex = { version = "1.10.4", features = ["std", "perf", "unicode-case", "unicode-perl"], default-features = false }
The `unicode-case` is needed to use the `case_insensitive(true)` on the regex which will apply almost only on the `log_level` and I believe it's better to make it a bit more forgiving.

As for converting to lower case it's done only on the `log_level` part not the whole string. 
I believe module name in `rust` should always be snake case but still I think it's better not to risk transforming it.

And I just realized that the `LevelFilter::from_str` is in fact already case-insensitive, so they are not needed.

2024-05-22 13:31 UTC, BlackDex commented on Cargo.toml
> +regex = { version = "1.10.4", features = ["std", "perf", "unicode-case", "unicode-perl"], default-features = false }
I disagree here. You convert the levels to lowercase your self to match on. All crate names need to be lowercase as kinda mentioned here: https://blog.rust-lang.org/2023/10/27/crates-io-non-canonical-downloads.html

So, being forgiving can also be done by fully converting the `LOG_LEVEL` string to a lowercase value and match on that.
I also checked several log crates on how they handle this, and they just split the string on `=` and passes the split[1] element as level, since the log crate checks it case-insensitive anyway.

Also, converting everything to lowercase also makes it more forgiving on the crate-names if someone uses a capital there.

2024-06-28 13:30 UTC, Timshel commented
Hey, any chance to merge this ?

2024-06-28 14:09 UTC, BlackDex commented
Ill see if i have some time shortly to review again

2024-07-17 18:51 UTC, BlackDex requested changes
Looks nice, and seems to work great :).

Just some small items to address and i have questions about.

2024-07-17 18:51 UTC, BlackDex commented on src/config.rs
> +        /// Log level: `info,path::to::module=warn`
This is the wrong format. It now looks like this in the admin interface.
![image](https://github.com/user-attachments/assets/ee313679-5f06-4cea-8e68-adb73e4c0c71)

It probably should be something like this (wording or grammar not check)
```rust
/// Log level |> Valid values are "trace", "debug", "info", "warn", "error" and "off"
/// For a specific module append it as a comma separated value "info,path::to::module=debug"
```

2024-07-17 18:51 UTC, BlackDex commented on .env.template
> +# LOG_LEVEL=info,path::to::module=debug
We want the values in the template file to match with the default values mostly.
So probably best to keep it as `info`. But add a real working example maybe?
Something like this maybe?
```
## For example, to only see debug logs for icons use: LOG_LEVEL="info,vaultwarden::api::icons=debug"
```

2024-07-17 18:51 UTC, BlackDex commented on src/config.rs
>          log_level:              String, false,  def,    "Info".to_string();
Maybe the default can also be changed to a lowercase `info`. I do not think that will hurt anything.

2024-07-17 18:51 UTC, BlackDex commented on src/main.rs
> +        logger = logger.level_for(path.to_string(), level);
I have not tested it, but why is this sorted? Is there any benefit doing this?

I do not think it will matter in which order you set them. Fern will try to match the most specific path entry anyway, doesn't matter if it is added at the top or bottom of the list.

2024-07-17 19:32 UTC, BlackDex requested changes

2024-07-18 13:39 UTC, Timshel commented on src/main.rs
> +        logger = logger.level_for(path.to_string(), level);
Honestly it was simpler to sort than to test that the sort was not necessary :sweat_smile:.

2024-07-18 13:59 UTC, Timshel commented on src/config.rs
> +        /// Log level: `info,path::to::module=warn`
I think it's a leftover of when I made it editable for a time.

2024-07-18 14:22 UTC, BlackDex commented on src/main.rs
> +        logger = logger.level_for(path.to_string(), level);
But sorting when not needed at all is useless of course.

2024-07-23 16:19 UTC, BlackDex submitted a review, later dismissed
Thanks, looks like a nice addition :)

2024-07-23 22:49 UTC, dani-garcia commented on src/main.rs
>      }
I don't think this collect is necessary, you can just iterate over `default_levels` directly I think:
```suggestion
    for (path, level) in default_levels {
        logger = logger.level_for(path.to_string(), level);
    }
```

2024-07-24 07:42 UTC, Timshel commented on src/main.rs
>      }
O yes a leftover of when I removed the sort.

2024-07-24 11:20 UTC, BlackDex approved these changes

2024-07-24 14:48 UTC, dani-garcia approved these changes

2024-07-24 14:49 UTC, merged