Add playwright create/login test for all db
dani-garcia/vaultwarden pull request #4369
Opened 2024-02-20 18:08 UTC by Timshel

Hey

So I extracted the Playwright tests I wrote for the SSO PR since it could be reviewed independently.

This allow to test account creation and login on all three databases.

The setup phase might be a bit verbose but I didn´t want to introduce another dependency to handle the building.
Structure could be a bit more flat but in the SSO [PR](https://github.com/Timshel/vaultwarden/tree/sso-support/test) it include an additional `docker-compose` to run Keycloak.

2024-02-20 19:01 UTC, williamdes reviewed
Great idea to extract the tests.
Are they run by any CI ?
Should lines be added to .github/* workflow(s) ?

2024-02-20 19:18 UTC, Timshel commented
Since it's using docker to run `MaridaDb` and `Postgres` no idea how easy it is to integrate.
Additionally the SSO version use `docker-compose` :(

2024-02-20 20:39 UTC, tribut commented on test/scenarios/README.md
> +This allow to run integration testss using [Playwright](https://playwright.dev/).
```suggestion
This allows running integration tests using [Playwright](https://playwright.dev/).
```

2024-02-20 20:39 UTC, tribut commented on test/scenarios/README.md
> +It use it's own [test.env](/test/scenarios/test.env) with different ports to not collide with a running dev instance.
```suggestion
It uses its own [test.env](/test/scenarios/test.env) with different ports to not collide with a running dev instance.
```

2024-02-20 22:33 UTC, stefan0xC requested changes
Tanks for the PR and the initiative. Adding a way to do some form of integration testing has been on my personal todo list for a long time but I had no time to really dive into it. (I was evaluating the Rust-based options like [thirtyfour](https://crates.io/crates/thirtyfour) but I don't think it's there yet.)

1) I'm not sure I'm a fan of the `test/scenarios` subfolder. I think it would make more sense to add it in the root directory of the project (so that testing becomes more important and not hidden away) and adding support for CI would be great too. Which is why I've also suggested some changes that would be important if we decide to make testing more of a first class citizen. (But this can be done at a later time too probably, so maybe it's enough to rename it as `playwright` directory.)

2) I've not looked into playwright enough to suggest concrete changes but I think that fundamentally it's not configured correctly (i.e. instead of browsers we should use the databases as projects because vaultwarden is fundamentally a backend project). And also I'd like to have the option to only run `sqlite` tests since running the containers for the other databases takes a long time and most of the time I'd be developing against the sqlite database. (I mean so that I can run `npx playwright test --project=sqlite` to speed up the tests.)

3) The setup is currently not that useful for developing Vaultwarden, so this would have to be adapted to our needs. (And also for CI.) But I think it's a great proof of concept.

4) One change I'd also like to see is the removal of the SSO specific parts because I think those should be added separately.

5) Lastly (but that's just a nit), the project is called Vaultwarden not VaultWarden. :smirk:

2024-02-21 08:39 UTC, Timshel commented on test/scenarios/README.md
> +# OpenID Keycloak scenarios
O yes some leftover I missed sorry,

2024-02-21 08:57 UTC, Timshel commented
@stefan0xC hey first thanks for the review :).

> 1. I'm not sure I'm a fan of the `test/scenarios` subfolder. 

Unsure if you mean to move it to `/scenarios`  ? as I mentioned in SSO PR there is additional logic for SSO with a `docker-compose` for keycloak that can be used to test locally and for scenarios. It's living in `/test/oidc/keycloak`.

> 2.  on the databases

At first I wanted just a quick way to test migrations (made a broken one recently). But the projects feature look interesting will check it.

> 3. The setup is currently not that useful for developing Vaultwarden

I'm unsure what you mean by that, but yes they are integration tests not made for developing more for checking non regression of the core feature of the application.

> 4. One change I'd also like to see is the removal of the SSO 

Yep sorry some stragglers.

2024-02-21 08:58 UTC, Timshel commented on test/scenarios/tests/login_mariadb.spec.ts
> +    execSync(`docker run --rm --name ${process.env.MARIADB_CONTAINER} \
Will check project feature and probably keep only the `login.spec` with a way to run against a specified DB.

2024-02-21 09:03 UTC, Timshel commented on test/scenarios/global-setup.ts
> +            fs.rmSync("./data/web-vault", { recursive: true, force: true });
The `data` path is relative to `test/scenarios`.
Having this controlled by the tests allow to:
 - ensure tests are running against the correct version
 - run the test without external manual setups

2024-02-21 09:06 UTC, Timshel commented on test/scenarios/global-setup.ts
> +    retrieveFrontend();
I kind of see it the opposite way. The only place I would reuse prebuilt stuff is on the CI since I can trust what is used.
Locally I want it to run separately from my dev setup and for it to be as independent as possible to minimize the need for manual setup and the risk of running against an invalid version (Was thinking of keeping a hash of the src folder to ensure that the compile `vaultwarden` is up to date with the `src`).

2024-02-21 09:09 UTC, Timshel commented on test/scenarios/global-setup.ts
> +    if( !fs.existsSync('data/vaultwarden') ){
The  `data` folder is relative to the `test/scenario` an already kind of a temp folder.
By laziness I kept the `data` name since it's the default for the `DATA_FOLDER` setting.

2024-02-21 09:09 UTC, Timshel commented on test/scenarios/playwright.config.ts
> +    ],
Will look into it.

2024-02-21 09:41 UTC, stefan0xC commented on test/scenarios/playwright.config.ts
> +    ],
Something like the following should work, so we could also get rid of the database specific code:
```JavaScript
    projects: [
        {
            name: 'setup',
            testMatch: /global.setup\.ts/,
            teardown: 'teardown',
        },
        {
            name: 'teardown',
            testMatch: /global.teardown\.ts/,
        },
        {
            name: 'sqlite-teardown',
            testMatch: /sqlite.teardown\.ts/,
        },
        {
            name: 'firefox',
            use: { ...devices['Desktop Firefox'] },
	    dependencies: ['setup'],
        },
	{
	    name: 'sqlite',
	    dependencies: ['firefox'],
	    testMatch: /sqlite.setup\.ts/,
	    teardown: 'sqlite-teardown',
	},
	/* also for postgres and mariadb/mysql * /
    ],
```
The example was adapted from https://playwright.dev/docs/api/class-testproject#test-project-teardown but using the globalSetup could also work.

2024-02-21 10:22 UTC, stefan0xC commented
> Unsure if you mean to move it to `/scenarios` ? as I mentioned in SSO PR there is additional logic for SSO with a `docker-compose` for keycloak that can be used to test locally and for scenarios. It's living in `/test/oidc/keycloak`.
> 

I'd move it to `/playwright` for now (to keep the non-Rust stuff outside the root directory). I've not looked at your repository but it sounds to me like you are duplicating some setup stuff that should not be necessary.

Setup wise the stuff specific for SSO could be added to a separate project (that does a `SSO specific` setup). I've not thought about the folder layout but if we think long term it would make sense to me that tests specific to some kind of configuration that might require additional setup (i.e. if mail is required or not) should be possible and if we divide the stuff by subfolders (or have some naming convention) we can use `testMatch` and `testIgnore` to filter for the different test scenarios...

> > 3. The setup is currently not that useful for developing Vaultwarden
> 
> I'm unsure what you mean by that, but yes they are integration tests not made for developing more for checking non regression of the core feature of the application.
> 

I meant in context with my other comments in regards to what assumptions we make about the integration of the tests with the rest of the project and also if this should be part of the CI. For me this is more of an open discussion point and much of it should be addressed by the maintainers and/or could probably also be addressed later.

2024-02-21 10:32 UTC, stefan0xC commented on test/scenarios/global-utils.ts
> +        fs.rmSync("data/db.sqlite3-wal", { force: true });
Yeah, I wouldn't make it too configurable I meant more for test isolation to keep different test scenarios from interfering with each other and to get more of a clean slate.

2024-02-21 10:39 UTC, Timshel commented
> I'd move it to /playwright for now

I know it's not practical but I'd like to settle on a layout which work with the SSO stuff since my goal with this PR is to facilitate review. If I still need to move everything in the SSO pr it defeat the purpose.

> you are duplicating some setup stuff that should not be necessary

Can you give me some pointer on which stuff ?

> Setup wise the stuff specific for SSO could be added to a separate project

Since I configured the project for database I'm unsure how it would work.
I wrote just a separate test file which now can be tested against each of the DB (at least once I rebased).
And you can see that in the SSO tests I wrote I change the config ([ex](https://github.com/Timshel/vaultwarden/blob/sso-support/test/scenarios/tests/sso_login.spec.ts#L82)) of the server so I don't think the project mechanism would work 

There is the issue of detecting if we need to start the Keycloak stuff.

2024-02-21 10:43 UTC, stefan0xC commented on test/scenarios/global-setup.ts
> +    if( !fs.existsSync('data/vaultwarden') ){
That's my point that it's not temporary. The only files that will currently be deleted are the `db.sqlite3` files but what about the other files?
I mean, as it stand I can't just remove the `data/` folder because the vaultwarden binary and the web-vault are definitely not in the right location. (I.e. this should at least use the `WEB_VAULT_FOLDER` variable instead of assuming `data/web-vault`)

2024-02-21 11:27 UTC, stefan0xC commented
> I know it's not practical but I'd like to settle on a layout which work with the SSO stuff since my goal with this PR is to facilitate review. If I still need to move everything in the SSO pr it defeat the purpose.

Yeah, I get that but I think the keycloak stuff could just as well be added as a subfolder of the `playwright` directory (or if it makes more sense to the root directory of the project as well)? Since this is project written mainly in Rust I think that we might want to add a `tests` folder (for `cargo test`) eventually and it wouldn't do to have two similarly named folders (and keeping it as as separate folder named after the tool would be more in line with the `docker` folder). I mean, if we setup the playwright stuff to be more flexible I don't think that backporting the changes to your SSO PR would be that hard. (And like I said I'm not sure about the folder layout myself but I am definitely not a fan of looking into unnecessary subfolders.)

> Can you give me some pointer on which stuff ?

Sorry, like I said I've not looked at your repository. I'm thinking about keeping your SSO changes separate for now so it will be easier to merge. Having a separate setup file for SSO specific changes (i.e. everything you've ripped out to make the web-vault compatible) should be done in a separate setup file). I mean, ideally this shouldn't even be needed because the SSO stuff uses it's own official web vault build which can be just pointed at with `WEB_VAULT_FOLDER`.

2024-02-21 11:41 UTC, Timshel commented
Ok I'll move it to `/playwright`.
The Keycloak `docker-compose` is also used to run a dev instance that's why I did not include it directly.

Do you think it would make sense to move it inside the `docker` folder  ?  something like `docker/keycloak` (maybe with a dockerignore to prevent polluting the docker build context).

2024-02-21 14:21 UTC, Timshel commented on test/scenarios/global-setup.ts
> +    if( !fs.existsSync('data/vaultwarden') ){
I renamed it to temp,  and fixed the invalid reference to the Vaultwarden binary. Web-vault was fine I believe.

2024-02-21 14:22 UTC, Timshel commented
So moved everything and used `Projects` in the SSO PR and it's not too bad : https://github.com/Timshel/vaultwarden/blob/sso-support/playwright/playwright.config.ts#L38

2024-05-13 10:12 UTC, Timshel commented
Hey,

Where do we stand with this ?  Is there still interest ? Should I change the way it works ?
I could expand the tests but not before this is merged.

This would probably be useful to help with faster merge/integration of the front-end.
For ex https://github.com/dani-garcia/bw_web_builds/pull/160 is out of date again since `v2024.4.3` was released.

2024-05-13 10:17 UTC, stefan0xC commented
> For ex [dani-garcia/bw_web_builds#160](https://github.com/dani-garcia/bw_web_builds/pull/160) is out of date again since `v2024.4.3` was released.

[`web-v2024.4.3`](https://github.com/bitwarden/clients/releases/tag/web-v2024.4.3) has not been released.

2024-05-13 10:24 UTC, Timshel commented
A yes I was a bit fast when I checked the release, but my point is more that there is a struggle to keep pace with the clients release.

2024-05-14 19:09 UTC, stefan0xC commented
Well, I am interested but like I said I don't think that the current implementation is all that useful yet for how we do things and in my view we should discuss first how this would help us and where.

> I don't know what is the current flow

The current flow is that when upstream releases a new web-vault, someone creates a PR in the [bw_web_builds](https://github.com/dani-garcia/bw_web_builds) repository (where we keep track of our patches for the web-vault), this is then reviewed, merged and released. After the patched web-vault is released (and built and uploaded by CI), someone also has to create a PR to use the new web-vault in vaultwarden (which also needs to be merged as well to land in `testing`).

We certainly could improve this flow by adding playwright tests to the mix, as it would make it easier for making sure our patches stay compatible and reduce the burden of the maintainers but as I said that's a larger discussion because it might not make sense to add it to the `vaultwarden` repository when the patches to the web-vault are kept and developed in a separate repository.

Personally, I think that we probably could switch to a monorepo approach or alternatively have a separately managed repository for testing but that's something I'd like the input from @BlackDex and @dani-garcia on. I mean for me it would also make sense to rethink how vaultwarden is released and maybe work on multiple branches, e.g. a `stable` branch for hot fixes to the latest release, a `testing` branch for preparing the next release and an `unstable` one which tracks the latest changes and where the integration between the web-vault and vaultwarden (or new features) might not be guaranteed. (But that's something that the maintainers would have to decide.)

2024-05-14 21:23 UTC, Timshel commented
Thinking on it in this current version it would be awkward to try to use it to validate new version of the front-end since I made it to rely on something already published. Of course, it could be changed but it would still mean using something outside the project.

At the same time I don't think moving this outside of Vaultwarden is a good idea since it's useful to ensure non regression from code modification in Vaultwarden and I found it quite useful to test things like database migration too (on all engines which is quite a pain manually otherwise).

2024-07-06 21:11 UTC, Timshel commented
Hey

Worked on it a bit, wanted to add the ability to run against a non released version of `bw_web_builds`.
Made it able to run the docker build and extract the `web-vault` of a commit from a configurable `bw_web_builds` project.
But the Playwright setup was becoming even more janky :(.

So switched to using `docker-compose` to handle the build, this make it way cleaner but can't make it to handle conditional dependencies.

So running tests for postgres looks something like this

```bash
export DOCKER_BUILDKIT=1
docker-compose --env-file test.env --profile postgres  up -d Postgres
docker-compose --env-file test.env run Playwright test --project=postgres
```

To run with a custom version of the web-vault:
```bash
export DOCKER_BUILDKIT=1
export PW_WV_REPO_URL=https://github.com/stefan0xC/bw_web_builds
export PW_WV_COMMIT_HASH=c5b5279a8478385cee66a8cdfc804690cffe0315
docker-compose --env-file test.env up --build WebVault
docker-compose --env-file test.env run Playwright
```

Part of the handling of dependencies could be hidden/improved with a script.

2024-07-08 20:37 UTC, Timshel commented
Added `docker-compose` control in `Playwright` so to run all tests:

```bash
export DOCKER_BUILDKIT=1
docker-compose --env-file test.env run Playwright
```

2024-07-26 17:00 UTC, Timshel commented
Added integration with https://github.com/maildev/maildev in the tests to be able to check the mail sent.
This will allow to test things like 2FA mail authentication and organization invitation.

2024-08-20 15:30 UTC, Timshel commented
Added some Organization invitation tests and switched to the `compose` plugin instead of `docker-compose`.
This now depends on : 
- https://github.com/dani-garcia/vaultwarden/pull/4827
- https://github.com/dani-garcia/vaultwarden/pull/4856

2024-09-05 15:15 UTC, Timshel commented
Rebased on main since both previously PR are merged :).
Added some email 2FA tests :).

2024-09-12 13:26 UTC, closed without merging