Change API and structs to camelCase
dani-garcia/vaultwarden pull request #4386
Opened 2024-02-28 00:10 UTC by dani-garcia

This PR changes all the project's structs and API inputs and outputs from the old `PascalCase` format to the new `camelCase` format. At the moment the clients support both but that won't be a thing forever.

I haven't had the time to fully test this, but at least the basic things work. There may be some things missing, and I still need to review what we store in the db to make sure that there aren't any backwards compat issues.

This might also cause problems with other pending PRs so we can wait to merge it until they are dealt with.

Some fields that have special casing:
- `OTP` in `/accounts/verify-otp`, as that's what the clients send. That said we also check `otp`
- `Keys` and `Nfc` in yubikey, this is for backwards compat with older values stored on the server, now we serialize new versions to `keys` and `nfc`.
- `AttestationObject` and `clientDataJson` in webauthn, as that's what the clients send. This is a bigger annoyance as it complicates the use of the webauthn crate.
- Organization policies, this is for backwards compat with older values stored on the server, now we serialize new versions as `camelCase`.

2024-05-25 15:44 UTC, BlackDex requested changes
I still see a few non-camelCase key's in outputted JSON. For example in `identity.rs`
Ill check further but this was what is saw rather quickly.

2024-05-25 15:51 UTC, BlackDex commented
Also, card vault types have `SSN` in there, that currently seems to be converted to `sSN`, which will probably break.

2024-05-25 16:31 UTC, BlackDex commented
Also, not sure, but isn't it more useful to use `fn convert_json_key_lcase_first` from the utils mod? It might need some adjustments to also check for `ssn` maybe, but that should help with nested values stored in the database. And also for items like the Org Policies for example.

2024-06-16 15:25 UTC, quexten commented
On this PR, and web 2024.05 confirming users to orgs does not work (I'm not sure if this is due to the PR, or due to the web vault changing), but since this is the same kind of issue it makes sense to solve here. Specifically, the body the web vault sends contains "key:", while the server expects "Key:" on the post body to` /api/organizations/{orgid}/users/{userid}/confirm`

2024-06-16 15:38 UTC, quexten commented
Also, for native app compatibility, there seem to be some keys missing for organization profile responses, like 

["accessSecretsManager"](https://github.com/bitwarden/server/blob/b5241f1a9731ea74f22c2f4fe1072421f857429e/src/Api/AdminConsole/Models/Response/ProfileOrganizationResponseModel.cs#L157-L160)

causing the native app(s) [only tested for iOS] to crash for accounts in an organization.

2024-06-16 16:42 UTC, quexten commented
Also, somehow all custom fields in sync are null on this branch.

2024-06-16 21:09 UTC, dani-garcia commented
@quexten Thanks for the review! I fixed the invalid case in `key` for the confirm and added the missing organization profile fields, which seems to work in both the new android and ios apps. The null fields should be also fixed with https://github.com/dani-garcia/vaultwarden/pull/4386/commits/d5148bc38639036b4b9fdb271275bdcc3f8c9b14, we were parsing the JSON incorrectly and ignoring the error.

@BlackDex I didn't even notice `convert_json_key_lcase_first` being there, but yeah I've switched it over in https://github.com/dani-garcia/vaultwarden/pull/4386/commits/f0bf5bd7f9ca799ff4040cdd0228040ea18528c4, which required adding the check for `ssn` using `_process_key` (also removed some clones)

2024-06-18 23:31 UTC, dani-garcia commented
Native apps are available in beta now, so we should try getting this merged soon: 
https://fosstodon.org/@bitwarden/112639925158165590
https://community.bitwarden.com/t/about-the-beta-program/39185

2024-06-18 23:35 UTC, dani-garcia commented
So far only bug remaining that I know of is that the Android app can't upload attachments or sends.

The android app sends a `multipart/mixed` header instead of the `multipart/form-data` header that the ios app and the rest of the clients send. I'll see if that's something we can change in the app.

2024-06-19 10:38 UTC, BlackDex commented
Ill see if i can do some more testing soon.

2024-06-19 13:43 UTC, BlackDex requested changes
I just did some testing with my local accounts i use for debugging, and these are my findings so far.

- The admin UI doesn't work, the user and org overview are broken because the handlebar templates are not updated.
- For some reason in the Android Emulator i can't login at all, but that is not something we can fix i think.

On my physical phone (Pixel 7) it also doesn't work, i can login, but the sync fails on the client side.

- Sends have a `text` object which have the keys `Hidden` and `Text` those are still capital-case
```json
  "text": {
      "Hidden": false,
      "Text": "2.j2Z/rN...TbjMvCQ==|/Kk0bfdc...68kv8A==|W1qbVban...AVJYYJRPy/WbK5iQeEQJIWwJh1k="
  }
```
- The same for Sends `file`:
```json
  "file": {
      "FileName": "2.KcN9y...GuollclQ==|XxaO+KyT4fjIIYRb...MNxZ8VeHAAz4=|hruuM...PU4A=",
      "Id": "25587de08f158fe7ecfef24d22fc600c596efaf53bc5d7e23125e75c033a49bb",
      "Size": 10737,
      "SizeName": "10.49 KB"
  },
```

Other than that, i have not yet found anything which could be wrong any futher

2024-06-19 13:59 UTC, BlackDex commented
Small update, Those sends were added via the PascalCase version of Vaultwarden.

2024-06-19 15:33 UTC, dani-garcia commented
Okay, sends should be fixed and changed to lowercase now, and the admin templates are updated too.

I've also updated the org revoke API endpoint which was using `Ids` as key too.

2024-06-20 09:52 UTC, BlackDex commented
Login with device seems to result in an error, where the request was unable to be processed.
Not checked how this works for the current vault.bitwarden.com though.

2024-06-20 11:29 UTC, albatrosify commented
I've tried sends: Text is okay. File results in an error for me with the beta app...
I compiled the remove_upcase branch just 10 mins ago...

2024-06-20 14:48 UTC, BlackDex commented
Some values need to be converted from `int` to `String`, else the client will fail on those.
Not sure if the `MasterPasswordPolicy` need to be there too, but it at least is in Upstream.

```diff
diff --git a/src/api/identity.rs b/src/api/identity.rs
index 89c82859..523a267a 100644
--- a/src/api/identity.rs
+++ b/src/api/identity.rs
@@ -564,8 +564,11 @@ async fn _json_err_twofactor(providers: &[i32], user_uuid: &str, conn: &mut DbCo
     let mut result = json!({
         "error" : "invalid_grant",
         "error_description" : "Two factor required.",
-        "TwoFactorProviders" : providers,
-        "TwoFactorProviders2" : {} // { "0" : null }
+        "TwoFactorProviders" : providers.iter().map(|i| i.to_string()).collect::<Vec<String>>(),
+        "TwoFactorProviders2" : {}, // { "0" : null }
+        "MasterPasswordPolicy": {
+            "Object": "masterPasswordPolicy"
+        }
     });
 
     for provider in providers {
```

2024-06-20 18:55 UTC, dani-garcia commented
I fixed an issue with Sends sending their size as a number which was breaking the ios app, also fixed the issue mentioned with twofactorproviders

2024-06-21 16:44 UTC, albatrosify commented
I can confirm this solves the issue I had with sends.

2024-06-23 19:29 UTC, BlackDex approved these changes

2024-06-23 19:31 UTC, merged

2024-06-23 20:23 UTC, dani-garcia commented
I see there's a lot of interest in this issue so for anyone who's following this, the docker images including this PR are now available at the `vaultwarden/server:testing` and  `vaultwarden/server:testing-alpine` tags. Please let us know if you find any issues with them. Thanks!

2024-06-23 21:31 UTC, BlackDex commented
> POST /api/ciphers/create fails on testing using Android Native Beta

I can reproduce this too. Looks like the client still send `Cipher` instead of `cipher`. Not sure if that is intended.

2024-06-23 21:57 UTC, WesleyBryie commented
I can also reproduce, running latest Bitwarden Beta on Android 14 and `testing` branch pulled just a minute ago on my vaultwarden instance. BW app shows "We were unable to process your request. Please try again or contact us."

2024-06-24 16:33 UTC, lukasj98 commented
On IOS it is working perfect ( Version 2024.6.1 Build 1151, IOS 17.5.1)

2024-06-24 17:45 UTC, dani-garcia commented
The issue with cipher creation in Android should be fixed now with https://github.com/dani-garcia/vaultwarden/pull/4670, builds should be ready in half an hour-ish

2024-06-24 17:55 UTC, andre1808 commented
Sorry if this is an odd question, but can I share the data set of the prod version along the testing version?

I’ve tried the testing image earlier (seperate data folder) and it was working fine on my iPhone. So I thought about using it along the prod environment and maybe switch apps back and forth.

2024-06-24 18:00 UTC, BlackDex commented
If the database is not SQLite, it kinda can. Push/Websocket notifications will not traverse those different servers, but that is about it

2024-06-24 18:39 UTC, TheRsKing commented
I can also confirm that it works on iOS

2024-06-24 20:56 UTC, tonyxu-io commented
I'm unable to download/view attachment on iOS beta app. Not sure if that's related though.

2024-06-24 21:27 UTC, BlackDex commented
> I'm unable to download/view attachment on iOS beta app. Not sure if that's related though.

Works for me on Android. Check your domain settings. If those are not correct it will not work.

2024-06-24 22:12 UTC, lukasj98 commented
> I'm unable to download/view attachment on iOS beta app. Not sure if that's related though.

It is working perfect on iOS

2024-06-25 00:32 UTC, tonyxu-io commented
> > I'm unable to download/view attachment on iOS beta app. Not sure if that's related though.
> 
> It is working perfect on iOS 

I just tested again. It seems like image attachments works fine but PDF attachment doesn't work.

2024-06-25 06:07 UTC, BlackDex commented
> > > I'm unable to download/view attachment on iOS beta app. Not sure if that's related though.
> > 
> > 
> > It is working perfect on iOS
> 
> I just tested again. It seems like image attachments works fine but PDF attachment doesn't work.

PDF works fine for me too. it might be your phone which has issues with the attachment maybe? For me it just saves the files and i need to open it with a different app afterwards. So it doesn't matter what extension it is using.

2024-07-07 04:37 UTC, ItsMelody commented
Am I correct in understanding that we are now supposed to be able to connect to self-hosted Vaultwarden instances in the new Beta app of Bitwarden? Because I haven't had any updates on my docker container for Vaultwarden and it also still doesn't let me log in with the Beta app...

2024-07-07 04:54 UTC, tonyxu-io commented
> Am I correct in understanding that we are now supposed to be able to connect to self-hosted Vaultwarden instances in the new Beta app of Bitwarden? Because I haven't had any updates on my docker container for Vaultwarden and it also still doesn't let me log in with the Beta app...

You need to use testing branch.

https://github.com/dani-garcia/vaultwarden/pull/4386#issuecomment-2185313928

2024-07-07 05:09 UTC, magisk317 commented
I can log in to the beta version, but I can't sync/refresh the data. The log is as follows. Who can help me?

App prompt, "We are unable to process your request.Please try again or contact us."

```
[2024-07-07 05:01:27.691][request][INFO] GET /api/devices/knowndevice
[2024-07-07 05:01:27.693][response][INFO] (get_known_device) GET /api/devices/knowndevice => 200 OK
[2024-07-07 05:01:52.495][request][INFO] POST /identity/accounts/prelogin
[2024-07-07 05:01:52.497][response][INFO] (prelogin) POST /identity/accounts/prelogin => 200 OK
[2024-07-07 05:01:52.912][request][INFO] POST /identity/connect/token
[2024-07-07 05:01:53.040][vaultwarden::api::identity][INFO] User *****@***.com logged in successfully. IP: 10.0.0.20
[2024-07-07 05:01:53.040][response][INFO] (login) POST /identity/connect/token => 200 OK
[2024-07-07 05:01:54.079][request][INFO] GET /api/accounts/revision-date
[2024-07-07 05:01:54.082][response][INFO] (revision_date) GET /api/accounts/revision-date => 200 OK
[2024-07-07 05:01:54.089][request][INFO] GET /api/sync
[2024-07-07 05:01:54.133][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
[2024-07-07 05:01:54.136][request][INFO] GET /api/ciphers/has-unassigned-ciphers
[2024-07-07 05:01:54.137][vaultwarden::api::core::ciphers][ERROR] Cipher doesn't exist
[2024-07-07 05:01:54.137][response][INFO] (get_cipher) GET /api/ciphers/<uuid> => 400 Bad Request
[2024-07-07 05:01:57.487][request][INFO] GET /api/accounts/revision-date
[2024-07-07 05:01:57.488][response][INFO] (revision_date) GET /api/accounts/revision-date => 200 OK
[2024-07-07 05:01:57.507][request][INFO] GET /api/sync
[2024-07-07 05:01:57.540][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
```

2024-07-07 07:55 UTC, BlackDex commented
@magisk317 , then there might be something else in your data which either isn't correct and maybe we should fix, or something else strange.

Have you tried the latest mobile app version?
Try the latest build from the build workflow artifacts.
Android: https://github.com/bitwarden/android/actions/workflows/build.yml
iOS: https://github.com/bitwarden/ios/actions/workflows/build.yml

2024-07-07 08:11 UTC, magisk317 commented
> @magisk317，那么您的数据中可能还存在其他不正确的内容，也许我们应该进行修复，或者存在其他奇怪的内容。
> 
> 您尝试过最新的移动应用程序版本吗？ 尝试从构建工作流工件中获取最新版本。Android ： https: [//github.com/bitwarden/android/actions/workflows/build.yml](https://github.com/bitwarden/android/actions/workflows/build.yml) iOS：https: [//github.com/bitwarden/ios/actions/workflows/build.yml](https://github.com/bitwarden/ios/actions/workflows/build.yml)

I tried, the phenomenon is the same, even the log is the same, but strangely, unofficial clients can be used normally, such as [keyguard](https://github.com/AChep/keyguard-app/tree/r20240417).

2024-07-07 08:41 UTC, BlackDex commented
The new clients are more strict. So something in the output of the sync is causing issues. Unless we can see the output it would be hard for us to figure out out.

It probably is something in the data column in the ciphers table.
But it could be something else.

2024-08-15 13:22 UTC, ZerkerEOD commented
Is there a fix for this? I just had my android app updated and as soon as I log in I am greeted with that message. I updated the backend and that didn't fix it for me.

2024-08-15 13:42 UTC, BlackDex commented
@ZerkerEOD with what message? And what is the specific issue?
Did you updated to Vaultwarden v1.32.0?

2024-08-15 14:02 UTC, mhzawadi commented
@ZerkerEOD can confirm that `1.32.0` does fix any issues with the new Bitwarden Beta app, make sure your running `1.32.0`

2024-08-15 14:12 UTC, ZerkerEOD commented
> @ZerkerEOD with what message? And what is the specific issue? Did you updated to Vaultwarden v1.32.0?

The message is, "We were unable to process your request. Please try again or contact us." If I click try again it does the same thing. If I go to the Settings -> Other - There is no date for last sync and if I click the “Sync now” button it just goes into a sync that won't end unless I force close the app. 

The server is showing version 1.32.0. Looks like the official bitwarden app is the cause as my vault works every where else. The app updated to the beta version finally and it started. So I left the beta and deleted and reinstalled and it looks like they pushed the beta into production.

2024-08-15 14:21 UTC, mhzawadi commented
@ZerkerEOD Your very right, the old app is now the new Beta app. But both work for me, did you reset the data for the app?

2024-08-15 14:25 UTC, ZerkerEOD commented
> @ZerkerEOD Your very right, the old app is now the new Beta app. But both work for me, did you reset the data for the app?

I did, I first tried to delete cache and storage, then I deleted the application, left the beta, waited for that to register and then installed the app fresh again. Still doing the same thing.

2024-08-15 14:45 UTC, mhzawadi commented
@ZerkerEOD Did you update your LB config to remove the WebSockets stuff?

2024-08-15 15:44 UTC, ZerkerEOD commented
> @ZerkerEOD Did you update your LB config to remove the WebSockets stuff?

To be honest, I never had any load balancer stuff in my LB configs. I use Traefik for that and it has the following:

![image](https://github.com/user-attachments/assets/b70ee5fc-de19-431b-9307-1a09ea5d04f0)

My web entry point automatically redirects everything to HTTPS also. So I could technically remove the web from the entry points.

2024-08-15 15:50 UTC, BlackDex commented
It then must be some entry which is causing an issue.
You might want to try the debug android build which you can download from the release page in the Bitwarden repo on GitHub. 

And then use adb to see if something there reports what the issue is. That would help us fix this.

Else you need to inspect the sync response manually and see if you see anything strange there compared to all other emtries.

2024-08-15 16:32 UTC, ZerkerEOD commented
I will get to that hopefully later today if not this weekend. I am a little busy right now. I was able to get it working using Keyguard. But I do prefer the original app.

2024-08-31 14:53 UTC, ZerkerEOD commented
@BlackDex, do you know what ADB commands would be needed? I have used it before to root my phones but that is about it.

2024-08-31 15:20 UTC, BlackDex commented
well, first you need to install the `-dev`/`-qa` app, else no output will be shown at all.
But it seems it will only show the http requests/responses. No errors seem to appear at all in the logs.

So, you might still try. The command you are looking for is probably `adb logcat`.
Also see https://github.com/dani-garcia/vaultwarden/issues/4870, where there are some posts which describe on how to get some details.

2024-11-18 04:44 UTC, magisk317 commented
> @BlackDex, do you know what ADB commands would be needed? I have used it before to root my phones but that is about it.

@ZerkerEOD I don't know if your problem has been solved? But my problem is still there...

@BlackDex I installed the dev version and grabbed the logcat, I don't know if it will be useful for this problem, if there is anything else that needs to be done, you can comment me

[log.txt](https://github.com/user-attachments/files/17794749/log.txt)

2025-01-18 10:06 UTC, celevra commented
Same problem here: We were unable to process your request. Please try again or contact us.

2025-01-20 07:53 UTC, celevra commented
we are on 1.32.7 isnt it the latest release?

2025-01-20 07:54 UTC, BlackDex commented
Try testing then, which has some extra fixes not yet released

2025-01-20 07:55 UTC, Gerardv514 commented
> we are on 1.32.7 isnt it the latest release?

I'd imagine same error but different problem then.

2025-01-21 07:55 UTC, celevra commented
no changes if i switch to testing. The new app isn't usable.

```
### Your environment (Generated via diagnostics page)

* Vaultwarden version: v1.32.7-ef2695de
* Web-vault version: v2025.1.0
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Database type: SQLite
* Database version: 3.46.0
* Environment settings overridden!: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Websocket Check: true
* HTTP Response Checks: true

### Config & Details (Generated via diagnostics page)

<details><summary>Show Config & Details</summary>

**Config:**

```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "***:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_connect_src": "",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://******************",
  "domain_origin": "*****://******************",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "enforce_single_org_with_reset_pw_policy": false,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Zeitschel",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": true,
  "push_identity_uri": "https://identity.bitwarden.eu",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.eu",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": true,
  "signups_domains_whitelist": "*************,******************,*********,**************************",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "*********************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "*********************",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "*******",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": "97896",
  "yubico_secret_key": "***",
  "yubico_server": null
}
```

</details>

```

2025-01-22 12:02 UTC, P3RF3CTION commented
I can confirm the error/issue using latest web vault and vaultwarden version as in the comment above (only difference Ubuntu 24.04 os). Tested with latest bitwarden and beta app of bitwarden on Android. I would appreciate any help or necessary logs to provide as evidence.

2025-01-22 12:04 UTC, BlackDex commented
@P3RF3CTION Are you using `latest` or `testing` tagged container images?
Since the current `testing` tagged images based upon the `main` branch have some fixes not yet released to a stable version yet.

2025-01-22 12:06 UTC, BlackDex commented
@celevra, what is the message you get?
If using an Android device, what does `adb logcat` return when you try to do a sync?
What are there any sync attempts done at all according to the Vaultwarden logs?

2025-01-22 12:12 UTC, celevra commented
@BlackDex in the App i get 'We were unable to process your request. Please try again or contact us.'
in the log i can see
```
[2025-01-22 12:11:20.004][request][INFO] GET /api/sync
[2025-01-22 12:11:20.266][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
```
i have no clue what adb logcat is, i will ask google ;-)

2025-01-22 12:12 UTC, BlackDex commented
Asking google will be the right place as it's the android debug tool hehe.

2025-01-22 12:14 UTC, BlackDex commented
Also @P3RF3CTION same for you, try to see what `adb logcat` shows.

For me i can login and sync with a test account which has broken entries in the database and are fixed during sync.
It can be that you need to full clear data of the app and login again because sometimes the cached data could cause issues too.

2025-01-22 12:17 UTC, celevra commented
@BlackDex allready cleared the app, thats not the Problem

2025-01-22 12:57 UTC, celevra commented
@BlackDex here is the logcat

```
01-22 13:55:57.030  2565  2565 D FreecessController: UFZ : com.x8bit.bitwarden(11308)
01-22 13:55:57.031  2565  2565 D FreecessController: UFZ : com.x8bit.bitwarden(0), reason: TopApp-ScreenOn
01-22 13:55:57.103  2565  3729 D MdnieScenarioControlService:  packageName : com.x8bit.bitwarden    className : com.x8bit.bitwarden.MainActivity
01-22 13:55:58.161  2565  7559 V WindowManager: Collecting in transition 11561: ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}, caller=com.android.server.wm.Transition.collect:753 com.android.server.wm.TransitionController.collect:975 com.android.server.wm.ActivityRecord.setVisibility:6429 com.android.server.wm.ActivityRecord.setVisibility:6381 com.android.server.wm.TaskFragment.resumeTopActivity:1741
01-22 13:55:58.161  2565  7559 D WindowManager: prepareSync <SYNC_STATE_WAITING_FOR_DRAW>, mPrepareSyncSeqId=0, win=Window{38894d u0 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity}
01-22 13:55:58.162  2565  7559 V WindowManager: Setting visibility of Window{38894d u0 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity}: true, caller=com.android.server.wm.WindowContainer.sendAppVisibilityToClients:1305 com.android.server.wm.WindowToken.setClientVisible:454 com.android.server.wm.ActivityRecord.setClientVisible:8235 com.android.server.wm.ActivityRecord.setVisibility:6532 com.android.server.wm.ActivityRecord.setVisibility:6381
01-22 13:55:58.162  2565  7559 D ActivityTaskManager: scheduleTopResumedActivityChanged, onTop=true, r=ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}, caller=com.android.server.wm.ActivityTaskSupervisor.scheduleTopResumedActivityStateIfNeeded:2904 com.android.server.wm.ActivityTaskSupervisor.updateTopResumedActivityIfNeeded:2896 com.android.server.wm.TaskFragment.setResumedActivity:580 com.android.server.wm.TaskFragment.onActivityStateChanged:904 com.android.server.wm.ActivityRecord.setState:6892 com.android.server.wm.TaskFragment.resumeTopActivity:1756
01-22 13:55:58.162  2565  7559 D WindowManager: rotationForOrientation, orientationSource=ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}
01-22 13:55:58.162  2565  7559 D WindowManager: rotationForOrientation, orientationSource=ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}
01-22 13:55:58.163  2565  7559 D WindowManager: rotationForOrientation, orientationSource=ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}
01-22 13:55:58.164  2565  7559 V WindowManager: Collecting in transition 11561: ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}, caller=com.android.server.wm.Transition.collect:753 com.android.server.wm.TransitionController.collect:975 com.android.server.wm.ActivityRecord.setVisibility:6429 com.android.server.wm.ActivityRecord.setVisibility:6381 com.android.server.wm.ActivityRecord.completeResumeLocked:7499
01-22 13:55:58.164 11308 11308 D ViewRootImpl@817cd79[MainActivity]: WindowStopped on com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity set to false
01-22 13:55:58.165  2565  7559 D WindowManager: rotationForOrientation, orientationSource=ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}
01-22 13:55:58.165  2565  7559 D ActivityTaskManager: Add starting ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}: typeParam=62 startingData=com.android.server.wm.SnapshotStartingData@6de8f3
01-22 13:55:58.166  2565  7559 V WindowManager: Added starting ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}: startingWindow=null startingView=com.android.server.wm.StartingSurfaceController$StartingSurface@ab869b0
01-22 13:55:58.167  2565  2834 D WindowManager: SyncGroup 11561:  Unfinished container: ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006} mSyncState=2
01-22 13:55:58.168  2565  4842 V WindowManager: addWindow: ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006} startingWindow=Window{7a9005e u0 SnapshotStartingWindow for taskId=49006}
01-22 13:55:58.170  2565  3988 D WindowManager: SyncGroup 11561:  Unfinished container: ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006} mSyncState=2
01-22 13:55:58.174  2565  2834 V WindowManager: Start calculating TransitionInfo based on participants: {ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}}
01-22 13:55:58.174  2565  2834 V WindowManager:   Final targets: [Task{7cd7471 #49006 type=standard A=10713:com.x8bit.bitwarden}, DefaultTaskDisplayArea_d0@247360341]
01-22 13:55:58.175  2565  2834 I SurfaceControl: show, t=StartTransaction_SyncId<11561>, sc=Surface(name=ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006})/@0x2a9f402, caller=com.android.server.wm.Transition.onTransactionReady:2012 com.android.server.wm.BLASTSyncEngine$SyncGroup.finishNow:321 com.android.server.wm.BLASTSyncEngine$SyncGroup.tryFinish:242 com.android.server.wm.BLASTSyncEngine$SyncGroup.-$$Nest$mtryFinish:0 com.android.server.wm.BLASTSyncEngine.onSurfacePlacement:685 com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace:993
01-22 13:55:58.175  2565  2834 V WindowManager:         {WCT{RemoteToken{670ea2d Task{7cd7471 #49006 type=standard A=10713:com.x8bit.bitwarden}}} m=TO_FRONT f=NONE p=WCT{RemoteToken{7f5e224 DefaultTaskDisplayArea_d0@247360341}} leash=Surface(name=Task=49006)/@0x312207c sb=Rect(0, 0 - 1440, 3088) eb=Rect(0, 0 - 1440, 3088) d=0 inset=Rect(0, 100 - 0, 53)},
01-22 13:55:58.176  2565  2830 V WindowManager:         {WCT{RemoteToken{670ea2d Task{7cd7471 #49006 type=standard A=10713:com.x8bit.bitwarden}}} m=TO_FRONT f=NONE p=WCT{RemoteToken{7f5e224 DefaultTaskDisplayArea_d0@247360341}} leash=Surface(name=Task=49006)/@0x312207c sb=Rect(0, 0 - 1440, 3088) eb=Rect(0, 0 - 1440, 3088) d=0 inset=Rect(0, 100 - 0, 53)},
01-22 13:55:58.176  2565  2834 D InsetsSourceProvider: updateFakeControlTarget: fakeControl=InsetsSourceControl: {dc040000 mType=statusBars mSurfacePosition=Point(0, 0) mInsetsHint=Insets{left=0, top=0, right=0, bottom=0}}, fakeTarget=Window{38894d u0 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity}
01-22 13:55:58.176  2565  2834 D InsetsSourceProvider: updateFakeControlTarget: fakeControl=InsetsSourceControl: {bd150001 mType=navigationBars mSurfacePosition=Point(0, 0) mInsetsHint=Insets{left=0, top=0, right=0, bottom=0}}, fakeTarget=Window{38894d u0 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity}
01-22 13:55:58.178  2565  2833 D SGM:FgCheckThread: noteResumeComponent(), received pkgName: com.x8bit.bitwarden, userId: 0
01-22 13:55:58.178  2565  2833 I GameSDK@LifeCycle: noteResumeComponent(): package name  : com.x8bit.bitwarden
01-22 13:55:58.178  2565  3622 D SGM:FgCheckThread: onLooperPrepared(), msg: MSG_APP_RESUME, pkgName: com.x8bit.bitwarden, userid: 0
01-22 13:55:58.181  1776  1776 I Layer   : Layer [ActivityRecord{9cb11fb u0 com.x8bit.bitwarden/.MainActivity t49006}#202484] hidden!! flag(0)
01-22 13:55:58.186  2565  3622 D SGM:FgCheckThread:   handleUserPresent(). resume signal is needed for com.x8bit.bitwarden
01-22 13:55:58.188  2565  2565 D MdnieScenarioControlService:  packageName : com.x8bit.bitwarden    className : com.x8bit.bitwarden.MainActivity
01-22 13:55:58.220  2565  4642 D InsetsSourceProvider: updateControlForTarget: control=InsetsSourceControl: {dc040000 mType=statusBars initiallyVisible mSurfacePosition=Point(0, 0) mInsetsHint=Insets{left=0, top=100, right=0, bottom=0}}, target=Window{38894d u0 com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity}, from=com.android.server.wm.InsetsStateController.onControlTargetChanged:363 com.android.server.wm.InsetsStateController.onBarControlTargetChanged:329 com.android.server.wm.InsetsPolicy.updateBarControlTarget:173 com.android.server.wm.InsetsPolicy.updateSystemBars:843 com.android.server.wm.DisplayPolicy.updateSystemBarsLw:3484
01-22 13:55:58.220  2565  3622 D SGM:FgCheckThread:   handleUserPresent(). resume signal is needed for c [...]

2025-01-22 14:54 UTC, BlackDex commented
@celevra, unfortunately this is not enough. The main reason is that not everything is tagged with `com.x8bit.bitwarden` or `bitwarden` and thus will not be shown when filtered.

I did some testing and checking my self, best would be to use something like this `grep` command, which hopefully gets the log we need.

```bash
grep -A20 -iE '(Process:.*bitwarden|android.runtime.JavaProxyThrowable)'
```

2025-01-22 15:59 UTC, BlackDex commented
and what about:

```bash
adb logcat | grep -A20 -iE '(Process:.*bitwarden|android.runtime.JavaProxyThrowable)'
```

And then try to sync.
Because it should generate something, if not, then something else strange is going on.
Maybe SSL Cert or something.

2025-01-22 16:11 UTC, celevra commented
@BlackDex no nothing, but this is the log from "bitwarden allready started und just hit refresh until error".

```
01-22 17:08:42.978  1674 24719 I sec_fr_SehFace: SehFace::getServicePid
01-22 17:08:42.978  1674 24719 I sec_fr_SehFace: FaceServicePID : 1674
01-22 17:08:42.978  2138 32572 E cameraserver: isBiometricsFaceService : face AIDL HAL Pid(1674) is not same with callingPid(25982)
01-22 17:08:42.979  2565  4925 I EDMNativeHelperService: isCameraEnabled
01-22 17:08:42.979  2565  4925 D EDMNativeHelper: isCameraEnabled
01-22 17:08:42.979  2565  4925 D EDMNativeHelper: checking for camera in EnterpriseDeviceManagerService
01-22 17:08:42.980  2565  4925 D EnterpriseDeviceManagerService: isCameraEnabledNative
01-22 17:08:42.980  2565  4925 D EnterpriseDeviceManagerService: checking for camera in restriction policy
01-22 17:08:42.980  2565  4925 D RestrictionPolicy: isCameraEnabled ret(true) userId(0) cxtInfo.mCallerUid(1000) cxtInfo.mContainerId(0)
01-22 17:08:43.033  1636  8777 D vendor.qti.bluetooth@1.1-wake_lock: Release wakelock is released
01-22 17:08:43.068  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:43.068  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:43.167  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:43.168  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:43.269  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:43.269  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:43.368  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:43.368  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:43.397  2137  2137 I CNSS    : cnss_open_log_file: directory /data/vendor/log/wifi/ created
01-22 17:08:43.468  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:43.468  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:43.570  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:43.570  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:43.606  2565  2809 I system_server: Background concurrent mark compact GC freed 557807(20MB) AllocSpace objects, 256(5944KB) LOS objects, 12% free, 174MB/198MB, paused 4.915ms,12.401ms total 562.100ms
01-22 17:08:43.606  1643 30556 I sensors-hal: handle_sns_client_event:574, [0][845689] accel_sample [ 1.113,  5.578,  8.246] 1582099157209295
01-22 17:08:43.665   897   897 I hwservicemanager: getTransport: Cannot find entry vendor.samsung.hardware.biometrics.face@2.0::ISehBiometricsFace/default in either framework or device VINTF manifest.
01-22 17:08:43.666  1674 24719 I sec_fr_SehFace: SehFace::getServicePid
01-22 17:08:43.666  1674 24719 I sec_fr_SehFace: FaceServicePID : 1674
01-22 17:08:43.666  2138 32050 E cameraserver: isBiometricsFaceService : face AIDL HAL Pid(1674) is not same with callingPid(25982)
01-22 17:08:43.667  2565  4925 I EDMNativeHelperService: isCameraEnabled
01-22 17:08:43.667  2565  4925 D EDMNativeHelper: isCameraEnabled
01-22 17:08:43.668  2565  4925 D EDMNativeHelper: checking for camera in EnterpriseDeviceManagerService
01-22 17:08:43.668  2565  4925 D EnterpriseDeviceManagerService: isCameraEnabledNative
01-22 17:08:43.668  2565  4925 D EnterpriseDeviceManagerService: checking for camera in restriction policy
01-22 17:08:43.668  2565  4925 D RestrictionPolicy: isCameraEnabled ret(true) userId(0) cxtInfo.mCallerUid(1000) cxtInfo.mContainerId(0)
01-22 17:08:43.669  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:43.669  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:43.769  7551  7551 I SDHMS:LOAD: type: LoadsFreqs, value: 0:18:3:874752:1132800:864000:884735:2803200:614400:220:220:220
01-22 17:08:43.777  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:43.777  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:43.791  2565  7608 I EDMNativeHelperService: isCameraEnabled
01-22 17:08:43.792  2565  7608 D EDMNativeHelper: isCameraEnabled
01-22 17:08:43.792  2565  7608 D EDMNativeHelper: checking for camera in EnterpriseDeviceManagerService
01-22 17:08:43.792  2565  7608 D EnterpriseDeviceManagerService: isCameraEnabledNative
01-22 17:08:43.792  2565  7608 D EnterpriseDeviceManagerService: checking for camera in restriction policy
01-22 17:08:43.792  2565  7608 D RestrictionPolicy: isCameraEnabled ret(true) userId(0) cxtInfo.mCallerUid(10105) cxtInfo.mContainerId(0)
01-22 17:08:43.878  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:43.878  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:43.977  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:43.977  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:44.078  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:44.078  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:44.178  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:44.178  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:44.280  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer  at index 0
01-22 17:08:44.280  1776  1873 D RenderEngine: [SEC_GC_CMN_SF_EFFECTS] drawLayersInternal,1279, Rendering layer com.x8bit.bitwarden/com.x8bit.bitwarden.MainActivity$_11308#219923 at index 1
01-22 17:08:44.296  3993  3993 D StatusBarIconController: ignoring old pipeline callbacks, because the new mobile icons are enabled
01-22 17:08:44.334  2565  3797 I SemWifiServiceDetector: NSD results: [0, 1, 2, 0, 0, 1, 2, 0, 1] Traff. type 1 Thr 1311
01-22 17:08:44.483  1643 32687 I sensors-hal: handle_sns_std_sensor_event:436, [SSC_LIGHT] P: 294(294),m:13,c:307,b:78,c0:111240,l:295,f(r):100,u(bl):107,j:292
01-22 17:08:44.513 10292 10335 V CpEventLog(u150): cp_state: [                 contacts = {contacts=0, raw_contacts=0, data=0, account={secphone(1)=0, samsung(2)=0, sim(3)=0, sim2(4)=0, agg(5)=0, vnd.sec.contact.phone_personal [...]

2025-01-25 18:39 UTC, P3RF3CTION commented
To provide an update to this Topic after installing the previous APK for Android of Bitwarden the Issue is resolved https://github.com/bitwarden/android/tree/v2024.11.7. So the latest patch notes of the bitwarden app might contain any hint or change that is leading to the error. It is definitely something from the bitwarden app which vaultwarden does not support right now. This means  the version of  https://github.com/bitwarden/android/releases/tag/v2025.1.0 and also https://github.com/bitwarden/android/releases/tag/v2024.12.0 have a breaking change since both provide the same error. 
Quick and dirty issue solution is to reinstall the version 11.7 from the bitwarden repo.

2025-01-25 18:53 UTC, BlackDex commented
That is probably not the best way. And the latest version released today should provide a working sync as far as i know. 

Best would be to try and get the logs of the app. 
It should be possible to filter only the app with the following command.

```bash
adb logcat --pid=$(adb shell pidof -s com.x8bit.bitwarden)
```

2025-01-26 06:49 UTC, celevra commented
@BlackDex now on 1.33.0
here is the log with the pid switch:

```
--------- beginning of main
01-26 07:45:50.585 29845 29845 I x8bit.bitwarden: Using CollectorTypeCMC GC.
01-26 07:45:50.590 29845 29845 E x8bit.bitwarden: Not starting debugger since process cannot load the jdwp agent.
01-26 07:45:50.593 29845 29845 D ActivityThread: setConscryptValidator
01-26 07:45:50.593 29845 29845 D ActivityThread: setConscryptValidator - put
01-26 07:45:50.599 29845 29845 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10713; state: ENABLED
01-26 07:45:50.599 29845 29845 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10713; state: ENABLED
01-26 07:45:50.630 29845 29845 W ziparchive: Unable to open '/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.arm64_v8a.dm': No such file or directory
01-26 07:45:50.630 29845 29845 W ziparchive: Unable to open '/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.arm64_v8a.dm': No such file or directory
01-26 07:45:50.631 29845 29845 W x8bit.bitwarden: Entry not found
01-26 07:45:50.631 29845 29845 W ziparchive: Unable to open '/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.de.dm': No such file or directory
01-26 07:45:50.631 29845 29845 W ziparchive: Unable to open '/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.de.dm': No such file or directory
01-26 07:45:50.631 29845 29845 W x8bit.bitwarden: Entry not found
01-26 07:45:50.632 29845 29845 W ziparchive: Unable to open '/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.xxhdpi.dm': No such file or directory
01-26 07:45:50.632 29845 29845 W ziparchive: Unable to open '/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.xxhdpi.dm': No such file or directory
01-26 07:45:50.632 29845 29845 W x8bit.bitwarden: Entry not found
01-26 07:45:50.633 29845 29845 D nativeloader: Configuring clns-4 for other apk /data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/base.apk:/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.arm64_v8a.apk:/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.de.apk:/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.xxhdpi.apk. target_sdk_version=35, uses_libraries=, library_path=/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/lib/arm64:/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/base.apk!/lib/arm64-v8a:/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.arm64_v8a.apk!/lib/arm64-v8a:/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_config.de.apk!/lib/arm64-v8a:/data/app/~~1RvdgzAhcPlmBFr2-EVcsg==/com.x8bit.bitwarden-_Bxts8Lx2Pj9wyDvkLZtQA==/split_c
01-26 07:45:50.640 29845 29845 V GraphicsEnvironment: Currently set values for:
01-26 07:45:50.640 29845 29845 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
01-26 07:45:50.640 29845 29845 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
01-26 07:45:50.640 29845 29845 V GraphicsEnvironment: ANGLE GameManagerService for com.x8bit.bitwarden: false
01-26 07:45:50.640 29845 29845 V GraphicsEnvironment: com.x8bit.bitwarden is not listed in per-application setting
01-26 07:45:50.640 29845 29845 V GraphicsEnvironment: App is not on the allowlist for updatable production driver.
01-26 07:45:50.646 29845 29845 D CompatibilityChangeReporter: Compat change id reported: 183155436; UID 10713; state: ENABLED
01-26 07:45:50.647 29845 29845 D SessionsDependencies: Dependency to CRASHLYTICS added.
01-26 07:45:50.647 29845 29845 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
01-26 07:45:50.650 29845 29845 D FirebaseSessions: Initializing Firebase Sessions SDK.
01-26 07:45:50.650 29845 29845 D CompatibilityChangeReporter: Compat change id reported: 3400644; UID 10713; state: ENABLED
01-26 07:45:50.651 29845 29845 I FirebaseCrashlytics: Initializing Firebase Crashlytics 19.3.0 for com.x8bit.bitwarden
01-26 07:45:50.660 29845 29845 D SessionsDependencies: Subscriber CRASHLYTICS registered.
01-26 07:45:50.677 29845 29869 D CompatibilityChangeReporter: Compat change id reported: 247079863; UID 10713; state: ENABLED
01-26 07:45:50.677 29845 29869 D SessionConfigFetcher: Fetching settings from server.
01-26 07:45:50.677 29845 29845 I FirebaseInitProvider: FirebaseApp initialization successful
01-26 07:45:50.683 29845 29845 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
01-26 07:45:50.685 29845 29845 D WM-PackageManagerHelper: Skipping component enablement for androidx.work.impl.background.systemjob.SystemJobService
01-26 07:45:50.685 29845 29845 D WM-Schedulers: Created SystemJobScheduler and enabled SystemJobService
01-26 07:45:50.689 29845 29890 D WM-ForceStopRunnable: The default process name was not specified.
01-26 07:45:50.689 29845 29890 D WM-ForceStopRunnable: Performing cleanup operations.
01-26 07:45:50.689 29845 29881 D TrafficStats: tagSocket(84) with statsTag=0xffffffff, statsUid=-1
01-26 07:45:50.690 29845 29885 D TrafficStats: tagSocket(87) with statsTag=0xffffffff, statsUid=-1
01-26 07:45:50.697 29845 29875 I FirebaseCrashlytics: Saved version control info
01-26 07:45:50.700 29845 29890 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10713; state: ENABLED
01-26 07:45:50.711 29845 29890 D WM-ForceStopRunnable: Application was force-stopped, rescheduling.
01-26 07:45:50.725 29845 29900 D WM-PackageManagerHelper: Skipping component enablement for androidx.work.impl.background.systemalarm.RescheduleReceiver
01-26 07:45:50.730 29845 29882 D CompatibilityChangeReporter: Compat change id reported: 194532703; UID 10713; state: ENABLED
01-26 07:45:50.730 29845 29882 D CompatibilityChangeReporter: Compat change id reported: 253665015; UID 10713; state: ENABLED
01-26 07:45:50.746 29845 29845 D OpenGLRenderer: HWUI - treat SMPTE_170M as sRGB
01-26 07:45:50.749 29845 29913 I AdrenoGLES-0: QUALCOMM build                   : 7b26bdd942, Iab69c31769
01-26 07:45:50.749 29845 29913 I AdrenoGLES-0: Build Date                       : 08/28/23
01-26 07:45:50.749 29845 29913 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: E031.41.03.44
01-26 07:45:50.749 29845 29913 I AdrenoGLES-0: Local Branch                     : 
01-26 07:45:50.749 29845 29913 I AdrenoGLES-0: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.VENDOR.13.2.0.11.00.00.855.659
01-26 07:45:50.749 29845 29913 I AdrenoGLES-0: Remote Branch                    : NONE
01-26 07:45:50.749 29845 29913 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
01-26 07:45:50.749 29845 29913 I AdrenoGLES-0: Build Config                     : S P 14.1.4 AArch64
01-26 07:45:50.749 29845 29913 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
01-26 07:45:50.749 29845 29913 I AdrenoGLES-0: Driver Version                   : 0676.42
01-26 07:45:50.751 29845 29915 I TRuntime.CctTransportBackend: Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
01-26 07:45:50.755 29845 29913 I AdrenoGLES-0: PFP: 0x01740158, ME: 0x00000000
01-26 07:45:50.758 29845 29913 W Adreno-AppProfiles: Could not find QSPM HAL service. Skipping adreno profile processing.
01-26 07:45:50.758 29845 29845 I DecorView: setWindowBackground: isPopOver=false color=fffafafa d=android.graphics.drawable.ColorDrawable@2b54395
01-26 07:45:50.759 29845 29913 I AdrenoUtils: <ReadGpuID:407>: Reading chip ID through GSL
01-26 07:45:50.765 29845 29845 I PendingIntentHandler: Request not found in pendingIntent
01-26 [...]

2025-01-26 07:32 UTC, BlackDex commented
And you tried to do a sync which generated an error message during this log output?

2025-01-26 08:48 UTC, celevra commented
Yes, two times

2025-01-26 09:13 UTC, BlackDex commented
Weird. Not seeing anything useful.
Could you install the dev version `com.x8bit.bitwarden.dev.apk` downloadable from here https://github.com/bitwarden/android/actions/runs/12959134324

And run the same command but then for dev like.
```bash
adb logcat --pid=$(adb shell pidof -s com.x8bit.bitwarden.dev)
```
Hopefully that provides more details.

2025-01-26 09:33 UTC, celevra commented
there is now a lot of output inclusive passwords, usernames and so on. So not safe to post here
is this the relevant entry?

```
01-26 10:29:56.053 16187 17122 W NetworkResultCall: Network Error: https://api.bitwarden.com/sync
01-26 10:29:56.053 16187 17122 W NetworkResultCall: java.time.format.DateTimeParseException: Text '2024-11-06T19:31:50.603166900Z' could not be parsed at index 27
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2050)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1952)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at java.time.ZonedDateTime.parse(ZonedDateTime.java:593)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at com.x8bit.bitwarden.data.platform.datasource.network.serializer.ZonedDateTimeSerializer.deserialize(ZonedDateTimeSerializer.kt:27)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at com.x8bit.bitwarden.data.platform.datasource.network.serializer.ZonedDateTimeSerializer.deserialize(ZonedDateTimeSerializer.kt:15)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.ContextualSerializer.deserialize(ContextualSerializer.kt:67)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at com.x8bit.bitwarden.data.vault.datasource.network.model.SyncResponseJson$Cipher$Login$$serializer.deserialize(SyncResponseJson.kt:688)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at com.x8bit.bitwarden.data.vault.datasource.network.model.SyncResponseJson$Cipher$Login$$serializer.deserialize(SyncResponseJson.kt:688)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at com.x8bit.bitwarden.data.vault.datasource.network.model.SyncResponseJson$Cipher$$serializer.deserialize(SyncResponseJson.kt:435)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at com.x8bit.bitwarden.data.vault.datasource.network.model.SyncResponseJson$Cipher$$serializer.deserialize(SyncResponseJson.kt:435)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.encoding.CompositeDecoder.decodeSerializableElement$default(Decoding.kt:539)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at com.x8bit.bitwarden.data.vault.datasource.network.model.SyncResponseJson$$serializer.deserialize(SyncResponseJson.kt:26)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at com.x8bit.bitwarden.data.vault.datasource.network.model.SyncResponseJson$$serializer.deserialize(SyncResponseJson.kt:26)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:149)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:26)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:11)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:7)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:246)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:156)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
01-26 10:29:56.053 16187 17122 W NetworkResultCall: 	at java.lang.Thread.run(Thread.java:1012)

```

2025-01-26 09:41 UTC, P3RF3CTION commented
> That is probably not the best way. And the latest version released today should provide a working sync as far as i know.
> 
> Best would be to try and get the logs of the app. It should be possible to filter only the app with the following command.
> 
> ```shell
> adb logcat --pid=$(adb shell pidof -s com.x8bit.bitwarden)
> ```

I can confirm updating to 1.33.0 resolves the issue with the latest Android app.

2025-01-26 10:22 UTC, BlackDex commented
@celevra , yes, that is useful, now i only need to know where that specific date is coming from!
I thought we had fixed all those dates at all places, but seems we missed something.

So somewhere in the sync data that date is located. I would need to know where that date is located.

2025-01-26 10:29 UTC, celevra commented
@BlackDex 
"passwordRevisionDate":"2024-11-06T19:31:50.603166900Z"

2025-01-26 10:36 UTC, BlackDex commented
On which kind of elementen? Can you provide more json context?
You can change the `2.` strings but we can't decrypt them anyways.
And can you provide the context of an other item too? Which also has the passwordRevisionDate?

2025-01-26 10:45 UTC, BlackDex commented
The strange thing is, that string should be impossible. 
The dates should be formatted to have a 6 digit subseconds and not 9.

2025-01-26 10:53 UTC, BlackDex commented
And, after providing more context. You can probably fix this your self by search for the uuid of that cipher, and change the date to have 6 digets instead of 9, and if that is the only one it should fix your sync.

2025-01-26 10:56 UTC, celevra commented
@BlackDex don't know if it helps, i came from enpass, than onepassword and than bitwarden so there passwords have gone through 2 conversions.

```
"uris":[{"match":null,"uri":"2.ogLU9zNz2xk/gceDtvhv3Q==|KPcOFrn4np2JTcsSWfXt6bqgkOvvFz9TJyojab5c8TxUh2eVQue4FEvsndqcuuS4|4cEkgmte/MlfmeyVJ43WWPX33+FcxRB4sYvHUuXFs3k="}],"username":"2.Y4XaUVl3BdonLwaWofOlYA==|byJ64smVTBAB8Cc8PUWYQTWiZT9DlbGeuUSr27jyHX0=|5XXNr46g0otXAf/vUVqso5mMb0Vobp2cZchYFo6fsm4="},"deletedDate":null,"edit":true,"favorite":false,"fields":[],"folderId":null,"id":"040f54fa-2a66-48e4-bf7f-4fd4358ba33b","identity":null,"key":null,"login":{"fido2Credentials":[],"password":"2.d7VAtSN/CpkVlE31vK8opw==|bs82lG8sqmPr4aWtx9Gbje3UkzlUYBqQ3jFO53URAh0=|0XKklZeBZFa7zuRRFmQuMBOeT1s94SUYlv3KDRu4eYE=","passwordRevisionDate":"2024-11-06T19:31:50.603166900Z","totp":"2.hcnG9l2AfZTfvVyCPfKO5A==|PQU+q8oYFiAvapEbP2YjF11zIQVc70Y36Ao31pbPpew=|QAjnSAIeuZQpHvRetsYaceLz7JXkQC74ZsKNNu7gWxE=","uri":"2.ogLU9zNz2xk/gceDtvhv3Q==|KPcOFrn4np2JTcsSWfXt6bqgkOvvFz9TJyojab5c8TxUh2eVQue4FEvsndqcuuS4|4cEkgmte/MlfmeyVJ43WWPX33+FcxRB4sYvHUuXFs3k=","uris":[{"match":null,"uri":"2.ogLU9zNz2xk/gceDtvhv3Q==|KPcOFrn4np2JTcsSWfXt6bqgkOvvFz9TJyojab5c8TxUh2eVQue4FEvsndqcuuS4|4cEkgmte/MlfmeyVJ43WWPX33+FcxRB4sYvHUuXFs3k="}],"username":"2.Y4XaUVl3BdonLwaWofOlYA==|byJ64smVTBAB8Cc8PUWYQTWiZT9DlbGeuUSr27jyHX0=|5XXNr46g0otXAf/vUVqso5mMb0Vobp2cZchYFo6fsm4="},"name":"2.HtuPmIm0fGM/QfWwkdipnA==|r87/CLa7/7Zoyribl3BCzA==|yH2a/pn5IcHk/U+w/8lOYWOmJozXwnL4atGQk8VaokI=","notes":"2.dnAvvvXLMNgFexGoqK/dVw==|XnH0Nxgr/7IeQS9IcxyLxg==|/JUQsOPXar08EUXCJMZz5DkFtKEUn6yQ1XNpAQlRvfs=","object":"cipherDetails","organizationId":"a5dd5982-4db8-4121-a9ae-c15161bc8580","organizationUseTotp":true,"passwordHistory":[],"reprompt":0,"revisionDate":"2024-11-06T19:33:05.910283Z","secureNote":null,"sshKey":null,"type":1,"viewPassword":true},{"attachments":null,"card":null,"collectionIds":[],"creationDate":"2024-02-21T14:41:32.125127Z","data":{"autofillOnPageLoad":null,"fields":[],"name":"2.CZVMFWwr3a/UUdeiIXNSdw==|MXPka5vmgHrj8OhCZjtrlQ==|hOy+D8ecNMuI4UlbxOm4Q9i9KmgIPvyXm0Tu+yqAq4M=","notes":null,"password":"2.iL2Zog6z1Dzh/ZGDpw0O0w==|gCCEhr+li6iNZy4WlvjTCQ==|4LDSbMl56/Dq9NWyz1L0OEd/vFdElOFWRSkV9hTJ4bA=","passwordHistory":[],"passwordRevisionDate":null,"totp":null,"uri":null,"uris":[],"username":null},"deletedDate":null,"edit":true,"favorite":false,"fields":[],"folderId":null,"id":"0419737d-dd8f-4afb-9843-dd66b76d3199","identity":null,"key":null,"login":{"autofillOnPageLoad":null,"password":"2.iL2Zog6z1Dzh/ZGDpw0O0w==|gCCEhr+li6iNZy4WlvjTCQ==|4LDSbMl56/Dq9NWyz1L0OEd/vFdElOFWRSkV9hTJ4bA=","passwordRevisionDate":null,"totp":null,"uri":null
01-26 11:29:13.315 16187  7748 D 
```

2025-01-26 10:59 UTC, BlackDex commented
Thanks, that helps. 
I think we need to add some extra checks and conversions then.
Ill look into it somewhere today.

2025-01-26 18:00 UTC, celevra commented
@BlackDex after correcting one entry, the next pops up in the sync log.
All entries created with [keyguard](https://github.com/AChep/keyguard-app)
should i create an bug report also at the keyguard-app to make change the timestamps?

2025-01-26 18:05 UTC, BlackDex commented
Yea, that might be a good thing to do in any case

2025-01-26 18:05 UTC, celevra commented
done https://github.com/AChep/keyguard-app/issues/792

2025-01-27 17:20 UTC, BlackDex commented
I also have a fix implemented, doing some extra testing.

2025-01-27 19:02 UTC, BlackDex commented
Fix is located here #5477