WIP: Update Key Rotation web-vault v2023.3.x
dani-garcia/vaultwarden pull request #4446
Opened 2024-03-22 23:36 UTC by BlackDex

WIP For some added fields during key rotation change

2024-03-23 12:04 UTC, BlackDex commented
There seems to be a bug in 2024.3.0 (and probably the latest 2024.2.x also).

There is a phantom folder without an `id`, that causes an issue. This also happens on a Self-Hosted Bitwarden.

2024-03-23 14:11 UTC, stefan0xC commented
> There seems to be a bug in 2024.3.0 (and probably the latest 2024.2.x also).
> 
> There is a phantom folder without an `id`, that causes an issue. This also happens on a Self-Hosted Bitwarden.

What do you mean?

2024-03-23 14:20 UTC, BlackDex commented
> > There seems to be a bug in 2024.3.0 (and probably the latest 2024.2.x also).
> > There is a phantom folder without an `id`, that causes an issue. This also happens on a Self-Hosted Bitwarden.
> 
> What do you mean?

That during key rotation there is a folder in the folders array without an id, but with a name. Which isn't allowed.
It also breaks on there self-hosted instance, and probably also on the cloud environment. I have not yet tested that.

2024-03-23 21:47 UTC, stefan0xC commented
Yep. Looking into it I think that it seems like the empty folder is sent by the client as it is added to the folderViews but not filtered out anymore (since https://github.com/bitwarden/clients/pull/6881)
Cf. https://github.com/bitwarden/clients/blob/web-v2023.12.0/apps/web/src/app/auth/settings/change-password.component.ts#L235-L242 vs. https://github.com/bitwarden/clients/blob/web-v2024.3.0/apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts#L118-L130

2024-03-23 21:55 UTC, stefan0xC commented
A workaround would be that we change https://github.com/dani-garcia/vaultwarden/blob/2d98aa304501b0f710d3a97ec854acdfc115228f/src/api/core/accounts.rs#L441 to `Option<String>` and skip the processing of it accordingly https://github.com/dani-garcia/vaultwarden/blob/2d98aa304501b0f710d3a97ec854acdfc115228f/src/api/core/accounts.rs#L474-L475

2024-03-23 22:10 UTC, BlackDex commented
> A workaround would be that we change
> 
> https://github.com/dani-garcia/vaultwarden/blob/2d98aa304501b0f710d3a97ec854acdfc115228f/src/api/core/accounts.rs#L440-L441
> to `Option<String>` and skip the processing of it accordingly
> 
> https://github.com/dani-garcia/vaultwarden/blob/2d98aa304501b0f710d3a97ec854acdfc115228f/src/api/core/accounts.rs#L474-L475

I'm working on that indeed. But bumping into other strange issues.
Like they started sending org ciphers too, which we probably do not want to update i think.
So we need to skip those too.

2024-03-23 22:41 UTC, stefan0xC commented
>  It also breaks on there Self-Hosted images. Strangely it doesn't on the cloud, even with the same versions.

Not familiar with bitwarden self-hosted. Might be related to whether you have enabled the `key-rotation-improvements` feature flag? At least [the validation seems to differ when it's enabled](https://github.com/bitwarden/server/blob/6a0f6e1dac85f1940226735bf7c5907189c2ef9b/src/Api/Auth/Controllers/AccountsController.cs#L442).

2024-03-23 22:50 UTC, BlackDex commented
> > It also breaks on there Self-Hosted images. Strangely it doesn't on the cloud, even with the same versions.
> 
> Not familiar with bitwarden self-hosted. Might be related to whether you have enabled the `key-rotation-improvements` feature flag? At least [the validation seems to differ when it's enabled](https://github.com/bitwarden/server/blob/6a0f6e1dac85f1940226735bf7c5907189c2ef9b/src/Api/Auth/Controllers/AccountsController.cs#L442).

Indeed, that is enabled on Cloud, but not on the Self-Hosted Bitwarden, that might be the difference indeed.

2024-03-23 23:15 UTC, BlackDex commented
Ah, that flag does make it better for us. But it doesn't change the layout.
I think it already sends it in this format because of a version check maybe?

Not sure since we had 2023.9.1 there, and i just now changed it to 2024.2.0, but that didn't make a difference really.
The flag does. It prevents some other calls to be done afterwards :) which are handled already with the new format.

2024-03-23 23:22 UTC, BlackDex commented
Hmm. Maybe the org ciphers are needed for the flexible collections feature maybe?
Not sure how those work actually.

2024-03-24 00:56 UTC, Gerardv514 commented
Curious if the title of this Pr is a type, should v2023.3 be v2024.3?

2024-03-25 23:03 UTC, BlackDex commented
Technically this PR works. But i want to check for some more optimizations.

2024-03-25 23:20 UTC, Gerardv514 reviewed
Change title on commit to 2024.3 as well?

2024-03-25 23:30 UTC, Gerardv514 requested changes

2024-03-25 23:30 UTC, Gerardv514 commented on src/api/core/accounts.rs
> +    // TODO: See if we can wrap everything within a SQL Transaction. If something fails it should reverte everything.
spelling on revert

2024-04-06 11:59 UTC, dani-garcia approved these changes

2024-04-06 12:42 UTC, merged