Optimize Dockerfiles
dani-garcia/vaultwarden pull request #4532
Opened 2024-05-01 17:33 UTC by dfunkt

Move some ARGs closer to the build stage, potentially improving caching:
Example: I usually set VW_VERSION to be the latest commit hash, without this change I'd have to also rebuild the dependencies even if they didn't change since the previous layers would get invalidated.

Remove redundant COPY commands:
They can be combined, no point in using extra layers if it can be avoided.

2024-05-02 09:38 UTC, GaetanJeff approved these changes

2024-05-02 20:34 UTC, BlackDex commented
Saving a lot of layers at the top is not that efficiënt i think.
Ill have to check, there were some reasons i didn't combined the, but not sure.

2024-05-02 20:46 UTC, dfunkt commented
Fair enough, if there's stuff here that you don't like just tell me and I'll remove it.

I've been running my builds for a while with these changes and I figured other people might benefit from them as well.

2024-05-02 20:48 UTC, BlackDex commented
> Fair enough, if there's stuff here that you don't like just tell me and I'll remove it.
> 
> I've been running my builds for a while with these changes and I figured other people might benefit from them as well.

Do you build all arch's?

2024-05-02 20:49 UTC, dfunkt commented
amd64 and arm64, both for personal use

2024-05-02 21:26 UTC, williamdes commented
A good tool to check this PR is https://github.com/wagoodman/dive

2024-05-02 21:43 UTC, BlackDex commented
> A good tool to check this PR is https://github.com/wagoodman/dive

I use that too indeed. But that will only work for the final image, not for the build layer.

2024-05-02 22:02 UTC, dfunkt commented
What do you guys think about including this as well?
https://docs.docker.com/build/cache/#use-the-dedicated-run-cache

2024-05-02 22:51 UTC, BlackDex commented
It doesn't really add anything useful i think. 
The main reason is that we went fresh images which have the latest packages available to keep up-to-date and all CVE's are gone as good as possible.

Also, docker buildx does some nice caching by it self. And we already use build caches during our release pipeline.

We used that before btw, which was useful back then, and not building in parallel. When building in parallel it gave some issues, which can be solved, but then it loses its benefits.

2024-05-03 12:43 UTC, BlackDex commented
While optimizing for layers does not have any benefit for the build part, it also doesn't hurt in this case.
The only time it will hurt is when you are testing/debugging the last apt commands in the same RUN. But that will not be often i hope.

2024-05-03 12:45 UTC, BlackDex requested changes
Looks fine by me.

2024-05-03 12:45 UTC, BlackDex commented on docker/Dockerfile.j2
> +{% endif %}
The comment `# Configure the DB ARG as late as possible to not invalidate the cached layers above` can be placed above the `if` and then also be removed from the `else`.

2024-05-03 13:45 UTC, BlackDex approved these changes

2024-05-19 18:32 UTC, dani-garcia approved these changes

2024-05-19 18:32 UTC, merged