Remove mimalloc workaround
dani-garcia/vaultwarden pull request #4606
Opened 2024-06-02 08:39 UTC by dfunkt

- libatomic linking for armv6 has been fixed in mimalloc v0.1.42

For reference: https://github.com/purpleprotocol/mimalloc_rust/commit/446fc231151cfab485b0ac7d5178baf797799dda

2024-06-02 08:41 UTC, williamdes approved these changes

2024-06-06 13:13 UTC, BlackDex requested changes
This unfortunately is not true.
The new mimalloc-sys crate actually breaks everything.
It also seems it has been broken for a longer time already.
So, this is something we need to look into.

The binaries do work within an Alpine environment, but not as a true static binary anymore.

2024-06-14 12:18 UTC, dfunkt commented
Are we waiting for a new crate release or should I override it with commit https://github.com/purpleprotocol/mimalloc_rust/commit/992c9da4c5afba7fbf4c5815c43c8f0fbd2a8da6?

2024-06-14 12:20 UTC, BlackDex commented
I have not yet checked if the removal works for all arch's.

2024-06-23 19:29 UTC, BlackDex approved these changes

2024-06-24 17:44 UTC, merged