Add orgUserHasExistingUser parameters to org invite
dani-garcia/vaultwarden pull request #4827
Opened 2024-08-08 18:00 UTC by Timshel

With the new web-vault `web-v2024.6.2` the organization invitation logic was rewritten (had a look since organization invitation is now working even with sso :tada:).

Discovered that there were additional parameters that were not used such as `orgUserHasExistingUser` which allows to control if the user is redirected to the create account or login page (Cf  [web-v2024.6.2/accept-organization.component.ts](https://github.com/bitwarden/clients/blob/web-v2024.6.2/apps/web/src/app/auth/organization-invite/accept-organization.component.ts#L69), but this already existed before).

The additional `orgSsoIdentifier` parameter could then be added to the SSO PR.

2024-08-08 18:47 UTC, stefan0xC reviewed
Looks mostly good to me. I do have some questions though.

2024-08-08 18:47 UTC, stefan0xC commented on src/mail.rs
> +            "url": String::from(url).replace("/?email", "/#/accept-organization/?email"),
Would it be possible to [join](https://docs.rs/url/latest/url/struct.Url.html#method.join) `/#/accept-organization/` to the base url, when constructing the `url`, instead of replacing it here? Or is there a reason for doing it like that?

2024-08-08 18:47 UTC, stefan0xC commented on src/mail.rs
> +            .append_pair("organizationName", org_name)
Am I correct in assuming that doing it this way will automatically url encode the parameters?

2024-08-08 18:47 UTC, stefan0xC commented on src/mail.rs
> +            query_params.append_pair("orgUserHasExistingUser", "true");
Do you know when this would be false?

2024-08-08 18:47 UTC, stefan0xC commented on src/mail.rs
> +// The url cannot be fully built using `url.Url` since the anchor `#` should be after the query parameters
What does this comment mean exactly? Aren't you replacing the `/?email` with `/#/accept-organization/?email below? (Is this related to my other question? If so I would move the comment down before the replace.)

2024-08-08 18:54 UTC, Timshel commented on src/mail.rs
> +// The url cannot be fully built using `url.Url` since the anchor `#` should be after the query parameters
It is, by definition the anchor `#` should be after the query parameters.
So if set at the start you'll end up with an url: `domain.com/?token=toto#/accept-organization/`

2024-08-08 18:55 UTC, Timshel commented on src/mail.rs
> +            query_params.append_pair("orgUserHasExistingUser", "true");
when using the `sso` if you want to redirect to the SSO login flow.

2024-08-08 18:57 UTC, Timshel commented on src/mail.rs
> +            .append_pair("organizationName", org_name)
I believe it does: cf: https://docs.rs/url/latest/url/struct.Url.html#method.query_pairs_mut

2024-08-08 19:00 UTC, stefan0xC commented on src/mail.rs
> +            query_params.append_pair("orgUserHasExistingUser", "true");
Ah, makes sense.

2024-08-08 19:07 UTC, stefan0xC commented on src/mail.rs
> +// The url cannot be fully built using `url.Url` since the anchor `#` should be after the query parameters
This comment should be moved down then (and maybe also reworded a bit as it's saying the opposite to me).
```suggestion
// The url cannot be fully built using `url.Url` since the anchor `#` would be after the query parameters so we use `replace` as a work around here
```

2024-08-08 19:10 UTC, Timshel commented on src/mail.rs
> +// The url cannot be fully built using `url.Url` since the anchor `#` should be after the query parameters
Do you prefer it just before the `Url::parse` or lower down before the `replace` ?

2024-08-08 19:13 UTC, stefan0xC commented on src/mail.rs
> +// The url cannot be fully built using `url.Url` since the anchor `#` should be after the query parameters
If possible I would add the comment directly above the replace (as this is where I was wondering why it's done this way and where I think it would be most relevant).

2024-08-08 20:51 UTC, Timshel commented on src/mail.rs
> +// The url cannot be fully built using `url.Url` since the anchor `#` should be after the query parameters
Realized that the `replace` was invalid if the domain included a subpath.
Could have just removed the `/  but I think this new version should be safer.

2024-08-09 15:21 UTC, BlackDex requested changes
Overall i think it looks nice.
Just a small remark.

2024-08-09 15:21 UTC, BlackDex commented on src/mail.rs
> +    let url = format!("{}/#/accept-organization/?{}", CONFIG.domain(), query.query().unwrap_or(""));
I think it is best to handle this unwrap manually instead of using `unwrap_or()`.
This could cause issues when something with the unwrap goes wrong here.

Best to check if unwrap works or not and error out.
Something like this maybe?
```rust
if let query_string = match query.query() {
  Ok(query) => query,
  Err(e) => err!("Unable to build invite url", format!("Query Build Error {e:?}")),
};
```

2024-08-09 15:48 UTC, Timshel commented on src/mail.rs
> +    let url = format!("{}/#/accept-organization/?{}", CONFIG.domain(), query.query().unwrap_or(""));
I had agreed at first but the `unwrap` is here because of an `Option` not an `Error`.

That's why I believed it's ok to `unwrap` since I'm guessing it returns `None` only if there is no query parameters which should never happen.

2024-08-09 16:03 UTC, Timshel commented on src/mail.rs
> +    let url = format!("{}/#/accept-organization/?{}", CONFIG.domain(), query.query().unwrap_or(""));
I'm all for enforcing type constraint and proper checking but in some cases I believe the handling just add bloat and lower code legibility. 
Same reason I did not handle the potential `Error` and used an even riskier `unwrap` earlier: `url::Url::parse("https://query.builder").unwrap()`.

But if you think it's worth it I'll make the change.

2024-08-09 16:06 UTC, BlackDex commented on src/mail.rs
> +    let url = format!("{}/#/accept-organization/?{}", CONFIG.domain(), query.query().unwrap_or(""));
Well, either use plain `unwrap()` if you are sure it never happens, but that could panic if not. Else i would suggest to use my suggestion. But i would at least not use `unwrap_or()`, since then we would never know.

2024-08-09 16:12 UTC, BlackDex commented on src/mail.rs
> +    let url = format!("{}/#/accept-organization/?{}", CONFIG.domain(), query.query().unwrap_or(""));
Ow, `expect("Invite query string")` is also an option.

2024-08-09 16:20 UTC, Timshel commented on src/mail.rs
> +    let url = format!("{}/#/accept-organization/?{}", CONFIG.domain(), query.query().unwrap_or(""));
Pushed the `match` version.

2024-08-09 16:44 UTC, dfunkt commented on src/mail.rs
> +        None => err!(format!("Failed to build invite url query parameters")),
```suggestion
        None => err!(format!("Failed to build invite URL query parameters")),
```
I feel like this would be better from a stylistic point of view.

2024-08-30 19:27 UTC, BlackDex approved these changes

2024-08-30 19:31 UTC, BlackDex commented
Nice, works well.

2024-09-01 13:55 UTC, dani-garcia approved these changes

2024-09-01 13:55 UTC, merged