Switch to Whitelisting in .dockerignore
dani-garcia/vaultwarden pull request #4856
Opened 2024-08-14 17:11 UTC by Timshel

Hey,

Recently mistakenly added `.git` to the `.dockerignore` in another PR because I thought it might be responsible for unnecessary rebuild (it was not anyway).

But with so many blacklisted element I think switching to a whitelist style is simpler.

2024-08-19 10:55 UTC, BlackDex requested changes

2024-08-19 11:22 UTC, williamdes commented on .dockerignore
> +!.git
I would say prefix everything with /
That's what I use normally as not having / causes side effects

2024-08-19 12:05 UTC, Timshel commented on .dockerignore
> +!.git
My understanding is that it makes no difference: https://docs.docker.com/build/building/context/#syntax

2024-08-19 12:28 UTC, williamdes commented on .dockerignore
> +!.git
But not in inverted ignore patterns normally 🤔

2024-08-19 13:08 UTC, Timshel commented on .dockerignore
> +!.git
Looking at the [code](https://github.com/moby/patternmatcher/blob/main/ignorefile/ignorefile.go#L59) it's not the `!` prefix is handled before removing leading `/`.

2024-08-19 14:33 UTC, tessus commented on .dockerignore
> +// Blacklist everything
May I ask why? Rewriting terms because they include white/black/master/slave is idiotic. Especially if the origins of those terms are completely different from what offended parties might think. If you don't believe me, reading up on history might help.
The only result that this entire BS had was that people have to use 2 git statements to checkout the master/main branch depending on the project (because whatever you use first is most likely the wrong one). Great job.

I really thought long and hard whether I should even state my opinion in fear of being crucified for being someone that I am not, but this is ridiculous. I guess humanity has just lost all sense of reality when it comes to what is really important.

Ok, might the hate comments commence...

2024-08-19 14:37 UTC, stefan0xC commented on .dockerignore
> +// Blacklist everything
Why do you care?

2024-08-19 14:38 UTC, tessus commented on .dockerignore
> +// Blacklist everything
Why do you?

2024-08-19 14:56 UTC, Timshel commented on .dockerignore
> +// Blacklist everything
> I really thought long and hard whether I should even state my opinion

You shouldn't have ...

> I guess humanity has just lost all sense of reality when it comes to what is really important.

Say the guy who comes to complain in a random PR ...

Anyway if anyone truly care for a reason I would say that Ignore/Allow is just a better description of the concepts and I had no issue making the change.

And please don't respond, I won't.

2024-08-19 15:03 UTC, stefan0xC commented on .dockerignore
> +// Blacklist everything
I don't think anyone cares enough that you would lose your job over this. The question is why does it bother you if someone suggests using a less controversial term? It doesn't affect you either way how this comment is called. If it's not offensive to you because you know about the etymological history of a term that's great for you but the inconvenience caused by requesting this change is immaterial.

2024-08-19 15:07 UTC, BlackDex commented on .dockerignore
> +// Blacklist everything
Well, it also is called a docker*ignore* file, not a docker*blacklist* file.

2024-08-19 15:07 UTC, tessus commented on .dockerignore
> +// Blacklist everything
What bothers me is that these terms even became controversial. 

@BlackDex please delete or mark my comments as off-topic.

2024-08-21 19:54 UTC, BlackDex approved these changes

2024-08-21 19:58 UTC, dani-garcia approved these changes

2024-08-21 19:59 UTC, merged