Update issue template
dani-garcia/vaultwarden pull request #4882
Opened 2024-08-22 15:48 UTC by BlackDex

Updated the issue template a bit regarding some remarks in the previous pr.

Also made it so that collapsing all items will show all the specific item id's instead of there types. Easy for editiing :).

2024-08-22 15:59 UTC, stefan0xC requested changes

2024-08-22 15:59 UTC, stefan0xC commented on .github/ISSUE_TEMPLATE/bug_report.yml
>        description: How did you deployed Vaultwarden?
```suggestion
      description: How did you deploy Vaultwarden?
```

2024-08-22 15:59 UTC, stefan0xC commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: On what operating system are running the Vaultwarden server?
```suggestion
      description: On what operating system are you running the Vaultwarden server?
```

2024-08-22 15:59 UTC, stefan0xC commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: Provide the logs generated by Vaultwarden generated during the time this issue occurs.
```suggestion
      description: Provide the logs generated by Vaultwarden during the time this issue occurs.
```

2024-08-22 15:59 UTC, stefan0xC commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        See here how to [Enabling admin page](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page).
```suggestion
        See here [how to enable the admin page](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page).
```

2024-08-22 16:09 UTC, BlackDex commented
Thanks @stefan0xC, i adjusted the items :).

2024-08-23 19:47 UTC, stefan0xC approved these changes

2024-08-23 20:03 UTC, dani-garcia approved these changes

2024-08-23 20:03 UTC, merged