Allow enforcing Single Org with pw reset policy
dani-garcia/vaultwarden pull request #4903
Opened 2024-08-28 14:04 UTC by BlackDex

Bitwarden only allows the Reset Password policy to be set when the Single Org policy is enabled already. This PR adds a check so that this can be enforced when a config option is enabled.

Since Vaultwarden encouraged to use multiple orgs when groups were not available yet we should not enable this by default now. This might be something to do in the future.

When enabled, it will prevent the Reset Password policy to be enabled if the Single Org policy is not enabled. It will also prevent the Single Org policy to be disabled if the Reset Password policy is enabled.

Fixes #4855

2024-08-28 14:52 UTC, stefan0xC requested changes

2024-08-28 14:52 UTC, stefan0xC commented on src/api/core/organizations.rs
> +        && (pol_type_enum == OrgPolicyType::ResetPassword || pol_type_enum == OrgPolicyType::SingleOrg)
```suggestion
```
I think this is a bit superfluous. Do we really need to check for these conditions twice?

I think you could alternatively also get rid of one level of indentation by checking CONFIG.enforce_single_org_with_reset_pw_policy() twice instead.

2024-08-28 15:16 UTC, BlackDex commented on src/api/core/organizations.rs
> +        && (pol_type_enum == OrgPolicyType::ResetPassword || pol_type_enum == OrgPolicyType::SingleOrg)
Well, there are other policies to check also.
This does prevent checking the other if's everytime when the config is enabled.

2024-08-28 15:20 UTC, stefan0xC commented on src/api/core/organizations.rs
> +        && (pol_type_enum == OrgPolicyType::ResetPassword || pol_type_enum == OrgPolicyType::SingleOrg)
Are the other ifs that expensive compared to this one? :thinking:

2024-08-28 17:35 UTC, BlackDex commented on src/api/core/organizations.rs
> +        && (pol_type_enum == OrgPolicyType::ResetPassword || pol_type_enum == OrgPolicyType::SingleOrg)
Not that much, there is an extra check done `data.enabled` but that is about it.
I removed it, also as this endpoint is probably not used that much anyway :).

2024-08-28 17:41 UTC, stefan0xC approved these changes

2024-08-30 19:37 UTC, dani-garcia approved these changes

2024-08-30 19:37 UTC, merged