Actually use Device Type for mails
dani-garcia/vaultwarden pull request #4916
Opened 2024-09-03 07:46 UTC by dfunkt

- match Bitwarden behaviour
- remove upcase_first, no longer needed and it would also interfere with device types like iOS, macOS

Examples:

Chrome Extension
Before -> New Device Logged In From/Incomplete Two-Step Login FromDevice Type: Chrome
After -> New Device Logged In From/Incomplete Two-Step Login From/Device Type: Chrome Extension

Poco F3 (shows up as M2012K11AG)
Before -> New Device Logged In From/Incomplete Two-Step Login FromDevice Type: M2012K11AG
After -> New Device Logged In From/Incomplete Two-Step Login From/Device Type: Android

2024-09-03 17:43 UTC, jjlin commented
If the device type is Android or iOS, the mobile client should include a device model as the name, so the notification email should ideally include that info for those device types. I'm not sure if any other device types include useful model/name info.

2024-09-03 18:01 UTC, dfunkt commented
Let's not forget that the email template says "Device Type", not "Device Type and Name/Model" or anything like that.
Example: https://github.com/dani-garcia/vaultwarden/blob/248e561b3fe6a8172751374df980c6cd43c841d5/src/static/templates/email/new_device_logged_in.html.hbs#L22
Ideally I try to stick as close as possible to Bitwarden's behaviour when implementing these changes, and the emails from them don't specify the device name/model number either.

Nonetheless, let's see what others have to say about this change.

2024-09-03 18:13 UTC, jjlin commented
Vaultwarden does various things differently from Bitwarden, as long as they are compatible improvements. For example, Bitwarden does not even have a 2FA incomplete notification AFAIK.

2024-09-03 20:29 UTC, BlackDex commented
I agree with @jjlin.
For all the client functionality we should stay as close as possible.
Server-side specific changes should be looked at if it has no impact client side or might alter a way of working.

But for something like emails shouldn't be an issue. 
I actually love it shows we the device name and not only type.
So both would be better. 

I even was thinking about adding basic location detection based upon IP.

2024-09-04 11:47 UTC, dfunkt commented
New variant with device name and device type included.
Examples:
![Screenshot from 2024-09-04 14-44-43](https://github.com/user-attachments/assets/e3542539-1989-4dfc-aa7f-df9e6c6b87c2)
![Screenshot from 2024-09-04 14-44-58](https://github.com/user-attachments/assets/0d006320-029b-425a-9ad4-5fcfda8ef454)

2024-09-04 19:00 UTC, jjlin commented on migrations/mysql/2024-09-04-091351_use_device_types/down.sql
> +ALTER TABLE `twofactor_incomplete` DROP COLUMN `device_atype`;
```suggestion
ALTER TABLE `twofactor_incomplete` DROP COLUMN `device_type`;
```
Same name change for all the other migration files

2024-09-04 19:00 UTC, jjlin commented on src/db/models/two_factor_incomplete.rs
> +        pub device_atype: i32,
```suggestion
        pub device_type: i32,
```

2024-09-04 19:00 UTC, jjlin commented on src/db/models/two_factor_incomplete.rs
> +        device_atype: &i32,
```suggestion
        device_type: i32,
```

2024-09-04 19:00 UTC, jjlin commented on src/db/schemas/mysql/schema.rs
> +        device_atype -> Integer,
```suggestion
        device_type -> Integer,
```
Same comment for the other schema files

2024-09-04 19:00 UTC, jjlin commented on src/api/identity.rs
> +    TwoFactorIncomplete::mark_incomplete(&user.uuid, &device.uuid, &device.name, &device.atype, ip, conn).await?;
```suggestion
    TwoFactorIncomplete::mark_incomplete(&user.uuid, &device.uuid, &device.name, device.type, ip, conn).await?;
```

2024-09-04 19:23 UTC, dfunkt commented
I chose atype on purpose to match how it was in device.rs:
https://github.com/dani-garcia/vaultwarden/blob/248e561b3fe6a8172751374df980c6cd43c841d5/src/db/models/device.rs#L19
Which one do you prefer @BlackDex? atype or just type?

2024-09-04 19:28 UTC, BlackDex commented
`type` is the correct name. The only reason there is an `a` in front is because you can't use that as a variable name.

2024-09-04 19:30 UTC, jjlin commented
> I chose atype on purpose to match how it was in device.rs:
> 
> https://github.com/dani-garcia/vaultwarden/blob/248e561b3fe6a8172751374df980c6cd43c841d5/src/db/models/device.rs#L19

This is only called `atype` because you can't have an identifier that's just called `type`. There are many other existing instances of `device_type` in the code.

2024-09-04 21:11 UTC, dfunkt commented
Hopefully things are good now

2024-09-09 08:31 UTC, BlackDex requested changes

2024-09-09 08:31 UTC, BlackDex commented on src/api/identity.rs
> +            &DeviceType::from_i32(device.atype).to_string(),
I would suggest to just sent `&Device` instead of two different values from the same object.
So `&device` should be enough.

2024-09-09 08:31 UTC, BlackDex commented on src/api/identity.rs
> +            &DeviceType::from_i32(device.atype).to_string(),
Same here as above of course

2024-09-09 10:43 UTC, dfunkt commented
@BlackDex Not sure if this is what you meant, but that's all I could come up with. I'm not particularly familiar with Rust (or programming in general tbh).

2024-09-09 10:54 UTC, BlackDex requested changes
Yes, that is what i mend indeed.

I just noticed something else too. Not that important, but no need to create new variables for those items actually.

2024-09-09 10:54 UTC, BlackDex commented on src/mail.rs
> +    let device_type = DeviceType::from_i32(device.atype).to_string();
These do not have to be a variable.
They can be added directly to the `json!()` bellow on lines 461 and 462.

2024-09-09 10:54 UTC, BlackDex commented on src/mail.rs
> +    let device_name = upcase_first(device_name);
Same here, move this directly into the `json!()` below in line 487.

2024-09-09 11:01 UTC, dfunkt commented on src/mail.rs
> +    let device_type = DeviceType::from_i32(device.atype).to_string();
Done

2024-09-09 11:01 UTC, dfunkt commented on src/mail.rs
> +    let device_name = upcase_first(device_name);
Done

2024-09-09 11:15 UTC, dfunkt commented on src/mail.rs
> -            "device": device,
Maybe I should modify this to ```&device.name``` as well in order to keep existing templates compatible?

2024-09-09 11:15 UTC, dfunkt commented on src/mail.rs
> -            "device": device,
Same here

2024-09-09 11:33 UTC, BlackDex approved these changes

2024-09-09 11:33 UTC, BlackDex commented on src/mail.rs
> -            "device": device,
Well, users will then miss the other variable. So they should now be triggered to adjust the templates.
We could add an extra item in the changelogs for this.

I would leave it as  you have right now from my point of view.

2024-09-18 17:03 UTC, dani-garcia approved these changes

2024-09-18 17:03 UTC, merged

2024-09-19 13:45 UTC, gbe0 commented
With this merged I get the following on startup:

```
[2024-09-19 10:17:36.721][panic][ERROR] thread 'main' panicked at 'Error running migrations: QueryError(DieselMigrationName { name: "2024-09-04-091351_use_device_type_for_mails", version: MigrationVersion("20240904091351") }, DatabaseError(Unknown, "syntax error at or near \"`\""))': src/db/mod.rs:495
   0: vaultwarden::init_logging::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: vaultwarden::db::DbPool::from_config
   8: vaultwarden::main::{{closure}}
   9: vaultwarden::main
  10: std::sys::backtrace::__rust_begin_short_backtrace
  11: main
  12: <unknown>
  13: __libc_start_main
  14: _start
```

My DB is `PostgreSQL 16.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit`.

I rolled back and there are no issues.

2024-10-05 19:17 UTC, Gerardv514 commented
@dfunkt i just checked this out. I have an iOS device and just tried to login to the web vault using Google chrome iOS app, i closed out on the 2fa page which prompted the 2fa incomplete notification. Device type and device name both say safari, is that normal?

2024-10-05 19:54 UTC, dfunkt commented
I think that might be due to Chrome using the browser engine as Safari on iOS. I expect this happens with Bitwarden as well, but I don't have any iOS devices in order to test this theory.

TL;DR: I think this is normal

2024-10-05 20:01 UTC, Gerardv514 commented
I also attempted the iOS bitwarden app, and device name was iPhone 15,2 and device type was iOS. 

So as you said probably normal due to browser not passing the info along.