Add dynamic CSS support
dani-garcia/vaultwarden pull request #4940
Opened 2024-09-11 12:38 UTC by BlackDex

Together with https://github.com/dani-garcia/bw_web_builds/pull/180 this PR will add support for dynamic CSS changes.

For example, we could hide the register link if signups are not allowed. In the future show or hide the SSO button depending on if it is enabled or not.

There also is a special `user.vaultwarden.scss` file so that users can add custom CSS without the need to modify the default (static) changes. This will prevent future changes from not being applied and still have the custom user changes to be added.

2024-09-11 12:39 UTC, BlackDex commented
@Timshel This might be nice for your SSO PR :)

2024-09-11 14:56 UTC, BlackDex commented
I think the examples are probably better to be somewhere on the wiki and just have a commented link to this wiki in the `user.vaultwarden.scss.hbs` file it self.

2024-09-12 17:29 UTC, BlackDex commented
Some examples here for the user file:

```css
/**** START Custom User Changes ****/

/* Hide `Authenticator app` 2FA (First item of the list) */
app-two-factor-setup ul.list-group.list-group-2fa li.list-group-item:nth-child(1) {
  @extend %vw-hide;
}

/* Hide `YubiKey OTP security key` 2FA (Second item of the list) */
/* Note: This will also be hidden automatically if the Yubikey config is net set */
app-two-factor-setup ul.list-group.list-group-2fa li.list-group-item:nth-child(2) {
  @extend %vw-hide;
}

/* Hide `Duo` 2FA (Third item of the list) */
app-two-factor-setup ul.list-group.list-group-2fa li.list-group-item:nth-child(3) {
  @extend %vw-hide;
}

/* Hide `FIDO2 WebAuthn` 2FA (Fourth item of the list) */
app-two-factor-setup ul.list-group.list-group-2fa li.list-group-item:nth-child(4) {
  @extend %vw-hide;
}

/* Hide `Email` 2FA (Fifth item of the list) */
/* Note: This will also be hidden automatically if email is not enabled */
app-two-factor-setup ul.list-group.list-group-2fa li.list-group-item:nth-child(5) {
  @extend %vw-hide;
}

/* Use a custom login logo */
app-login img.logo {
	content: url(../images/my-custom-login.logo.png) !important;
}

/* Use a custom top left logo global */
bit-icon > svg {
  display: none !important;
}
bit-icon::before {
  display: block;
  content: "" !important;
  width: 175px !important;
  height: 30px !important;
  background-image: url(../images/my-custom-global-logo.png) !important;
  background-repeat: no-repeat !important;
  background-size: contain;
}

/* Use a custom top left logo different per vault/admin */
bit-icon > svg {
  display: none !important;
}
bit-icon::before {
  display: block;
  content: "" !important;
  width: 175px !important;
  height: 30px !important;
  background-repeat: no-repeat !important;
  background-size: contain;
}
app-user-layout bit-icon::before {
  background-image: url(../images/my-custom-password-manager-logo.png) !important;
}
app-organization-layout bit-icon::before {
  background-image: url(../images/my-custom-admin-console-logo.png) !important;
}

/**** END Custom User Changes ****/
```

2024-09-12 17:35 UTC, BlackDex commented
I removed the examples from the source and added a (temporary) link to the wiki where we (and other users) can add and update examples for the custom CSS entries.

2024-09-13 14:53 UTC, Letgamer commented
would it be possible with the dynamic CSS support to enable dark mode by default?

2024-09-13 15:57 UTC, BlackDex commented
> would it be possible with the dynamic CSS support to enable dark mode by default?

I do not think that is possible. 
But I'm not sure either. Maybe it is possible to change the default class? But I'm not sure.

2024-09-13 16:16 UTC, stefan0xC commented
@BlackDex we could change the web-vault so it defaults to using the `system` theme. I tested this over a year ago https://github.com/bitwarden/clients/commit/636a359fe6abab176ad7c370e0166f7313aabc74 (so no idea if this still works. I guess it most likely would have to be adapted).

2024-09-14 03:47 UTC, stefan0xC commented on src/api/web.rs
> +    .expect("scss/vaultwarden.scss to compile");
Wouldn't it be better if that already fails on startup when validating the config? Otherwise rocket will just fail the request for the `vaultwarden.css` with status code `500` and all changes will be ignored.

2024-09-14 04:31 UTC, BlackDex commented on src/api/web.rs
> +    .expect("scss/vaultwarden.scss to compile");
It probably is. And it was it there back of my mind. 
It might be a good option to lead it during startup and put it in a static variable maybe. And if template reloading is enabled do it again here, else serve the already processed file.

2024-09-18 16:59 UTC, dani-garcia commented on src/api/web.rs
> +    .expect("scss/vaultwarden.scss to compile");
I agree that some validation and caching would be nice to have, to avoid breaking the web vault accidentally.

I also think it might be interesting to add some other values to `css_options` like web vault version and vaultwarden version, to have css templates that can work with more than one vault version, and handle backwards/forwards compat better.

2024-09-18 17:07 UTC, BlackDex commented on src/api/web.rs
> +    .expect("scss/vaultwarden.scss to compile");
Yea, the versions i had in mind too.

Maybe we might want to validate and load it into cache/config. And upon error abort loading Vaultwarden.
That will not work when reload templates is on btw.

We might be able to load the embedded version then, but that might be strange too.

2024-10-05 14:19 UTC, BlackDex commented
Ok, @stefan0xC & @dani-garcia.

Instead of caching internally or stop loading Vaultwarden in case a template error was made I now fallback to the inner templates.

The main reason for this is, if someone adjusts the templates at runtime it will still fail and would make it also hard to fallback on.

This way, we will always use the fallback if any error occurs and the CSS will still be rendered, but just not with the extra modifications.

2024-10-10 22:03 UTC, stefan0xC requested changes
If you want to reproduce, I've just tested if the fallbacks work with a missing closing bracket 
```handlebars
body {
--custom-property: {{web_vault_version}};
```

2024-10-10 22:10 UTC, BlackDex commented on src/api/web.rs
> +    let scss = match CONFIG.render_template("scss/vaultwarden.scss", &css_options) {
Did you compiled it with your changes in place, in the templates folder? Or located in a totally different location?

Because i had the same issue when i was testing and compiled the bad fallback into Vaultwarden it self hehe

2024-10-10 22:12 UTC, BlackDex commented on src/api/web.rs
> +                .render_inner_template("scss/vaultwarden.scss", &css_options)
The difference is that the first loads templates on disk, the latter only extracts them from the built-in files.

2024-10-10 22:12 UTC, stefan0xC commented on src/api/web.rs
> +    let scss = match CONFIG.render_template("scss/vaultwarden.scss", &css_options) {
provided via "data/templates/scss/user.vaultwarden.scss.hbs"

2024-10-10 22:13 UTC, BlackDex commented on src/static/templates/scss/vaultwarden.scss.hbs
> +}
Ah, it was also still in the bw_web_builds.

2024-10-10 22:13 UTC, BlackDex commented on src/api/web.rs
> +            // Something went wrong compiling the scss. Fallback to the built-in tempaltes
Thanks

2024-10-10 22:14 UTC, BlackDex commented on src/api/web.rs
> +    let scss = match CONFIG.render_template("scss/vaultwarden.scss", &css_options) {
Hmm, it should fallback. Ill have to revisit this part of the code again.

2024-10-10 22:18 UTC, stefan0xC commented on src/api/web.rs
> +                .render_inner_template("scss/vaultwarden.scss", &css_options)
Because of the `#[inline]`? Why would that be the case?

2024-10-10 22:29 UTC, BlackDex commented on src/api/web.rs
> +                .render_inner_template("scss/vaultwarden.scss", &css_options)
No, because that code part uses the files stored in the `inner` key which are built-in during compile-time.

2024-10-10 22:49 UTC, stefan0xC commented on src/api/web.rs
> +                .render_inner_template("scss/vaultwarden.scss", &css_options)
but there's nothing before the call to differentiate the two cases https://github.com/dani-garcia/vaultwarden/blob/68d04f124b336dea6d2b7f3208af1e865b10ffb2/src/config.rs#L1265 so I don't understand how this would be different. I meant it previously also used the `inner` key, so why would there be a difference?

I mean as far as I understand it all the registered templates are overwritten by https://github.com/dani-garcia/vaultwarden/blob/68d04f124b336dea6d2b7f3208af1e865b10ffb2/src/config.rs#L1359-L1362

2024-10-10 23:03 UTC, stefan0xC commented on src/api/web.rs
> +    let scss = match CONFIG.render_template("scss/vaultwarden.scss", &css_options) {
Do you have perhaps activated `reload_templates`? Because then it falls back to the initially loaded templates (whatever they maybe) not the statically compiled ones (as far as I understand it).

2024-10-12 17:52 UTC, BlackDex commented
@stefan0xC i have fixed it now. Tested it both with and without the template reloading.
And both with and without overwriting both `scss` template files.

2024-10-13 09:03 UTC, stefan0xC approved these changes
Tested it and seems to work as intended. Only in case of an `TemplateError` (e.g. an unclosed `{{#if}} statement) the loading of handlebar templates will panic on startup.
```
thread 'main' panicked at src/config.rs:1374:78:
called `Result::unwrap()` on an `Err` value: TemplateError { reason: InvalidSyntax("expected escape, expression, html_expression, decorator_expression, partial_expression, invert_tag, invert_chain_tag, helper_block_start, helper_block_end, decorator_block_start, partial_block_start, raw_block_start, hbs_comment, or hbs_comment_compact"), template_name: Some("scss/vaultwarden.scss"), line_no: Some(5), column_no: Some(1), segment: Some("   2 | }\n   3 | {{#if bla}}\n") }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
But I think this is fine.

2024-10-13 09:11 UTC, BlackDex commented on src/api/web.rs
> +            warn!("Compiling the Vaultwarden SCSS styles failed. {e}");
How should we improve it? The error message is is generated by the scss compiler. 

What do you suggest?

2024-10-13 09:18 UTC, BlackDex commented
That Startup panic isn't something we can really catch, as that is done during template loading. And it's the responsibility of the user who edits the templates of course, same goes for when we adjust templates for the mails or admin interface.

We could always add fallbacks for everything, and in case of errors ignore the users adjustments. But that is out of scope for this PR i think.

2024-10-13 09:35 UTC, stefan0xC commented on src/api/web.rs
> +            warn!("Compiling the Vaultwarden SCSS styles failed. {e}");
The `stdin` threw me off but I think it's probably fine. (I was thinking that we could also mention from which files it was generated but I think this could also be done in a troubleshooting section on the wiki.)

2024-10-13 15:30 UTC, BlackDex commented on src/api/web.rs
> +            warn!("Compiling the Vaultwarden SCSS styles failed. {e}");
Sounds good to me.
Ill prepare a wiki already so that i can add the correct link into the user file.

2024-10-13 18:48 UTC, BlackDex commented
Ok. I created a basic Wiki page for now. https://github.com/dani-garcia/vaultwarden/wiki/Customize-Vaultwarden-CSS
We can add more examples and detailed information there regarding this feature.

2024-11-11 19:04 UTC, dani-garcia approved these changes

2024-11-11 19:14 UTC, merged

2024-11-18 20:11 UTC, BlackDex commented
@lukasj98 i have reverted that just now. As it isn't usable a.t.m. since the web-vault doesn't support this yet.

We still have to release a web-vault which will load that file instead of using the built-in patched CSS.
So, it isn't usable yet. But to have this working in a correct way, it would first be merged into Vaultwarden and in a stable release before we were able to release a new web-vault which has support for this.

The main reason is that if for some reason someone would start using a newer web-vault without the support of this on the server side there would be issues hehe.

2024-11-18 20:30 UTC, lukasj98 commented
Oh sorry