Update `README.md`
dani-garcia/vaultwarden pull request #4961
Opened 2024-09-18 10:06 UTC by georglauterbach

## Description

New contributor here that want to switch to Vaulwarden. I would like to help this project by improving the README a bit. While maintaining [other projects on GitHub](https://github.com/docker-mailserver/docker-mailserver), I learned quite a lot about good documentation and the value of a proper README, and hence, I'd like to give something back and improve the README of this project.

Please have a look at [what it looks like at the moment](https://github.com/georglauterbach/vaultwarden/tree/patch-1).

Please tell me if you think I removed something that was not supposed to be removed.**

## Details

- Updated the heading (was too verbose)
- Removed superflous links from the badges list
- Pulled text together to make the text easier to read (it was too scattered, making it hard to read)
- added proper [GitHub Markdown alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) to make notes and important messages stand out (instead of just using bold text)
- Added articles where necessary
- Added a link to the Helm chart for installations in Kubernets clusters
- Updated the command for running the image with Docker
  - The command is for testing purposed, i.e. there is no need to restart anything or detach (you actually want to see the log)
  - The container can be removed once stopped; since the data is persisted, there is no issue at all
- updated headings to make them uniform (especially the level)
- removed HTML and converted to pure Markdown, which is preffered in Markdown

2024-09-21 09:20 UTC, stefan0xC requested changes
Thanks for your contribution. Since you are basically proposing a rewrite of the whole document I was wondering whether you have also looked at the existing PR #4931 which does the same but in a slightly different direction?

2024-09-21 09:20 UTC, stefan0xC commented on README.md
> +> [!NOTE]
Do you know how these alerts are rendered on Docker Hub? I mean the README at https://hub.docker.com/r/vaultwarden/server does not seem to be using the most recent README anyway but if we change this to a GitHub-specific syntax this might look weird.

2024-09-21 23:17 UTC, georglauterbach commented
> Thanks for your contribution. Since you are basically proposing a rewrite of the whole document I was wondering whether you have also looked at the existing PR #4931 which does the same but in a slightly different direction?


I only discovered #4931 after I proposed the changes in this PR... do you think I should close this one in favor of #4931?

2024-09-21 23:18 UTC, georglauterbach commented on README.md
> +There is a [Helm chart for Vaultwarden](https://github.com/guerzon/vaultwarden).
I can remove it :)

2024-09-21 23:19 UTC, georglauterbach commented on README.md
> +This project is a full implementation of the Bitwarden API, including:
Will reword.

2024-09-21 23:21 UTC, georglauterbach commented on README.md
> -If you have an available domain name, you can get HTTPS certificates with [Let's Encrypt](https://letsencrypt.org/), or you can generate self-signed certificates with utilities like [mkcert](https://
I think this is cluttering the README; Vaultwarden should not be concerned with TLS certificates. Giving the reader the insight that "If you have an available domain name, you can get HTTPS certificates" is definitely less interesting and more obvious than the link to the Helm chart earlier, which was rejected for being cluttering.

2024-09-21 23:23 UTC, georglauterbach commented on README.md
> -If you have an available domain name, you can get HTTPS certificates with [Let's Encrypt](https://letsencrypt.org/), or you can generate self-signed certificates with utilities like [mkcert](https://
I agree that the installation section as a whole needs a rework.. This step also depends on where the installation instructions should go, after all.

Over at [`docker-mailserver/docker-mailserver`](https://github.com/docker-mailserver/docker-mailserver/), I moved the Wiki to GitHub pages and MKdocs, which is very nice to work with. Depending on the outcome, these instructions might be better suited on the according Wiki pages, whether this is GitHub's Wiki or GitHub Pages.

2024-09-21 23:23 UTC, georglauterbach commented on README.md
> -[![ghcr.io](https://img.shields.io/badge/ghcr.io-download-blue)](https://github.com/dani-garcia/vaultwarden/pkgs/container/vaultwarden)
It links to a page that you can reach anyway on the project page via the "Packages" section.

2024-09-21 23:24 UTC, georglauterbach commented on README.md
> -[![GitHub Release](https://img.shields.io/github/release/dani-garcia/vaultwarden.svg)](https://github.com/dani-garcia/vaultwarden/releases/latest)
It links to a page that you can reach anyway on the project page via the "Releases" section.

2024-09-21 23:27 UTC, georglauterbach commented on README.md
> +> [!NOTE]
I am not sure whether they render at all on DockerHub, but in my experience, you would rather not sync the README to DockerHub 1:1 anyway. Linking to the project README or giving a shorter version is easier to maintain, so I'd not worry.

2024-10-11 21:21 UTC, georglauterbach commented
Closing this for now; no time to dedicate to this and there is another PR queued up.

2024-10-11 21:21 UTC, closed without merging