Update README
dani-garcia/vaultwarden pull request #5153
Opened 2024-11-01 11:37 UTC by BlackDex

Updating the Readme to be more modern and more clear. Added and moved several shields/badges and changed some default colors to have a better contrast. Added a Disclaimer section.

Closes #4901
Closes #4930
Closes #4931
Closes #5024

2024-11-01 11:48 UTC, BlackDex commented
Also, to view the readme in how it would look like see this link: https://github.com/dani-garcia/vaultwarden/tree/b8f7e8880653c0e8e0919da355794cad9695f01b

2024-11-01 11:58 UTC, dfunkt requested changes

2024-11-01 11:58 UTC, dfunkt commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
```suggestion
Have a question, suggestion or need setup help? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussions) or [Discourse Forums](https://vaultwarden.discourse.group/).
```

2024-11-01 11:58 UTC, dfunkt commented on README.md
> +To use Docker compose you need to create a `docker-compose.yaml` which will hold the configuration to run the Vaultwarden container.
```suggestion
To use Docker compose you need to create a `compose.yaml` which will hold the configuration to run the Vaultwarden container.
```
For reference: https://github.com/compose-spec/compose-spec/blob/main/03-compose-file.md

2024-11-01 11:58 UTC, dfunkt commented on README.md
> +Nearly complete implementation of the Bitwarden Client API is provided including:
```suggestion
A nearly complete implementation of the Bitwarden Client API is provided, including:
```

2024-11-01 11:58 UTC, dfunkt commented on README.md
> +Encountered a bug or crash? Please search our issue tracker and discussions to see if it's already been reported. If not, please [start a new discussions](https://github.com/dani-garcia/vaultwarden/d
```suggestion
Encountered a bug or crash? Please search our issue tracker and discussions to see if it's already been reported. If not, please [start a new discussion](https://github.com/dani-garcia/vaultwarden/discussions) or [create a new issue](https://github.com/dani-garcia/vaultwarden/issues/). Ensure you're using the latest version of Vaultwarden and there aren't any similar issues open or closed!
```

2024-11-01 11:58 UTC, dfunkt commented on README.md
> +> **When using this server, please report any bugs or suggestions directly to us (See [Get in touch](#get-in-touch)), regardless of whatever clients you are using (mobile, desktop, browser...). DO NO
```suggestion
> **When using this server, please report any bugs or suggestions directly to us (see [Get in touch](#get-in-touch)), regardless of whatever clients you are using (mobile, desktop, browser...). DO NOT use the official Bitwarden support channels.**
```

2024-11-01 11:58 UTC, dfunkt commented on README.md
> +An alternative server implementation of the Bitwarden Client API written in Rust and compatible with [official Bitwarden clients](https://bitwarden.com/download/) [[disclaimer](#disclaimer)], perfect
```suggestion
An alternative server implementation of the Bitwarden Client API, written in Rust and compatible with the [official Bitwarden clients](https://bitwarden.com/download/) [[disclaimer](#disclaimer)], perfect for self-hosted deployment where running the official resource-heavy service might not be ideal.
```

2024-11-01 12:03 UTC, BlackDex commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
I actually have run this specific line through two AI's and grammar tools to get this right. So i think the original version is ok as-is.

2024-11-01 12:09 UTC, BlackDex commented on README.md
> +To use Docker compose you need to create a `docker-compose.yaml` which will hold the configuration to run the Vaultwarden container.
Well, i kept it as is. But since it is almost a year old the new standard was created. It might be good to change it too indeed.

2024-11-01 12:16 UTC, BlackDex commented on README.md
> +An alternative server implementation of the Bitwarden Client API written in Rust and compatible with [official Bitwarden clients](https://bitwarden.com/download/) [[disclaimer](#disclaimer)], perfect
`the` doesn't add anything here, without is better i think.

2024-11-01 12:17 UTC, dfunkt commented on README.md
> +An alternative server implementation of the Bitwarden Client API written in Rust and compatible with [official Bitwarden clients](https://bitwarden.com/download/) [[disclaimer](#disclaimer)], perfect
Yeah, I could see that. But I think the comma should've been added.

2024-11-01 12:17 UTC, dfunkt commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
Fair enough.

2024-11-01 12:22 UTC, BlackDex commented
Thanks for the review @dfunkt !

2024-11-01 12:42 UTC, dfunkt requested changes

2024-11-01 12:42 UTC, dfunkt commented on README.md
> +A Nearly complete implementation of the Bitwarden Client API is provided including:
```suggestion
A nearly complete implementation of the Bitwarden Client API is provided, including:
```

2024-11-01 12:42 UTC, dfunkt commented on README.md
> +There are also [community driven packages](https://github.com/dani-garcia/vaultwarden/wiki/Third-party-packages) which can be used, but those might be lagging behind in release or might deviate in th
```suggestion
There are also [community driven packages](https://github.com/dani-garcia/vaultwarden/wiki/Third-party-packages) which can be used, but those might be lagging behind the latest version or might deviate in the way Vaultwarden is configured, as described in our [Wiki](https://github.com/dani-garcia/vaultwarden/wiki).
```

2024-11-01 13:29 UTC, dfunkt approved these changes

2024-11-01 21:22 UTC, jjlin commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
As a native English speaker, "need help setup" is definitely not grammatical. I think you have too much faith in computers...

2024-11-01 21:40 UTC, BlackDex commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
What a nice way of telling it is wrong @jjlin.
As you know I'm not native English, and even my native spelling is sometimes off (as are for native English speakers).

And since i didn't had that much fait did used multiple if you would have read my post a bit better.

But thanks for your comment, ill adjust accordingly.

2024-11-01 21:49 UTC, jjlin commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
Well, someone already pointed it out as an issue, but you insisted it was fine because you ran it through several tools, so I'm not sure what you expected me to say here.

2024-11-01 21:52 UTC, BlackDex commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
You could just have mentioned it without the last remark.
A last sentence mentioning it would indeed be better to use something else, or provide an alternative would be much nicer 😄

2024-11-01 21:56 UTC, dfunkt commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
I think @jjlin meant it like to not put so much faith in these LLMs, since they hallucinate and all that.

2024-11-01 22:02 UTC, BlackDex commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
I understood what he meant. And i know the can hallucinate or provide wrong answers. That is also why i used other grammar tools. And i too know those could also be wrong, but all tools i used didn't mentioned it to be wrong.

Anyway, thanks for the comments. I'll adjust the wording.

2024-11-02 09:04 UTC, BlackDex commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
I have remove the term setup all together.
I think that might be better.

If not please provide any other other suggestion.

2024-11-02 10:38 UTC, dfunkt commented on README.md
> +Have a question, suggestion or need help setup? Join our community on [Matrix](https://matrix.to/#/#vaultwarden:matrix.org), [GitHub Discussions](https://github.com/dani-garcia/vaultwarden/discussion
Looks good to me.

2024-11-02 10:38 UTC, dfunkt approved these changes

2024-11-02 21:20 UTC, dani-garcia approved these changes

2024-11-02 21:20 UTC, merged