Implement registration with required verified email
dani-garcia/vaultwarden pull request #5215
Opened 2024-11-21 00:19 UTC by dani-garcia

New versions of the clients support a new registration flow that also allows enforcing email verification. This is a working implementation of that new API.

The clients implementations are gated behind two feature flags that I have enabled, I've used a web vault compiled from the main branch, but older releases might also work.

Still a draft as I still need to test Invites/emergency access

2025-02-05 08:08 UTC, stefan0xC commented on src/api/identity.rs
> +    name: String,
`name` should be optional as far as I've tested it with `web-v2025.1.2`.

2025-02-05 08:29 UTC, stefan0xC commented
> Still a draft as I still need to test Invites/emergency access

Emergency access will fail
```
[2025-02-05 09:25:23.688][request][INFO] POST /identity/accounts/register/finish
[2025-02-05 09:25:23.688][vaultwarden::api::core::accounts][ERROR] Email verification token is required
[2025-02-05 09:25:23.688][response][INFO] (register_finish) POST /identity/accounts/register/finish => 400 Bad Request
```

There is an `acceptEmergencyAccessInviteToken` in the request though.

Same with invitations / `orgInviteToken`:
```
[2025-02-05 09:28:00.722][request][INFO] POST /identity/accounts/register/finish
[2025-02-05 09:28:00.722][vaultwarden::api::core::accounts][ERROR] Email verification token is required
[2025-02-05 09:28:00.722][response][INFO] (register_finish) POST /identity/accounts/register/finish => 400 Bad Request
```

2025-02-05 22:51 UTC, dani-garcia commented
Thanks for the testing @stefan0xC , I've fixed emergency access now and I'll look into the org invites tomorrow.

2025-02-06 07:05 UTC, stefan0xC commented
I'm not sure if accepting the emergency access invitation in `_register` is necessary because it seems like the client will sent a separate request after registration is finished to accept the emergency access anyway (which will then fail because there is no pending emergency access request to be accepted anymore):

```
[2025-02-06 07:46:59.770][request][INFO] POST /identity/accounts/register/finish
[2025-02-06 07:47:02.319][response][INFO] (register_finish) POST /identity/accounts/register/finish => 200 OK
[2025-02-06 07:47:02.481][request][INFO] POST /identity/accounts/prelogin
[2025-02-06 07:47:02.482][response][INFO] (prelogin) POST /identity/accounts/prelogin => 200 OK
[2025-02-06 07:47:02.652][request][INFO] POST /identity/connect/token
[2025-02-06 07:47:04.890][vaultwarden::api::identity][INFO] User [...] logged in successfully. IP: 192.168.1.100
[2025-02-06 07:47:04.891][response][INFO] (login) POST /identity/connect/token => 200 OK
[2025-02-06 07:47:05.076][request][INFO] GET /api/config
[2025-02-06 07:47:05.076][response][INFO] (config) GET /api/config => 200 OK
[2025-02-06 07:47:05.292][request][INFO] POST /identity/connect/token
[2025-02-06 07:47:05.294][response][INFO] (login) POST /identity/connect/token => 200 OK
[2025-02-06 07:47:05.319][request][INFO] GET /notifications/hub?access_token=eyJ0eXAiOiJKV1QiL
[2025-02-06 07:47:05.320][vaultwarden::api::notifications][INFO] Accepting Rocket WS connection from 192.168.1.100
[2025-02-06 07:47:05.320][response][INFO] (websockets_hub) GET /notifications/hub?<data..> => 200 OK
[2025-02-06 07:47:05.446][request][INFO] GET /api/sync?excludeDomains=true
[2025-02-06 07:47:05.448][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
[2025-02-06 07:47:05.955][request][INFO] POST /api/emergency-access/0ac804b7-232d-44c8-b701-ae2615a07eba/accept
[2025-02-06 07:47:05.957][vaultwarden::api::core::emergency_access][ERROR] Emergency access not valid.
[2025-02-06 07:47:05.963][response][INFO] (accept_invite) POST /api/emergency-access/<emer_id>/accept => 400 Bad Request
[2025-02-06 07:47:06.558][request][INFO] GET /api/accounts/revision-date
[2025-02-06 07:47:06.559][response][INFO] (revision_date) GET /api/accounts/revision-date => 200 OK
[2025-02-06 07:47:06.570][request][INFO] GET /api/accounts/profile
[2025-02-06 07:47:06.571][response][INFO] (profile) GET /api/accounts/profile => 200 OK
```

2025-02-06 19:50 UTC, dani-garcia commented
Oops didn't notice the client was doing the accept right afterwards, same thing with the org invites so the only thing I do is validate the claims in the token match with the request now.

2025-02-06 22:05 UTC, stefan0xC requested changes
@dani-garcia I could not yet accept an organization invite. Also with the new registration flow a `token` will not be send anymore so we should change it to `org_invite_token` accordingly.

2025-02-06 22:36 UTC, stefan0xC commented on src/api/core/accounts.rs
> +    org_invite_token: Option<String>,
As far as I've tested it that seems to work both with `web-v2025.1.1` (with and without the feature flags set) and `web-v2025.1.2`.

2025-03-05 08:56 UTC, stefan0xC commented
@dani-garcia Since `email_verified` already does the job I also think that we could probably get rid of the separate `verified_by_invite` boolean like this: https://github.com/dani-garcia/vaultwarden/commit/1d5606ffe219a3194bbf8417c17bd3249f6a361c or else users that have already been verified (because of the new registration flow) would get a separate mail asking them to verify their mail address again.

2025-03-17 09:22 UTC, stefan0xC approved these changes

2025-03-17 15:28 UTC, merged