Add partial role support for manager only using web-vault v2024.12.0
dani-garcia/vaultwarden pull request #5219
Opened 2024-11-21 20:37 UTC by BlackDex

- Add the custom role which replaces the manager role
- Added mini-details endpoint used by v2024.12.0

These changes try to add the custom role in such a way that it stays compatible with the older manager role. It will convert a manager role into a custom role, and if a manager has `access-all` rights, it will enable the correct custom roles. Upon saving it will convert these back to the old format.

What this does is making sure you are able to revert back to an older version of Vaultwarden without issues. This way we can support newer web-vault's and still be compatible with a previous Vaultwarden version if needed.

In the future this needs to be changed to full role support though.

2024-11-21 20:41 UTC, BlackDex commented
This PR needs a web-vault built from this PR https://github.com/dani-garcia/bw_web_builds/pull/186
I'm have yet to fix the CSS, since it now still hides some elements which need to be visible.

But it would be nice if some people are able to test this PR using a web-vault built from the PR linked above.

2024-11-21 22:10 UTC, tessus commented
> In the future this needs to be changed to full role support though.

May I suggest to add more comments to the code, where your changes from this PR have to be reverted when full role support is implemented. Unless you you'll keep the compat layer even then.

It is quite possible to forget to remove/change current code/behavior when the "future" changes are not close to this PR. Please ignore, if I am way off.

2024-11-22 19:42 UTC, BlackDex commented
@tessus done :)

@stefan0xC I have fixed the icon in the collapsed menu.

2024-11-25 16:35 UTC, BlackDex commented
As mentioned before, this PR needs a new web-vault version for which a PR can be found here:
 - https://github.com/dani-garcia/bw_web_builds/pull/186

CI builds of this web-vault can be downloaded here:
 - https://github.com/dani-garcia/bw_web_builds/actions/runs/12013212076 in the artifacts section.

2024-12-06 20:47 UTC, tessus commented
If this is the only PR required for the new web vault, is it possible to merge this and then release the new web vault - maybe this weekend?
I've been running it for a few days now and didn't run into any issues. Although I am sure I haven't tested all edge cases and every single functionality.

2024-12-07 09:25 UTC, BlackDex commented
I'd rather first fix a native client issue and release a version and after that merge this.

I also think it is better to first release the web-vault and then add that release to this PR.

2024-12-07 09:56 UTC, dfunkt commented
Not sure if this belongs here or in the web vault PR, but I seem to be offered the option to log in with a passkey (which obviously doesn't work):
![image](https://github.com/user-attachments/assets/9779d35a-0df6-4dae-81c1-20a0286fb8c0)

2024-12-07 10:42 UTC, BlackDex commented
> Not sure if this belongs here or in the web vault PR, but I seem to be offered the option to log in with a passkey (which obviously doesn't work):

Thanks! I fixed it just now.

2024-12-07 10:45 UTC, dfunkt commented
Now that I think about it, shouldn't the create account line also be hidden? I have signups disabled.

2024-12-07 10:52 UTC, BlackDex commented
> Now that I think about it, shouldn't the create account line also be hidden? I have signups disabled.

Also fixed now :)

2024-12-11 20:44 UTC, BlackDex commented
I'm checking to see if we can update to v2024.12.0. There seem to be some minor changes and some endpoints added.

2024-12-11 23:09 UTC, BlackDex commented
Code is adjusted to support v2024.12.0 now. Not too much changed.

2024-12-16 23:22 UTC, tessus commented
> I'd rather first fix a native client issue and release a version and after that merge this.

The native client issue has been fixed and a new version has been released.

Is it possible to merge this now and release the new web-vault 2024.12.0 (or the other way around as you suggested)?

2024-12-17 01:41 UTC, tessus commented
> If not then just try to build and run it yourself

I already do. If you had read my earlier comments, you would have known.

2024-12-17 09:47 UTC, stefan0xC commented
@BlackDex the [endpoint `/api/organizations/<org_id>/groups/details`](https://github.com/bitwarden/clients/blob/b7ec74df5aecd0efe8bb4c6433f279d437a135c3/apps/web/src/app/admin-console/organizations/core/services/group/group-api.service.ts#L52-L65) seems to be missing, which appears to break my ability to edit users with `web-v2024.12.0`.
![image](https://github.com/user-attachments/assets/c19862a4-083e-4683-87f7-85c2fa6d9955)

2024-12-17 10:20 UTC, BlackDex commented
@stefan0xC seems to work for me:
```
[response][INFO] (get_groups_details) GET /api/organizations/<org_id>/groups/details => 200 OK
```

Be sure to pull in the latest commit and are on:
```
git rev-parse HEAD
748a24219ed2b3d74b72ff6c12d9bad7f2fb3cc6
```

2024-12-17 10:44 UTC, stefan0xC commented
@BlackDex if the group has `accessAll` it works
```json
{
  "accessAll": true,
  "collections": [],
  "externalId": null,
  "id": "41917ddc-7cf7-47d0-bd7f-7b24d21c2b71",
  "name": "manager group",
  "object": "groupDetails",
  "organizationId": "152bd996-19f9-40ee-b991-e52333a7e719"
}
```

but it fails when the group has permissions for individual collections:
```json
{
  "accessAll": false,
  "collections": [
    {
      "hidePasswords": true,
      "id": "f39e653f-3191-4312-887d-931889be5d20",
      "manage": false,
      "readOnly": false
    },
    {
      "hidePasswords": true,
      "id": "ca4b77ab-c849-47f4-a6f3-c4ebde35d5f0",
      "manage": false,
      "readOnly": true
    }
  ],
  "externalId": null,
  "id": "41917ddc-7cf7-47d0-bd7f-7b24d21c2b71",
  "name": "manager group",
  "object": "groupDetails",
  "organizationId": "152bd996-19f9-40ee-b991-e52333a7e719"
}
```

2024-12-17 10:49 UTC, BlackDex commented
@stefan0xC What happens then exactly?
It doesn't work? And is it mixed with with an accessAll?

2024-12-17 11:08 UTC, stefan0xC commented
> @stefan0xC What happens then exactly? It doesn't work? And is it mixed with with an accessAll?

The exception happened when I tried to open the Custom user member (which used to be a Manager role without `accessAll`) or the group. But now after changing the group I can't seem to be able to replicate the issue anymore.

2024-12-17 15:36 UTC, stefan0xC commented on src/static/templates/scss/vaultwarden.scss.hbs
> +app-login form p {
This will also hide the `Logging in as bla@example.com` on the password field.
![image](https://github.com/user-attachments/assets/aa13df0c-5944-463e-ac6a-b53a28fb4b73)

2024-12-17 15:44 UTC, dfunkt commented on src/static/templates/scss/vaultwarden.scss.hbs
> +app-login form p {
Is this even needed anymore since v2024.12.0 contains commit https://github.com/bitwarden/clients/commit/f5e6fc8ed5a4756d7866ae05118ff795ec68a374?

2024-12-17 18:15 UTC, BlackDex commented on src/static/templates/scss/vaultwarden.scss.hbs
> +app-login form p {
It should, but somehow this doesn't work.

2024-12-17 18:33 UTC, BlackDex commented on src/static/templates/scss/vaultwarden.scss.hbs
> +app-login form p {
Fix this now, also hiding the `<hr>` since that is used to divide the text and the button.

2024-12-23 13:48 UTC, stefan0xC requested changes
Found a small issue.

2024-12-24 01:35 UTC, tessus commented on src/api/core/organizations.rs
> +        .map(|uo| (uo.uuid, uo.atype))
I've been reading the code a bit and I think more comments would make sense.

e.g. in the atruct `UserOrganization`, what's the `uuid` and `user_uuid` for? Someone can only understand that, if they read and understand the entire code.

And as you have shown here, the usage of these members is apparently not always that clear.

Don't take this the wrong way, I'd add the comments myself, but I doubt I understand all the different abstraction layers and levels in their entirety. I am also not saying that you should add those comments, but that I'd like to see more comments that explain certain connections and layers.

2024-12-24 11:32 UTC, BlackDex commented on src/api/core/organizations.rs
> +        .map(|uo| (uo.uuid, uo.atype))
I'm almost certain i changed this to have it working at all because it wasn't. I'll have to revisit it.

2024-12-24 11:53 UTC, stefan0xC commented on src/api/core/organizations.rs
> +        .map(|uo| (uo.uuid, uo.atype))
Well, I did not test if it still works. I just noticed the discrepancy when trying to apply your changes upon my newtype branch (#5320) because it would not even compile with the wrong id.

@tessus I'm not sure if comments would help. As I've shown they can be wrong or misleading. But to answer your question: Generally the `uuid` refers to an entity itself (e.g. the `UserOrganization` relation or whatever is stored in the `users_organizations` table) while it does not with a prefix (e.g. `user_uuid` refers to a `User` entity). I think the database schema is more consistent about this than the rest of the code base.

2024-12-24 15:37 UTC, stefan0xC commented on src/api/core/organizations.rs
> +        .map(|uo| (uo.uuid, uo.atype))
Here is an visualization of the relevant database relations
![output9](https://github.com/user-attachments/assets/56a9a834-d622-4031-b96d-46051fa195c6)

Created with [visualize-sqlite](https://github.com/UhhhWaitWhat/visualize-sqlite/) and dot after dropping the other tables from a fresh `db.sqlite3`:
```bash
for t in __diesel_schema_migrations attachments auth_requests ciphers ciphers_collections devices emergency_access event favorites folders folders_ciphers invitations org_policies organization_api_key sends twofactor twofactor_duo_ctx twofactor_incomplete
do 
    sqlite3 data/db.sqlite3 "drop table $t"
    visualize-sqlite data/db.sqlite3  | dot -Tpng > image.png
done
    visualize-sqlite data/db.sqlite3  | dot -Tpng > image.png
```

2024-12-24 17:05 UTC, tessus commented on src/api/core/organizations.rs
> +        .map(|uo| (uo.uuid, uo.atype))
Ah, ok. Thanks for that. I was wondering why an n:m table would have its own uuid. However looking at the diagram, the naming is rather inconsistent and a bit confusing.

2024-12-25 01:37 UTC, stefan0xC commented on src/api/core/organizations.rs
> +                    *users_org_type.get(&collection_user.user_uuid).unwrap_or(&(UserOrgType::User as i32)),
Okay I looked further into it and I think part of what makes it tricky is that we have two functions that retrieve a `CollectionUser` with an `user_uuid` pointing to  `users_organization.uuid` instead of `users.uuid` which is probably why this is so confusing:
https://github.com/dani-garcia/vaultwarden/blob/ed4ad67e732c213beaec78970cdb68e48bee3dc1/src/db/models/collection.rs#L514-L521

https://github.com/dani-garcia/vaultwarden/blob/ed4ad67e732c213beaec78970cdb68e48bee3dc1/src/db/models/collection.rs#L610-L619

2024-12-25 01:39 UTC, stefan0xC commented on src/api/core/organizations.rs
> +                .map(|uo| (uo.uuid, uo.atype))
Or not.

2024-12-30 16:13 UTC, BlackDex commented on src/api/core/organizations.rs
> +        .map(|uo| (uo.uuid, uo.atype))
@stefan0xC i have renamed the function to also mention the swap, that should for now make it clear.
But this should be revisited i think in the future.

2024-12-30 17:14 UTC, BlackDex commented
@stefan0xC & @dfunkt, i have been testing a bit more, but i can't find anything strange my self.
If you have anything which should be solved or issues encountered, please let me know, else will try to merge this soonisch.

2024-12-30 18:29 UTC, stefan0xC approved these changes
I don't think I can find anything else. I mean that a Manager that does not have access to all collection will not have access to the admin console is probably expected. One question I would have left is if we should not make this a permanent change  and save the `manage` permission in the CollectionUser / GroupUser relations accordingly? Since that seems a bit weird to just keep deriving it. But I wonder if that's possible without implementing custom permissions as well.

2024-12-30 18:32 UTC, BlackDex commented
I'd rather do that while implementing the other rights too.
Because it also need some auth/header rights changes too.

2024-12-30 19:38 UTC, dfunkt approved these changes
I've been using this PR for the past few weeks, no further problems to report.

2025-01-01 15:31 UTC, Gerardv514 requested changes
to

2025-01-01 15:43 UTC, Gerardv514 requested changes

2025-01-01 15:43 UTC, Gerardv514 commented on src/api/core/organizations.rs
> +    // HACK: We need the raw user-type be be sure custom role is selected to determine the access_all permission
```suggestion
    // HACK: We need the raw user-type to be sure custom role is selected to determine the access_all permission
```

2025-01-01 15:46 UTC, BlackDex commented on src/api/core/organizations.rs
> +    // HACK: We need the raw user-type be be sure custom role is selected to determine the access_all permission
thx fixed

2025-01-01 15:58 UTC, Gerardv514 requested changes

2025-01-01 15:58 UTC, Gerardv514 commented on src/api/core/organizations.rs
> +    // Since the parent checkbox is not send to the server we need to check and verify the child checkboxes
```suggestion
    // Since the parent checkbox is not sent to the server we need to check and verify the child checkboxes
```

2025-01-01 15:58 UTC, Gerardv514 commented on src/api/core/organizations.rs
> +    // Since the parent checkbox is not send to the server we need to check and verify the child checkboxes
```suggestion
    // Since the parent checkbox is not sent to the server we need to check and verify the child checkboxes
```

2025-01-01 15:58 UTC, Gerardv514 commented on src/db/models/organization.rs
> +        // Because BitWarden want the status to be -1 for revoked users we need to catch that here.
```suggestion
        // Because BitWarden wants the status to be -1 for revoked users we need to catch that here.
```

2025-01-04 18:31 UTC, dani-garcia approved these changes

2025-01-04 18:31 UTC, merged